In [1]:
import pandas as pd

In [23]:
pd.set_option('display.max_columns', None)

In [24]:
df = pd.read_csv(
    'data/Bezoeken per voertuig 01-01-2025 - 31-12-2025.Csv',
    sep=';',
    encoding='utf-16',
    skiprows=1
)

C:\Users\aniek.kasius\AppData\Local\Temp\ipykernel_6744\1523193955.py:1: DtypeWarning: Columns (0: Contact) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [25]:
df

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,967 (VDG-43-S),02-01-2025,06:48,07:17,10:27,"35,90",00:28,3:10,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,3:39,0:28,3:10,0:00,"35,90",51.905395,4.332835
1,967 (VDG-43-S),02-01-2025,10:27,10:39,10:43,"5,10",00:11,0:03,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,3:54,0:40,3:14,0:00,"41,00",51.905395,4.332835
2,967 (VDG-43-S),02-01-2025,10:43,11:36,12:17,"61,00",00:53,0:41,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,5:29,1:33,3:55,0:00,"102,00",51.905395,4.332835
3,967 (VDG-43-S),02-01-2025,12:17,12:58,14:51,"27,30",00:40,1:52,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,8:02,2:14,5:47,0:00,"129,30",51.905395,4.332835
4,967 (VDG-43-S),02-01-2025,14:51,15:06,06:55,"3,70",00:15,15:49,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,8:17,2:29,5:47,8:17,"133,00",51.905395,4.332835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59128,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
59129,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
59130,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400
59131,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293
59132,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417

In [26]:
# bekijken welke auto's elke dag naar het depot gaan
depot_naam = "Kamerlingh Onnesweg 9, Dordrecht"

In [27]:
# als de dataframe al in de juiste volgorde staat:
# per Date en SerialNumber de eerste en laatste rij pakken

eerste_stop = (
    df.groupby(["Date", "SerialNumber"], sort=False)
      .first()
      .reset_index()[["Date", "SerialNumber", "VisitingAddress"]]
      .rename(columns={"VisitingAddress": "eerste_stop"})
)

laatste_stop = (
    df.groupby(["Date", "SerialNumber"], sort=False)
      .last()
      .reset_index()[["Date", "SerialNumber", "VisitingAddress"]]
      .rename(columns={"VisitingAddress": "laatste_stop"})
)

# samenvoegen
start_eind_check = eerste_stop.merge(
    laatste_stop,
    on=["Date", "SerialNumber"],
    how="inner"
)

# alleen groepen die starten én eindigen bij depot
groepen_depot_start_eind = start_eind_check[
    (start_eind_check["eerste_stop"] == depot_naam) &
    (start_eind_check["laatste_stop"] == depot_naam)
][["Date", "SerialNumber"]]

# originele dataset filteren op die groepen
df01 = df.merge(
    groepen_depot_start_eind,
    on=["Date", "SerialNumber"],
    how="inner"
)

df01

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,967 (VDG-43-S),14-10-2025,07:50,08:20,09:41,"35,70",00:29,1:20,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:50,0:29,1:20,0:00,"35,70",51.780592,4.638408
1,967 (VDG-43-S),14-10-2025,09:41,09:42,10:08,"0,10",00:01,0:26,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,2:17,0:30,1:46,0:00,"35,80",51.780628,4.639095
2,967 (VDG-43-S),14-10-2025,10:08,10:47,11:21,"43,10",00:38,0:33,"Ronsseweg 410, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Ronsseweg 410,2803ZX,Gouda,NaN,0:00,3:30,1:09,2:20,0:00,"78,90",52.018870,4.705445
3,967 (VDG-43-S),14-10-2025,11:21,11:30,11:54,"1,60",00:09,0:24,"Van De Puttestraat 119, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Van De Puttestraat 119,2804JL,Gouda,NaN,0:00,4:03,1:18,2:45,0:00,"80,50",52.027592,4.708583
4,967 (VDG-43-S),14-10-2025,11:54,12:06,13:26,"3,00",00:11,1:19,"De Lange Van Wijngaardenstraat 5, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,De Lange Van Wijngaardenstraat 5,2806WN,Gouda,NaN,0:00,5:35,1:29,4:05,0:00,"83,50",52.013176,4.718882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
2742,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
2743,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400
2744,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293
2745,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417

In [28]:
# meerdere latitutes voor zelfde adres dus nu de gemiddelde nemen van de coordinaten en dat gebruiken als coördinaat van dat adres
coords_per_adres = df01.groupby("VisitingAddress")[["Lat", "Long"]].mean().reset_index()

In [29]:
df01 = df01.drop(columns=["Lat", "Long"])

df01 = df01.merge(coords_per_adres, on="VisitingAddress", how="left")

In [30]:
df01.info()

<class 'pandas.DataFrame'>
RangeIndex: 2746 entries, 0 to 2745
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SerialNumber         2746 non-null   str
 1   Date                 2746 non-null   str
 2   StartRide            2746 non-null   str
 3   Start                2746 non-null   str
 4   Stop                 2746 non-null   str
 5   Distance             2746 non-null   str
 6   TravelTime           2746 non-null   str
 7   Duration             2746 non-null   str
 8   VisitingAddress      2746 non-null   str
 9   Description          776 non-null    str
 10  DriverName           2568 non-null   str
 11  GroupName            2746 non-null   str
 12  Contact              0 non-null      object
 13  Remark               0 non-null      str
 14  To                   2744 non-null   str
 15  ZipCode              2741 non-null   str
 16  City                 2746 non-null   str
 17  ProjectNumber        776 non-null    float64
 18  Break                2746 non-null   str
 19  TotalTime            2746 non-null   str
 20  TotalTravelTime      2746 non-null   str
 21  TotalDuration        2746 non-null   str
 22  TotalTimeMinusBreak  2746 non-null   str
 23  TotalDistance        2746 non-null   str
 24  Lat                  2746 non-null   float64
 25  Long                 2746 non-null   float64
dtypes: float64(3), object(1), str(22)
memory usage: 557.9+ KB

In [31]:
# missende waarden zipcode toevoegen
df01[df01['ZipCode'].isna()]

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
744,1313 (VPS-11-J),18-02-2025,07:26,07:26,08:09,"0,00",00:00,0:42,", ?",NaN,Robin Kovács,BBT Dordrecht/MHG,NaN,NaN,NaN,NaN,?,NaN,0:00,1:31,0:39,0:51,0:00,"34,50",0.000000,0.000000
2208,1705 (V-18-FXR),14-08-2025,10:29,11:01,11:01,"30,74",00:32,0:00,De Val,NaN,Marcus Dekker,BBT Dordrecht/MHG,NaN,NaN,NaN,NaN,De Val,NaN,0:00,4:15,2:19,1:56,0:00,"158,79",51.622348,3.904958
2223,1705 (V-18-FXR),15-08-2025,10:20,10:58,11:07,"30,84",00:38,0:08,"Straalweg 10, Zierikzee",NaN,Marcus Dekker,BBT Dordrecht/MHG,NaN,NaN,Straalweg 10,NaN,Zierikzee,NaN,0:00,4:39,2:24,2:15,0:00,"126,98",51.628897,3.913879
2444,1775 (V-11-GGL),06-03-2025,11:19,11:20,11:36,"0,17",00:01,0:16,"Amphia Ziekenhuis Molengracht 1, Breda",NaN,Frido Wijnen,BBT Dordrecht/MHG,NaN,NaN,Amphia Ziekenhuis Molengracht 1,NaN,Breda,NaN,0:00,4:09,2:00,2:09,0:00,"137,36",51.582759,4.798088
2457,1775 (V-11-GGL),26-03-2025,11:04,11:05,12:21,"0,18",00:00,1:16,"Amphia Ziekenhuis Molengracht 1, Breda",NaN,Geertjan van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Amphia Ziekenhuis Molengracht 1,NaN,Breda,NaN,0:00,4:33,1:15,3:17,0:00,"45,42",51.582759,4.798088

In [32]:
df01.loc[[2444, 2457], "ZipCode"] = "4818 CK"
df01.loc[[2223], "ZipCode"] = "4301 RJ"

In [33]:
# van het ene voertuig en die dag er geheel uithalen, want niets bekend over die coordinaten
df02 = df01[
    ~(
        (df01["Date"] == "18-02-2025") &
        (df01["SerialNumber"] == '1313 (VPS-11-J)')
    )
]

df02

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,967 (VDG-43-S),14-10-2025,07:50,08:20,09:41,"35,70",00:29,1:20,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:50,0:29,1:20,0:00,"35,70",51.780575,4.638942
1,967 (VDG-43-S),14-10-2025,09:41,09:42,10:08,"0,10",00:01,0:26,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,2:17,0:30,1:46,0:00,"35,80",51.780575,4.638942
2,967 (VDG-43-S),14-10-2025,10:08,10:47,11:21,"43,10",00:38,0:33,"Ronsseweg 410, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Ronsseweg 410,2803ZX,Gouda,NaN,0:00,3:30,1:09,2:20,0:00,"78,90",52.018912,4.705532
3,967 (VDG-43-S),14-10-2025,11:21,11:30,11:54,"1,60",00:09,0:24,"Van De Puttestraat 119, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Van De Puttestraat 119,2804JL,Gouda,NaN,0:00,4:03,1:18,2:45,0:00,"80,50",52.027633,4.708537
4,967 (VDG-43-S),14-10-2025,11:54,12:06,13:26,"3,00",00:11,1:19,"De Lange Van Wijngaardenstraat 5, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,De Lange Van Wijngaardenstraat 5,2806WN,Gouda,NaN,0:00,5:35,1:29,4:05,0:00,"83,50",52.013176,4.718882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
2742,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
2743,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.791025,4.665775
2744,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783431,4.686274
2745,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780575,4.638942

In [34]:
# rij van traveltime en duration omzetten naar aantal minuten in plaats van string
# Zet om naar timedelta
df02['TravelTime'] = pd.to_timedelta(df02['TravelTime'] + ':00')
df02['Duration'] = pd.to_timedelta(df02['Duration'] + ':00')
df02.info()

<class 'pandas.DataFrame'>
Index: 2730 entries, 0 to 2745
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SerialNumber         2730 non-null   str
 1   Date                 2730 non-null   str
 2   StartRide            2730 non-null   str
 3   Start                2730 non-null   str
 4   Stop                 2730 non-null   str
 5   Distance             2730 non-null   str
 6   TravelTime           2730 non-null   timedelta64[us]
 7   Duration             2730 non-null   timedelta64[us]
 8   VisitingAddress      2730 non-null   str
 9   Description          773 non-null    str
 10  DriverName           2552 non-null   str
 11  GroupName            2730 non-null   str
 12  Contact              0 non-null      object
 13  Remark               0 non-null      str
 14  To                   2729 non-null   str
 15  ZipCode              2729 non-null   str
 16  City                 2730 non-null   str
 17  ProjectNumber        773 non-null    float64
 18  Break                2730 non-null   str
 19  TotalTime            2730 non-null   str
 20  TotalTravelTime      2730 non-null   str
 21  TotalDuration        2730 non-null   str
 22  TotalTimeMinusBreak  2730 non-null   str
 23  TotalDistance        2730 non-null   str
 24  Lat                  2730 non-null   float64
 25  Long                 2730 non-null   float64
dtypes: float64(3), object(1), str(20), timedelta64[us](2)
memory usage: 575.9+ KB

In [35]:
# omzetten naar minuten
df02['TravelTime'] = df02['TravelTime'].dt.total_seconds() // 60
df02['Duration'] = df02['Duration'].dt.total_seconds() // 60

In [36]:
df02['From'] = (
    df02.groupby(['Date', 'SerialNumber'])['VisitingAddress']
    .shift(1)
)

df02['From'] = df02['From'].fillna(depot_naam)

In [37]:
df02.head(20)

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,From
0,967 (VDG-43-S),14-10-2025,07:50,08:20,09:41,"35,70",29.0,80.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:50,0:29,1:20,0:00,"35,70",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
1,967 (VDG-43-S),14-10-2025,09:41,09:42,10:08,"0,10",1.0,26.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,2:17,0:30,1:46,0:00,"35,80",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2,967 (VDG-43-S),14-10-2025,10:08,10:47,11:21,"43,10",38.0,33.0,"Ronsseweg 410, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Ronsseweg 410,2803ZX,Gouda,NaN,0:00,3:30,1:09,2:20,0:00,"78,90",52.018912,4.705532,"Kamerlingh Onnesweg 9, Dordrecht"
3,967 (VDG-43-S),14-10-2025,11:21,11:30,11:54,"1,60",9.0,24.0,"Van De Puttestraat 119, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Van De Puttestraat 119,2804JL,Gouda,NaN,0:00,4:03,1:18,2:45,0:00,"80,50",52.027633,4.708537,"Ronsseweg 410, Gouda"
4,967 (VDG-43-S),14-10-2025,11:54,12:06,13:26,"3,00",11.0,79.0,"De Lange Van Wijngaardenstraat 5, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,De Lange Van Wijngaardenstraat 5,2806WN,Gouda,NaN,0:00,5:35,1:29,4:05,0:00,"83,50",52.013176,4.718882,"Van De Puttestraat 119, Gouda"
5,967 (VDG-43-S),14-10-2025,13:26,13:37,15:40,"1,20",11.0,123.0,"manege 1, gouda",manege,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,manege 1,2806 zc,gouda,0.0,0:00,7:49,1:41,6:08,0:00,"84,70",52.007652,4.718276,"De Lange Van Wijngaardenstraat 5, Gouda"
6,967 (VDG-43-S),14-10-2025,15:40,16:47,09:12,"51,10",66.0,984.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,8:56,2:47,6:08,8:56,"135,80",51.780575,4.638942,"manege 1, gouda"
7,967 (VDG-43-S),23-10-2025,07:02,07:02,09:27,"0,00",0.0,144.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,2:24,0:00,2:24,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
8,967 (VDG-43-S),23-10-2025,09:27,10:11,12:45,"40,00",44.0,154.0,"Sint Liduinastraat 15, Schiedam",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Sint Liduinastraat 15,3117CN,Schiedam,NaN,0:00,5:43,0:44,4:58,0:00,"40,00",51.914049,4.394404,"Kamerlingh Onnesweg 9, Dordrecht"
9,967 (VDG-43-S),23-10-2025,12:45,12:55,15:37,"1,30",9.0,162.0,"Loeffstraat 103, Schiedam",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Loeffstraat 103,3119SG,Schiedam,NaN,0:00,8:35,0:54,7:40,0:00,"41,30",51.920100,4.388351,"Sint Liduinastraat 15, Schiedam"
10,967 (VDG-43-S),23-10-2025,15:37,15:42,15:51,"1,60",4.0,8.0,"Sint Liduinastraat 15, Schiedam",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Sint Liduinastraat 15,3117CN,Schiedam,NaN,0:00,8:48,0:59,7:49,0:00,"42,90",51.914049,4.394404,"Loeffstraat 103, Schiedam"
11,967 (VDG-43-S),23-10-2025,15:51,16:53,07:15,"36,10",61.0,862.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,9:50,2:01,7:49,9:50,"79,00",51.780575,4.638942,"Sint Liduinastraat 15, Schiedam"
12,967 (VDG-43-S),07-11-2025,08:56,09:38,08:37,"35,70",41.0,5699.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,170:32,2:47,167:44,170:32,"119,20",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
13,967 (VDG-43-S),14-11-2025,09:41,11:12,11:14,"107,20",91.0,2.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Auto Mertens Auto Mertens,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:33,1:31,0:02,0:00,"107,20",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
14,967 (VDG-43-S),14-11-2025,11:14,11:16,07:02,"0,20",2.0,9825.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Auto Mertens Auto Mertens,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,165:20,1:33,163:47,0:00,"107,40",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
15,967 (VDG-43-S),21-11-2025,07:02,07:03,08:49,"0,10",1.0,8746.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,165:22,1:34,163:47,165:22,"107,50",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
16,967 (VDG-43-S),23-12-2025,08:10,08:42,14:36,"35,70",31.0,354.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,6:25,0:31,5:54,0:00,"35,70",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
17,967 (VDG-43-S),23-12-2025,14:36,14:38,15:07,"0,10",2.0,28.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,6:56,0:33,6:22,6:56,"35,80",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
18,1001 (VFK-90-R),25-04-2025,06:59,07:13,07:44,"12,97",14.0,30.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Aart van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:45,0:14,0:30,0:00,"12,97",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
19,1001 (VFK-90-R),25-04-2025,07:44,08:20,09:55,"41,04",36.0,94.0,"Onyxdijk 183, Roosendaal",NaN,Aart van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Onyxdijk 183,4706LL,Roosendaal,NaN,0:00,2:56,0:51,2:04,0:00,"54,01",51.518541,4.491785,"Kamerlingh Onnesweg 9, Dordrecht"

In [38]:
df02[df02['VisitingAddress'] == df02['From']]

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,From
0,967 (VDG-43-S),14-10-2025,07:50,08:20,09:41,"35,70",29.0,80.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:50,0:29,1:20,0:00,"35,70",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
1,967 (VDG-43-S),14-10-2025,09:41,09:42,10:08,"0,10",1.0,26.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,2:17,0:30,1:46,0:00,"35,80",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
7,967 (VDG-43-S),23-10-2025,07:02,07:02,09:27,"0,00",0.0,144.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,2:24,0:00,2:24,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
12,967 (VDG-43-S),07-11-2025,08:56,09:38,08:37,"35,70",41.0,5699.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,170:32,2:47,167:44,170:32,"119,20",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
13,967 (VDG-43-S),14-11-2025,09:41,11:12,11:14,"107,20",91.0,2.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Auto Mertens Auto Mertens,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:33,1:31,0:02,0:00,"107,20",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2724,1775 (V-11-GGL),10-11-2025,15:50,15:51,07:39,"0,20",1.0,947.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Frido Wijnen,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,8:49,4:04,4:45,8:49,"204,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2725,1775 (V-11-GGL),25-11-2025,07:00,07:01,08:12,"0,16",1.0,70.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Frido Wijnen,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:11,0:01,1:10,0:00,"0,16",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2734,1775 (V-11-GGL),25-11-2025,15:29,15:31,08:06,"0,19",1.0,995.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Frido Wijnen,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,8:30,2:41,5:48,8:30,"78,79",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2735,1775 (V-11-GGL),31-12-2025,06:28,06:51,07:04,"25,68",23.0,12.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:36,0:23,0:12,0:00,"25,68",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2736,1775 (V-11-GGL),31-12-2025,07:04,07:05,07:42,"0,18",1.0,37.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:14,0:24,0:50,0:00,"25,86",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"

In [39]:
(
    (df02['VisitingAddress'] == df02['From']) &
    (df02['VisitingAddress'] == depot_naam)
).sum()

np.int64(529)

In [40]:
verdacht = df02[
    (df02['VisitingAddress'] == depot_naam) &
    (df02['From'] == depot_naam) &
    (df02['Duration'] > 180)
]

verdacht

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,From
12,967 (VDG-43-S),07-11-2025,08:56,09:38,08:37,"35,70",41.0,5699.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,170:32,2:47,167:44,170:32,"119,20",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
14,967 (VDG-43-S),14-11-2025,11:14,11:16,07:02,"0,20",2.0,9825.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Auto Mertens Auto Mertens,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,165:20,1:33,163:47,0:00,"107,40",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
15,967 (VDG-43-S),21-11-2025,07:02,07:03,08:49,"0,10",1.0,8746.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,165:22,1:34,163:47,165:22,"107,50",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
16,967 (VDG-43-S),23-12-2025,08:10,08:42,14:36,"35,70",31.0,354.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,6:25,0:31,5:54,0:00,"35,70",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
28,1001 (VFK-90-R),25-04-2025,15:49,15:50,07:14,"0,00",0.0,16764.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,8:51,4:10,4:40,8:51,"211,19",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2682,1775 (V-11-GGL),14-10-2025,14:45,14:45,08:18,"0,01",0.0,1052.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,6:48,2:15,4:33,6:48,"67,36",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2693,1775 (V-11-GGL),29-10-2025,14:32,14:32,07:48,"0,01",0.0,1035.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Frido Wijnen,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,6:43,3:04,3:39,6:43,"92,46",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2706,1775 (V-11-GGL),04-11-2025,14:55,14:56,07:49,"0,20",0.0,1013.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Frido Wijnen,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,6:57,2:49,4:07,6:57,"123,54",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2724,1775 (V-11-GGL),10-11-2025,15:50,15:51,07:39,"0,20",1.0,947.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Frido Wijnen,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,8:49,4:04,4:45,8:49,"204,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2734,1775 (V-11-GGL),25-11-2025,15:29,15:31,08:06,"0,19",1.0,995.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Frido Wijnen,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,8:30,2:41,5:48,8:30,"78,79",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"

In [41]:
df02

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,From
0,967 (VDG-43-S),14-10-2025,07:50,08:20,09:41,"35,70",29.0,80.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:50,0:29,1:20,0:00,"35,70",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
1,967 (VDG-43-S),14-10-2025,09:41,09:42,10:08,"0,10",1.0,26.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,2:17,0:30,1:46,0:00,"35,80",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2,967 (VDG-43-S),14-10-2025,10:08,10:47,11:21,"43,10",38.0,33.0,"Ronsseweg 410, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Ronsseweg 410,2803ZX,Gouda,NaN,0:00,3:30,1:09,2:20,0:00,"78,90",52.018912,4.705532,"Kamerlingh Onnesweg 9, Dordrecht"
3,967 (VDG-43-S),14-10-2025,11:21,11:30,11:54,"1,60",9.0,24.0,"Van De Puttestraat 119, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Van De Puttestraat 119,2804JL,Gouda,NaN,0:00,4:03,1:18,2:45,0:00,"80,50",52.027633,4.708537,"Ronsseweg 410, Gouda"
4,967 (VDG-43-S),14-10-2025,11:54,12:06,13:26,"3,00",11.0,79.0,"De Lange Van Wijngaardenstraat 5, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,De Lange Van Wijngaardenstraat 5,2806WN,Gouda,NaN,0:00,5:35,1:29,4:05,0:00,"83,50",52.013176,4.718882,"Van De Puttestraat 119, Gouda"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",10.0,50.0,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793,"Crooswijksesingel 18, Rotterdam"
2742,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",19.0,19.0,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842,"Van Beethovenlaan 56, Rotterdam"
2743,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",30.0,17.0,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.791025,4.665775,"Dotterlei 143, Capelle Aan Den Ijssel"
2744,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",8.0,7.0,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783431,4.686274,"Groen Van Prinstererweg 38, Dordrecht"
2745,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",8.0,11.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780575,4.638942,"Minnaertweg 4, Dordrecht"

## Zorgen dat de dubbele depot naam wordt verwijderd

In [42]:
import pandas as pd

def clean_depot_rows_start_end(
    df,
    depot_name,
    vehicle_col='SerialNumber',
    date_col='Date',
    address_col='VisitingAddress',
    sort_col='StartRide'
):
    """
    Houdt per voertuig + datum:
    - aan het BEGIN slechts 1 depot-rij over
    - aan het EINDE slechts 1 depot-rij over

    Aaneengesloten dubbele depot-rijen aan begin/einde worden verwijderd.
    """

    df = df.copy()
    df[date_col] = pd.to_datetime(df[date_col], errors='coerce')
    df = df.sort_values([vehicle_col, date_col, sort_col]).copy()

    cleaned_groups = []
    removed_rows = []

    for (veh, dt), group in df.groupby([vehicle_col, date_col], sort=False):
        group = group.copy().reset_index()
        group['_orig_index'] = group['index']
        group = group.drop(columns=['index'])

        # depot indicator
        is_depot = group[address_col].eq(depot_name)

        # -----------------
        # begin van de dag
        # -----------------
        first_non_depot = (~is_depot).idxmax() if (~is_depot).any() else None

        remove_start_idx = []
        if len(group) > 0 and is_depot.iloc[0]:
            if first_non_depot is None:
                # hele dag bestaat alleen uit depot-rijen -> houd 1 rij over
                remove_start_idx = list(range(1, len(group)))
            else:
                # eerste blok depot-rijen: houd alleen de eerste
                if first_non_depot > 1:
                    remove_start_idx = list(range(1, first_non_depot))

        # tijdelijk verwijderen voor analyse einde
        keep_mask = pd.Series(True, index=group.index)
        keep_mask.loc[remove_start_idx] = False
        temp_group = group[keep_mask].copy().reset_index(drop=True)

        is_depot_temp = temp_group[address_col].eq(depot_name)

        # -----------------
        # einde van de dag
        # -----------------
        remove_end_orig_idx = []

        if len(temp_group) > 0 and is_depot_temp.iloc[-1]:
            non_depot_positions = temp_group.index[~is_depot_temp]

            if len(non_depot_positions) == 0:
                # alles is depot -> houd 1 rij over
                remove_end_positions = list(range(1, len(temp_group)))
            else:
                last_non_depot = non_depot_positions.max()
                # alles na laatste niet-depot is eindblok depot
                depot_tail_start = last_non_depot + 1
                if depot_tail_start < len(temp_group) - 1:
                    # houd alleen de eerste depot-rij van het eindblok
                    remove_end_positions = list(range(depot_tail_start + 1, len(temp_group)))
                else:
                    remove_end_positions = []

            remove_end_orig_idx = temp_group.loc[remove_end_positions, '_orig_index'].tolist()
        else:
            remove_end_positions = []

        remove_start_orig_idx = group.loc[remove_start_idx, '_orig_index'].tolist()
        remove_all_orig_idx = set(remove_start_orig_idx + remove_end_orig_idx)

        removed = df.loc[df.index.isin(remove_all_orig_idx)].copy()
        kept = df.loc[
            df.index.isin(group['_orig_index']) & ~df.index.isin(remove_all_orig_idx)
        ].copy()

        removed_rows.append(removed)
        cleaned_groups.append(kept)

    df_clean = pd.concat(cleaned_groups, ignore_index=False).sort_values(
        [vehicle_col, date_col, sort_col]
    )
    df_removed = pd.concat(removed_rows, ignore_index=False).sort_values(
        [vehicle_col, date_col, sort_col]
    )

    return df_clean, df_removed

In [43]:
df03, df_removed = clean_depot_rows_start_end(
    df=df02,
    depot_name=depot_naam,
    vehicle_col='SerialNumber',
    date_col='Date',
    address_col='VisitingAddress',
    sort_col='StartRide'
)

C:\Users\aniek.kasius\AppData\Local\Temp\ipykernel_6744\2025942214.py:20: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[date_col] = pd.to_datetime(df[date_col], errors='coerce')

In [44]:
print("Aantal verwijderde rijen:", len(df_removed))

print(
    df_removed[['SerialNumber', 'Date', 'VisitingAddress']]
)

Aantal verwijderde rijen: 291
         SerialNumber       Date                   VisitingAddress
28    1001 (VFK-90-R) 2025-04-25  Kamerlingh Onnesweg 9, Dordrecht
35    1026 (VFR-80-J) 2025-10-20  Kamerlingh Onnesweg 9, Dordrecht
39    1047 (VFT-61-Z) 2025-06-20  Kamerlingh Onnesweg 9, Dordrecht
40    1047 (VFT-61-Z) 2025-06-20  Kamerlingh Onnesweg 9, Dordrecht
52    1047 (VFT-61-Z) 2025-06-20  Kamerlingh Onnesweg 9, Dordrecht
...               ...        ...                               ...
2734  1775 (V-11-GGL) 2025-11-25  Kamerlingh Onnesweg 9, Dordrecht
2736  1775 (V-11-GGL) 2025-12-31  Kamerlingh Onnesweg 9, Dordrecht
1      967 (VDG-43-S) 2025-10-14  Kamerlingh Onnesweg 9, Dordrecht
14     967 (VDG-43-S) 2025-11-14  Kamerlingh Onnesweg 9, Dordrecht
17     967 (VDG-43-S) 2025-12-23  Kamerlingh Onnesweg 9, Dordrecht

[291 rows x 3 columns]

In [45]:
verwijderd_per_route = (
    df_removed
    .groupby(['SerialNumber', 'Date'])
    .size()
    .reset_index(name='aantal_verwijderd')
)

print(verwijderd_per_route)

        SerialNumber       Date  aantal_verwijderd
0    1001 (VFK-90-R) 2025-04-25                  1
1    1026 (VFR-80-J) 2025-10-20                  1
2    1047 (VFT-61-Z) 2025-06-20                  3
3    1185 (VJL-22-K) 2025-01-03                  7
4    1185 (VJL-22-K) 2025-01-08                  1
..               ...        ...                ...
167  1775 (V-11-GGL) 2025-11-25                  1
168  1775 (V-11-GGL) 2025-12-31                  1
169   967 (VDG-43-S) 2025-10-14                  1
170   967 (VDG-43-S) 2025-11-14                  1
171   967 (VDG-43-S) 2025-12-23                  1

[172 rows x 3 columns]

In [46]:
print("Origineel:", len(df02))
print("Schoon:", len(df03))

Origineel: 2730
Schoon: 2439

In [47]:
controle = (
    df03
    .sort_values(['SerialNumber', 'Date', 'StartRide'])
    .groupby(['SerialNumber', 'Date'])
    .agg(
        eerste_adres=('VisitingAddress', 'first'),
        laatste_adres=('VisitingAddress', 'last'),
        aantal_rijen=('VisitingAddress', 'size')
    )
    .reset_index()
)

controle['start_bij_depot'] = controle['eerste_adres'].eq(depot_naam)
controle['eindigt_bij_depot'] = controle['laatste_adres'].eq(depot_naam)

controle

,SerialNumber,Date,eerste_adres,laatste_adres,aantal_rijen,start_bij_depot,eindigt_bij_depot
0,1001 (VFK-90-R),2025-04-25,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",10,True,True
1,1001 (VFK-90-R),2025-08-08,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",4,True,True
2,1001 (VFK-90-R),2025-08-19,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",1,True,True
3,1026 (VFR-80-J),2025-10-20,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",1,True,True
4,1026 (VFR-80-J),2025-10-30,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",1,True,True
...,...,...,...,...,...,...,...
229,967 (VDG-43-S),2025-10-23,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",5,True,True
230,967 (VDG-43-S),2025-11-07,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",1,True,True
231,967 (VDG-43-S),2025-11-14,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",1,True,True
232,967 (VDG-43-S),2025-11-21,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",1,True,True
233,967 (VDG-43-S),2025-12-23,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",1,True,True

In [48]:
controle['correct'] = (
    controle['start_bij_depot'] &
    controle['eindigt_bij_depot']
)

In [49]:
goede_routes = controle[controle['correct']]
print(goede_routes)

        SerialNumber       Date                      eerste_adres  \
0    1001 (VFK-90-R) 2025-04-25  Kamerlingh Onnesweg 9, Dordrecht
1    1001 (VFK-90-R) 2025-08-08  Kamerlingh Onnesweg 9, Dordrecht
2    1001 (VFK-90-R) 2025-08-19  Kamerlingh Onnesweg 9, Dordrecht
3    1026 (VFR-80-J) 2025-10-20  Kamerlingh Onnesweg 9, Dordrecht
4    1026 (VFR-80-J) 2025-10-30  Kamerlingh Onnesweg 9, Dordrecht
..               ...        ...                               ...
229   967 (VDG-43-S) 2025-10-23  Kamerlingh Onnesweg 9, Dordrecht
230   967 (VDG-43-S) 2025-11-07  Kamerlingh Onnesweg 9, Dordrecht
231   967 (VDG-43-S) 2025-11-14  Kamerlingh Onnesweg 9, Dordrecht
232   967 (VDG-43-S) 2025-11-21  Kamerlingh Onnesweg 9, Dordrecht
233   967 (VDG-43-S) 2025-12-23  Kamerlingh Onnesweg 9, Dordrecht

                        laatste_adres  aantal_rijen  start_bij_depot  \
0    Kamerlingh Onnesweg 9, Dordrecht            10             True
1    Kamerlingh Onnesweg 9, Dordrecht             4             True
2    Kamerlingh Onnesweg 9, Dordrecht             1             True
3    Kamerlingh Onnesweg 9, Dordrecht             1             True
4    Kamerlingh Onnesweg 9, Dordrecht             1             True
..                                ...           ...              ...
229  Kamerlingh Onnesweg 9, Dordrecht             5             True
230  Kamerlingh Onnesweg 9, Dordrecht             1             True
231  Kamerlingh Onnesweg 9, Dordrecht             1             True
232  Kamerlingh Onnesweg 9, Dordrecht             1             True
233  Kamerlingh Onnesweg 9, Dordrecht             1             True

     eindigt_bij_depot  correct
0                 True     True
1                 True     True
2                 True     True
3                 True     True
4                 True     True
..                 ...      ...
229               True     True
230               True     True
231               True     True
232               True     True
233               True     True

[234 rows x 8 columns]

In [50]:
# kijken naar de rij met de andere missende waarde
gekozen_datum = "14-08-2025"
gekozen_serial = "1705 (V-18-FXR)"

subset = df03[
    (df03["Date"] == gekozen_datum) &
    (df03["SerialNumber"] == gekozen_serial)
]

In [52]:
# van het ene voertuig en die dag er geheel uithalen, want niets bekend over die coordinaten
df04 = df03[
    ~(
        (df03["Date"] == "14-08-2025") &
        (df03["SerialNumber"] == '1705 (V-18-FXR)')
    )
]

df04

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,From
18,1001 (VFK-90-R),2025-04-25,06:59,07:13,07:44,"12,97",14.0,30.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Aart van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:45,0:14,0:30,0:00,"12,97",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
19,1001 (VFK-90-R),2025-04-25,07:44,08:20,09:55,"41,04",36.0,94.0,"Onyxdijk 183, Roosendaal",NaN,Aart van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Onyxdijk 183,4706LL,Roosendaal,NaN,0:00,2:56,0:51,2:04,0:00,"54,01",51.518541,4.491785,"Kamerlingh Onnesweg 9, Dordrecht"
20,1001 (VFK-90-R),2025-04-25,09:55,10:15,10:42,"17,60",20.0,27.0,"Lambertijnenhof 212, Bergen Op Zoom",NaN,Aart van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Lambertijnenhof 212,4614CH,Bergen Op Zoom,NaN,0:00,3:43,1:11,2:32,0:00,"71,61",51.506608,4.293024,"Onyxdijk 183, Roosendaal"
21,1001 (VFK-90-R),2025-04-25,10:42,10:48,10:55,"0,00",5.0,6.0,"Lambertijnenhof 212, Bergen Op Zoom",NaN,Aart van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Lambertijnenhof 212,4614CH,Bergen Op Zoom,NaN,0:00,3:56,1:17,2:38,0:00,"71,61",51.506608,4.293024,"Lambertijnenhof 212, Bergen Op Zoom"
22,1001 (VFK-90-R),2025-04-25,10:55,11:55,12:25,"41,82",60.0,29.0,"Oostelijke Achterweg 20, Middelharnis",NaN,Aart van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Oostelijke Achterweg 20,3241CM,Middelharnis,NaN,0:00,5:26,2:17,3:08,0:00,"113,43",51.757658,4.167531,"Lambertijnenhof 212, Bergen Op Zoom"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,967 (VDG-43-S),2025-10-23,15:51,16:53,07:15,"36,10",61.0,862.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,9:50,2:01,7:49,9:50,"79,00",51.780575,4.638942,"Sint Liduinastraat 15, Schiedam"
12,967 (VDG-43-S),2025-11-07,08:56,09:38,08:37,"35,70",41.0,5699.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,170:32,2:47,167:44,170:32,"119,20",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
13,967 (VDG-43-S),2025-11-14,09:41,11:12,11:14,"107,20",91.0,2.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Auto Mertens Auto Mertens,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:33,1:31,0:02,0:00,"107,20",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
15,967 (VDG-43-S),2025-11-21,07:02,07:03,08:49,"0,10",1.0,8746.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,165:22,1:34,163:47,165:22,"107,50",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
16,967 (VDG-43-S),2025-12-23,08:10,08:42,14:36,"35,70",31.0,354.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,6:25,0:31,5:54,0:00,"35,70",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"

In [53]:
df04['Date'].unique()

<DatetimeArray>
['2025-04-25 00:00:00', '2025-08-08 00:00:00', '2025-08-19 00:00:00',
 '2025-10-20 00:00:00', '2025-10-30 00:00:00', '2025-06-05 00:00:00',
 '2025-06-20 00:00:00', '2025-07-17 00:00:00', '2025-01-03 00:00:00',
 '2025-01-08 00:00:00',
 ...
 '2025-02-19 00:00:00', '2025-03-05 00:00:00', '2025-04-01 00:00:00',
 '2025-05-22 00:00:00', '2025-06-30 00:00:00', '2025-07-15 00:00:00',
 '2025-08-11 00:00:00', '2025-10-13 00:00:00', '2025-11-10 00:00:00',
 '2025-11-07 00:00:00']
Length: 163, dtype: datetime64[us]

In [54]:
result = df04.groupby('Date')['SerialNumber'].nunique()
result

Date
2025-01-03    4
2025-01-06    2
2025-01-07    1
2025-01-08    2
2025-01-10    1
             ..
2025-12-23    2
2025-12-27    1
2025-12-29    1
2025-12-30    1
2025-12-31    3
Name: SerialNumber, Length: 163, dtype: int64

In [55]:
max_datum = result.idxmax()
max_aantal = result.max()

print("Datum met meeste aantal voertuigen:", max_datum)
print("Aantal unieke voertuigen:", max_aantal)

Datum met meeste aantal voertuigen: 2025-01-03 00:00:00
Aantal unieke voertuigen: 4

In [56]:
df05 = df04[df04['Date'] == max_datum]
df05

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,From
54,1185 (VJL-22-K),2025-01-03,08:10,08:10,08:42,"0,00",0.0,32.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
61,1185 (VJL-22-K),2025-01-03,08:45,09:11,09:23,"14,16",26.0,11.0,"Touwbaan 4, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Touwbaan 4,3363WB,Sliedrecht,NaN,0:00,1:13,0:28,0:44,0:00,"14,16",51.826966,4.749114,"Kamerlingh Onnesweg 9, Dordrecht"
62,1185 (VJL-22-K),2025-01-03,09:23,09:29,09:30,"2,22",6.0,0.0,"Kerkbuurt 220, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 220,3361BM,Sliedrecht,NaN,0:00,1:20,0:35,0:45,0:00,"16,38",51.823225,4.768590,"Touwbaan 4, Sliedrecht"
63,1185 (VJL-22-K),2025-01-03,09:30,09:30,09:50,"0,01",0.0,19.0,"Kerkbuurt 220, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 220,3361BM,Sliedrecht,NaN,0:00,1:40,0:35,1:05,0:00,"16,39",51.823225,4.768590,"Kerkbuurt 220, Sliedrecht"
64,1185 (VJL-22-K),2025-01-03,09:50,09:55,10:06,"1,57",4.0,11.0,"Kerkbuurt 143, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 143,3361BE,Sliedrecht,NaN,0:00,1:56,0:39,1:16,0:00,"17,96",51.823264,4.770902,"Kerkbuurt 220, Sliedrecht"
65,1185 (VJL-22-K),2025-01-03,10:06,10:19,10:33,"4,14",12.0,14.0,"Jupiterstraat 257, Hardinxveld-Giessendam",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Jupiterstraat 257,3371TD,Hardinxveld-Giessendam,NaN,0:00,2:23,0:52,1:31,0:00,"22,10",51.823749,4.822809,"Kerkbuurt 143, Sliedrecht"
66,1185 (VJL-22-K),2025-01-03,10:33,10:48,12:22,"10,86",14.0,94.0,"Banneweg 57, Gorinchem",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Banneweg 57,4204AA,Gorinchem,NaN,0:00,4:12,1:07,3:05,0:00,"32,96",51.838450,4.956741,"Jupiterstraat 257, Hardinxveld-Giessendam"
67,1185 (VJL-22-K),2025-01-03,12:22,13:18,13:24,"33,32",55.0,6.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:14,2:02,3:11,0:00,"66,28",51.780575,4.638942,"Banneweg 57, Gorinchem"
1264,1597 (VZT-42-V),2025-01-03,07:55,08:22,08:34,"0,02",26.0,12.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:38,0:26,0:12,0:00,"0,02",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
1265,1597 (VZT-42-V),2025-01-03,08:34,08:56,09:15,"18,51",21.0,19.0,"Oosterhagen 17, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Oosterhagen 17,3078CL,Rotterdam,NaN,0:00,1:19,0:48,0:31,0:00,"18,53",51.888750,4.559416,"Kamerlingh Onnesweg 9, Dordrecht"
1266,1597 (VZT-42-V),2025-01-03,09:15,09:36,09:45,"7,80",20.0,9.0,"Boergoensestraat 128, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Boergoensestraat 128,3082KD,Rotterdam,NaN,0:00,1:49,1:08,0:40,0:00,"26,33",51.891205,4.470011,"Oosterhagen 17, Rotterdam"
1267,1597 (VZT-42-V),2025-01-03,09:45,10:04,10:04,"2,35",18.0,0.0,"Maashaven O.Z. 103, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Maashaven O.Z. 103,3072HS,Rotterdam,NaN,0:00,2:08,1:27,0:41,0:00,"28,68",51.901234,4.496563,"Boergoensestraat 128, Rotterdam"
1268,1597 (VZT-42-V),2025-01-03,10:04,10:20,11:16,"7,23",15.0,56.0,"Motorstraat 96, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Motorstraat 96,3083AP,Rotterdam,NaN,0:00,3:21,1:43,1:37,0:00,"35,91",51.887398,4.495184,"Maashaven O.Z. 103, Rotterdam"
1269,1597 (VZT-42-V),2025-01-03,11:16,11:29,12:01,"3,64",13.0,32.0,"Haastrechtstraat 130, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Haastrechtstraat 130,3079DC,Rotterdam,NaN,0:00,4:06,1:56,2:09,0:00,"39,55",51.880008,4.536397,"Motorstraat 96, Rotterdam"
1270,1597 (VZT-42-V),2025-01-03,12:01,12:07,12:20,"1,93",5.0,12.0,"Pietersdijk 60, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Pietersdijk 60,3079TD,Rotterdam,NaN,0:00,4:24,2:02,2:21,0:00,"41,48",51.876503,4.553646,"Haastrechtstraat 130, Rotterdam"
1271,1597 (VZT-42-V),2025-01-03,12:20,12:27,12:35,"2,21",7.0,7.0,"Oosterhagen 17, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Oosterhagen 17,3078CL,Rotterdam,NaN,0:00,4:39,2:09,2:29,0:00,"43,69",51.888750,4.559416,"Pietersdijk 60, Rotterdam"
1272,1597 (VZT-42-V),2025-01-03,12:35,12:52,12:58,"11,07",17.0,5.0,"Reling 19, Barendrecht",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Reling 19,2993DN,Barendrecht,NaN,0:00,5:03,2:27,2:35,0:00,"54,76",51.849359,4.499366,"Oosterhagen 17, Rotterdam"
1273,1597 (VZT-42-V),2025-01-03,12:58,13:25,13:34,"21,97",26.0,9.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:39,2:54,2:44,0:00,"76,73",51.780575,4.638942,"Reling 19, Barendrecht"
1511,1702 (V-19-FXR),2025-01-03,06:35,06:58,07:24,"24,64",22.0,26.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:49,0:22,0:26,0:00,"24,64",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
1512,1702 (V-19-FXR),2025-01-03,07:24,08:08,08:11,"60,56",43.0,2.0,"De Poort 24, Rilland",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,De Poort 24,4411PA,Rilland,NaN,0:00,1:35,1:06,0:29,0:00,"85,20",51.422283,4.191320,"Kamerlingh Onnesweg 9, Dordrecht"
1513,1702 (V-19-FXR),2025-01-03,08:11,08:17,08:22,"7,25",6.0,4.0,"Vliete 1, Krabbendijke",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Vliete 1,4413RX,Krabbendijke,NaN,0:00,1:46,1:12,0:33,0:00,"92,45",51.422752,4.096608,"De Poort 24, Rilland"
1514,1702 (V-19-FXR),2025-01-03,08:22,09:01,09:16,"58,17",39.0,14.0,"Rooseveltlaan 1, Axel",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Rooseveltlaan 1,4571HT,Axel,NaN,0:00,2:40,1:52,0:48,0:00,"150,62",51.264685,3.901397,"Vliete 1, Krabbendijke"
1515,1702 (V-19-FXR),2025-01-03,09:16,09:25,09:47,"7,16",8.0,22.0,"Molenstraat 95, Zaamslag",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Molenstraat 95,4543CN,Zaamslag,NaN,0:00,3:11,2:01,1:10,0:00,"157,78",51.309240,3.907953,"Rooseveltlaan 1, Axel"
1516,1702 (V-19-FXR),2025-01-03,09:47,09:58,10:49,"7,01",11.0,51.0,"Pattistpark 137, Terneuzen",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Pattistpark 137,4532HZ,Terneuzen,NaN,0:00,4:14,2:12,2:01,0:00,"164,79",51.334506,3.856501,"Molenstraat 95, Zaamslag"
1517,1702 (V-19-FXR),2025-01-03,10:49,10:53,11:40,"2,43",4.0,46.0,"Bachlaan 88, Terneuzen",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Bachlaan 88,4536GD,Terneuzen,NaN,0:00,5:05,2:16,2:48,0:00,"167,22",51.319094,3.846695,"Pattistpark 137, Terneuzen"
1518,1702 (V-19-FXR),2025-01-03,11:40,12:13,12:35,"33,41",32.0,22.0,"Agaat 2 -12 , Middelburg",Stichting Philadelphia Zorg - Agaat Wonen (WL),Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Agaat 2 -12,4337 MX,Middelburg,0.0,0:00,5:59,2:49,3:10,0:00,"200,63",51.492920,3.618485,"Bachlaan 88, Terneuzen"
1519,1702 (V-19-FXR),2025-01-03,12:35,12:42,13:09,"2,83",7.0,26.0,"Noordbolwerk 33, Middelburg",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Noordbolwerk 33,4331SH,Middelburg,NaN,0:00,6:33,2:56,3:37,0:00,"203,46",51.504090,3.611025,"Agaat 2 -12 , Middelburg"
1520,1702 (V-19-FXR),2025-01-03,13:09,13:12,13:51,"0,79",3.0,38.0,"Latijnse Schoolstraat 19, Middelburg",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Latijnse Schoolstraat 19,4331BP,Middelburg,NaN,0:00,7:15,2:59,4:15,0:00,"204,25",51.499649,3.612773,"Noordbolwerk 33, Middelburg"
1521,1702 (V-19-FXR),2025-01-03,13:51,15:09,15:15,"108,39",78.0,5.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,8:39,4:18,4:21,0:00,"312,64",51.780575,4.638942,"Latijnse Schoolstraat 19, Middelburg"
2390,1775 (V-11-GGL),2025-01-03,06:36,07:06,07:15,"36,04",29.0,8.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:38,0:29,0:08,0:00,"36,04",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2392,1775 (V-11-GGL),2025-01-03,07:45,07:57,08:31,"8,48",11.0,34.0,"Plantageweg 3, Zwijndrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Plantageweg 3,3333GZ,Zwijndrecht,NaN,0:00,1:55,0:41,1:13,0:00,"44,65",51.815547,4.630499,"Kamerlingh Onnesweg 9, Dordrecht"
2393,1775 (V-11-GGL),2025-01-03,08:31,08:51,08:54,"12,78",19.0,3.0,"Bankastraat 158, Dordrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Bankastraat 158,3312GT,Dordrecht,NaN,0:00,2:17,1:01,1:16,0:00,"57,43",51.807925,4.686165,"Plantageweg 3, Zwijndrecht"
2394,1775 (V-11-GGL),2025-01-03,08:54,09:00,09:27,"2,60",6.0,26.0,"Albert Schweitzerplaats 1, Dordrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Albert Schweitzerplaats 1,3318AS,Dordrecht,NaN,0:00,2:50,1:07,1:43,0:00,"60,03",51.792806,4.682687,"Bankastraat 158, Dordrecht"
2395,1775 (V-11-GGL),2025-01-03,09:27,09:33,09:37,"2,58",5.0,4.0,"Minnaertweg 4, Dordrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,3:00,1:13,1:47,0:00,"62,61",51.783431,4.686274,"Albert Schweitzerplaats 1, Dordrecht"
2396,1775 (V-11-GGL),2025-01-03,09:37,09:44,10:06,"2,58",6.0,21.0,"Groen Van Prinstererweg 38, Dordrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,3:29,1:20,2:09,0:00,"65,19",51.791025,4.665775,"Minnaertweg 4, Dordrecht"
2397,1775 (V-11-GGL),2025-01-03,10:06,10:14,10:18,"3,40",8.0,3.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,3:41,1:28,2:13,0:00,"68,59",51.780575,4.638942,"Groen Van Prinstererweg 38, Dordrecht"

In [58]:
df05.info()

<class 'pandas.DataFrame'>
Index: 36 entries, 54 to 2397
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SerialNumber         36 non-null     str
 1   Date                 36 non-null     datetime64[us]
 2   StartRide            36 non-null     str
 3   Start                36 non-null     str
 4   Stop                 36 non-null     str
 5   Distance             36 non-null     str
 6   TravelTime           36 non-null     float64
 7   Duration             36 non-null     float64
 8   VisitingAddress      36 non-null     str
 9   Description          9 non-null      str
 10  DriverName           35 non-null     str
 11  GroupName            36 non-null     str
 12  Contact              0 non-null      object
 13  Remark               0 non-null      str
 14  To                   36 non-null     str
 15  ZipCode              36 non-null     str
 16  City                 36 non-null     str
 17  ProjectNumber        9 non-null      float64
 18  Break                36 non-null     str
 19  TotalTime            36 non-null     str
 20  TotalTravelTime      36 non-null     str
 21  TotalDuration        36 non-null     str
 22  TotalTimeMinusBreak  36 non-null     str
 23  TotalDistance        36 non-null     str
 24  Lat                  36 non-null     float64
 25  Long                 36 non-null     float64
 26  From                 36 non-null     str
dtypes: datetime64[us](1), float64(5), object(1), str(20)
memory usage: 7.9+ KB

## Baseline

In [62]:
import pandas as pd

def hhmm_naar_minuten(x):
    if pd.isna(x):
        return 0
    
    x = str(x).strip()

    if x == "" or x.lower() == "nan":
        return 0

    # Als er geen dubbele punt in zit
    if ":" not in x:
        return 0

    delen = x.split(":")

    # hh:mm
    if len(delen) == 2:
        uren = int(delen[0])
        minuten = int(delen[1])
        return uren * 60 + minuten

    # hh:mm:ss
    if len(delen) == 3:
        uren = int(delen[0])
        minuten = int(delen[1])
        seconden = int(delen[2])
        return uren * 60 + minuten + round(seconden / 60)

    return 0


def minuten_naar_tekst(minuten):
    minuten = int(minuten)
    uren = minuten // 60
    rest_minuten = minuten % 60
    
    if uren == 0:
        return f"{rest_minuten} minuten"
    elif rest_minuten == 0:
        return f"{uren} uur"
    else:
        return f"{uren} uur en {rest_minuten} minuten"


# ==============================
# DATA VOORBEREIDEN
# ==============================

df_vrp = df05.copy()

df_vrp["Distance"] = (
    df_vrp["Distance"]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .astype(float)
)

df_vrp["TravelTime_min"] = df_vrp["TravelTime"].apply(hhmm_naar_minuten)
df_vrp["Duration_min"] = df_vrp["Duration"].apply(hhmm_naar_minuten)


# ==============================
# OUTPUT PER BUS
# ==============================

for voertuig, groep in df_vrp.groupby("SerialNumber"):
    
    if "Date" in groep.columns:
        groep = groep.sort_values(["Date", "StartRide"])
    else:
        groep = groep.sort_values("StartRide")
    
    route = groep["VisitingAddress"].astype(str).tolist()
    
    totale_afstand = groep["Distance"].sum()
    totale_reistijd = groep["TravelTime_min"].sum()
    totale_servicetijd = groep["Duration_min"].sum()
    
    print(f"Bus {voertuig}:")
    print(" - ".join(route))
    print(f"Servicetijd (Duration): {minuten_naar_tekst(totale_servicetijd)} totaal")
    print(f"Reistijd (TravelTime): {minuten_naar_tekst(totale_reistijd)} totaal")
    print(f"Totale afstand: {round(totale_afstand, 2)} km")
    print("-" * 60)

Bus 1185 (VJL-22-K):
Kamerlingh Onnesweg 9, Dordrecht - Touwbaan 4, Sliedrecht - Kerkbuurt 220, Sliedrecht - Kerkbuurt 220, Sliedrecht - Kerkbuurt 143, Sliedrecht - Jupiterstraat 257, Hardinxveld-Giessendam - Banneweg 57, Gorinchem - Kamerlingh Onnesweg 9, Dordrecht
Servicetijd (Duration): 0 minuten totaal
Reistijd (TravelTime): 0 minuten totaal
Totale afstand: 66.28 km
------------------------------------------------------------
Bus 1597 (VZT-42-V):
Kamerlingh Onnesweg 9, Dordrecht - Oosterhagen 17, Rotterdam - Boergoensestraat 128, Rotterdam - Maashaven O.Z. 103, Rotterdam - Motorstraat 96, Rotterdam - Haastrechtstraat 130, Rotterdam - Pietersdijk 60, Rotterdam - Oosterhagen 17, Rotterdam - Reling 19, Barendrecht - Kamerlingh Onnesweg 9, Dordrecht
Servicetijd (Duration): 0 minuten totaal
Reistijd (TravelTime): 0 minuten totaal
Totale afstand: 76.73 km
------------------------------------------------------------
Bus 1702 (V-19-FXR):
Kamerlingh Onnesweg 9, Dordrecht - De Poort 24, Rilland - Vliete 1, Krabbendijke - Rooseveltlaan 1, Axel - Molenstraat 95, Zaamslag - Pattistpark 137, Terneuzen - Bachlaan 88, Terneuzen - Agaat 2 -12 , Middelburg - Noordbolwerk 33, Middelburg - Latijnse Schoolstraat 19, Middelburg - Kamerlingh Onnesweg 9, Dordrecht
Servicetijd (Duration): 0 minuten totaal
Reistijd (TravelTime): 0 minuten totaal
Totale afstand: 312.64 km
------------------------------------------------------------
Bus 1775 (V-11-GGL):
Kamerlingh Onnesweg 9, Dordrecht - Plantageweg 3, Zwijndrecht - Bankastraat 158, Dordrecht - Albert Schweitzerplaats 1, Dordrecht - Minnaertweg 4, Dordrecht - Groen Van Prinstererweg 38, Dordrecht - Kamerlingh Onnesweg 9, Dordrecht
Servicetijd (Duration): 0 minuten totaal
Reistijd (TravelTime): 0 minuten totaal
Totale afstand: 68.46 km
------------------------------------------------------------