In [1]:
import pandas as pd
import numpy as np
from math import sin, cos, atan2, sqrt, radians
from ortools.constraint_solver import pywrapcp, routing_enums_pb2

In [ ]:
pd.set_option('display.max_columns', None)
GOOGLE_API_KEY = "AIzaSyBxF_u8cR0AzJZNRgbODy8SzAVB8aVPscA"

In [3]:
df = pd.read_csv(
    'data/Bezoeken per voertuig 01-01-2025 - 31-12-2025.Csv',
    sep=';',
    encoding='utf-16',
    skiprows=1
)

C:\Users\aniek.kasius\AppData\Local\Temp\ipykernel_21664\1523193955.py:1: DtypeWarning: Columns (0: Contact) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [4]:
# Datum en tijd goed zetten
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True, errors="coerce")

# Sorteren op echte ritvolgorde
df = df.sort_values(["Date", "SerialNumber", "StartRide"]).copy()

In [5]:
df

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
4156,1040 (VFT-36-H),2025-01-01,13:57,13:57,13:59,"0,00",00:00,0:01,"Dokter Rietveldplein 22, Papendrecht",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Dokter Rietveldplein 22,3353SJ,Papendrecht,NaN,0:00,0:02,0:00,0:01,0:00,"0,00",51.823878,4.689373
4157,1040 (VFT-36-H),2025-01-01,13:59,14:00,07:04,"0,17",00:00,17:04,"Dokter Rietveldplein 22, Papendrecht",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Dokter Rietveldplein 22,3353SJ,Papendrecht,NaN,0:00,0:03,0:01,0:01,0:03,"0,17",51.823918,4.689510
23890,1326 (VNT-05-X),2025-01-01,10:52,10:54,06:48,"0,56",00:01,19:54,"Slobbengorsweg 100, Papendrecht",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Slobbengorsweg 100,3351LH,Papendrecht,NaN,0:00,0:01,0:01,0:00,0:01,"0,56",51.823409,4.677820
34792,1515 (VVF-65-D),2025-01-01,10:28,11:12,11:28,"55,60",00:43,0:15,"Onyxdijk 167, Roosendaal",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Onyxdijk 167,4706LL,Roosendaal,NaN,0:00,0:59,0:43,0:15,0:00,"55,60",51.518796,4.492111
34793,1515 (VVF-65-D),2025-01-01,11:28,12:08,12:14,"52,00",00:39,0:05,"Prickwaert 66, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Prickwaert 66,3363BD,Sliedrecht,NaN,0:00,1:45,1:23,0:21,0:00,"107,60",51.827532,4.758798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59128,1775 (V-11-GGL),2025-12-31,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
59129,1775 (V-11-GGL),2025-12-31,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
59130,1775 (V-11-GGL),2025-12-31,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400
59131,1775 (V-11-GGL),2025-12-31,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293
59132,1775 (V-11-GGL),2025-12-31,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417

In [6]:
# bekijken welke auto's elke dag naar het depot gaan
depot_naam = "Kamerlingh Onnesweg 9, Dordrecht"

In [7]:
# als de dataframe al in de juiste volgorde staat:
# per Date en SerialNumber de eerste en laatste rij pakken

eerste_stop = (
    df.groupby(["Date", "SerialNumber"], sort=False)
      .first()
      .reset_index()[["Date", "SerialNumber", "VisitingAddress"]]
      .rename(columns={"VisitingAddress": "eerste_stop"})
)

laatste_stop = (
    df.groupby(["Date", "SerialNumber"], sort=False)
      .last()
      .reset_index()[["Date", "SerialNumber", "VisitingAddress"]]
      .rename(columns={"VisitingAddress": "laatste_stop"})
)

# samenvoegen
start_eind_check = eerste_stop.merge(
    laatste_stop,
    on=["Date", "SerialNumber"],
    how="inner"
)

# alleen groepen die starten én eindigen bij depot
groepen_depot_start_eind = start_eind_check[
    (start_eind_check["eerste_stop"] == depot_naam) &
    (start_eind_check["laatste_stop"] == depot_naam)
][["Date", "SerialNumber"]]

# originele dataset filteren op die groepen
df01 = df.merge(
    groepen_depot_start_eind,
    on=["Date", "SerialNumber"],
    how="inner"
)

df01

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,1185 (VJL-22-K),2025-01-03,08:10,08:10,08:42,"0,00",00:00,0:32,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780550,4.638887
1,1185 (VJL-22-K),2025-01-03,08:42,08:42,08:42,"0,00",00:00,0:00,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780622,4.638795
2,1185 (VJL-22-K),2025-01-03,08:42,08:42,08:42,"0,00",00:00,0:00,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780622,4.638792
3,1185 (VJL-22-K),2025-01-03,08:42,08:43,08:43,"0,00",00:00,0:00,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780622,4.638792
4,1185 (VJL-22-K),2025-01-03,08:43,08:43,08:43,"0,00",00:00,0:00,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:33,0:00,0:32,0:00,"0,00",51.780622,4.638792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,1775 (V-11-GGL),2025-12-31,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
2742,1775 (V-11-GGL),2025-12-31,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
2743,1775 (V-11-GGL),2025-12-31,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400
2744,1775 (V-11-GGL),2025-12-31,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293
2745,1775 (V-11-GGL),2025-12-31,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417

In [8]:
# meerdere latitutes voor zelfde adres dus nu de gemiddelde nemen van de coordinaten en dat gebruiken als coördinaat van dat adres
coords_per_adres = df01.groupby("VisitingAddress")[["Lat", "Long"]].mean().reset_index()

In [9]:
df01 = df01.drop(columns=["Lat", "Long"])

df01 = df01.merge(coords_per_adres, on="VisitingAddress", how="left")

In [10]:
df01.info()

<class 'pandas.DataFrame'>
RangeIndex: 2746 entries, 0 to 2745
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SerialNumber         2746 non-null   str
 1   Date                 2746 non-null   datetime64[us]
 2   StartRide            2746 non-null   str
 3   Start                2746 non-null   str
 4   Stop                 2746 non-null   str
 5   Distance             2746 non-null   str
 6   TravelTime           2746 non-null   str
 7   Duration             2746 non-null   str
 8   VisitingAddress      2746 non-null   str
 9   Description          776 non-null    str
 10  DriverName           2568 non-null   str
 11  GroupName            2746 non-null   str
 12  Contact              0 non-null      object
 13  Remark               0 non-null      str
 14  To                   2744 non-null   str
 15  ZipCode              2741 non-null   str
 16  City                 2746 non-null   str
 17  ProjectNumber        776 non-null    float64
 18  Break                2746 non-null   str
 19  TotalTime            2746 non-null   str
 20  TotalTravelTime      2746 non-null   str
 21  TotalDuration        2746 non-null   str
 22  TotalTimeMinusBreak  2746 non-null   str
 23  TotalDistance        2746 non-null   str
 24  Lat                  2746 non-null   float64
 25  Long                 2746 non-null   float64
dtypes: datetime64[us](1), float64(3), object(1), str(21)
memory usage: 557.9+ KB

In [11]:
# missende waarden zipcode toevoegen
df01[df01['ZipCode'].isna()]

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
360,1313 (VPS-11-J),2025-02-18,07:26,07:26,08:09,"0,00",00:00,0:42,", ?",NaN,Robin Kovács,BBT Dordrecht/MHG,NaN,NaN,NaN,NaN,?,NaN,0:00,1:31,0:39,0:51,0:00,"34,50",0.000000,0.000000
546,1775 (V-11-GGL),2025-03-06,11:19,11:20,11:36,"0,17",00:01,0:16,"Amphia Ziekenhuis Molengracht 1, Breda",NaN,Frido Wijnen,BBT Dordrecht/MHG,NaN,NaN,Amphia Ziekenhuis Molengracht 1,NaN,Breda,NaN,0:00,4:09,2:00,2:09,0:00,"137,36",51.582759,4.798088
726,1775 (V-11-GGL),2025-03-26,11:04,11:05,12:21,"0,18",00:00,1:16,"Amphia Ziekenhuis Molengracht 1, Breda",NaN,Geertjan van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Amphia Ziekenhuis Molengracht 1,NaN,Breda,NaN,0:00,4:33,1:15,3:17,0:00,"45,42",51.582759,4.798088
1788,1705 (V-18-FXR),2025-08-14,10:29,11:01,11:01,"30,74",00:32,0:00,De Val,NaN,Marcus Dekker,BBT Dordrecht/MHG,NaN,NaN,NaN,NaN,De Val,NaN,0:00,4:15,2:19,1:56,0:00,"158,79",51.622348,3.904958
1814,1705 (V-18-FXR),2025-08-15,10:20,10:58,11:07,"30,84",00:38,0:08,"Straalweg 10, Zierikzee",NaN,Marcus Dekker,BBT Dordrecht/MHG,NaN,NaN,Straalweg 10,NaN,Zierikzee,NaN,0:00,4:39,2:24,2:15,0:00,"126,98",51.628897,3.913879

In [12]:
df01.loc[[546, 726], "ZipCode"] = "4818 CK"
df01.loc[[1814], "ZipCode"] = "4301 RJ"

In [13]:
# van het ene voertuig en die dag er geheel uithalen, want niets bekend over die coordinaten
df02 = df01[
    ~(
        (df01["Date"] == "18-02-2025") &
        (df01["SerialNumber"] == '1313 (VPS-11-J)')
    )
]

df02

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,1185 (VJL-22-K),2025-01-03,08:10,08:10,08:42,"0,00",00:00,0:32,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942
1,1185 (VJL-22-K),2025-01-03,08:42,08:42,08:42,"0,00",00:00,0:00,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942
2,1185 (VJL-22-K),2025-01-03,08:42,08:42,08:42,"0,00",00:00,0:00,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942
3,1185 (VJL-22-K),2025-01-03,08:42,08:43,08:43,"0,00",00:00,0:00,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942
4,1185 (VJL-22-K),2025-01-03,08:43,08:43,08:43,"0,00",00:00,0:00,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:33,0:00,0:32,0:00,"0,00",51.780575,4.638942
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,1775 (V-11-GGL),2025-12-31,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
2742,1775 (V-11-GGL),2025-12-31,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
2743,1775 (V-11-GGL),2025-12-31,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.791025,4.665775
2744,1775 (V-11-GGL),2025-12-31,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783431,4.686274
2745,1775 (V-11-GGL),2025-12-31,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780575,4.638942

In [14]:
# rij van traveltime en duration omzetten naar aantal minuten in plaats van string
# Zet om naar timedelta
df02['TravelTime'] = pd.to_timedelta(df02['TravelTime'] + ':00')
df02['Duration'] = pd.to_timedelta(df02['Duration'] + ':00')
df02.info()

<class 'pandas.DataFrame'>
Index: 2730 entries, 0 to 2745
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SerialNumber         2730 non-null   str
 1   Date                 2730 non-null   datetime64[us]
 2   StartRide            2730 non-null   str
 3   Start                2730 non-null   str
 4   Stop                 2730 non-null   str
 5   Distance             2730 non-null   str
 6   TravelTime           2730 non-null   timedelta64[us]
 7   Duration             2730 non-null   timedelta64[us]
 8   VisitingAddress      2730 non-null   str
 9   Description          773 non-null    str
 10  DriverName           2552 non-null   str
 11  GroupName            2730 non-null   str
 12  Contact              0 non-null      object
 13  Remark               0 non-null      str
 14  To                   2729 non-null   str
 15  ZipCode              2729 non-null   str
 16  City                 2730 non-null   str
 17  ProjectNumber        773 non-null    float64
 18  Break                2730 non-null   str
 19  TotalTime            2730 non-null   str
 20  TotalTravelTime      2730 non-null   str
 21  TotalDuration        2730 non-null   str
 22  TotalTimeMinusBreak  2730 non-null   str
 23  TotalDistance        2730 non-null   str
 24  Lat                  2730 non-null   float64
 25  Long                 2730 non-null   float64
dtypes: datetime64[us](1), float64(3), object(1), str(19), timedelta64[us](2)
memory usage: 575.9+ KB

In [15]:
# omzetten naar minuten
df02['TravelTime'] = df02['TravelTime'].dt.total_seconds() // 60
df02['Duration'] = df02['Duration'].dt.total_seconds() // 60

In [16]:
df02['From'] = (
    df02.groupby(['Date', 'SerialNumber'])['VisitingAddress']
    .shift(1)
)

df02['From'] = df02['From'].fillna(depot_naam)

In [17]:
df02.head(20)

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,From
0,1185 (VJL-22-K),2025-01-03,08:10,08:10,08:42,"0,00",0.0,32.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
1,1185 (VJL-22-K),2025-01-03,08:42,08:42,08:42,"0,00",0.0,0.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2,1185 (VJL-22-K),2025-01-03,08:42,08:42,08:42,"0,00",0.0,0.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
3,1185 (VJL-22-K),2025-01-03,08:42,08:43,08:43,"0,00",0.0,0.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
4,1185 (VJL-22-K),2025-01-03,08:43,08:43,08:43,"0,00",0.0,0.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:33,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
5,1185 (VJL-22-K),2025-01-03,08:43,08:45,08:45,"0,00",1.0,0.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:34,0:02,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
6,1185 (VJL-22-K),2025-01-03,08:45,08:45,08:45,"0,00",0.0,0.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:35,0:02,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
7,1185 (VJL-22-K),2025-01-03,08:45,09:11,09:23,"14,16",26.0,11.0,"Touwbaan 4, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Touwbaan 4,3363WB,Sliedrecht,NaN,0:00,1:13,0:28,0:44,0:00,"14,16",51.826966,4.749114,"Kamerlingh Onnesweg 9, Dordrecht"
8,1185 (VJL-22-K),2025-01-03,09:23,09:29,09:30,"2,22",6.0,0.0,"Kerkbuurt 220, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 220,3361BM,Sliedrecht,NaN,0:00,1:20,0:35,0:45,0:00,"16,38",51.823225,4.768590,"Touwbaan 4, Sliedrecht"
9,1185 (VJL-22-K),2025-01-03,09:30,09:30,09:50,"0,01",0.0,19.0,"Kerkbuurt 220, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 220,3361BM,Sliedrecht,NaN,0:00,1:40,0:35,1:05,0:00,"16,39",51.823225,4.768590,"Kerkbuurt 220, Sliedrecht"
10,1185 (VJL-22-K),2025-01-03,09:50,09:55,10:06,"1,57",4.0,11.0,"Kerkbuurt 143, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 143,3361BE,Sliedrecht,NaN,0:00,1:56,0:39,1:16,0:00,"17,96",51.823264,4.770902,"Kerkbuurt 220, Sliedrecht"
11,1185 (VJL-22-K),2025-01-03,10:06,10:19,10:33,"4,14",12.0,14.0,"Jupiterstraat 257, Hardinxveld-Giessendam",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Jupiterstraat 257,3371TD,Hardinxveld-Giessendam,NaN,0:00,2:23,0:52,1:31,0:00,"22,10",51.823749,4.822809,"Kerkbuurt 143, Sliedrecht"
12,1185 (VJL-22-K),2025-01-03,10:33,10:48,12:22,"10,86",14.0,94.0,"Banneweg 57, Gorinchem",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Banneweg 57,4204AA,Gorinchem,NaN,0:00,4:12,1:07,3:05,0:00,"32,96",51.838450,4.956741,"Jupiterstraat 257, Hardinxveld-Giessendam"
13,1185 (VJL-22-K),2025-01-03,12:22,13:18,13:24,"33,32",55.0,6.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:14,2:02,3:11,0:00,"66,28",51.780575,4.638942,"Banneweg 57, Gorinchem"
14,1185 (VJL-22-K),2025-01-03,13:24,13:25,09:09,"0,20",1.0,4063.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:15,2:04,3:11,5:15,"66,48",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
15,1597 (VZT-42-V),2025-01-03,07:55,08:22,08:34,"0,02",26.0,12.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:38,0:26,0:12,0:00,"0,02",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
16,1597 (VZT-42-V),2025-01-03,08:34,08:56,09:15,"18,51",21.0,19.0,"Oosterhagen 17, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Oosterhagen 17,3078CL,Rotterdam,NaN,0:00,1:19,0:48,0:31,0:00,"18,53",51.888750,4.559416,"Kamerlingh Onnesweg 9, Dordrecht"
17,1597 (VZT-42-V),2025-01-03,09:15,09:36,09:45,"7,80",20.0,9.0,"Boergoensestraat 128, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Boergoensestraat 128,3082KD,Rotterdam,NaN,0:00,1:49,1:08,0:40,0:00,"26,33",51.891205,4.470011,"Oosterhagen 17, Rotterdam"
18,1597 (VZT-42-V),2025-01-03,09:45,10:04,10:04,"2,35",18.0,0.0,"Maashaven O.Z. 103, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Maashaven O.Z. 103,3072HS,Rotterdam,NaN,0:00,2:08,1:27,0:41,0:00,"28,68",51.901234,4.496563,"Boergoensestraat 128, Rotterdam"
19,1597 (VZT-42-V),2025-01-03,10:04,10:20,11:16,"7,23",15.0,56.0,"Motorstraat 96, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Motorstraat 96,3083AP,Rotterdam,NaN,0:00,3:21,1:43,1:37,0:00,"35,91",51.887398,4.495184,"Maashaven O.Z. 103, Rotterdam"

In [18]:
df02[df02['VisitingAddress'] == df02['From']]

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,From
0,1185 (VJL-22-K),2025-01-03,08:10,08:10,08:42,"0,00",0.0,32.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
1,1185 (VJL-22-K),2025-01-03,08:42,08:42,08:42,"0,00",0.0,0.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2,1185 (VJL-22-K),2025-01-03,08:42,08:42,08:42,"0,00",0.0,0.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
3,1185 (VJL-22-K),2025-01-03,08:42,08:43,08:43,"0,00",0.0,0.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
4,1185 (VJL-22-K),2025-01-03,08:43,08:43,08:43,"0,00",0.0,0.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:33,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2720,1335 (VPP-97-V),2025-12-30,06:45,07:15,12:32,"24,94",29.0,1757.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:29,0:29,0:00,0:29,"24,94",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2721,1185 (VJL-22-K),2025-12-31,08:06,08:19,08:59,"6,01",12.0,40.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Geertjan van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:52,0:12,0:40,0:00,"6,01",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2734,1480 (VVF-57-D),2025-12-31,06:09,06:28,10:34,"14,78",18.0,246.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Peter van den Bosch,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,4:24,0:18,4:06,4:24,"14,78",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2735,1775 (V-11-GGL),2025-12-31,06:28,06:51,07:04,"25,68",23.0,12.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:36,0:23,0:12,0:00,"25,68",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2736,1775 (V-11-GGL),2025-12-31,07:04,07:05,07:42,"0,18",1.0,37.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:14,0:24,0:50,0:00,"25,86",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"

In [19]:
(
    (df02['VisitingAddress'] == df02['From']) &
    (df02['VisitingAddress'] == depot_naam)
).sum()

np.int64(529)

In [20]:
verdacht = df02[
    (df02['VisitingAddress'] == depot_naam) &
    (df02['From'] == depot_naam) &
    (df02['Duration'] > 180)
]

verdacht

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,From
14,1185 (VJL-22-K),2025-01-03,13:24,13:25,09:09,"0,20",1.0,4063.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:15,2:04,3:11,5:15,"66,48",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
25,1597 (VZT-42-V),2025-01-03,13:34,13:35,07:25,"0,05",0.0,3949.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:40,2:55,2:44,5:40,"76,78",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
39,1702 (V-19-FXR),2025-01-03,15:18,15:18,08:12,"0,00",0.0,3894.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,8:43,4:18,4:24,8:43,"312,67",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
48,1775 (V-11-GGL),2025-01-03,10:18,10:19,07:44,"0,16",0.0,5604.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,3:42,1:29,2:13,3:42,"68,75",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
62,1313 (VPS-11-J),2025-01-06,12:50,12:51,06:27,"0,10",1.0,1056.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Robin Kovács,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,6:27,3:24,3:03,6:27,"97,90",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2668,1185 (VJL-22-K),2025-12-17,16:22,16:22,08:47,"0,06",0.0,2424.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Geertjan van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,8:19,3:56,4:23,8:19,"116,86",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2692,1705 (V-18-FXR),2025-12-19,16:46,16:47,06:30,"0,15",0.0,13783.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Marcus Dekker,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,9:38,4:49,4:49,9:38,"282,18",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2705,967 (VDG-43-S),2025-12-23,08:10,08:42,14:36,"35,70",31.0,354.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,6:25,0:31,5:54,0:00,"35,70",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2720,1335 (VPP-97-V),2025-12-30,06:45,07:15,12:32,"24,94",29.0,1757.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:29,0:29,0:00,0:29,"24,94",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2734,1480 (VVF-57-D),2025-12-31,06:09,06:28,10:34,"14,78",18.0,246.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Peter van den Bosch,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,4:24,0:18,4:06,4:24,"14,78",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"

In [21]:
df02

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,From
0,1185 (VJL-22-K),2025-01-03,08:10,08:10,08:42,"0,00",0.0,32.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
1,1185 (VJL-22-K),2025-01-03,08:42,08:42,08:42,"0,00",0.0,0.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2,1185 (VJL-22-K),2025-01-03,08:42,08:42,08:42,"0,00",0.0,0.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
3,1185 (VJL-22-K),2025-01-03,08:42,08:43,08:43,"0,00",0.0,0.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
4,1185 (VJL-22-K),2025-01-03,08:43,08:43,08:43,"0,00",0.0,0.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:33,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,1775 (V-11-GGL),2025-12-31,09:17,09:28,10:18,"5,81",10.0,50.0,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793,"Crooswijksesingel 18, Rotterdam"
2742,1775 (V-11-GGL),2025-12-31,10:18,10:38,10:57,"6,61",19.0,19.0,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842,"Van Beethovenlaan 56, Rotterdam"
2743,1775 (V-11-GGL),2025-12-31,10:57,11:28,11:46,"22,78",30.0,17.0,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.791025,4.665775,"Dotterlei 143, Capelle Aan Den Ijssel"
2744,1775 (V-11-GGL),2025-12-31,11:46,11:54,12:02,"1,99",8.0,7.0,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783431,4.686274,"Groen Van Prinstererweg 38, Dordrecht"
2745,1775 (V-11-GGL),2025-12-31,12:02,12:10,12:21,"5,18",8.0,11.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780575,4.638942,"Minnaertweg 4, Dordrecht"

## Zorgen dat de dubbele depot naam wordt verwijderd

In [22]:
import pandas as pd

def clean_depot_rows_start_end(
    df,
    depot_name,
    vehicle_col='SerialNumber',
    date_col='Date',
    address_col='VisitingAddress',
    sort_col='StartRide'
):
    """
    Houdt per voertuig + datum:
    - aan het BEGIN slechts 1 depot-rij over
    - aan het EINDE slechts 1 depot-rij over

    Aaneengesloten dubbele depot-rijen aan begin/einde worden verwijderd.
    """

    df = df.copy()
    df[date_col] = pd.to_datetime(df[date_col], errors='coerce')
    df = df.sort_values([vehicle_col, date_col, sort_col]).copy()

    cleaned_groups = []
    removed_rows = []

    for (veh, dt), group in df.groupby([vehicle_col, date_col], sort=False):
        group = group.copy().reset_index()
        group['_orig_index'] = group['index']
        group = group.drop(columns=['index'])

        # depot indicator
        is_depot = group[address_col].eq(depot_name)

        # -----------------
        # begin van de dag
        # -----------------
        first_non_depot = (~is_depot).idxmax() if (~is_depot).any() else None

        remove_start_idx = []
        if len(group) > 0 and is_depot.iloc[0]:
            if first_non_depot is None:
                # hele dag bestaat alleen uit depot-rijen -> houd 1 rij over
                remove_start_idx = list(range(1, len(group)))
            else:
                # eerste blok depot-rijen: houd alleen de eerste
                if first_non_depot > 1:
                    remove_start_idx = list(range(1, first_non_depot))

        # tijdelijk verwijderen voor analyse einde
        keep_mask = pd.Series(True, index=group.index)
        keep_mask.loc[remove_start_idx] = False
        temp_group = group[keep_mask].copy().reset_index(drop=True)

        is_depot_temp = temp_group[address_col].eq(depot_name)

        # -----------------
        # einde van de dag
        # -----------------
        remove_end_orig_idx = []

        if len(temp_group) > 0 and is_depot_temp.iloc[-1]:
            non_depot_positions = temp_group.index[~is_depot_temp]

            if len(non_depot_positions) == 0:
                # alles is depot -> houd 1 rij over
                remove_end_positions = list(range(1, len(temp_group)))
            else:
                last_non_depot = non_depot_positions.max()
                # alles na laatste niet-depot is eindblok depot
                depot_tail_start = last_non_depot + 1
                if depot_tail_start < len(temp_group) - 1:
                    # houd alleen de eerste depot-rij van het eindblok
                    remove_end_positions = list(range(depot_tail_start + 1, len(temp_group)))
                else:
                    remove_end_positions = []

            remove_end_orig_idx = temp_group.loc[remove_end_positions, '_orig_index'].tolist()
        else:
            remove_end_positions = []

        remove_start_orig_idx = group.loc[remove_start_idx, '_orig_index'].tolist()
        remove_all_orig_idx = set(remove_start_orig_idx + remove_end_orig_idx)

        removed = df.loc[df.index.isin(remove_all_orig_idx)].copy()
        kept = df.loc[
            df.index.isin(group['_orig_index']) & ~df.index.isin(remove_all_orig_idx)
        ].copy()

        removed_rows.append(removed)
        cleaned_groups.append(kept)

    df_clean = pd.concat(cleaned_groups, ignore_index=False).sort_values(
        [vehicle_col, date_col, sort_col]
    )
    df_removed = pd.concat(removed_rows, ignore_index=False).sort_values(
        [vehicle_col, date_col, sort_col]
    )

    return df_clean, df_removed

In [23]:
df03, df_removed = clean_depot_rows_start_end(
    df=df02,
    depot_name=depot_naam,
    vehicle_col='SerialNumber',
    date_col='Date',
    address_col='VisitingAddress',
    sort_col='StartRide'
)

In [24]:
print("Aantal verwijderde rijen:", len(df_removed))

print(
    df_removed[['SerialNumber', 'Date', 'VisitingAddress']]
)

Aantal verwijderde rijen: 291
         SerialNumber       Date                   VisitingAddress
898   1001 (VFK-90-R) 2025-04-25  Kamerlingh Onnesweg 9, Dordrecht
2259  1026 (VFR-80-J) 2025-10-20  Kamerlingh Onnesweg 9, Dordrecht
1307  1047 (VFT-61-Z) 2025-06-20  Kamerlingh Onnesweg 9, Dordrecht
1308  1047 (VFT-61-Z) 2025-06-20  Kamerlingh Onnesweg 9, Dordrecht
1320  1047 (VFT-61-Z) 2025-06-20  Kamerlingh Onnesweg 9, Dordrecht
...               ...        ...                               ...
2610  1775 (V-11-GGL) 2025-11-25  Kamerlingh Onnesweg 9, Dordrecht
2736  1775 (V-11-GGL) 2025-12-31  Kamerlingh Onnesweg 9, Dordrecht
2217   967 (VDG-43-S) 2025-10-14  Kamerlingh Onnesweg 9, Dordrecht
2495   967 (VDG-43-S) 2025-11-14  Kamerlingh Onnesweg 9, Dordrecht
2706   967 (VDG-43-S) 2025-12-23  Kamerlingh Onnesweg 9, Dordrecht

[291 rows x 3 columns]

In [25]:
verwijderd_per_route = (
    df_removed
    .groupby(['SerialNumber', 'Date'])
    .size()
    .reset_index(name='aantal_verwijderd')
)

print(verwijderd_per_route)

        SerialNumber       Date  aantal_verwijderd
0    1001 (VFK-90-R) 2025-04-25                  1
1    1026 (VFR-80-J) 2025-10-20                  1
2    1047 (VFT-61-Z) 2025-06-20                  3
3    1185 (VJL-22-K) 2025-01-03                  7
4    1185 (VJL-22-K) 2025-01-08                  1
..               ...        ...                ...
167  1775 (V-11-GGL) 2025-11-25                  1
168  1775 (V-11-GGL) 2025-12-31                  1
169   967 (VDG-43-S) 2025-10-14                  1
170   967 (VDG-43-S) 2025-11-14                  1
171   967 (VDG-43-S) 2025-12-23                  1

[172 rows x 3 columns]

In [26]:
print("Origineel:", len(df02))
print("Schoon:", len(df03))

Origineel: 2730
Schoon: 2439

In [27]:
controle = (
    df03
    .sort_values(['SerialNumber', 'Date', 'StartRide'])
    .groupby(['SerialNumber', 'Date'])
    .agg(
        eerste_adres=('VisitingAddress', 'first'),
        laatste_adres=('VisitingAddress', 'last'),
        aantal_rijen=('VisitingAddress', 'size')
    )
    .reset_index()
)

controle['start_bij_depot'] = controle['eerste_adres'].eq(depot_naam)
controle['eindigt_bij_depot'] = controle['laatste_adres'].eq(depot_naam)

controle

,SerialNumber,Date,eerste_adres,laatste_adres,aantal_rijen,start_bij_depot,eindigt_bij_depot
0,1001 (VFK-90-R),2025-04-25,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",10,True,True
1,1001 (VFK-90-R),2025-08-08,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",4,True,True
2,1001 (VFK-90-R),2025-08-19,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",1,True,True
3,1026 (VFR-80-J),2025-10-20,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",1,True,True
4,1026 (VFR-80-J),2025-10-30,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",1,True,True
...,...,...,...,...,...,...,...
229,967 (VDG-43-S),2025-10-23,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",5,True,True
230,967 (VDG-43-S),2025-11-07,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",1,True,True
231,967 (VDG-43-S),2025-11-14,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",1,True,True
232,967 (VDG-43-S),2025-11-21,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",1,True,True
233,967 (VDG-43-S),2025-12-23,"Kamerlingh Onnesweg 9, Dordrecht","Kamerlingh Onnesweg 9, Dordrecht",1,True,True

In [28]:
controle['correct'] = (
    controle['start_bij_depot'] &
    controle['eindigt_bij_depot']
)

In [29]:
goede_routes = controle[controle['correct']]
print(goede_routes)

        SerialNumber       Date                      eerste_adres  \
0    1001 (VFK-90-R) 2025-04-25  Kamerlingh Onnesweg 9, Dordrecht
1    1001 (VFK-90-R) 2025-08-08  Kamerlingh Onnesweg 9, Dordrecht
2    1001 (VFK-90-R) 2025-08-19  Kamerlingh Onnesweg 9, Dordrecht
3    1026 (VFR-80-J) 2025-10-20  Kamerlingh Onnesweg 9, Dordrecht
4    1026 (VFR-80-J) 2025-10-30  Kamerlingh Onnesweg 9, Dordrecht
..               ...        ...                               ...
229   967 (VDG-43-S) 2025-10-23  Kamerlingh Onnesweg 9, Dordrecht
230   967 (VDG-43-S) 2025-11-07  Kamerlingh Onnesweg 9, Dordrecht
231   967 (VDG-43-S) 2025-11-14  Kamerlingh Onnesweg 9, Dordrecht
232   967 (VDG-43-S) 2025-11-21  Kamerlingh Onnesweg 9, Dordrecht
233   967 (VDG-43-S) 2025-12-23  Kamerlingh Onnesweg 9, Dordrecht

                        laatste_adres  aantal_rijen  start_bij_depot  \
0    Kamerlingh Onnesweg 9, Dordrecht            10             True
1    Kamerlingh Onnesweg 9, Dordrecht             4             True
2    Kamerlingh Onnesweg 9, Dordrecht             1             True
3    Kamerlingh Onnesweg 9, Dordrecht             1             True
4    Kamerlingh Onnesweg 9, Dordrecht             1             True
..                                ...           ...              ...
229  Kamerlingh Onnesweg 9, Dordrecht             5             True
230  Kamerlingh Onnesweg 9, Dordrecht             1             True
231  Kamerlingh Onnesweg 9, Dordrecht             1             True
232  Kamerlingh Onnesweg 9, Dordrecht             1             True
233  Kamerlingh Onnesweg 9, Dordrecht             1             True

     eindigt_bij_depot  correct
0                 True     True
1                 True     True
2                 True     True
3                 True     True
4                 True     True
..                 ...      ...
229               True     True
230               True     True
231               True     True
232               True     True
233               True     True

[234 rows x 8 columns]

## Rij met missende waarde

In [30]:
# kijken naar de rij met de andere missende waarde
gekozen_datum = "14-08-2025"
gekozen_serial = "1705 (V-18-FXR)"

subset = df03[
    (df03["Date"] == gekozen_datum) &
    (df03["SerialNumber"] == gekozen_serial)
]

In [ ]:
# van voertuigen/dagen met ontbrekende of onbetrouwbare locatiegegevens de hele rit verwijderen
df04 = df03[
    ~(
        (df03["Date"] == "14-08-2025") &
        (df03["SerialNumber"] == "1705 (V-18-FXR)")
    )
]
df04 = df04.copy()

df04 = df04[
    ~(
        (df04["Date"] == "18-02-2025") &
        (df04["SerialNumber"] == "1313 (VPS-11-J)")
    )
]
df04 = df04.copy()

# handmatige correctie bekende missende postcode
df04.loc[[9872, 13191], "ZipCode"] = "4818 CK"

df04 = df04[
    ~(
        (df04["Date"] == "11-02-2025") &
        (df04["SerialNumber"] == "1313 (VPS-11-J)")
    )
]
df04 = df04.copy()

df04 = df04[
    ~(
        (df04["Date"] == "05-08-2025") &
        (df04["SerialNumber"] == "1597 (VZT-42-V)")
    )
]
df04 = df04.copy()

df04 = df04[
    ~(
        (df04["Date"] == "03-11-2025") &
        (df04["SerialNumber"] == "1597 (VZT-42-V)")
    )
]
df04 = df04.copy()

df04

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,From
888,1001 (VFK-90-R),2025-04-25,06:59,07:13,07:44,"12,97",14.0,30.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Aart van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:45,0:14,0:30,0:00,"12,97",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
889,1001 (VFK-90-R),2025-04-25,07:44,08:20,09:55,"41,04",36.0,94.0,"Onyxdijk 183, Roosendaal",NaN,Aart van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Onyxdijk 183,4706LL,Roosendaal,NaN,0:00,2:56,0:51,2:04,0:00,"54,01",51.518541,4.491785,"Kamerlingh Onnesweg 9, Dordrecht"
890,1001 (VFK-90-R),2025-04-25,09:55,10:15,10:42,"17,60",20.0,27.0,"Lambertijnenhof 212, Bergen Op Zoom",NaN,Aart van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Lambertijnenhof 212,4614CH,Bergen Op Zoom,NaN,0:00,3:43,1:11,2:32,0:00,"71,61",51.506608,4.293024,"Onyxdijk 183, Roosendaal"
891,1001 (VFK-90-R),2025-04-25,10:42,10:48,10:55,"0,00",5.0,6.0,"Lambertijnenhof 212, Bergen Op Zoom",NaN,Aart van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Lambertijnenhof 212,4614CH,Bergen Op Zoom,NaN,0:00,3:56,1:17,2:38,0:00,"71,61",51.506608,4.293024,"Lambertijnenhof 212, Bergen Op Zoom"
892,1001 (VFK-90-R),2025-04-25,10:55,11:55,12:25,"41,82",60.0,29.0,"Oostelijke Achterweg 20, Middelharnis",NaN,Aart van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Oostelijke Achterweg 20,3241CM,Middelharnis,NaN,0:00,5:26,2:17,3:08,0:00,"113,43",51.757658,4.167531,"Lambertijnenhof 212, Bergen Op Zoom"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2291,967 (VDG-43-S),2025-10-23,15:51,16:53,07:15,"36,10",61.0,862.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,9:50,2:01,7:49,9:50,"79,00",51.780575,4.638942,"Sint Liduinastraat 15, Schiedam"
2416,967 (VDG-43-S),2025-11-07,08:56,09:38,08:37,"35,70",41.0,5699.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,170:32,2:47,167:44,170:32,"119,20",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2494,967 (VDG-43-S),2025-11-14,09:41,11:12,11:14,"107,20",91.0,2.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Auto Mertens Auto Mertens,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:33,1:31,0:02,0:00,"107,20",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2577,967 (VDG-43-S),2025-11-21,07:02,07:03,08:49,"0,10",1.0,8746.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,165:22,1:34,163:47,165:22,"107,50",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
2705,967 (VDG-43-S),2025-12-23,08:10,08:42,14:36,"35,70",31.0,354.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,6:25,0:31,5:54,0:00,"35,70",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"

## Model 3

In [32]:
df04['Date'].unique()

<DatetimeArray>
['2025-04-25 00:00:00', '2025-08-08 00:00:00', '2025-08-19 00:00:00',
 '2025-10-20 00:00:00', '2025-10-30 00:00:00', '2025-06-05 00:00:00',
 '2025-06-20 00:00:00', '2025-07-17 00:00:00', '2025-01-03 00:00:00',
 '2025-01-08 00:00:00',
 ...
 '2025-02-19 00:00:00', '2025-03-05 00:00:00', '2025-04-01 00:00:00',
 '2025-05-22 00:00:00', '2025-06-30 00:00:00', '2025-07-15 00:00:00',
 '2025-08-11 00:00:00', '2025-10-13 00:00:00', '2025-11-10 00:00:00',
 '2025-11-07 00:00:00']
Length: 163, dtype: datetime64[us]

In [33]:
result = df04.groupby('Date')['SerialNumber'].nunique()
result

Date
2025-01-03    4
2025-01-06    2
2025-01-07    1
2025-01-08    2
2025-01-10    1
             ..
2025-12-23    2
2025-12-27    1
2025-12-29    1
2025-12-30    1
2025-12-31    3
Name: SerialNumber, Length: 163, dtype: int64

In [34]:
max_datum = result.idxmax()
max_aantal = result.max()

print("Datum met meeste aantal voertuigen:", max_datum)
print("Aantal unieke voertuigen:", max_aantal)

Datum met meeste aantal voertuigen: 2025-01-03 00:00:00
Aantal unieke voertuigen: 4

In [35]:
df05 = df04[df04['Date'] == max_datum]
df05

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,From
0,1185 (VJL-22-K),2025-01-03,08:10,08:10,08:42,"0,00",0.0,32.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
7,1185 (VJL-22-K),2025-01-03,08:45,09:11,09:23,"14,16",26.0,11.0,"Touwbaan 4, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Touwbaan 4,3363WB,Sliedrecht,NaN,0:00,1:13,0:28,0:44,0:00,"14,16",51.826966,4.749114,"Kamerlingh Onnesweg 9, Dordrecht"
8,1185 (VJL-22-K),2025-01-03,09:23,09:29,09:30,"2,22",6.0,0.0,"Kerkbuurt 220, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 220,3361BM,Sliedrecht,NaN,0:00,1:20,0:35,0:45,0:00,"16,38",51.823225,4.768590,"Touwbaan 4, Sliedrecht"
9,1185 (VJL-22-K),2025-01-03,09:30,09:30,09:50,"0,01",0.0,19.0,"Kerkbuurt 220, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 220,3361BM,Sliedrecht,NaN,0:00,1:40,0:35,1:05,0:00,"16,39",51.823225,4.768590,"Kerkbuurt 220, Sliedrecht"
10,1185 (VJL-22-K),2025-01-03,09:50,09:55,10:06,"1,57",4.0,11.0,"Kerkbuurt 143, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 143,3361BE,Sliedrecht,NaN,0:00,1:56,0:39,1:16,0:00,"17,96",51.823264,4.770902,"Kerkbuurt 220, Sliedrecht"
11,1185 (VJL-22-K),2025-01-03,10:06,10:19,10:33,"4,14",12.0,14.0,"Jupiterstraat 257, Hardinxveld-Giessendam",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Jupiterstraat 257,3371TD,Hardinxveld-Giessendam,NaN,0:00,2:23,0:52,1:31,0:00,"22,10",51.823749,4.822809,"Kerkbuurt 143, Sliedrecht"
12,1185 (VJL-22-K),2025-01-03,10:33,10:48,12:22,"10,86",14.0,94.0,"Banneweg 57, Gorinchem",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Banneweg 57,4204AA,Gorinchem,NaN,0:00,4:12,1:07,3:05,0:00,"32,96",51.838450,4.956741,"Jupiterstraat 257, Hardinxveld-Giessendam"
13,1185 (VJL-22-K),2025-01-03,12:22,13:18,13:24,"33,32",55.0,6.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:14,2:02,3:11,0:00,"66,28",51.780575,4.638942,"Banneweg 57, Gorinchem"
15,1597 (VZT-42-V),2025-01-03,07:55,08:22,08:34,"0,02",26.0,12.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:38,0:26,0:12,0:00,"0,02",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
16,1597 (VZT-42-V),2025-01-03,08:34,08:56,09:15,"18,51",21.0,19.0,"Oosterhagen 17, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Oosterhagen 17,3078CL,Rotterdam,NaN,0:00,1:19,0:48,0:31,0:00,"18,53",51.888750,4.559416,"Kamerlingh Onnesweg 9, Dordrecht"
17,1597 (VZT-42-V),2025-01-03,09:15,09:36,09:45,"7,80",20.0,9.0,"Boergoensestraat 128, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Boergoensestraat 128,3082KD,Rotterdam,NaN,0:00,1:49,1:08,0:40,0:00,"26,33",51.891205,4.470011,"Oosterhagen 17, Rotterdam"
18,1597 (VZT-42-V),2025-01-03,09:45,10:04,10:04,"2,35",18.0,0.0,"Maashaven O.Z. 103, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Maashaven O.Z. 103,3072HS,Rotterdam,NaN,0:00,2:08,1:27,0:41,0:00,"28,68",51.901234,4.496563,"Boergoensestraat 128, Rotterdam"
19,1597 (VZT-42-V),2025-01-03,10:04,10:20,11:16,"7,23",15.0,56.0,"Motorstraat 96, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Motorstraat 96,3083AP,Rotterdam,NaN,0:00,3:21,1:43,1:37,0:00,"35,91",51.887398,4.495184,"Maashaven O.Z. 103, Rotterdam"
20,1597 (VZT-42-V),2025-01-03,11:16,11:29,12:01,"3,64",13.0,32.0,"Haastrechtstraat 130, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Haastrechtstraat 130,3079DC,Rotterdam,NaN,0:00,4:06,1:56,2:09,0:00,"39,55",51.880008,4.536397,"Motorstraat 96, Rotterdam"
21,1597 (VZT-42-V),2025-01-03,12:01,12:07,12:20,"1,93",5.0,12.0,"Pietersdijk 60, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Pietersdijk 60,3079TD,Rotterdam,NaN,0:00,4:24,2:02,2:21,0:00,"41,48",51.876503,4.553646,"Haastrechtstraat 130, Rotterdam"
22,1597 (VZT-42-V),2025-01-03,12:20,12:27,12:35,"2,21",7.0,7.0,"Oosterhagen 17, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Oosterhagen 17,3078CL,Rotterdam,NaN,0:00,4:39,2:09,2:29,0:00,"43,69",51.888750,4.559416,"Pietersdijk 60, Rotterdam"
23,1597 (VZT-42-V),2025-01-03,12:35,12:52,12:58,"11,07",17.0,5.0,"Reling 19, Barendrecht",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Reling 19,2993DN,Barendrecht,NaN,0:00,5:03,2:27,2:35,0:00,"54,76",51.849359,4.499366,"Oosterhagen 17, Rotterdam"
24,1597 (VZT-42-V),2025-01-03,12:58,13:25,13:34,"21,97",26.0,9.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:39,2:54,2:44,0:00,"76,73",51.780575,4.638942,"Reling 19, Barendrecht"
26,1702 (V-19-FXR),2025-01-03,06:35,06:58,07:24,"24,64",22.0,26.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:49,0:22,0:26,0:00,"24,64",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
27,1702 (V-19-FXR),2025-01-03,07:24,08:08,08:11,"60,56",43.0,2.0,"De Poort 24, Rilland",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,De Poort 24,4411PA,Rilland,NaN,0:00,1:35,1:06,0:29,0:00,"85,20",51.422283,4.191320,"Kamerlingh Onnesweg 9, Dordrecht"
28,1702 (V-19-FXR),2025-01-03,08:11,08:17,08:22,"7,25",6.0,4.0,"Vliete 1, Krabbendijke",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Vliete 1,4413RX,Krabbendijke,NaN,0:00,1:46,1:12,0:33,0:00,"92,45",51.422752,4.096608,"De Poort 24, Rilland"
29,1702 (V-19-FXR),2025-01-03,08:22,09:01,09:16,"58,17",39.0,14.0,"Rooseveltlaan 1, Axel",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Rooseveltlaan 1,4571HT,Axel,NaN,0:00,2:40,1:52,0:48,0:00,"150,62",51.264685,3.901397,"Vliete 1, Krabbendijke"
30,1702 (V-19-FXR),2025-01-03,09:16,09:25,09:47,"7,16",8.0,22.0,"Molenstraat 95, Zaamslag",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Molenstraat 95,4543CN,Zaamslag,NaN,0:00,3:11,2:01,1:10,0:00,"157,78",51.309240,3.907953,"Rooseveltlaan 1, Axel"
31,1702 (V-19-FXR),2025-01-03,09:47,09:58,10:49,"7,01",11.0,51.0,"Pattistpark 137, Terneuzen",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Pattistpark 137,4532HZ,Terneuzen,NaN,0:00,4:14,2:12,2:01,0:00,"164,79",51.334506,3.856501,"Molenstraat 95, Zaamslag"
32,1702 (V-19-FXR),2025-01-03,10:49,10:53,11:40,"2,43",4.0,46.0,"Bachlaan 88, Terneuzen",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Bachlaan 88,4536GD,Terneuzen,NaN,0:00,5:05,2:16,2:48,0:00,"167,22",51.319094,3.846695,"Pattistpark 137, Terneuzen"
33,1702 (V-19-FXR),2025-01-03,11:40,12:13,12:35,"33,41",32.0,22.0,"Agaat 2 -12 , Middelburg",Stichting Philadelphia Zorg - Agaat Wonen (WL),Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Agaat 2 -12,4337 MX,Middelburg,0.0,0:00,5:59,2:49,3:10,0:00,"200,63",51.492920,3.618485,"Bachlaan 88, Terneuzen"
34,1702 (V-19-FXR),2025-01-03,12:35,12:42,13:09,"2,83",7.0,26.0,"Noordbolwerk 33, Middelburg",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Noordbolwerk 33,4331SH,Middelburg,NaN,0:00,6:33,2:56,3:37,0:00,"203,46",51.504090,3.611025,"Agaat 2 -12 , Middelburg"
35,1702 (V-19-FXR),2025-01-03,13:09,13:12,13:51,"0,79",3.0,38.0,"Latijnse Schoolstraat 19, Middelburg",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Latijnse Schoolstraat 19,4331BP,Middelburg,NaN,0:00,7:15,2:59,4:15,0:00,"204,25",51.499649,3.612773,"Noordbolwerk 33, Middelburg"
36,1702 (V-19-FXR),2025-01-03,13:51,15:09,15:15,"108,39",78.0,5.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,8:39,4:18,4:21,0:00,"312,64",51.780575,4.638942,"Latijnse Schoolstraat 19, Middelburg"
40,1775 (V-11-GGL),2025-01-03,06:36,07:06,07:15,"36,04",29.0,8.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:38,0:29,0:08,0:00,"36,04",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
42,1775 (V-11-GGL),2025-01-03,07:45,07:57,08:31,"8,48",11.0,34.0,"Plantageweg 3, Zwijndrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Plantageweg 3,3333GZ,Zwijndrecht,NaN,0:00,1:55,0:41,1:13,0:00,"44,65",51.815547,4.630499,"Kamerlingh Onnesweg 9, Dordrecht"
43,1775 (V-11-GGL),2025-01-03,08:31,08:51,08:54,"12,78",19.0,3.0,"Bankastraat 158, Dordrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Bankastraat 158,3312GT,Dordrecht,NaN,0:00,2:17,1:01,1:16,0:00,"57,43",51.807925,4.686165,"Plantageweg 3, Zwijndrecht"
44,1775 (V-11-GGL),2025-01-03,08:54,09:00,09:27,"2,60",6.0,26.0,"Albert Schweitzerplaats 1, Dordrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Albert Schweitzerplaats 1,3318AS,Dordrecht,NaN,0:00,2:50,1:07,1:43,0:00,"60,03",51.792806,4.682687,"Bankastraat 158, Dordrecht"
45,1775 (V-11-GGL),2025-01-03,09:27,09:33,09:37,"2,58",5.0,4.0,"Minnaertweg 4, Dordrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,3:00,1:13,1:47,0:00,"62,61",51.783431,4.686274,"Albert Schweitzerplaats 1, Dordrecht"
46,1775 (V-11-GGL),2025-01-03,09:37,09:44,10:06,"2,58",6.0,21.0,"Groen Van Prinstererweg 38, Dordrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,3:29,1:20,2:09,0:00,"65,19",51.791025,4.665775,"Minnaertweg 4, Dordrecht"
47,1775 (V-11-GGL),2025-01-03,10:06,10:14,10:18,"3,40",8.0,3.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,3:41,1:28,2:13,0:00,"68,59",51.780575,4.638942,"Groen Van Prinstererweg 38, Dordrecht"

In [36]:
import time
import numpy as np
import pandas as pd
from math import radians, sin, cos, sqrt, atan2
from ortools.constraint_solver import pywrapcp, routing_enums_pb2

## Model 3

In [37]:
# ==============================
# INSTELLINGEN
# ==============================

gekozen_datum = max_datum    # kies hier de dag
depot_adres = depot_naam
depot_lat = 51.780575
depot_long = 4.638942

TIME_LIMIT_SECONDS = 10
MAX_ADRESSEN_PER_BUS = 15
MAX_ROUTE_TIME_MIN = 8 * 60      # bijvoorbeeld 8 uur
GEM_SNELHEID_KM_U = 40           # voor omrekenen afstand -> reistijd

In [38]:
# ==============================
# DATA VOORBEREIDEN
# ==============================

df = df05.copy()

# Datum netjes omzetten
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Gekozen datum ook datetime maken
gekozen_datum = pd.to_datetime(gekozen_datum)

# Filter op 1 dag
df_dag = df[df['Date'].dt.date == gekozen_datum.date()].copy()

print("Aantal rijen in df_dag:", len(df_dag))
print("Aantal voertuigen op deze dag:", df_dag['SerialNumber'].nunique())

# Controle
df_dag

Aantal rijen in df_dag: 36
Aantal voertuigen op deze dag: 4

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,From
0,1185 (VJL-22-K),2025-01-03,08:10,08:10,08:42,"0,00",0.0,32.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
7,1185 (VJL-22-K),2025-01-03,08:45,09:11,09:23,"14,16",26.0,11.0,"Touwbaan 4, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Touwbaan 4,3363WB,Sliedrecht,NaN,0:00,1:13,0:28,0:44,0:00,"14,16",51.826966,4.749114,"Kamerlingh Onnesweg 9, Dordrecht"
8,1185 (VJL-22-K),2025-01-03,09:23,09:29,09:30,"2,22",6.0,0.0,"Kerkbuurt 220, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 220,3361BM,Sliedrecht,NaN,0:00,1:20,0:35,0:45,0:00,"16,38",51.823225,4.768590,"Touwbaan 4, Sliedrecht"
9,1185 (VJL-22-K),2025-01-03,09:30,09:30,09:50,"0,01",0.0,19.0,"Kerkbuurt 220, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 220,3361BM,Sliedrecht,NaN,0:00,1:40,0:35,1:05,0:00,"16,39",51.823225,4.768590,"Kerkbuurt 220, Sliedrecht"
10,1185 (VJL-22-K),2025-01-03,09:50,09:55,10:06,"1,57",4.0,11.0,"Kerkbuurt 143, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 143,3361BE,Sliedrecht,NaN,0:00,1:56,0:39,1:16,0:00,"17,96",51.823264,4.770902,"Kerkbuurt 220, Sliedrecht"
11,1185 (VJL-22-K),2025-01-03,10:06,10:19,10:33,"4,14",12.0,14.0,"Jupiterstraat 257, Hardinxveld-Giessendam",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Jupiterstraat 257,3371TD,Hardinxveld-Giessendam,NaN,0:00,2:23,0:52,1:31,0:00,"22,10",51.823749,4.822809,"Kerkbuurt 143, Sliedrecht"
12,1185 (VJL-22-K),2025-01-03,10:33,10:48,12:22,"10,86",14.0,94.0,"Banneweg 57, Gorinchem",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Banneweg 57,4204AA,Gorinchem,NaN,0:00,4:12,1:07,3:05,0:00,"32,96",51.838450,4.956741,"Jupiterstraat 257, Hardinxveld-Giessendam"
13,1185 (VJL-22-K),2025-01-03,12:22,13:18,13:24,"33,32",55.0,6.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:14,2:02,3:11,0:00,"66,28",51.780575,4.638942,"Banneweg 57, Gorinchem"
15,1597 (VZT-42-V),2025-01-03,07:55,08:22,08:34,"0,02",26.0,12.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:38,0:26,0:12,0:00,"0,02",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
16,1597 (VZT-42-V),2025-01-03,08:34,08:56,09:15,"18,51",21.0,19.0,"Oosterhagen 17, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Oosterhagen 17,3078CL,Rotterdam,NaN,0:00,1:19,0:48,0:31,0:00,"18,53",51.888750,4.559416,"Kamerlingh Onnesweg 9, Dordrecht"
17,1597 (VZT-42-V),2025-01-03,09:15,09:36,09:45,"7,80",20.0,9.0,"Boergoensestraat 128, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Boergoensestraat 128,3082KD,Rotterdam,NaN,0:00,1:49,1:08,0:40,0:00,"26,33",51.891205,4.470011,"Oosterhagen 17, Rotterdam"
18,1597 (VZT-42-V),2025-01-03,09:45,10:04,10:04,"2,35",18.0,0.0,"Maashaven O.Z. 103, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Maashaven O.Z. 103,3072HS,Rotterdam,NaN,0:00,2:08,1:27,0:41,0:00,"28,68",51.901234,4.496563,"Boergoensestraat 128, Rotterdam"
19,1597 (VZT-42-V),2025-01-03,10:04,10:20,11:16,"7,23",15.0,56.0,"Motorstraat 96, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Motorstraat 96,3083AP,Rotterdam,NaN,0:00,3:21,1:43,1:37,0:00,"35,91",51.887398,4.495184,"Maashaven O.Z. 103, Rotterdam"
20,1597 (VZT-42-V),2025-01-03,11:16,11:29,12:01,"3,64",13.0,32.0,"Haastrechtstraat 130, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Haastrechtstraat 130,3079DC,Rotterdam,NaN,0:00,4:06,1:56,2:09,0:00,"39,55",51.880008,4.536397,"Motorstraat 96, Rotterdam"
21,1597 (VZT-42-V),2025-01-03,12:01,12:07,12:20,"1,93",5.0,12.0,"Pietersdijk 60, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Pietersdijk 60,3079TD,Rotterdam,NaN,0:00,4:24,2:02,2:21,0:00,"41,48",51.876503,4.553646,"Haastrechtstraat 130, Rotterdam"
22,1597 (VZT-42-V),2025-01-03,12:20,12:27,12:35,"2,21",7.0,7.0,"Oosterhagen 17, Rotterdam",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Oosterhagen 17,3078CL,Rotterdam,NaN,0:00,4:39,2:09,2:29,0:00,"43,69",51.888750,4.559416,"Pietersdijk 60, Rotterdam"
23,1597 (VZT-42-V),2025-01-03,12:35,12:52,12:58,"11,07",17.0,5.0,"Reling 19, Barendrecht",NaN,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Reling 19,2993DN,Barendrecht,NaN,0:00,5:03,2:27,2:35,0:00,"54,76",51.849359,4.499366,"Oosterhagen 17, Rotterdam"
24,1597 (VZT-42-V),2025-01-03,12:58,13:25,13:34,"21,97",26.0,9.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Kees Kuiper,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:39,2:54,2:44,0:00,"76,73",51.780575,4.638942,"Reling 19, Barendrecht"
26,1702 (V-19-FXR),2025-01-03,06:35,06:58,07:24,"24,64",22.0,26.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:49,0:22,0:26,0:00,"24,64",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
27,1702 (V-19-FXR),2025-01-03,07:24,08:08,08:11,"60,56",43.0,2.0,"De Poort 24, Rilland",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,De Poort 24,4411PA,Rilland,NaN,0:00,1:35,1:06,0:29,0:00,"85,20",51.422283,4.191320,"Kamerlingh Onnesweg 9, Dordrecht"
28,1702 (V-19-FXR),2025-01-03,08:11,08:17,08:22,"7,25",6.0,4.0,"Vliete 1, Krabbendijke",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Vliete 1,4413RX,Krabbendijke,NaN,0:00,1:46,1:12,0:33,0:00,"92,45",51.422752,4.096608,"De Poort 24, Rilland"
29,1702 (V-19-FXR),2025-01-03,08:22,09:01,09:16,"58,17",39.0,14.0,"Rooseveltlaan 1, Axel",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Rooseveltlaan 1,4571HT,Axel,NaN,0:00,2:40,1:52,0:48,0:00,"150,62",51.264685,3.901397,"Vliete 1, Krabbendijke"
30,1702 (V-19-FXR),2025-01-03,09:16,09:25,09:47,"7,16",8.0,22.0,"Molenstraat 95, Zaamslag",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Molenstraat 95,4543CN,Zaamslag,NaN,0:00,3:11,2:01,1:10,0:00,"157,78",51.309240,3.907953,"Rooseveltlaan 1, Axel"
31,1702 (V-19-FXR),2025-01-03,09:47,09:58,10:49,"7,01",11.0,51.0,"Pattistpark 137, Terneuzen",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Pattistpark 137,4532HZ,Terneuzen,NaN,0:00,4:14,2:12,2:01,0:00,"164,79",51.334506,3.856501,"Molenstraat 95, Zaamslag"
32,1702 (V-19-FXR),2025-01-03,10:49,10:53,11:40,"2,43",4.0,46.0,"Bachlaan 88, Terneuzen",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Bachlaan 88,4536GD,Terneuzen,NaN,0:00,5:05,2:16,2:48,0:00,"167,22",51.319094,3.846695,"Pattistpark 137, Terneuzen"
33,1702 (V-19-FXR),2025-01-03,11:40,12:13,12:35,"33,41",32.0,22.0,"Agaat 2 -12 , Middelburg",Stichting Philadelphia Zorg - Agaat Wonen (WL),Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Agaat 2 -12,4337 MX,Middelburg,0.0,0:00,5:59,2:49,3:10,0:00,"200,63",51.492920,3.618485,"Bachlaan 88, Terneuzen"
34,1702 (V-19-FXR),2025-01-03,12:35,12:42,13:09,"2,83",7.0,26.0,"Noordbolwerk 33, Middelburg",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Noordbolwerk 33,4331SH,Middelburg,NaN,0:00,6:33,2:56,3:37,0:00,"203,46",51.504090,3.611025,"Agaat 2 -12 , Middelburg"
35,1702 (V-19-FXR),2025-01-03,13:09,13:12,13:51,"0,79",3.0,38.0,"Latijnse Schoolstraat 19, Middelburg",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Latijnse Schoolstraat 19,4331BP,Middelburg,NaN,0:00,7:15,2:59,4:15,0:00,"204,25",51.499649,3.612773,"Noordbolwerk 33, Middelburg"
36,1702 (V-19-FXR),2025-01-03,13:51,15:09,15:15,"108,39",78.0,5.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,8:39,4:18,4:21,0:00,"312,64",51.780575,4.638942,"Latijnse Schoolstraat 19, Middelburg"
40,1775 (V-11-GGL),2025-01-03,06:36,07:06,07:15,"36,04",29.0,8.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:38,0:29,0:08,0:00,"36,04",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
42,1775 (V-11-GGL),2025-01-03,07:45,07:57,08:31,"8,48",11.0,34.0,"Plantageweg 3, Zwijndrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Plantageweg 3,3333GZ,Zwijndrecht,NaN,0:00,1:55,0:41,1:13,0:00,"44,65",51.815547,4.630499,"Kamerlingh Onnesweg 9, Dordrecht"
43,1775 (V-11-GGL),2025-01-03,08:31,08:51,08:54,"12,78",19.0,3.0,"Bankastraat 158, Dordrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Bankastraat 158,3312GT,Dordrecht,NaN,0:00,2:17,1:01,1:16,0:00,"57,43",51.807925,4.686165,"Plantageweg 3, Zwijndrecht"
44,1775 (V-11-GGL),2025-01-03,08:54,09:00,09:27,"2,60",6.0,26.0,"Albert Schweitzerplaats 1, Dordrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Albert Schweitzerplaats 1,3318AS,Dordrecht,NaN,0:00,2:50,1:07,1:43,0:00,"60,03",51.792806,4.682687,"Bankastraat 158, Dordrecht"
45,1775 (V-11-GGL),2025-01-03,09:27,09:33,09:37,"2,58",5.0,4.0,"Minnaertweg 4, Dordrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,3:00,1:13,1:47,0:00,"62,61",51.783431,4.686274,"Albert Schweitzerplaats 1, Dordrecht"
46,1775 (V-11-GGL),2025-01-03,09:37,09:44,10:06,"2,58",6.0,21.0,"Groen Van Prinstererweg 38, Dordrecht",NaN,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,3:29,1:20,2:09,0:00,"65,19",51.791025,4.665775,"Minnaertweg 4, Dordrecht"
47,1775 (V-11-GGL),2025-01-03,10:06,10:14,10:18,"3,40",8.0,3.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Joost van der Linden,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,3:41,1:28,2:13,0:00,"68,59",51.780575,4.638942,"Groen Van Prinstererweg 38, Dordrecht"

In [39]:
# ==============================
# LOCATIES OPBOUWEN
# ==============================

depot_df = pd.DataFrame({
    'VisitingAddress': [depot_adres],
    'Lat': [depot_lat],
    'Long': [depot_long]
})

# Unieke klantlocaties van die dag
locations = (
    df_dag[['VisitingAddress', 'Lat', 'Long']]
    .dropna(subset=['VisitingAddress', 'Lat', 'Long'])
    .drop_duplicates()
    .reset_index(drop=True)
)

# Depot bovenaan zetten
locations = pd.concat([depot_df, locations], ignore_index=True)

# Dubbele adressen verwijderen, depot blijft dan bovenaan staan
locations = locations.drop_duplicates(subset=['VisitingAddress']).reset_index(drop=True)

# Node id
locations['node_id'] = locations.index

print("Aantal locaties incl. depot:", len(locations))
display(locations.head())

Aantal locaties incl. depot: 27

                             VisitingAddress        Lat      Long  node_id
0           Kamerlingh Onnesweg 9, Dordrecht  51.780575  4.638942        0
1                     Touwbaan 4, Sliedrecht  51.826966  4.749114        1
2                  Kerkbuurt 220, Sliedrecht  51.823225  4.768590        2
3                  Kerkbuurt 143, Sliedrecht  51.823264  4.770902        3
4  Jupiterstraat 257, Hardinxveld-Giessendam  51.823749  4.822809        4

In [40]:
# ==============================
# SERVICETIJDEN PER ADRES
# ==============================

service_times_df = (
    df_dag.groupby('VisitingAddress', as_index=False)['Duration']
    .median()
    .rename(columns={'Duration': 'service_time'})
)

service_times_df['service_time'] = (
    service_times_df['service_time']
    .fillna(0)
    .round()
    .astype(int)
)

# Koppelen aan locaties
locations = locations.merge(service_times_df, on='VisitingAddress', how='left')
locations['service_time'] = locations['service_time'].fillna(0).astype(int)

# Depot heeft geen servicetijd
locations.loc[locations['VisitingAddress'] == depot_adres, 'service_time'] = 0

print("Servicetijden toegevoegd")
display(locations.head())

Servicetijden toegevoegd

,VisitingAddress,Lat,Long,node_id,service_time
0,"Kamerlingh Onnesweg 9, Dordrecht",51.780575,4.638942,0,0
1,"Touwbaan 4, Sliedrecht",51.826966,4.749114,1,11
2,"Kerkbuurt 220, Sliedrecht",51.823225,4.768590,2,10
3,"Kerkbuurt 143, Sliedrecht",51.823264,4.770902,3,11
4,"Jupiterstraat 257, Hardinxveld-Giessendam",51.823749,4.822809,4,14

In [41]:
# ==============================
# AFSTANDSBEREKENING
# ==============================

def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # km
    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)

    a = sin(dlat / 2)**2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    return R * c

In [42]:
# ==============================
# DISTANCE MATRIX
# ==============================

n = len(locations)
distance_matrix = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        distance_matrix[i, j] = haversine(
            locations.loc[i, 'Lat'],
            locations.loc[i, 'Long'],
            locations.loc[j, 'Lat'],
            locations.loc[j, 'Long']
        )

# OR-Tools werkt liever met integers
distance_matrix = (distance_matrix * 1000).astype(int)  # meters

print("distance_matrix shape:", distance_matrix.shape)

distance_matrix shape: (27, 27)

In [43]:
# ==============================
# TIME MATRIX
# ==============================

time_matrix = np.round(
    (distance_matrix / 1000) / GEM_SNELHEID_KM_U * 60
).astype(int)

print("time_matrix shape:", time_matrix.shape)

time_matrix shape: (27, 27)

In [44]:
# ==============================
# CAPACITEIT
# ==============================

num_vehicles = df_dag['SerialNumber'].nunique()

demands = [0] + [1] * (len(locations) - 1)
vehicle_capacities = [MAX_ADRESSEN_PER_BUS] * num_vehicles

service_times = locations['service_time'].tolist()

print("Aantal voertuigen:", num_vehicles)
print("Lengte demands:", len(demands))
print("Lengte service_times:", len(service_times))

Aantal voertuigen: 4
Lengte demands: 27
Lengte service_times: 27

In [45]:
# ==============================
# MODEL 3 BOUWEN
# ==============================

def build_model_3(time_matrix,
                  distance_matrix,
                  num_vehicles,
                  demands,
                  vehicle_capacities,
                  service_times,
                  depot=0,
                  max_route_time=8*60):

    manager = pywrapcp.RoutingIndexManager(
        len(distance_matrix),
        num_vehicles,
        [depot] * num_vehicles,
        [depot] * num_vehicles
    )

    routing = pywrapcp.RoutingModel(manager)

    # --------------------------
    # afstand callback
    # --------------------------
    def distance_callback(from_index, to_index):
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return int(distance_matrix[from_node][to_node])

    distance_callback_index = routing.RegisterTransitCallback(distance_callback)
    routing.SetArcCostEvaluatorOfAllVehicles(distance_callback_index)

    # --------------------------
    # demand callback
    # --------------------------
    def demand_callback(from_index):
        from_node = manager.IndexToNode(from_index)
        return demands[from_node]

    demand_callback_index = routing.RegisterUnaryTransitCallback(demand_callback)

    routing.AddDimensionWithVehicleCapacity(
        demand_callback_index,
        0,
        vehicle_capacities,
        True,
        "Capacity"
    )

    # --------------------------
    # time callback
    # tijd = reistijd + servicetijd op huidige node
    # --------------------------
    def time_callback(from_index, to_index):
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)

        travel_time = time_matrix[from_node][to_node]
        service_time = service_times[from_node]

        return int(travel_time + service_time)

    time_callback_index = routing.RegisterTransitCallback(time_callback)

    routing.AddDimension(
        time_callback_index,
        0,                # meer wachttijd toegestaan
        max_route_time,   # maximale route-duur
        True,             # start op 0
        "Time"
    )

    return manager, routing

In [46]:
# ==============================
# TOTALE AFSTAND
# ==============================

def calculate_total_distance(solution, routing, num_vehicles):
    total_distance = 0

    for vehicle_id in range(num_vehicles):
        index = routing.Start(vehicle_id)
        while not routing.IsEnd(index):
            next_index = solution.Value(routing.NextVar(index))
            total_distance += routing.GetArcCostForVehicle(index, next_index, vehicle_id)
            index = next_index

    return total_distance

In [47]:
# ==============================
# ROUTES UITLEZEN
# ==============================

def extract_model_3_routes(solution, manager, routing, num_vehicles, locations, demands):
    totaal_afstand = 0
    routes_output = []

    time_dimension = routing.GetDimensionOrDie("Time")

    for vehicle_id in range(num_vehicles):
        index = routing.Start(vehicle_id)
        route_nodes = []
        route_adressen = []
        route_distance = 0
        route_demand = 0

        while not routing.IsEnd(index):
            node = manager.IndexToNode(index)
            route_nodes.append(node)
            route_adressen.append(locations.loc[node, 'VisitingAddress'])
            route_demand += demands[node]

            previous_index = index
            index = solution.Value(routing.NextVar(index))
            route_distance += routing.GetArcCostForVehicle(previous_index, index, vehicle_id)

        end_node = manager.IndexToNode(index)
        route_nodes.append(end_node)
        route_adressen.append(locations.loc[end_node, 'VisitingAddress'])

        totaal_afstand += route_distance
        eindtijd = solution.Value(time_dimension.CumulVar(index))

        routes_output.append({
            "vehicle_id": vehicle_id,
            "route_nodes": route_nodes,
            "route_adressen": route_adressen,
            "aantal_adressen": route_demand,
            "afstand_meters": route_distance,
            "afstand_km": round(route_distance / 1000, 2),
            "totale_tijd_min": eindtijd,
            "totale_tijd_uur": round(eindtijd / 60, 2)
        })

    return totaal_afstand, routes_output

In [48]:
# ==============================
# BESTE COMBINATIE KIEZEN
# ==============================

def get_best_parameters(df_results, allow_zero_distance=False):
    df_valid = df_results[df_results["solution_found"] == True].copy()
    df_valid = df_valid[df_valid["total_distance"].notna()]

    if not allow_zero_distance:
        df_valid = df_valid[df_valid["total_distance"] > 0]

    if df_valid.empty:
        raise ValueError(
            "Geen geldige oplossing gevonden voor Model 3. "
            "Controleer je data, capaciteit en route-tijdrestrictie."
        )

    best_row = df_valid.sort_values(
        by=["total_distance", "runtime_sec"],
        ascending=[True, True]
    ).iloc[0]

    return best_row["first_solution_strategy"], best_row["local_search_metaheuristic"]

In [49]:
best_fs3 = 'GLOBAL_CHEAPEST_ARC'
best_ls3 = 'GUIDED_LOCAL_SEARCH'

In [50]:
# ==============================
# MODEL 3 DEFINITIEF DRAAIEN
# ==============================

manager3, routing3 = build_model_3(
    time_matrix=time_matrix,
    distance_matrix=distance_matrix,
    num_vehicles=num_vehicles,
    demands=demands,
    vehicle_capacities=vehicle_capacities,
    service_times=service_times,
    depot=0,
    max_route_time=MAX_ROUTE_TIME_MIN
)

search_parameters3 = pywrapcp.DefaultRoutingSearchParameters()
search_parameters3.first_solution_strategy = getattr(
    routing_enums_pb2.FirstSolutionStrategy, best_fs3
)
search_parameters3.local_search_metaheuristic = getattr(
    routing_enums_pb2.LocalSearchMetaheuristic, best_ls3
)
search_parameters3.time_limit.seconds = TIME_LIMIT_SECONDS

solution3 = routing3.SolveWithParameters(search_parameters3)

In [51]:
# ==============================
# RESULTATEN MODEL 3
# ==============================

if solution3:
    totaal_afstand3, routes_output3 = extract_model_3_routes(
        solution=solution3,
        manager=manager3,
        routing=routing3,
        num_vehicles=num_vehicles,
        locations=locations,
        demands=demands
    )

    print(f"\nMODEL 3: Totaal aantal voertuigen: {num_vehicles}")
    print(f"MODEL 3: Totaal aantal locaties incl. depot: {len(locations)}")
    print(f"MODEL 3: Totale afstand: {round(totaal_afstand3 / 1000, 2)} km\n")

    for route in routes_output3:
        print(f"Bus {route['vehicle_id']}:")
        print(" -> ".join(route['route_adressen']))
        print(f"Aantal adressen: {route['aantal_adressen']}")
        print(f"Afstand: {route['afstand_km']} km")
        print(f"Totale tijd: {route['totale_tijd_min']} min ({route['totale_tijd_uur']} uur)")
        print("-" * 60)

else:
    print("MODEL 3: Geen oplossing gevonden.")

MODEL 3: Totaal aantal voertuigen: 4
MODEL 3: Totaal aantal locaties incl. depot: 27
MODEL 3: Totale afstand: 390.99 km

Bus 0:
Kamerlingh Onnesweg 9, Dordrecht -> Plantageweg 3, Zwijndrecht -> Bankastraat 158, Dordrecht -> Touwbaan 4, Sliedrecht -> Kerkbuurt 220, Sliedrecht -> Kerkbuurt 143, Sliedrecht -> Jupiterstraat 257, Hardinxveld-Giessendam -> Banneweg 57, Gorinchem -> Minnaertweg 4, Dordrecht -> Albert Schweitzerplaats 1, Dordrecht -> Groen Van Prinstererweg 38, Dordrecht -> Kamerlingh Onnesweg 9, Dordrecht
Aantal adressen: 10
Afstand: 51.15 km
Totale tijd: 304 min (5.07 uur)
------------------------------------------------------------
Bus 1:
Kamerlingh Onnesweg 9, Dordrecht -> Kamerlingh Onnesweg 9, Dordrecht
Aantal adressen: 0
Afstand: 0.0 km
Totale tijd: 0 min (0.0 uur)
------------------------------------------------------------
Bus 2:
Kamerlingh Onnesweg 9, Dordrecht -> Vliete 1, Krabbendijke -> Pattistpark 137, Terneuzen -> Bachlaan 88, Terneuzen -> Rooseveltlaan 1, Axel -> Molenstraat 95, Zaamslag -> De Poort 24, Rilland -> Kamerlingh Onnesweg 9, Dordrecht
Aantal adressen: 6
Afstand: 161.72 km
Totale tijd: 382 min (6.37 uur)
------------------------------------------------------------
Bus 3:
Kamerlingh Onnesweg 9, Dordrecht -> Pietersdijk 60, Rotterdam -> Oosterhagen 17, Rotterdam -> Haastrechtstraat 130, Rotterdam -> Motorstraat 96, Rotterdam -> Maashaven O.Z. 103, Rotterdam -> Boergoensestraat 128, Rotterdam -> Reling 19, Barendrecht -> Noordbolwerk 33, Middelburg -> Latijnse Schoolstraat 19, Middelburg -> Agaat 2 -12 , Middelburg -> Kamerlingh Onnesweg 9, Dordrecht
Aantal adressen: 10
Afstand: 178.12 km
Totale tijd: 479 min (7.98 uur)
------------------------------------------------------------

## Model 4

In [52]:
gekozen_datum = max_datum    # kies hier de dag
depot_adres = depot_naam
depot_lat = 51.780575
depot_long = 4.638942

TIME_LIMIT_SECONDS = 10
MAX_ADRESSEN_PER_BUS = 15
GEM_SNELHEID_KM_U = 40           # voor reistijd-benadering

# Depot time window
DEPOT_OPEN = 8 * 60              # 08:00
DEPOT_CLOSE = 16 * 60            # 18:00

In [53]:
df = df05.copy()

df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
gekozen_datum = pd.to_datetime(gekozen_datum)

df_dag = df[df['Date'].dt.date == gekozen_datum.date()].copy()

print("Aantal rijen in df_dag:", len(df_dag))
print("Aantal voertuigen:", df_dag['SerialNumber'].nunique())

display(df_dag.head())

Aantal rijen in df_dag: 36
Aantal voertuigen: 4

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,From
0,1185 (VJL-22-K),2025-01-03,08:10,08:10,08:42,"0,00",0.0,32.0,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,NaN,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:32,0:00,0:32,0:00,"0,00",51.780575,4.638942,"Kamerlingh Onnesweg 9, Dordrecht"
7,1185 (VJL-22-K),2025-01-03,08:45,09:11,09:23,"14,16",26.0,11.0,"Touwbaan 4, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Touwbaan 4,3363WB,Sliedrecht,NaN,0:00,1:13,0:28,0:44,0:00,"14,16",51.826966,4.749114,"Kamerlingh Onnesweg 9, Dordrecht"
8,1185 (VJL-22-K),2025-01-03,09:23,09:29,09:30,"2,22",6.0,0.0,"Kerkbuurt 220, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 220,3361BM,Sliedrecht,NaN,0:00,1:20,0:35,0:45,0:00,"16,38",51.823225,4.768590,"Touwbaan 4, Sliedrecht"
9,1185 (VJL-22-K),2025-01-03,09:30,09:30,09:50,"0,01",0.0,19.0,"Kerkbuurt 220, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 220,3361BM,Sliedrecht,NaN,0:00,1:40,0:35,1:05,0:00,"16,39",51.823225,4.768590,"Kerkbuurt 220, Sliedrecht"
10,1185 (VJL-22-K),2025-01-03,09:50,09:55,10:06,"1,57",4.0,11.0,"Kerkbuurt 143, Sliedrecht",NaN,Cornelis van der Giessen,BBT Dordrecht/MHG,NaN,NaN,Kerkbuurt 143,3361BE,Sliedrecht,NaN,0:00,1:56,0:39,1:16,0:00,"17,96",51.823264,4.770902,"Kerkbuurt 220, Sliedrecht"

In [54]:
depot_df = pd.DataFrame({
    'VisitingAddress': [depot_adres],
    'Lat': [depot_lat],
    'Long': [depot_long]
})

locations = (
    df_dag[['VisitingAddress', 'Lat', 'Long']]
    .dropna(subset=['VisitingAddress', 'Lat', 'Long'])
    .drop_duplicates()
    .reset_index(drop=True)
)

locations = pd.concat([depot_df, locations], ignore_index=True)
locations = locations.drop_duplicates(subset=['VisitingAddress']).reset_index(drop=True)

locations['node_id'] = locations.index

print("Aantal locaties incl. depot:", len(locations))
display(locations.head())

Aantal locaties incl. depot: 27

                             VisitingAddress        Lat      Long  node_id
0           Kamerlingh Onnesweg 9, Dordrecht  51.780575  4.638942        0
1                     Touwbaan 4, Sliedrecht  51.826966  4.749114        1
2                  Kerkbuurt 220, Sliedrecht  51.823225  4.768590        2
3                  Kerkbuurt 143, Sliedrecht  51.823264  4.770902        3
4  Jupiterstraat 257, Hardinxveld-Giessendam  51.823749  4.822809        4

In [55]:
service_times_df = (
    df_dag.groupby('VisitingAddress', as_index=False)['Duration']
    .median()
    .rename(columns={'Duration': 'service_time'})
)

service_times_df['service_time'] = (
    service_times_df['service_time']
    .fillna(0)
    .round()
    .astype(int)
)

locations = locations.merge(service_times_df, on='VisitingAddress', how='left')
locations['service_time'] = locations['service_time'].fillna(0).astype(int)

# depot heeft geen servicetijd
locations.loc[locations['VisitingAddress'] == depot_adres, 'service_time'] = 0

display(locations.head())

,VisitingAddress,Lat,Long,node_id,service_time
0,"Kamerlingh Onnesweg 9, Dordrecht",51.780575,4.638942,0,0
1,"Touwbaan 4, Sliedrecht",51.826966,4.749114,1,11
2,"Kerkbuurt 220, Sliedrecht",51.823225,4.768590,2,10
3,"Kerkbuurt 143, Sliedrecht",51.823264,4.770902,3,11
4,"Jupiterstraat 257, Hardinxveld-Giessendam",51.823749,4.822809,4,14

In [56]:
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # km
    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)

    a = sin(dlat / 2)**2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    return R * c

In [57]:
n = len(locations)
distance_matrix = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        distance_matrix[i, j] = haversine(
            locations.loc[i, 'Lat'],
            locations.loc[i, 'Long'],
            locations.loc[j, 'Lat'],
            locations.loc[j, 'Long']
        )

distance_matrix = (distance_matrix * 1000).astype(int)   # meters

print(distance_matrix.shape)

(27, 27)

In [58]:
# TIME MATRIX
# ==============================

time_matrix = np.round(
    (distance_matrix / 1000) / GEM_SNELHEID_KM_U * 60
).astype(int)

print(time_matrix.shape)

(27, 27)

In [59]:
# CAPACITEIT EN SERVICE
# ==============================

num_vehicles = df_dag['SerialNumber'].nunique()

demands = [0] + [1] * (len(locations) - 1)
vehicle_capacities = [MAX_ADRESSEN_PER_BUS] * num_vehicles

service_times = locations['service_time'].tolist()

print("Aantal voertuigen:", num_vehicles)
print("Lengte demands:", len(demands))
print("Lengte service_times:", len(service_times))

Aantal voertuigen: 4
Lengte demands: 27
Lengte service_times: 27

In [60]:
# TIME WINDOWS
# ==============================

locations['window_start'] = 8 * 60   # 08:00
locations['window_end'] = 16 * 60    # 18:00

# depot apart
locations.loc[locations['VisitingAddress'] == depot_adres, 'window_start'] = 8 * 60
locations.loc[locations['VisitingAddress'] == depot_adres, 'window_end'] = 16 * 60

time_windows = list(zip(locations['window_start'], locations['window_end']))


display(locations[['node_id', 'VisitingAddress', 'window_start', 'window_end']].head(10))

,node_id,VisitingAddress,window_start,window_end
0,0,"Kamerlingh Onnesweg 9, Dordrecht",480,960
1,1,"Touwbaan 4, Sliedrecht",480,960
2,2,"Kerkbuurt 220, Sliedrecht",480,960
3,3,"Kerkbuurt 143, Sliedrecht",480,960
4,4,"Jupiterstraat 257, Hardinxveld-Giessendam",480,960
5,5,"Banneweg 57, Gorinchem",480,960
6,6,"Oosterhagen 17, Rotterdam",480,960
7,7,"Boergoensestraat 128, Rotterdam",480,960
8,8,"Maashaven O.Z. 103, Rotterdam",480,960
9,9,"Motorstraat 96, Rotterdam",480,960

In [61]:
# ==============================
# MODEL 4 BOUWEN
# ==============================

def build_model_4(time_matrix,
                  distance_matrix,
                  num_vehicles,
                  demands,
                  vehicle_capacities,
                  service_times,
                  time_windows,
                  depot=0):

    manager = pywrapcp.RoutingIndexManager(
        len(distance_matrix),
        num_vehicles,
        [depot] * num_vehicles,
        [depot] * num_vehicles
    )

    routing = pywrapcp.RoutingModel(manager)

    def distance_callback(from_index, to_index):
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return int(distance_matrix[from_node][to_node])

    distance_callback_index = routing.RegisterTransitCallback(distance_callback)
    routing.SetArcCostEvaluatorOfAllVehicles(distance_callback_index)

    def demand_callback(from_index):
        from_node = manager.IndexToNode(from_index)
        return demands[from_node]

    demand_callback_index = routing.RegisterUnaryTransitCallback(demand_callback)

    routing.AddDimensionWithVehicleCapacity(
        demand_callback_index,
        0,
        vehicle_capacities,
        True,
        "Capacity"
    )

    def time_callback(from_index, to_index):
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)

        travel_time = time_matrix[from_node][to_node]
        service_time = service_times[from_node]

        return int(travel_time + service_time)

    time_callback_index = routing.RegisterTransitCallback(time_callback)

    routing.AddDimension(
        time_callback_index,
        12 * 60,    # ruime wachttijd
        24 * 60,    # volledige daghorizon
        False,
        "Time"
    )

    time_dimension = routing.GetDimensionOrDie("Time")

    # klanten
    for node in range(1, len(time_windows)):
        index = manager.NodeToIndex(node)
        start, end = time_windows[node]
        time_dimension.CumulVar(index).SetRange(int(start), int(end))

    # depot per voertuig
    depot_start, depot_end = time_windows[0]
    for vehicle_id in range(num_vehicles):
        start_index = routing.Start(vehicle_id)
        end_index = routing.End(vehicle_id)

        time_dimension.CumulVar(start_index).SetRange(int(depot_start), int(depot_end))
        time_dimension.CumulVar(end_index).SetRange(int(depot_start), int(depot_end))

    return manager, routing

In [62]:
# ==============================
# TOTALE AFSTAND
# ==============================

def calculate_total_distance(solution, routing, num_vehicles):
    total_distance = 0

    for vehicle_id in range(num_vehicles):
        index = routing.Start(vehicle_id)
        while not routing.IsEnd(index):
            next_index = solution.Value(routing.NextVar(index))
            total_distance += routing.GetArcCostForVehicle(index, next_index, vehicle_id)
            index = next_index

    return total_distance

In [63]:
# ==============================
# ==============================
# ROUTES UITLEZEN
# ==============================

def extract_model_4_routes(
    solution,
    manager,
    routing,
    num_vehicles,
    locations,
    demands,
    time_matrix
):
    totaal_afstand = 0
    routes_output = []

    time_dimension = routing.GetDimensionOrDie("Time")

    for vehicle_id in range(num_vehicles):
        start_index = routing.Start(vehicle_id)
        first_next = solution.Value(routing.NextVar(start_index))

        vehicle_used = not routing.IsEnd(first_next)

        index = start_index
        route_nodes = []
        route_adressen = []
        route_times = []
        route_travel_times = []
        route_service_times = []

        route_distance = 0
        route_demand = 0

        start_time = solution.Value(time_dimension.CumulVar(start_index))

        while not routing.IsEnd(index):
            node = manager.IndexToNode(index)
            tijd = solution.Value(time_dimension.CumulVar(index))

            route_nodes.append(node)
            route_adressen.append(locations.loc[node, "VisitingAddress"])
            route_times.append(tijd)
            route_demand += demands[node]

            # servicetijd op huidige locatie
            service_time = locations.loc[node, "service_time"]
            route_service_times.append(service_time)

            previous_index = index
            index = solution.Value(routing.NextVar(index))

            next_node = manager.IndexToNode(index)

            # rijtijd van huidige locatie naar volgende locatie
            travel_time = time_matrix[node][next_node]
            route_travel_times.append(travel_time)

            # afstand van huidige locatie naar volgende locatie
            route_distance += routing.GetArcCostForVehicle(
                previous_index,
                index,
                vehicle_id
            )

        end_node = manager.IndexToNode(index)
        end_time = solution.Value(time_dimension.CumulVar(index))

        route_nodes.append(end_node)
        route_adressen.append(locations.loc[end_node, "VisitingAddress"])
        route_times.append(end_time)

        # einddepot: meestal geen service/rijtijd meer tonen
        route_service_times.append(0)
        route_travel_times.append(0)

        totaal_afstand += route_distance

        if not vehicle_used:
            start_time_report = 0
            end_time_report = 0
            route_duration = 0
            route_times_report = [0, 0]
        else:
            start_time_report = start_time
            end_time_report = end_time
            route_duration = end_time - start_time
            route_times_report = route_times

        routes_output.append({
            "vehicle_id": vehicle_id,
            "vehicle_used": vehicle_used,
            "route_nodes": route_nodes,
            "route_adressen": route_adressen,
            "route_times_min": route_times_report,
            "route_travel_times_min": route_travel_times,
            "route_service_times_min": route_service_times,
            "aantal_adressen": route_demand,
            "afstand_meters": route_distance,
            "afstand_km": round(route_distance / 1000, 2),
            "start_tijd_min": start_time_report,
            "eind_tijd_min": end_time_report,
            "totale_tijd_min": route_duration,
            "totale_tijd_uur": round(route_duration / 60, 2)
        })

    return totaal_afstand, routes_output

In [64]:
best_fs4 = 'GLOBAL_CHEAPEST_ARC'
best_ls4 = 'GREEDY_DESCENT'

In [65]:
# ==============================
# MODEL 4 DEFINITIEF DRAAIEN
# ==============================

manager4, routing4 = build_model_4(
    time_matrix=time_matrix,
    distance_matrix=distance_matrix,
    num_vehicles=num_vehicles,
    demands=demands,
    vehicle_capacities=vehicle_capacities,
    service_times=service_times,
    time_windows=time_windows,
    depot=0,
)

search_parameters4 = pywrapcp.DefaultRoutingSearchParameters()
search_parameters4.first_solution_strategy = getattr(
    routing_enums_pb2.FirstSolutionStrategy, best_fs4
)
search_parameters4.local_search_metaheuristic = getattr(
    routing_enums_pb2.LocalSearchMetaheuristic, best_ls4
)
search_parameters4.time_limit.seconds = TIME_LIMIT_SECONDS

solution4 = routing4.SolveWithParameters(search_parameters4)

In [66]:
# ==============================
# RESULTATEN MODEL 4
# ==============================

if solution4:
    totaal_afstand4, routes_output4 = extract_model_4_routes(
        solution=solution4,
        manager=manager4,
        routing=routing4,
        num_vehicles=num_vehicles,
        locations=locations,
        demands=demands,
        time_matrix=time_matrix
    )

    print(f"\nMODEL 4: Totale afstand: {round(totaal_afstand4 / 1000, 2)} km\n")

    for route in routes_output4:
        print(f"Bus {route['vehicle_id']}:")
        for adres, tijd in zip(route['route_adressen'], route['route_times_min']):
            uur = tijd // 60
            minuut = tijd % 60
            print(f"{adres} @ {uur:02d}:{minuut:02d}")

        print(f"Aantal adressen: {route['aantal_adressen']}")
        print(f"Afstand: {route['afstand_km']} km")
        print(f"Totale tijd: {route['totale_tijd_min']} min ({route['totale_tijd_uur']} uur)")
        print("-" * 60)

else:
    print("MODEL 4: Geen oplossing gevonden.")

MODEL 4: Totale afstand: 390.99 km

Bus 0:
Kamerlingh Onnesweg 9, Dordrecht @ 08:00
Plantageweg 3, Zwijndrecht @ 08:06
Bankastraat 158, Dordrecht @ 08:46
Touwbaan 4, Sliedrecht @ 08:56
Kerkbuurt 220, Sliedrecht @ 09:09
Kerkbuurt 143, Sliedrecht @ 09:19
Jupiterstraat 257, Hardinxveld-Giessendam @ 09:35
Banneweg 57, Gorinchem @ 10:03
Minnaertweg 4, Dordrecht @ 12:06
Albert Schweitzerplaats 1, Dordrecht @ 12:12
Groen Van Prinstererweg 38, Dordrecht @ 12:40
Kamerlingh Onnesweg 9, Dordrecht @ 13:04
Aantal adressen: 10
Afstand: 51.15 km
Totale tijd: 304 min (5.07 uur)
------------------------------------------------------------
Bus 1:
Kamerlingh Onnesweg 9, Dordrecht @ 00:00
Kamerlingh Onnesweg 9, Dordrecht @ 00:00
Aantal adressen: 0
Afstand: 0.0 km
Totale tijd: 0 min (0.0 uur)
------------------------------------------------------------
Bus 2:
Kamerlingh Onnesweg 9, Dordrecht @ 08:00
Vliete 1, Krabbendijke @ 09:22
Pattistpark 137, Terneuzen @ 09:55
Bachlaan 88, Terneuzen @ 10:49
Rooseveltlaan 1, Axel @ 11:46
Molenstraat 95, Zaamslag @ 12:07
De Poort 24, Rilland @ 13:04
Kamerlingh Onnesweg 9, Dordrecht @ 14:22
Aantal adressen: 6
Afstand: 161.72 km
Totale tijd: 382 min (6.37 uur)
------------------------------------------------------------
Bus 3:
Kamerlingh Onnesweg 9, Dordrecht @ 08:00
Pietersdijk 60, Rotterdam @ 08:18
Oosterhagen 17, Rotterdam @ 08:32
Haastrechtstraat 130, Rotterdam @ 08:48
Motorstraat 96, Rotterdam @ 09:24
Maashaven O.Z. 103, Rotterdam @ 10:22
Boergoensestraat 128, Rotterdam @ 10:25
Reling 19, Barendrecht @ 10:42
Noordbolwerk 33, Middelburg @ 12:35
Latijnse Schoolstraat 19, Middelburg @ 13:02
Agaat 2 -12 , Middelburg @ 13:41
Kamerlingh Onnesweg 9, Dordrecht @ 15:59
Aantal adressen: 10
Afstand: 178.12 km
Totale tijd: 479 min (7.98 uur)
------------------------------------------------------------

In [67]:
for route in routes_output4:
    if not route["vehicle_used"]:
        continue

    print(f"Bus {route['vehicle_id']}:")

    for i, (adres, tijd) in enumerate(zip(route['route_adressen'], route['route_times_min'])):
        uur = tijd // 60
        minuut = tijd % 60

        rijtijd = route["route_travel_times_min"][i]
        servicetijd = route["route_service_times_min"][i]

        print(
            f"{adres} @ {uur:02d}:{minuut:02d} "
            f"| rijtijd naar volgende locatie: {rijtijd} min "
            f"| servicetijd op locatie: {servicetijd} min"
        )

    totale_rijtijd = sum(route["route_travel_times_min"])
    totale_servicetijd = sum(route["route_service_times_min"])

    print(f"Aantal adressen: {route['aantal_adressen']}")
    print(f"Afstand: {route['afstand_km']} km")
    print(f"Rijtijd: {totale_rijtijd} min ({totale_rijtijd / 60:.2f} uur)")
    print(f"Servicetijd: {totale_servicetijd} min ({totale_servicetijd / 60:.2f} uur)")
    print(f"Totale tijd: {route['totale_tijd_min']} min ({route['totale_tijd_uur']} uur)")
    print("-" * 60)

Bus 0:
Kamerlingh Onnesweg 9, Dordrecht @ 08:00 | rijtijd naar volgende locatie: 6 min | servicetijd op locatie: 0 min
Plantageweg 3, Zwijndrecht @ 08:06 | rijtijd naar volgende locatie: 6 min | servicetijd op locatie: 34 min
Bankastraat 158, Dordrecht @ 08:46 | rijtijd naar volgende locatie: 7 min | servicetijd op locatie: 3 min
Touwbaan 4, Sliedrecht @ 08:56 | rijtijd naar volgende locatie: 2 min | servicetijd op locatie: 11 min
Kerkbuurt 220, Sliedrecht @ 09:09 | rijtijd naar volgende locatie: 0 min | servicetijd op locatie: 10 min
Kerkbuurt 143, Sliedrecht @ 09:19 | rijtijd naar volgende locatie: 5 min | servicetijd op locatie: 11 min
Jupiterstraat 257, Hardinxveld-Giessendam @ 09:35 | rijtijd naar volgende locatie: 14 min | servicetijd op locatie: 14 min
Banneweg 57, Gorinchem @ 10:03 | rijtijd naar volgende locatie: 29 min | servicetijd op locatie: 94 min
Minnaertweg 4, Dordrecht @ 12:06 | rijtijd naar volgende locatie: 2 min | servicetijd op locatie: 4 min
Albert Schweitzerplaats 1, Dordrecht @ 12:12 | rijtijd naar volgende locatie: 2 min | servicetijd op locatie: 26 min
Groen Van Prinstererweg 38, Dordrecht @ 12:40 | rijtijd naar volgende locatie: 3 min | servicetijd op locatie: 21 min
Kamerlingh Onnesweg 9, Dordrecht @ 13:04 | rijtijd naar volgende locatie: 0 min | servicetijd op locatie: 0 min
Aantal adressen: 10
Afstand: 51.15 km
Rijtijd: 76 min (1.27 uur)
Servicetijd: 228 min (3.80 uur)
Totale tijd: 304 min (5.07 uur)
------------------------------------------------------------
Bus 2:
Kamerlingh Onnesweg 9, Dordrecht @ 08:00 | rijtijd naar volgende locatie: 82 min | servicetijd op locatie: 0 min
Vliete 1, Krabbendijke @ 09:22 | rijtijd naar volgende locatie: 29 min | servicetijd op locatie: 4 min
Pattistpark 137, Terneuzen @ 09:55 | rijtijd naar volgende locatie: 3 min | servicetijd op locatie: 51 min
Bachlaan 88, Terneuzen @ 10:49 | rijtijd naar volgende locatie: 11 min | servicetijd op locatie: 46 min
Rooseveltlaan 1, Axel @ 11:46 | rijtijd naar volgende locatie: 7 min | servicetijd op locatie: 14 min
Molenstraat 95, Zaamslag @ 12:07 | rijtijd naar volgende locatie: 35 min | servicetijd op locatie: 22 min
De Poort 24, Rilland @ 13:04 | rijtijd naar volgende locatie: 76 min | servicetijd op locatie: 2 min
Kamerlingh Onnesweg 9, Dordrecht @ 14:22 | rijtijd naar volgende locatie: 0 min | servicetijd op locatie: 0 min
Aantal adressen: 6
Afstand: 161.72 km
Rijtijd: 243 min (4.05 uur)
Servicetijd: 139 min (2.32 uur)
Totale tijd: 382 min (6.37 uur)
------------------------------------------------------------
Bus 3:
Kamerlingh Onnesweg 9, Dordrecht @ 08:00 | rijtijd naar volgende locatie: 18 min | servicetijd op locatie: 0 min
Pietersdijk 60, Rotterdam @ 08:18 | rijtijd naar volgende locatie: 2 min | servicetijd op locatie: 12 min
Oosterhagen 17, Rotterdam @ 08:32 | rijtijd naar volgende locatie: 3 min | servicetijd op locatie: 13 min
Haastrechtstraat 130, Rotterdam @ 08:48 | rijtijd naar volgende locatie: 4 min | servicetijd op locatie: 32 min
Motorstraat 96, Rotterdam @ 09:24 | rijtijd naar volgende locatie: 2 min | servicetijd op locatie: 56 min
Maashaven O.Z. 103, Rotterdam @ 10:22 | rijtijd naar volgende locatie: 3 min | servicetijd op locatie: 0 min
Boergoensestraat 128, Rotterdam @ 10:25 | rijtijd naar volgende locatie: 8 min | servicetijd op locatie: 9 min
Reling 19, Barendrecht @ 10:42 | rijtijd naar volgende locatie: 108 min | servicetijd op locatie: 5 min
Noordbolwerk 33, Middelburg @ 12:35 | rijtijd naar volgende locatie: 1 min | servicetijd op locatie: 26 min
Latijnse Schoolstraat 19, Middelburg @ 13:02 | rijtijd naar volgende locatie: 1 min | servicetijd op locatie: 38 min
Agaat 2 -12 , Middelburg @ 13:41 | rijtijd naar volgende locatie: 116 min | servicetijd op locatie: 22 min
Kamerlingh Onnesweg 9, Dordrecht @ 15:59 | rijtijd naar volgende locatie: 0 min | servicetijd op locatie: 0 min
Aantal adressen: 10
Afstand: 178.12 km
Rijtijd: 266 min (4.43 uur)
Servicetijd: 213 min (3.55 uur)
Totale tijd: 479 min (7.98 uur)
------------------------------------------------------------

## Model 5

In [68]:
from datetime import datetime, timedelta, timezone

In [ ]:
# ==============================
# MODEL 5 - GOOGLE MAPS REALISTISCHE REISTIJDEN
# ==============================

import requests
import numpy as np
import pandas as pd
import math

LAT_COL = "Lat"
LON_COL = "Long"

tomorrow = datetime.now(timezone.utc).date() + timedelta(days=1)

period_departure_times = {
    "ochtendspits": f"{tomorrow}T08:00:00Z",
    "dal": f"{tomorrow}T11:00:00Z",
    "avondspits": f"{tomorrow}T16:30:00Z",
    "overig": f"{tomorrow}T20:00:00Z",
}


def get_period_from_minutes(minutes):
    if pd.isna(minutes):
        return "overig"
    if 6 * 60 <= minutes < 9 * 60:
        return "ochtendspits"
    if 9 * 60 <= minutes < 15 * 60:
        return "dal"
    if 15 * 60 <= minutes < 18 * 60:
        return "avondspits"
    return "overig"


def parse_google_duration_to_minutes(duration_text):
    if duration_text is None:
        return None
    seconds = int(duration_text.replace("s", ""))
    return max(1, math.ceil(seconds / 60))


def build_google_waypoints(locations, lat_col="Lat", lon_col="Long"):
    waypoints = []

    for _, row in locations.iterrows():
        waypoints.append(
            {
                "waypoint": {
                    "location": {
                        "latLng": {
                            "latitude": float(row[lat_col]),
                            "longitude": float(row[lon_col]),
                        }
                    }
                }
            }
        )

    return waypoints


def chunks(lst, size):
    for i in range(0, len(lst), size):
        yield i, lst[i : i + size]


def build_google_matrices_batched(
    locations,
    api_key,
    departure_time,
    lat_col="Lat",
    lon_col="Long",
    origin_batch_size=10,
    destination_batch_size=10,
    fallback_large_minutes=999999,
    fallback_large_distance=999999999,
):
    n = len(locations)

    time_matrix = np.zeros((n, n), dtype=int)
    distance_matrix_google = np.zeros((n, n), dtype=int)

    all_waypoints = build_google_waypoints(
        locations=locations,
        lat_col=lat_col,
        lon_col=lon_col,
    )

    url = "https://routes.googleapis.com/distanceMatrix/v2:computeRouteMatrix"

    headers = {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": api_key,
        "X-Goog-FieldMask": (
            "originIndex,destinationIndex,duration,"
            "staticDuration,distanceMeters,status,condition"
        ),
    }

    for origin_start, origin_chunk in chunks(all_waypoints, origin_batch_size):
        for dest_start, dest_chunk in chunks(all_waypoints, destination_batch_size):
            body = {
                "origins": origin_chunk,
                "destinations": dest_chunk,
                "travelMode": "DRIVE",
                "routingPreference": "TRAFFIC_AWARE",
                "departureTime": departure_time,
            }

            response = requests.post(url, json=body, headers=headers)

            if response.status_code != 200:
                print("Status code:", response.status_code)
                print("Response text:", response.text)
                response.raise_for_status()

            results = response.json()

            for item in results:
                local_i = item["originIndex"]
                local_j = item["destinationIndex"]

                i = origin_start + local_i
                j = dest_start + local_j

                if i == j:
                    time_matrix[i, j] = 0
                    distance_matrix_google[i, j] = 0
                    continue

                duration_text = item.get("duration") or item.get("staticDuration")
                minutes = parse_google_duration_to_minutes(duration_text)

                distance_meters = item.get("distanceMeters")

                time_matrix[i, j] = (
                    fallback_large_minutes if minutes is None else minutes
                )

                distance_matrix_google[i, j] = (
                    fallback_large_distance if distance_meters is None else int(distance_meters)
                )

            time.sleep(0.1)

    for i in range(n):
        for j in range(n):
            if i != j:
                if time_matrix[i, j] == 0:
                    time_matrix[i, j] = fallback_large_minutes
                if distance_matrix_google[i, j] == 0:
                    distance_matrix_google[i, j] = fallback_large_distance

    return time_matrix, distance_matrix_google

c:\Users\aniek.kasius\AppData\Local\miniconda3\envs\vrp_env\Lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

In [ ]:
# ==============================
# MODEL 5 - TIME/DISTANCE MATRICES PER TIJDVAK VIA GOOGLE MAPS
# ==============================

time_matrices_model5 = {}
distance_matrices_model5 = {}

for period, departure_time in period_departure_times.items():
    print(f"Google matrix ophalen voor: {period} ({departure_time})")

    try:
        time_matrix_period, distance_matrix_google_period = build_google_matrices_batched(
            locations=locations,
            api_key=GOOGLE_API_KEY,
            departure_time=departure_time,
            lat_col=LAT_COL,
            lon_col=LON_COL,
            origin_batch_size=10,
            destination_batch_size=10,
        )

        time_matrices_model5[period] = time_matrix_period
        distance_matrices_model5[period] = distance_matrix_google_period

    except requests.exceptions.HTTPError as e:
        print("\nFOUT BIJ TIJDVAK:", period)
        print("Departure time:", departure_time)
        print("HTTP error:", e)

        if e.response is not None:
            print("Status code:", e.response.status_code)
            print("Google response:")
            print(e.response.text)

        break

print("Google Maps matrices aangemaakt voor:")
print(time_matrices_model5.keys())

Google reistijdmatrix ophalen voor: ochtendspits (2026-05-06T08:00:00Z)
Google reistijdmatrix ophalen voor: dal (2026-05-06T11:00:00Z)
Google reistijdmatrix ophalen voor: avondspits (2026-05-06T16:30:00Z)
Google reistijdmatrix ophalen voor: overig (2026-05-06T20:00:00Z)
Google Maps matrices aangemaakt voor:
dict_keys(['ochtendspits', 'dal', 'avondspits', 'overig'])

In [ ]:
distance_matrix_model5_google = np.round(
    (
        distance_matrices_model5["ochtendspits"]
        + distance_matrices_model5["dal"]
        + distance_matrices_model5["avondspits"]
        + distance_matrices_model5["overig"]
    )
    / 4
).astype(int)

In [72]:
# ==============================
# MODEL 5 - ROUTES MET TIJDSTIPPEN UITLEZEN
# ==============================

def extract_routes_with_times(solution, manager, routing, num_vehicles, locations):
    time_dimension = routing.GetDimensionOrDie("Time")
    routes = []

    for vehicle_id in range(num_vehicles):
        index = routing.Start(vehicle_id)
        route = []

        while not routing.IsEnd(index):
            node = manager.IndexToNode(index)
            current_time = solution.Value(time_dimension.CumulVar(index))
            next_index = solution.Value(routing.NextVar(index))
            next_node = manager.IndexToNode(next_index)

            route.append({
                "vehicle_id": vehicle_id,
                "node": node,
                "address": locations.loc[node, "VisitingAddress"],
                "time_min": current_time,
                "next_node": next_node
            })

            index = next_index

        end_node = manager.IndexToNode(index)
        end_time = solution.Value(time_dimension.CumulVar(index))

        route.append({
            "vehicle_id": vehicle_id,
            "node": end_node,
            "address": locations.loc[end_node, "VisitingAddress"],
            "time_min": end_time,
            "next_node": None
        })

        routes.append(route)

    return routes

In [73]:
# ==============================
# MODEL 5 - MATRIX ACTUALISEREN
# ==============================

def build_time_dependent_matrix_from_solution(routes, time_matrices_model5, base_time_matrix):
    new_matrix = base_time_matrix.copy()

    for route in routes:
        for step in route:
            from_node = step["node"]
            to_node = step["next_node"]

            if to_node is None:
                continue

            departure_time = step["time_min"]
            period = get_period_from_minutes(departure_time)

            new_matrix[from_node][to_node] = time_matrices_model5[period][from_node][to_node]

    return new_matrix

## Runnen

In [ ]:
# ==============================
# MODEL 5 - STRATEGIEËN VERGELIJKEN MET GOOGLE MATRICES
# ==============================

candidate_first_solution_strategies = [
    "PATH_CHEAPEST_ARC",
    "GLOBAL_CHEAPEST_ARC",
    "PARALLEL_CHEAPEST_INSERTION",
    "SAVINGS",
    "CHRISTOFIDES",
]

candidate_local_search_metaheuristics = [
    "GUIDED_LOCAL_SEARCH",
    "TABU_SEARCH",
    "SIMULATED_ANNEALING",
]

MAX_ITERATIONS_MODEL5 = 8

model5_strategy_results = []

overall_best_solution5 = None
overall_best_manager5 = None
overall_best_routing5 = None
overall_best_time_matrix5 = None
overall_best_fs5 = None
overall_best_ls5 = None
overall_best_distance5 = float("inf")
overall_best_runtime5 = float("inf")

# Startmatrix = gemiddelde van alle Google-tijdvakmatrices
base_start_matrix_model5 = np.round(
    (
        time_matrices_model5["ochtendspits"]
        + time_matrices_model5["dal"]
        + time_matrices_model5["avondspits"]
        + time_matrices_model5["overig"]
    )
    / 4
).astype(int)

for fs in candidate_first_solution_strategies:
    for ls in candidate_local_search_metaheuristics:
        print("=" * 80)
        print(f"TEST MODEL 5: {fs} + {ls}")
        print("=" * 80)

        time_matrix_model5_current = base_start_matrix_model5.copy()

        best_solution_combo = None
        best_manager_combo = None
        best_routing_combo = None
        best_time_matrix_combo = None
        final_distance_combo = None
        final_runtime_combo = None
        solution_found_combo = False

        for iteration in range(MAX_ITERATIONS_MODEL5):
            print(f"Iteratie {iteration + 1}")

            manager5, routing5 = build_model_4(
                time_matrix=time_matrix_model5_current,
                distance_matrix=distance_matrix_model5_google,
                num_vehicles=num_vehicles,
                demands=demands,
                vehicle_capacities=vehicle_capacities,
                service_times=service_times,
                time_windows=time_windows,
                depot=0,
            )

            search_parameters5 = pywrapcp.DefaultRoutingSearchParameters()
            search_parameters5.first_solution_strategy = getattr(
                routing_enums_pb2.FirstSolutionStrategy, fs
            )
            search_parameters5.local_search_metaheuristic = getattr(
                routing_enums_pb2.LocalSearchMetaheuristic, ls
            )
            search_parameters5.time_limit.seconds = TIME_LIMIT_SECONDS

            start_runtime = time.time()
            solution5 = routing5.SolveWithParameters(search_parameters5)
            runtime_sec = time.time() - start_runtime

            if solution5 is None:
                print("Geen oplossing gevonden.")
                break

            solution_found_combo = True

            totaal_afstand_iter, routes_output_iter = extract_model_4_routes(
                solution=solution5,
                manager=manager5,
                routing=routing5,
                num_vehicles=num_vehicles,
                locations=locations,
                demands=demands,
                time_matrix=time_matrix_model5_current,
            )

            final_distance_combo = totaal_afstand_iter
            final_runtime_combo = runtime_sec

            best_solution_combo = solution5
            best_manager_combo = manager5
            best_routing_combo = routing5
            best_time_matrix_combo = time_matrix_model5_current.copy()

            routes_with_times = extract_routes_with_times(
                solution=solution5,
                manager=manager5,
                routing=routing5,
                num_vehicles=num_vehicles,
                locations=locations,
            )

            new_time_matrix = build_time_dependent_matrix_from_solution(
                routes=routes_with_times,
                time_matrices_model5=time_matrices_model5,
                base_time_matrix=time_matrix_model5_current,
            )

            changes = np.sum(new_time_matrix != time_matrix_model5_current)
            print("Aantal aangepaste matrixwaarden:", changes)

            if changes == 0:
                print("Matrix stabiel.")
                break

            time_matrix_model5_current = new_time_matrix.copy()

        model5_strategy_results.append(
            {
                "first_solution_strategy": fs,
                "local_search_metaheuristic": ls,
                "solution_found": solution_found_combo,
                "total_distance_m": final_distance_combo,
                "total_distance_km": None
                if final_distance_combo is None
                else round(final_distance_combo / 1000, 2),
                "runtime_sec": final_runtime_combo,
                "iterations_completed": iteration + 1 if solution_found_combo else iteration,
            }
        )

        if solution_found_combo and final_distance_combo < overall_best_distance5:
            overall_best_distance5 = final_distance_combo
            overall_best_runtime5 = final_runtime_combo
            overall_best_solution5 = best_solution_combo
            overall_best_manager5 = best_manager_combo
            overall_best_routing5 = best_routing_combo
            overall_best_time_matrix5 = best_time_matrix_combo
            overall_best_fs5 = fs
            overall_best_ls5 = ls

df_model5_strategy_results = pd.DataFrame(model5_strategy_results)

display(
    df_model5_strategy_results.sort_values(
        by=["solution_found", "total_distance_m", "runtime_sec"],
        ascending=[False, True, True],
    )
)

# Beste combinatie terugzetten naar bestaande variabelen
best_solution5 = overall_best_solution5
best_manager5 = overall_best_manager5
best_routing5 = overall_best_routing5
best_time_matrix5 = overall_best_time_matrix5
best_fs5 = overall_best_fs5
best_ls5 = overall_best_ls5

print("\nBeste combinatie Model 5:")
print(best_fs5, "+", best_ls5)
print("Totale afstand:", round(overall_best_distance5 / 1000, 2), "km")
print("Runtime:", round(overall_best_runtime5, 2), "sec")

================================================================================
TEST MODEL 5: PATH_CHEAPEST_ARC + GUIDED_LOCAL_SEARCH
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 17
Iteratie 2
Aantal aangepaste matrixwaarden: 5
Iteratie 3
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.
================================================================================
TEST MODEL 5: PATH_CHEAPEST_ARC + TABU_SEARCH
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 17
Iteratie 2
Aantal aangepaste matrixwaarden: 15
Iteratie 3
Aantal aangepaste matrixwaarden: 2
Iteratie 4
Aantal aangepaste matrixwaarden: 1
Iteratie 5
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.
================================================================================
TEST MODEL 5: PATH_CHEAPEST_ARC + SIMULATED_ANNEALING
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 17
Iteratie 2
Aantal aangepaste matrixwaarden: 2
Iteratie 3
Aantal aangepaste matrixwaarden: 2
Iteratie 4
Aantal aangepaste matrixwaarden: 1
Iteratie 5
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.
================================================================================
TEST MODEL 5: GLOBAL_CHEAPEST_ARC + GUIDED_LOCAL_SEARCH
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 15
Iteratie 2
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.
================================================================================
TEST MODEL 5: GLOBAL_CHEAPEST_ARC + TABU_SEARCH
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 15
Iteratie 2
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.
================================================================================
TEST MODEL 5: GLOBAL_CHEAPEST_ARC + SIMULATED_ANNEALING
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 15
Iteratie 2
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.
================================================================================
TEST MODEL 5: PARALLEL_CHEAPEST_INSERTION + GUIDED_LOCAL_SEARCH
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 13
Iteratie 2
Aantal aangepaste matrixwaarden: 1
Iteratie 3
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.
================================================================================
TEST MODEL 5: PARALLEL_CHEAPEST_INSERTION + TABU_SEARCH
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 13
Iteratie 2
Aantal aangepaste matrixwaarden: 1
Iteratie 3
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.
================================================================================
TEST MODEL 5: PARALLEL_CHEAPEST_INSERTION + SIMULATED_ANNEALING
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 13
Iteratie 2
Aantal aangepaste matrixwaarden: 1
Iteratie 3
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.
================================================================================
TEST MODEL 5: SAVINGS + GUIDED_LOCAL_SEARCH
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 15
Iteratie 2
Aantal aangepaste matrixwaarden: 6
Iteratie 3
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.
================================================================================
TEST MODEL 5: SAVINGS + TABU_SEARCH
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 17
Iteratie 2
Aantal aangepaste matrixwaarden: 15
Iteratie 3
Aantal aangepaste matrixwaarden: 1
Iteratie 4
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.
================================================================================
TEST MODEL 5: SAVINGS + SIMULATED_ANNEALING
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 16
Iteratie 2
Aantal aangepaste matrixwaarden: 8
Iteratie 3
Aantal aangepaste matrixwaarden: 2
Iteratie 4
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.
================================================================================
TEST MODEL 5: CHRISTOFIDES + GUIDED_LOCAL_SEARCH
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 15
Iteratie 2
Aantal aangepaste matrixwaarden: 6
Iteratie 3
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.
================================================================================
TEST MODEL 5: CHRISTOFIDES + TABU_SEARCH
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 15
Iteratie 2
Aantal aangepaste matrixwaarden: 12
Iteratie 3
Aantal aangepaste matrixwaarden: 6
Iteratie 4
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.
================================================================================
TEST MODEL 5: CHRISTOFIDES + SIMULATED_ANNEALING
================================================================================
Iteratie 1
Aantal aangepaste matrixwaarden: 15
Iteratie 2
Aantal aangepaste matrixwaarden: 12
Iteratie 3
Aantal aangepaste matrixwaarden: 0
Matrix stabiel.

,first_solution_strategy,local_search_metaheuristic,solution_found,total_distance_m,total_distance_km,runtime_sec,iterations_completed
1,PATH_CHEAPEST_ARC,TABU_SEARCH,True,278899,278.90,4.275964,5
10,SAVINGS,TABU_SEARCH,True,278899,278.90,7.159884,4
7,PARALLEL_CHEAPEST_INSERTION,TABU_SEARCH,True,278899,278.90,9.915940,3
4,GLOBAL_CHEAPEST_ARC,TABU_SEARCH,True,278899,278.90,9.997103,2
8,PARALLEL_CHEAPEST_INSERTION,SIMULATED_ANNEALING,True,278899,278.90,9.998791,3
14,CHRISTOFIDES,SIMULATED_ANNEALING,True,278899,278.90,9.999543,3
5,GLOBAL_CHEAPEST_ARC,SIMULATED_ANNEALING,True,278899,278.90,10.000054,2
13,CHRISTOFIDES,TABU_SEARCH,True,278899,278.90,10.000202,4
6,PARALLEL_CHEAPEST_INSERTION,GUIDED_LOCAL_SEARCH,True,278899,278.90,10.000342,3
3,GLOBAL_CHEAPEST_ARC,GUIDED_LOCAL_SEARCH,True,278899,278.90,10.000666,2
0,PATH_CHEAPEST_ARC,GUIDED_LOCAL_SEARCH,True,278899,278.90,10.001190,3
12,CHRISTOFIDES,GUIDED_LOCAL_SEARCH,True,278899,278.90,10.003311,3
9,SAVINGS,GUIDED_LOCAL_SEARCH,True,278899,278.90,10.013076,3
2,PATH_CHEAPEST_ARC,SIMULATED_ANNEALING,True,280158,280.16,10.004228,5
11,SAVINGS,SIMULATED_ANNEALING,True,289593,289.59,9.994762,4

Beste combinatie Model 5:
PATH_CHEAPEST_ARC + GUIDED_LOCAL_SEARCH
Totale afstand: 278.9 km
Runtime: 10.0 sec

In [78]:
# ==============================
# MODEL 5 - RESULTATEN UITLEZEN
# ==============================

if best_solution5 is not None:
    totaal_afstand5, routes_output5 = extract_model_4_routes(
        solution=best_solution5,
        manager=best_manager5,
        routing=best_routing5,
        num_vehicles=num_vehicles,
        locations=locations,
        demands=demands,
        time_matrix=best_time_matrix5
    )

    print(f"\nMODEL 5: Totale afstand: {round(totaal_afstand5 / 1000, 2)} km")
    print(f"Gebruikte combinatie: {best_fs5} + {best_ls5}\n")

    for route in routes_output5:
        if not route["vehicle_used"]:
            continue

        print(f"Bus {route['vehicle_id']}:")

        for i, (adres, tijd) in enumerate(
            zip(route["route_adressen"], route["route_times_min"])
        ):
            uur = tijd // 60
            minuut = tijd % 60
            periode = get_period_from_minutes(tijd)

            rijtijd = route["route_travel_times_min"][i]
            servicetijd = route["route_service_times_min"][i]

            print(
                f"{adres} @ {uur:02d}:{minuut:02d} ({periode}) "
                f"| rijtijd naar volgende locatie: {rijtijd} min "
                f"| servicetijd op locatie: {servicetijd} min"
            )

        totale_rijtijd = sum(route["route_travel_times_min"])
        totale_servicetijd = sum(route["route_service_times_min"])

        print(f"Aantal adressen: {route['aantal_adressen']}")
        print(f"Afstand: {route['afstand_km']} km")
        print(f"Rijtijd: {totale_rijtijd} min ({totale_rijtijd / 60:.2f} uur)")
        print(f"Servicetijd: {totale_servicetijd} min ({totale_servicetijd / 60:.2f} uur)")
        print(f"Totale tijd: {route['totale_tijd_min']} min ({route['totale_tijd_uur']} uur)")
        print("-" * 60)

else:
    print("MODEL 5: Geen oplossing gevonden.")

MODEL 5: Totale afstand: 278.9 km
Gebruikte combinatie: PATH_CHEAPEST_ARC + GUIDED_LOCAL_SEARCH

Bus 0:
Kamerlingh Onnesweg 9, Dordrecht @ 08:00 (ochtendspits) | rijtijd naar volgende locatie: 8 min | servicetijd op locatie: 0 min
Groen Van Prinstererweg 38, Dordrecht @ 08:08 (ochtendspits) | rijtijd naar volgende locatie: 6 min | servicetijd op locatie: 21 min
Albert Schweitzerplaats 1, Dordrecht @ 08:35 (ochtendspits) | rijtijd naar volgende locatie: 6 min | servicetijd op locatie: 26 min
Bankastraat 158, Dordrecht @ 09:07 (dal) | rijtijd naar volgende locatie: 13 min | servicetijd op locatie: 3 min
Touwbaan 4, Sliedrecht @ 09:23 (dal) | rijtijd naar volgende locatie: 5 min | servicetijd op locatie: 11 min
Kerkbuurt 220, Sliedrecht @ 09:39 (dal) | rijtijd naar volgende locatie: 5 min | servicetijd op locatie: 10 min
Kerkbuurt 143, Sliedrecht @ 09:54 (dal) | rijtijd naar volgende locatie: 9 min | servicetijd op locatie: 11 min
Jupiterstraat 257, Hardinxveld-Giessendam @ 10:14 (dal) | rijtijd naar volgende locatie: 12 min | servicetijd op locatie: 14 min
Banneweg 57, Gorinchem @ 10:40 (dal) | rijtijd naar volgende locatie: 26 min | servicetijd op locatie: 94 min
Minnaertweg 4, Dordrecht @ 12:40 (dal) | rijtijd naar volgende locatie: 10 min | servicetijd op locatie: 4 min
Kamerlingh Onnesweg 9, Dordrecht @ 12:54 (dal) | rijtijd naar volgende locatie: 0 min | servicetijd op locatie: 0 min
Aantal adressen: 9
Afstand: 47.19 km
Rijtijd: 100 min (1.67 uur)
Servicetijd: 194 min (3.23 uur)
Totale tijd: 294 min (4.9 uur)
------------------------------------------------------------
Bus 1:
Kamerlingh Onnesweg 9, Dordrecht @ 08:00 (ochtendspits) | rijtijd naar volgende locatie: 45 min | servicetijd op locatie: 0 min
De Poort 24, Rilland @ 08:45 (ochtendspits) | rijtijd naar volgende locatie: 7 min | servicetijd op locatie: 2 min
Vliete 1, Krabbendijke @ 08:54 (ochtendspits) | rijtijd naar volgende locatie: 46 min | servicetijd op locatie: 4 min
Molenstraat 95, Zaamslag @ 09:44 (dal) | rijtijd naar volgende locatie: 10 min | servicetijd op locatie: 22 min
Rooseveltlaan 1, Axel @ 10:16 (dal) | rijtijd naar volgende locatie: 12 min | servicetijd op locatie: 14 min
Bachlaan 88, Terneuzen @ 10:42 (dal) | rijtijd naar volgende locatie: 5 min | servicetijd op locatie: 46 min
Pattistpark 137, Terneuzen @ 11:33 (dal) | rijtijd naar volgende locatie: 31 min | servicetijd op locatie: 51 min
Agaat 2 -12 , Middelburg @ 12:55 (dal) | rijtijd naar volgende locatie: 7 min | servicetijd op locatie: 22 min
Latijnse Schoolstraat 19, Middelburg @ 13:24 (dal) | rijtijd naar volgende locatie: 5 min | servicetijd op locatie: 38 min
Noordbolwerk 33, Middelburg @ 14:07 (dal) | rijtijd naar volgende locatie: 76 min | servicetijd op locatie: 26 min
Kamerlingh Onnesweg 9, Dordrecht @ 15:49 (avondspits) | rijtijd naar volgende locatie: 0 min | servicetijd op locatie: 0 min
Aantal adressen: 9
Afstand: 191.95 km
Rijtijd: 244 min (4.07 uur)
Servicetijd: 225 min (3.75 uur)
Totale tijd: 469 min (7.82 uur)
------------------------------------------------------------
Bus 2:
Kamerlingh Onnesweg 9, Dordrecht @ 08:00 (ochtendspits) | rijtijd naar volgende locatie: 12 min | servicetijd op locatie: 0 min
Plantageweg 3, Zwijndrecht @ 08:12 (ochtendspits) | rijtijd naar volgende locatie: 16 min | servicetijd op locatie: 34 min
Pietersdijk 60, Rotterdam @ 09:02 (dal) | rijtijd naar volgende locatie: 7 min | servicetijd op locatie: 12 min
Oosterhagen 17, Rotterdam @ 09:21 (dal) | rijtijd naar volgende locatie: 8 min | servicetijd op locatie: 13 min
Haastrechtstraat 130, Rotterdam @ 09:42 (dal) | rijtijd naar volgende locatie: 14 min | servicetijd op locatie: 32 min
Motorstraat 96, Rotterdam @ 10:28 (dal) | rijtijd naar volgende locatie: 7 min | servicetijd op locatie: 56 min
Maashaven O.Z. 103, Rotterdam @ 11:31 (dal) | rijtijd naar volgende locatie: 9 min | servicetijd op locatie: 0 min
Boergoensestraat 128, Rotterdam @ 11:40 (dal) | rijtijd naar volgende locatie: 17 min | servicetijd op locatie: 9 min
Reling 19, Barendrecht @ 12:06 (dal) | rijtijd naar volgende locatie: 21 min | servicetijd op locatie: 5 min
Kamerlingh Onnesweg 9, Dordrecht @ 12:32 (dal) | rijtijd naar volgende locatie: 0 min | servicetijd op locatie: 0 min
Aantal adressen: 8
Afstand: 39.76 km
Rijtijd: 111 min (1.85 uur)
Servicetijd: 161 min (2.68 uur)
Totale tijd: 272 min (4.53 uur)
------------------------------------------------------------

## Google maps

In [76]:
# ==============================
# MODEL 5 - GOOGLE MAPS LINKS MAKEN
# ==============================

def make_google_maps_url_from_nodes(route_nodes, locations, lat_col="Lat", lon_col="Long"):
    """
    Maakt een Google Maps route-link op basis van node-volgorde.
    Werkt zonder Google API key.
    """

    coords = []

    for node in route_nodes:
        lat = locations.loc[node, lat_col]
        lon = locations.loc[node, lon_col]

        if pd.isna(lat) or pd.isna(lon):
            continue

        coords.append(f"{lat},{lon}")

    if len(coords) < 2:
        return None

    return "https://www.google.com/maps/dir/" + "/".join(coords)


def extract_route_nodes_from_solution(solution, manager, routing, num_vehicles):
    """
    Haalt per voertuig de volgorde van bezochte nodes uit de OR-Tools oplossing.
    """

    all_routes_nodes = []

    for vehicle_id in range(num_vehicles):
        index = routing.Start(vehicle_id)
        route_nodes = []

        while not routing.IsEnd(index):
            node = manager.IndexToNode(index)
            route_nodes.append(node)
            index = solution.Value(routing.NextVar(index))

        end_node = manager.IndexToNode(index)
        route_nodes.append(end_node)

        all_routes_nodes.append({
            "vehicle_id": vehicle_id,
            "route_nodes": route_nodes,
            "vehicle_used": len(set(route_nodes)) > 1
        })

    return all_routes_nodes


# ==============================
# MODEL 5 - GOOGLE MAPS ROUTES PRINTEN
# ==============================

if best_solution5:
    google_maps_routes_model5 = extract_route_nodes_from_solution(
        solution=best_solution5,
        manager=best_manager5,
        routing=best_routing5,
        num_vehicles=num_vehicles
    )

    print("\n" + "=" * 80)
    print("MODEL 5 - GOOGLE MAPS ROUTELINKS")
    print("=" * 80)

    for route in google_maps_routes_model5:
        if not route["vehicle_used"]:
            continue

        maps_url = make_google_maps_url_from_nodes(
            route_nodes=route["route_nodes"],
            locations=locations,
            lat_col="Lat",
            lon_col="Long"
        )

        print(f"\nBus {route['vehicle_id']}:")
        print("Aantal stops:", len(route["route_nodes"]))

        if maps_url:
            print(maps_url)
        else:
            print("Geen geldige Google Maps-link mogelijk voor deze bus.")

else:
    print("Geen Model 5-oplossing beschikbaar om Google Maps-links te maken.")

================================================================================
MODEL 5 - GOOGLE MAPS ROUTELINKS
================================================================================

Bus 0:
Aantal stops: 11
https://www.google.com/maps/dir/51.780575,4.638942/51.79102472857143,4.665775114285714/51.79280641904762,4.6826865714285715/51.80792522,4.68616494/51.82696635,4.7491137/51.82322504,4.7685898/51.823264449999996,4.7709024499999995/51.82374876,4.82280886/51.83845036666667,4.95674095/51.7834310368421,4.686273663157895/51.780575,4.638942

Bus 1:
Aantal stops: 10
https://www.google.com/maps/dir/51.780575,4.638942/51.81554672222222,4.630499366666666/51.876502953846156,4.553646007692308/51.88874976,4.559416486666667/51.88000802727272,4.536396772727273/51.88739842,4.4951837/51.9012338,4.49656335/51.891205,4.470011100000001/51.8493588,4.4993659/51.780575,4.638942

Bus 2:
Aantal stops: 11
https://www.google.com/maps/dir/51.780575,4.638942/51.422283033333336,4.191319933333333/51.4227524,4.0966080499999995/51.30924004,3.9079534199999997/51.2646848,3.90139715/51.31909438,3.84669504/51.334505825,3.8565008/51.49291981428571,3.6184854857142854/51.49964944,3.61277264/51.504090107692306,3.611024753846154/51.780575,4.638942

In [162]:
import folium

In [163]:
# ==============================
# MODEL 5 - ROUTES VISUALISEREN OP KAART
# ==============================

def visualize_model5_routes_on_map(
    google_maps_routes_model5,
    locations,
    lat_col="Latitude",
    lon_col="Longitude",
    address_col="VisitingAddress"
):
    center_lat = locations[lat_col].mean()
    center_lon = locations[lon_col].mean()

    m = folium.Map(location=[center_lat, center_lon], zoom_start=10)

    colors = [
        "red", "blue", "green", "purple", "orange",
        "darkred", "cadetblue", "darkgreen", "black"
    ]

    for route in google_maps_routes_model5:
        if not route["vehicle_used"]:
            continue

        vehicle_id = route["vehicle_id"]
        route_nodes = route["route_nodes"]
        color = colors[vehicle_id % len(colors)]

        route_coords = []

        for stop_number, node in enumerate(route_nodes):
            row = locations.iloc[node]

            lat = row[lat_col]
            lon = row[lon_col]
            address = row[address_col]

            route_coords.append([lat, lon])

            folium.Marker(
                location=[lat, lon],
                popup=(
                    f"Bus {vehicle_id}<br>"
                    f"Stop {stop_number}<br>"
                    f"{address}"
                ),
                tooltip=f"Bus {vehicle_id} - stop {stop_number}",
                icon=folium.Icon(color=color if color != "black" else "gray")
            ).add_to(m)

        folium.PolyLine(
            route_coords,
            color=color,
            weight=4,
            opacity=0.8,
            tooltip=f"Route bus {vehicle_id}"
        ).add_to(m)

    return m

In [164]:
kaart_model5 = visualize_model5_routes_on_map(
    google_maps_routes_model5,
    locations,
    lat_col="Lat",
    lon_col="Long"
)

kaart_model5