In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv(
    'data/Bezoeken per voertuig 01-01-2025 - 31-12-2025.Csv',
    sep=';',
    encoding='utf-16',
    skiprows=1
)

C:\Users\aniek.kasius\AppData\Local\Temp\ipykernel_2936\1523193955.py:1: DtypeWarning: Columns (0: Contact) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [4]:
df

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,967 (VDG-43-S),02-01-2025,06:48,07:17,10:27,"35,90",00:28,3:10,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,3:39,0:28,3:10,0:00,"35,90",51.905395,4.332835
1,967 (VDG-43-S),02-01-2025,10:27,10:39,10:43,"5,10",00:11,0:03,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,3:54,0:40,3:14,0:00,"41,00",51.905395,4.332835
2,967 (VDG-43-S),02-01-2025,10:43,11:36,12:17,"61,00",00:53,0:41,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,5:29,1:33,3:55,0:00,"102,00",51.905395,4.332835
3,967 (VDG-43-S),02-01-2025,12:17,12:58,14:51,"27,30",00:40,1:52,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,8:02,2:14,5:47,0:00,"129,30",51.905395,4.332835
4,967 (VDG-43-S),02-01-2025,14:51,15:06,06:55,"3,70",00:15,15:49,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,8:17,2:29,5:47,8:17,"133,00",51.905395,4.332835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59128,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
59129,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
59130,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400
59131,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293
59132,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417

In [5]:
df["VisitingAddress"].unique()

<StringArray>
[            'Produktiestraat 2, Vlaardingen',
        'Nettenboetsterstraat 1, Vlaardingen',
           'Kamerlingh Onnesweg 9, Dordrecht',
      'Rijksweg A20 2, Nieuwerkerk Ad Ijssel',
        'Fransezoom 8, Nieuwerkerk Ad Ijssel',
                'Hoppersingel 3123, Schiedam',
           'Churchillsingel 449, Vlaardingen',
              'Ranonkelstraat 9, Spijkenisse',
                 'Voorberghlaan 35, Schiedam',
                            'manege 1, gouda',
 ...
                'Boezemsingel 106, Rotterdam',
                  'Beukelsweg 105, Rotterdam',
                 'Nieuwe Haven 233, Schiedam',
                 'Molenaar 8, Oud-Beijerland',
            'Ganshoeksingel 63, Lage Zwaluwe',
                   'Molenberg 13, Middelburg',
                    'Keplerweg 63, Dordrecht',
     'Laan Der Verenigde Naties 9, Dordrecht',
            'Ziedewijdsedijk 11, Barendrecht',
 'Molenvlietsingel 8, Krimpen Aan Den Ijssel']
Length: 6450, dtype: str

In [6]:
df[df["VisitingAddress"] == "Kamerlingh Onnesweg 9, Dordrecht"]

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
13,967 (VDG-43-S),17-02-2025,07:56,08:58,09:49,"36,00",01:02,0:50,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:52,1:02,0:50,0:00,"36,00",51.780551,4.638886
29,967 (VDG-43-S),19-02-2025,07:34,08:23,09:29,"35,90",00:49,1:05,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:55,0:49,1:05,0:00,"35,90",51.780618,4.638920
37,967 (VDG-43-S),20-02-2025,07:56,08:54,09:43,"35,90",00:58,0:48,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:46,0:58,0:48,0:00,"35,90",51.780554,4.638891
47,967 (VDG-43-S),21-02-2025,14:09,15:14,16:03,"41,90",01:05,0:48,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,8:51,2:23,6:28,0:00,"81,90",51.780491,4.638972
49,967 (VDG-43-S),24-02-2025,07:54,08:33,09:17,"36,20",00:38,0:43,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:22,0:38,0:43,0:00,"36,20",51.780570,4.638849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59114,1775 (V-11-GGL),24-12-2025,13:11,13:36,13:42,"26,74",00:24,0:05,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,6:09,2:58,3:10,0:00,"82,20",51.780543,4.639462
59115,1775 (V-11-GGL),24-12-2025,13:42,13:42,08:25,"0,08",00:00,138:42,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,6:09,2:59,3:10,6:09,"82,28",51.780596,4.638693
59122,1775 (V-11-GGL),31-12-2025,06:28,06:51,07:04,"25,68",00:23,0:12,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:36,0:23,0:12,0:00,"25,68",51.780570,4.639440
59123,1775 (V-11-GGL),31-12-2025,07:04,07:05,07:42,"0,18",00:01,0:37,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:14,0:24,0:50,0:00,"25,86",51.780616,4.638754
59132,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417

In [7]:
# bekijken welke auto's elke dag naar het depot gaan
depot_naam = "Kamerlingh Onnesweg 9, Dordrecht"

In [8]:
# als de dataframe al in de juiste volgorde staat:
# per Date en SerialNumber de eerste en laatste rij pakken

eerste_stop = (
    df.groupby(["Date", "SerialNumber"], sort=False)
      .first()
      .reset_index()[["Date", "SerialNumber", "VisitingAddress"]]
      .rename(columns={"VisitingAddress": "eerste_stop"})
)

laatste_stop = (
    df.groupby(["Date", "SerialNumber"], sort=False)
      .last()
      .reset_index()[["Date", "SerialNumber", "VisitingAddress"]]
      .rename(columns={"VisitingAddress": "laatste_stop"})
)

# samenvoegen
start_eind_check = eerste_stop.merge(
    laatste_stop,
    on=["Date", "SerialNumber"],
    how="inner"
)

# alleen groepen die starten én eindigen bij depot
groepen_depot_start_eind = start_eind_check[
    (start_eind_check["eerste_stop"] == depot_naam) &
    (start_eind_check["laatste_stop"] == depot_naam)
][["Date", "SerialNumber"]]

# originele dataset filteren op die groepen
df01 = df.merge(
    groepen_depot_start_eind,
    on=["Date", "SerialNumber"],
    how="inner"
)

df01

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,967 (VDG-43-S),14-10-2025,07:50,08:20,09:41,"35,70",00:29,1:20,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:50,0:29,1:20,0:00,"35,70",51.780592,4.638408
1,967 (VDG-43-S),14-10-2025,09:41,09:42,10:08,"0,10",00:01,0:26,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,2:17,0:30,1:46,0:00,"35,80",51.780628,4.639095
2,967 (VDG-43-S),14-10-2025,10:08,10:47,11:21,"43,10",00:38,0:33,"Ronsseweg 410, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Ronsseweg 410,2803ZX,Gouda,NaN,0:00,3:30,1:09,2:20,0:00,"78,90",52.018870,4.705445
3,967 (VDG-43-S),14-10-2025,11:21,11:30,11:54,"1,60",00:09,0:24,"Van De Puttestraat 119, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Van De Puttestraat 119,2804JL,Gouda,NaN,0:00,4:03,1:18,2:45,0:00,"80,50",52.027592,4.708583
4,967 (VDG-43-S),14-10-2025,11:54,12:06,13:26,"3,00",00:11,1:19,"De Lange Van Wijngaardenstraat 5, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,De Lange Van Wijngaardenstraat 5,2806WN,Gouda,NaN,0:00,5:35,1:29,4:05,0:00,"83,50",52.013176,4.718882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
2742,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
2743,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400
2744,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293
2745,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417

In [9]:
import folium
from folium.plugins import HeatMap
from IPython.display import display

c:\Users\aniek.kasius\AppData\Local\miniconda3\envs\vrp_env\Lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

In [10]:
import folium
from folium.plugins import HeatMap

lat_col = 'Lat'
lon_col = 'Long'

# Filter rijen zonder coördinaten
df01_heat = df01.dropna(subset=[lat_col, lon_col])

# Maak kaart (andere tiles om 403 te voorkomen)
m = folium.Map(
    location=[52.1, 5.3],
    zoom_start=8,
    tiles='CartoDB positron'
)

# Voeg heatmap toe
HeatMap(
    data=df01_heat[[lat_col, lon_col]].values,
    radius=8,
    blur=15
).add_to(m)

m

In [13]:
m.save("heatmap.html")