In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    'data/Bezoeken per voertuig 01-01-2025 - 31-12-2025.Csv',
    sep=';',
    encoding='utf-16',
    skiprows=1  # <-- dit is de key!
)

C:\Users\aniek.kasius\AppData\Local\Temp\ipykernel_5168\2624480332.py:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,967 (VDG-43-S),02-01-2025,06:48,07:17,10:27,"35,90",00:28,3:10,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,3:39,0:28,3:10,0:00,"35,90",51.905395,4.332835
1,967 (VDG-43-S),02-01-2025,10:27,10:39,10:43,"5,10",00:11,0:03,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,3:54,0:40,3:14,0:00,"41,00",51.905395,4.332835
2,967 (VDG-43-S),02-01-2025,10:43,11:36,12:17,"61,00",00:53,0:41,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,5:29,1:33,3:55,0:00,"102,00",51.905395,4.332835
3,967 (VDG-43-S),02-01-2025,12:17,12:58,14:51,"27,30",00:40,1:52,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,8:02,2:14,5:47,0:00,"129,30",51.905395,4.332835
4,967 (VDG-43-S),02-01-2025,14:51,15:06,06:55,"3,70",00:15,15:49,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,8:17,2:29,5:47,8:17,"133,00",51.905395,4.332835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59128,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
59129,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
59130,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400
59131,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293
59132,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417

In [5]:
df["VisitingAddress"].unique()

array(['Produktiestraat 2, Vlaardingen',
       'Nettenboetsterstraat 1, Vlaardingen',
       'Kamerlingh Onnesweg 9, Dordrecht', ...,
       'Laan Der Verenigde Naties 9, Dordrecht',
       'Ziedewijdsedijk 11, Barendrecht',
       'Molenvlietsingel 8, Krimpen Aan Den Ijssel'],
      shape=(6450,), dtype=object)

In [6]:
df[df["VisitingAddress"] == "Kamerlingh Onnesweg 9, Dordrecht"]

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
13,967 (VDG-43-S),17-02-2025,07:56,08:58,09:49,"36,00",01:02,0:50,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:52,1:02,0:50,0:00,"36,00",51.780551,4.638886
29,967 (VDG-43-S),19-02-2025,07:34,08:23,09:29,"35,90",00:49,1:05,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:55,0:49,1:05,0:00,"35,90",51.780618,4.638920
37,967 (VDG-43-S),20-02-2025,07:56,08:54,09:43,"35,90",00:58,0:48,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:46,0:58,0:48,0:00,"35,90",51.780554,4.638891
47,967 (VDG-43-S),21-02-2025,14:09,15:14,16:03,"41,90",01:05,0:48,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,8:51,2:23,6:28,0:00,"81,90",51.780491,4.638972
49,967 (VDG-43-S),24-02-2025,07:54,08:33,09:17,"36,20",00:38,0:43,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:22,0:38,0:43,0:00,"36,20",51.780570,4.638849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59114,1775 (V-11-GGL),24-12-2025,13:11,13:36,13:42,"26,74",00:24,0:05,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,6:09,2:58,3:10,0:00,"82,20",51.780543,4.639462
59115,1775 (V-11-GGL),24-12-2025,13:42,13:42,08:25,"0,08",00:00,138:42,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,6:09,2:59,3:10,6:09,"82,28",51.780596,4.638693
59122,1775 (V-11-GGL),31-12-2025,06:28,06:51,07:04,"25,68",00:23,0:12,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,0:36,0:23,0:12,0:00,"25,68",51.780570,4.639440
59123,1775 (V-11-GGL),31-12-2025,07:04,07:05,07:42,"0,18",00:01,0:37,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:14,0:24,0:50,0:00,"25,86",51.780616,4.638754
59132,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417

In [7]:
# bekijken welke auto's elke dag naar het depot gaan
depot_naam = "Kamerlingh Onnesweg 9, Dordrecht"

In [8]:
# eerste stop per dag per voertuig
idx_eerste = df.groupby(["Date", "SerialNumber"])["Start"].idxmin()
eerste_stop = df.loc[idx_eerste, ["Date", "SerialNumber", "VisitingAddress"]]
eerste_stop = eerste_stop.rename(columns={"VisitingAddress": "eerste_stop"})

# laatste stop per dag per voertuig
idx_laatste = df.groupby(["Date", "SerialNumber"])["Stop"].idxmax()
laatste_stop = df.loc[idx_laatste, ["Date", "SerialNumber", "VisitingAddress"]]
laatste_stop = laatste_stop.rename(columns={"VisitingAddress": "laatste_stop"})

# samenvoegen
start_eind_check = eerste_stop.merge(
    laatste_stop,
    on=["Date", "SerialNumber"],
    how="inner"
)

# alleen groepen die starten én eindigen bij depot
groepen_depot_start_eind = start_eind_check[
    (start_eind_check["eerste_stop"] == depot_naam) &
    (start_eind_check["laatste_stop"] == depot_naam)
][["Date", "SerialNumber"]]

# originele dataset filteren op die groepen
df01 = df.merge(
    groepen_depot_start_eind,
    on=["Date", "SerialNumber"],
    how="inner"
)

df01

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,967 (VDG-43-S),10-03-2025,07:52,08:29,09:52,"36,00",00:37,1:22,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:59,0:37,1:22,0:00,"36,00",51.780566,4.638908
1,967 (VDG-43-S),10-03-2025,09:52,10:31,10:35,"29,70",00:39,0:04,"Rijksweg A20 2, Nieuwerkerk Ad Ijssel",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Rijksweg A20 2,2913LW,Nieuwerkerk Ad Ijssel,NaN,0:00,2:43,1:16,1:26,0:00,"65,70",51.966202,4.588517
2,967 (VDG-43-S),10-03-2025,10:35,10:50,12:08,"13,70",00:14,1:17,"Ronsseweg 485, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Ronsseweg 485,2803ZG,Gouda,NaN,0:00,4:15,1:31,2:44,0:00,"79,40",52.018854,4.705738
3,967 (VDG-43-S),10-03-2025,12:08,12:14,13:40,"0,80",00:06,1:25,"Savelberghof 43, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Savelberghof 43,2805RT,Gouda,NaN,0:00,5:48,1:38,4:09,0:00,"80,20",52.020777,4.713963
4,967 (VDG-43-S),10-03-2025,13:40,14:07,14:32,"13,50",00:27,0:25,"Poorthuisstraat 59, Bergambacht",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Poorthuisstraat 59,2861DV,Bergambacht,NaN,0:00,6:40,2:05,4:35,0:00,"93,70",51.929160,4.784648
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5770,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
5771,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
5772,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400
5773,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293
5774,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417

In [9]:
df01["adres"] = df01["VisitingAddress"].str.split(",").str[0]

In [10]:
df01 = df01.rename(columns={
    "ZipCode": "postcode",
    "City": "plaats",
    "Lat": "latitude",
    "Long": "longitude"
})

In [11]:
df02 = df01

In [12]:
df02["adres"] = df02["adres"].str.strip().str.lower()
df02["postcode"] = df02["postcode"].str.strip().str.upper()
df02["plaats"] = df02["plaats"].str.strip().str.lower()

In [13]:
df02["postcode"] = (
    df02["postcode"]
    .str.strip()
    .str.upper()
    .str.replace(" ", "", regex=False)
)

In [14]:
df02["postcode"] = df02["postcode"].str.replace(
    r"(\d{4})([A-Z]{2})", r"\1 \2", regex=True
)

In [15]:
df02.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5775 entries, 0 to 5774
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SerialNumber         5775 non-null   object
 1   Date                 5775 non-null   object
 2   StartRide            5775 non-null   object
 3   Start                5775 non-null   object
 4   Stop                 5775 non-null   object
 5   Distance             5775 non-null   object
 6   TravelTime           5775 non-null   object
 7   Duration             5775 non-null   object
 8   VisitingAddress      5775 non-null   object
 9   Description          1602 non-null   object
 10  DriverName           5445 non-null   object
 11  GroupName            5775 non-null   object
 12  Contact              2 non-null      object
 13  Remark               0 non-null      object
 14  To                   5772 non-null   object
 15  postcode             5768 non-null   object
 16  plaats               5775 non-null   object
 17  ProjectNumber        1602 non-null   float64
 18  Break                5775 non-null   object
 19  TotalTime            5775 non-null   object
 20  TotalTravelTime      5775 non-null   object
 21  TotalDuration        5775 non-null   object
 22  TotalTimeMinusBreak  5775 non-null   object
 23  TotalDistance        5775 non-null   object
 24  latitude             5775 non-null   float64
 25  longitude            5775 non-null   float64
 26  adres                5775 non-null   object
dtypes: float64(3), object(24)
memory usage: 1.2+ MB

In [16]:
df03 = df02

In [17]:
df03[df03["postcode"].isna()]

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,postcode,plaats,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,latitude,longitude,adres
1496,1185 (VJL-22-K),03-06-2025,13:55,13:56,14:05,"0,17",00:01,0:09,"Amphia Ziekenhuis Molengracht 1, Breda",NaN,Geertjan van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Amphia Ziekenhuis Molengracht 1,NaN,breda,NaN,0:00,6:23,3:35,2:47,0:00,"169,98",51.582767,4.798070,amphia ziekenhuis molengracht 1
2529,1313 (VPS-11-J),18-02-2025,07:26,07:26,08:09,"0,00",00:00,0:42,", ?",NaN,Robin Kovács,BBT Dordrecht/MHG,NaN,NaN,NaN,NaN,?,NaN,0:00,1:31,0:39,0:51,0:00,"34,50",0.000000,0.000000,
4065,1597 (VZT-42-V),06-03-2025,15:12,15:25,06:01,"3,88",00:13,14:35,"Rondweg 1, Dordrecht",NaN,Sheamie Gerard,BBT Dordrecht/MHG,NaN,NaN,Rondweg 1,NaN,dordrecht,NaN,0:00,9:07,3:01,6:05,9:07,"78,89",51.813420,4.707171,rondweg 1
4760,1702 (V-19-FXR),12-09-2025,14:36,14:45,14:45,"5,43",00:08,0:00,", ?",NaN,Ronald Griend,BBT Dordrecht/MHG,NaN,NaN,NaN,NaN,?,NaN,0:00,7:04,3:18,3:46,0:00,"216,05",51.752231,4.157008,
5060,1705 (V-18-FXR),14-08-2025,10:29,11:01,11:01,"30,74",00:32,0:00,De Val,NaN,Marcus Dekker,BBT Dordrecht/MHG,NaN,NaN,NaN,NaN,de val,NaN,0:00,4:15,2:19,1:56,0:00,"158,79",51.622348,3.904958,de val
5394,1775 (V-11-GGL),06-03-2025,11:19,11:20,11:36,"0,17",00:01,0:16,"Amphia Ziekenhuis Molengracht 1, Breda",NaN,Frido Wijnen,BBT Dordrecht/MHG,NaN,NaN,Amphia Ziekenhuis Molengracht 1,NaN,breda,NaN,0:00,4:09,2:00,2:09,0:00,"137,36",51.582783,4.798137,amphia ziekenhuis molengracht 1
5437,1775 (V-11-GGL),26-03-2025,11:04,11:05,12:21,"0,18",00:00,1:16,"Amphia Ziekenhuis Molengracht 1, Breda",NaN,Geertjan van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Amphia Ziekenhuis Molengracht 1,NaN,breda,NaN,0:00,4:33,1:15,3:17,0:00,"45,42",51.582735,4.798040,amphia ziekenhuis molengracht 1

In [18]:
df03.loc[[1496, 5394, 5437], "postcode"] = "4818 CK"

In [19]:
df04 = df03

In [20]:
df04.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5775 entries, 0 to 5774
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SerialNumber         5775 non-null   object
 1   Date                 5775 non-null   object
 2   StartRide            5775 non-null   object
 3   Start                5775 non-null   object
 4   Stop                 5775 non-null   object
 5   Distance             5775 non-null   object
 6   TravelTime           5775 non-null   object
 7   Duration             5775 non-null   object
 8   VisitingAddress      5775 non-null   object
 9   Description          1602 non-null   object
 10  DriverName           5445 non-null   object
 11  GroupName            5775 non-null   object
 12  Contact              2 non-null      object
 13  Remark               0 non-null      object
 14  To                   5772 non-null   object
 15  postcode             5771 non-null   object
 16  plaats               5775 non-null   object
 17  ProjectNumber        1602 non-null   float64
 18  Break                5775 non-null   object
 19  TotalTime            5775 non-null   object
 20  TotalTravelTime      5775 non-null   object
 21  TotalDuration        5775 non-null   object
 22  TotalTimeMinusBreak  5775 non-null   object
 23  TotalDistance        5775 non-null   object
 24  latitude             5775 non-null   float64
 25  longitude            5775 non-null   float64
 26  adres                5775 non-null   object
dtypes: float64(3), object(24)
memory usage: 1.2+ MB

In [21]:
df_service = pd.read_excel("data/Serviceorders - 01-01-2025 - 31-12-2025.xlsx")

In [22]:
df_service

,Herstelstatuscodefilter,Toewijzingsdatumfilter,Responsdatumfilter,Resourcefilter,Resourcegroepfilter,Niet toegewezen,Opmerking,Documentnr.,Toewijzingsdatum,Resourcenr.,Herstelstatuscode,Resourcegroepnr.,Responsdatum,Laaste opmerking,Serviceordersoort,Postcode,Plaats,Punten,Aantal serviceorders,Aantal verkooporders,Cliëntnr.,Naam,Zorginstellingnaam,Orderdatum,Datum laatste opmerking,Verkoperscode,Omschrijving,Factuurnaam,Adres,Vaste monteur,Artikelnr.,Serienummer,Dagen in verwerking,Uw referentie,Portaalopmerking,Datum portaalopmerking,Totaalbedrag
0,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2322714,2025-02-18,OFFERTE,90,OFFERTE,2023-05-03,IV: Jop heeft Wouter gemaild om op te pakken 1...,REP,3232 LE,BRIELLE,12,5,0,K0011683,Mevr. B. van Toor,Careyn - De Plantage,2023-04-24,2025-02-13,JOP,Puma 40,CZ/Administratie Zorgkantoor,Plantageweg 4,Peter B,PUMA40.00010,18ZKCZ0245,288,202512200812820,NaN,NaT,943.42
1,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2339887,2025-11-27,JOP,99,ADVISEUR,2023-12-01,NH: lijst gemaakt voor Jop,REP,3363 WB,SLIEDRECHT,6,29,0,K0079751,Mevr. S. Mohar,ASVZ - De Merwebolder,2023-11-23,2025-02-14,JOP,MID Lectus,VGZ Zorgkantoor,Touwbaan 1,Tjerk P,MIDLECTUS.00010,VGZ002411,80,Wacht op zorginfo,NaN,NaT,0.00
2,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2341189,2025-01-20,OFFERTE,90,OFFERTE,2023-12-15,"ADV: vrijloophendel niet verkrijgbaar, nieuwe ...",REP,4301 NW,ZIERIKZEE,15,5,0,K0043840,Mevr. P. Verwest,Allevo - Zierik7,2023-12-08,NaT,ROBBY,Morgan Newton,CZ/Administratie Zorgkantoor,Emil Sandstromweg 2,Tom B,MORGANNEWTON.00010,55255110,262,202512200808613,NaN,NaT,2800.82
3,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2341990,2025-01-28,JOP,99,ADVISEUR,2023-12-29,NH: lijst voor Jop gemaakt,REP,2643 JJ,PIJNACKER,24,11,0,510431,Mw. S. Bhawanie,Pieter van Foreest - Weidevogelhof,2023-12-19,2025-02-14,JOP,Puma 40,NTAC Zorgkantoor,Raaigras 102,Cornelis van der G,PUMA40.00010,ZKS00464,286,Wacht op QQ-nummer,NaN,NaT,0.00
4,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2400380,2025-01-06,OFFERTE,90,OFFERTE,2024-01-15,"Uitgevoerd, ondertekening goedgekeurd",REP,4382 LJ,VLISSINGEN,9,27,2,K0062065,Mevr. N. Langstraat,S Heeren Loo - Nieuwe Zuidbeekseweg,2024-01-08,2025-05-13,RUUD,QUICKIE ATTITUDE HYBRID 2,CZ/Administratie Zorgkantoor,Stadhuisplein 22,Tom B,ATTITUDEH2.00010,5525FIE1241,231,202512200807424,NaN,NaT,1603.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25368,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2527954,2025-12-31,MARKE,90,MONTEURS,2026-01-09,BW: @Marke,REP,3078 RC,ROTTERDAM,0,14,0,K0024206,Dhr. E. Dam,Aafje - Meerweide,2025-12-31,NaT,RUUD,Puma Q400 M SedeoPro middenwielaandrijving,Zilveren Kruis Zorgkantoor,Grote Hagen 98,Sandro G,Q400M.00010,ACH0131305,51,NaN,NaN,NaT,15.41
25369,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2527961,2025-12-31,LIZA,99,MONTEURS,2026-01-09,Uitgevoerd,POREP,3079 TD,ROTTERDAM,0,19,0,K0069286,Dhr. P. Lugtigheid,Aafje - Smeetsland,2025-12-31,2025-12-31,JULIAN,Puma Q400 M SedeoPro middenwielaandrijving,Zilveren Kruis Zorgkantoor,Pietersdijk 60,Liza de G,Q400M.00010,ACH0130666,65,PO,NaN,NaT,0.00
25370,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2600367,2025-12-22,JOP,5,ADVISEUR,2026-07-20,Wacht op bericht,PASSING,2625 TD,DELFT,0,0,2,K0108508,Mevr. J.E. van der Hoeven-Bannier,Pieter van Foreest - Die Buytenweye,2026-01-07,2026-01-07,JOP,Roxx New Original Newton,NTAC Zorgkantoor,Chopinlaan 9,Cornelis van der G,ROXXNEWTON.00010,ZKS02784,60,Wacht op A nummer,NaN,NaT,0.00
25371,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2600377,2025-12-24,ROBBY,5,ADVISEUR,2026-07-20,Wacht op bericht,PASSING,4461 LX,GOES,0,9,0,K0101144,Dhr. A. Molenaar,Cedrah - Woonzorgcentrum Rehoboth,2026-01-07,2026-01-07,NATHALIEH,Ibis Pro rolstoel,CZ/Administratie Zorgkantoor,Bergweg 1,Vincent K,IBIS.00010,55253501,60,Wacht op zorginfo,NaN,NaT,0.00
25372,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2601272,2025-12-19,JOP,5,ADVISEUR,2026-07-30,Wacht op bericht,PASSING,3363 WB,SLIEDRECHT,0,4,0,162145,Mevr. E.P. Verweij,ASVZ - De Merwebolder,2026-01-19,2026-01-19,JOP,Match duwonderstel,VGZ Zorgkantoor,Touwbaan 1,Tjerk P,MATCHD.00010,UVIT-24519,52,Wacht op zorginfo,NaN,NaT,0.00

In [30]:
df_verkoop = pd.read_excel("data/Verkooporders - 01-01-2025 - 31-12-2025.xlsx")
df_verkoop

,Divisie,Documentfilter,Uitgevoerd,Planningdatum filter,Statuscode,Soort filter,Resource(groep)nr. filter,Uitbesteed,Productie status,Plandatum,Contractdatum,Serienr.,Originele samenstellingscode,Documentnr.,Uitgevoerd1,Resource(groep)nr.,Note,Postcode,Plaats,Zorginstellingnaam,Statuscode1,Gebruikers-id,Klantnaam,Laatste opmerkingsregel,Productie status1,Samenstellingscode,Verkoper
0,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-13,5526HR0514,8D,VOR240061208,1,NaN,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland,P010,BREVA\F.BOSCH,Mevr. A. van Putten-Vermoen,Verwacht: week 4,Nog te ondertekenen,8D,RUUD
1,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-13,5526HR0514,8D,VOR240061208,1,NaN,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland,P015,BREVA\M.KASLANDER,Mevr. A. van Putten-Vermoen,Verwacht: week 4,Nog te ondertekenen,8D,RUUD
2,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-08,ZKS02555,NTAC,VOR240061069,1,NaN,NaN,3141 CJ,MAASSLUIS,Argos - De Tweemaster,P025,BREVA\M.STROO,Mevr. J.G. Lamens-Bouter,NaN,Ondertekening goedgekeurd,NTAC,MEREL
3,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-09,ACH0124955,8D,VOR240061926,1,NaN,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,P025,BREVA\Y.YEH,Dhr. J. de Jong,Carla; ter controle,Nog te ondertekenen,8D,ROBBY
4,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-09,AGIS51556,8D,VOR240061936,1,NaN,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,P025,BREVA\P.KAPPER,Dhr. R. Petri,remblokjes blocker remsysteem nee,Nog te ondertekenen,8D,ROBBY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13535,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-22,5526HR0562,8D,VOR250062583,1,NaN,NaN,3265 BV,PIERSHIL,Verzorgingshuis Heemzicht,P135,AD\MARCEL.STROO,Mevr. H. Koesveld-Prins,Aangepast formulier in de bijlagen gedaan.,Nog te ondertekenen,8D,NATHALIEH
13536,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2026-01-02,ACH0127404,8D,VOR250063316,1,NaN,NaN,3055 JD,ROTTERDAM,WelThuis - de State Hillegersberg,P135,AD\MARCEL.STROO,Mevr. E.J. Boot-Tolk,Verwacht: week 2,Nog te ondertekenen,8D,MEREL
13537,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-15,55256260,10D,VOR250058380,1,NaN,NaN,4571 HT,AXEL,SVRZ - de Vurssche,P136,AD\K2-SVC-SOAPWEB-PROD,Mevr. E.E.M. Koorevaar-van de Putte,Gewijzigd: Week 1 ivm herbevestiging fabrikant,Ondertekening afgekeurd,10D,ROBBY
13538,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-15,55256260,10D,VOR250058380,1,NaN,NaN,4571 HT,AXEL,SVRZ - de Vurssche,P137,AD\K2-SVC-SOAPWEB-PROD,Mevr. E.E.M. Koorevaar-van de Putte,Gewijzigd: Week 1 ivm herbevestiging fabrikant,Ondertekening afgekeurd,10D,ROBBY
13539,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2026-01-02,NaN,RETOUR,VOR250063955,1,NaN,NaN,3136 EA,VLAARDINGEN,Zonnehuisgroep Vlaardingen - Cred. adm.,P150,AD\NANDA.VAN.SINTMAARTE,Zonnehuis groep - Zonnehuis,NaN,Middel opgehaald,RETOUR,JOP

In [31]:
# adres maken, kijken of zorginstelling in serviceorders ook in verkooporders staat, want dan kunnen we deze aan elkaar linken.
df_verkoop[df_verkoop["Zorginstellingnaam"].isin(df_service["Zorginstellingnaam"])]

,Divisie,Documentfilter,Uitgevoerd,Planningdatum filter,Statuscode,Soort filter,Resource(groep)nr. filter,Uitbesteed,Productie status,Plandatum,Contractdatum,Serienr.,Originele samenstellingscode,Documentnr.,Uitgevoerd1,Resource(groep)nr.,Note,Postcode,Plaats,Zorginstellingnaam,Statuscode1,Gebruikers-id,Klantnaam,Laatste opmerkingsregel,Productie status1,Samenstellingscode,Verkoper
0,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-13,5526HR0514,8D,VOR240061208,1,NaN,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland,P010,BREVA\F.BOSCH,Mevr. A. van Putten-Vermoen,Verwacht: week 4,Nog te ondertekenen,8D,RUUD
1,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-13,5526HR0514,8D,VOR240061208,1,NaN,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland,P015,BREVA\M.KASLANDER,Mevr. A. van Putten-Vermoen,Verwacht: week 4,Nog te ondertekenen,8D,RUUD
2,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-08,ZKS02555,NTAC,VOR240061069,1,NaN,NaN,3141 CJ,MAASSLUIS,Argos - De Tweemaster,P025,BREVA\M.STROO,Mevr. J.G. Lamens-Bouter,NaN,Ondertekening goedgekeurd,NTAC,MEREL
3,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-09,ACH0124955,8D,VOR240061926,1,NaN,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,P025,BREVA\Y.YEH,Dhr. J. de Jong,Carla; ter controle,Nog te ondertekenen,8D,ROBBY
4,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-09,AGIS51556,8D,VOR240061936,1,NaN,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,P025,BREVA\P.KAPPER,Dhr. R. Petri,remblokjes blocker remsysteem nee,Nog te ondertekenen,8D,ROBBY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13534,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-19,5526ER0565,5D,VOR250062615,1,NaN,NaN,3265 BV,PIERSHIL,Verzorgingshuis Heemzicht,P135,AD\MARCEL.STROO,Mevr. A. Kooiman-Van der Meer,Verwacht: week 2,Nog te ondertekenen,5D,NATHALIEH
13535,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-22,5526HR0562,8D,VOR250062583,1,NaN,NaN,3265 BV,PIERSHIL,Verzorgingshuis Heemzicht,P135,AD\MARCEL.STROO,Mevr. H. Koesveld-Prins,Aangepast formulier in de bijlagen gedaan.,Nog te ondertekenen,8D,NATHALIEH
13536,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2026-01-02,ACH0127404,8D,VOR250063316,1,NaN,NaN,3055 JD,ROTTERDAM,WelThuis - de State Hillegersberg,P135,AD\MARCEL.STROO,Mevr. E.J. Boot-Tolk,Verwacht: week 2,Nog te ondertekenen,8D,MEREL
13537,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-15,55256260,10D,VOR250058380,1,NaN,NaN,4571 HT,AXEL,SVRZ - de Vurssche,P136,AD\K2-SVC-SOAPWEB-PROD,Mevr. E.E.M. Koorevaar-van de Putte,Gewijzigd: Week 1 ivm herbevestiging fabrikant,Ondertekening afgekeurd,10D,ROBBY
13538,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-15,55256260,10D,VOR250058380,1,NaN,NaN,4571 HT,AXEL,SVRZ - de Vurssche,P137,AD\K2-SVC-SOAPWEB-PROD,Mevr. E.E.M. Koorevaar-van de Putte,Gewijzigd: Week 1 ivm herbevestiging fabrikant,Ondertekening afgekeurd,10D,ROBBY

In [32]:
df_service_unique = (
    df_service.groupby("Zorginstellingnaam", as_index=False)
    .first()[["Zorginstellingnaam", "Adres"]]
)

df_verkoop = df_verkoop.merge(
    df_service_unique,
    on="Zorginstellingnaam",
    how="left"
)
df_verkoop

,Divisie,Documentfilter,Uitgevoerd,Planningdatum filter,Statuscode,Soort filter,Resource(groep)nr. filter,Uitbesteed,Productie status,Plandatum,Contractdatum,Serienr.,Originele samenstellingscode,Documentnr.,Uitgevoerd1,Resource(groep)nr.,Note,Postcode,Plaats,Zorginstellingnaam,Statuscode1,Gebruikers-id,Klantnaam,Laatste opmerkingsregel,Productie status1,Samenstellingscode,Verkoper,Adres
0,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-13,5526HR0514,8D,VOR240061208,1,NaN,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland,P010,BREVA\F.BOSCH,Mevr. A. van Putten-Vermoen,Verwacht: week 4,Nog te ondertekenen,8D,RUUD,Oude Watering 15
1,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-13,5526HR0514,8D,VOR240061208,1,NaN,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland,P015,BREVA\M.KASLANDER,Mevr. A. van Putten-Vermoen,Verwacht: week 4,Nog te ondertekenen,8D,RUUD,Oude Watering 15
2,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-08,ZKS02555,NTAC,VOR240061069,1,NaN,NaN,3141 CJ,MAASSLUIS,Argos - De Tweemaster,P025,BREVA\M.STROO,Mevr. J.G. Lamens-Bouter,NaN,Ondertekening goedgekeurd,NTAC,MEREL,Vondelpark 2
3,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-09,ACH0124955,8D,VOR240061926,1,NaN,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,P025,BREVA\Y.YEH,Dhr. J. de Jong,Carla; ter controle,Nog te ondertekenen,8D,ROBBY,Hamakerstraat 77
4,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-09,AGIS51556,8D,VOR240061936,1,NaN,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,P025,BREVA\P.KAPPER,Dhr. R. Petri,remblokjes blocker remsysteem nee,Nog te ondertekenen,8D,ROBBY,Hamakerstraat 77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13535,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-22,5526HR0562,8D,VOR250062583,1,NaN,NaN,3265 BV,PIERSHIL,Verzorgingshuis Heemzicht,P135,AD\MARCEL.STROO,Mevr. H. Koesveld-Prins,Aangepast formulier in de bijlagen gedaan.,Nog te ondertekenen,8D,NATHALIEH,Voorstraat 26
13536,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2026-01-02,ACH0127404,8D,VOR250063316,1,NaN,NaN,3055 JD,ROTTERDAM,WelThuis - de State Hillegersberg,P135,AD\MARCEL.STROO,Mevr. E.J. Boot-Tolk,Verwacht: week 2,Nog te ondertekenen,8D,MEREL,Beethovenlaan 60
13537,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-15,55256260,10D,VOR250058380,1,NaN,NaN,4571 HT,AXEL,SVRZ - de Vurssche,P136,AD\K2-SVC-SOAPWEB-PROD,Mevr. E.E.M. Koorevaar-van de Putte,Gewijzigd: Week 1 ivm herbevestiging fabrikant,Ondertekening afgekeurd,10D,ROBBY,Rooseveltlaan 1
13538,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-15,55256260,10D,VOR250058380,1,NaN,NaN,4571 HT,AXEL,SVRZ - de Vurssche,P137,AD\K2-SVC-SOAPWEB-PROD,Mevr. E.E.M. Koorevaar-van de Putte,Gewijzigd: Week 1 ivm herbevestiging fabrikant,Ondertekening afgekeurd,10D,ROBBY,Rooseveltlaan 1
13539,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2026-01-02,NaN,RETOUR,VOR250063955,1,NaN,NaN,3136 EA,VLAARDINGEN,Zonnehuisgroep Vlaardingen - Cred. adm.,P150,AD\NANDA.VAN.SINTMAARTE,Zonnehuis groep - Zonnehuis,NaN,Middel opgehaald,RETOUR,JOP,NaN

In [33]:
df_verkoop[df_verkoop["Adres"].isna()]['Zorginstellingnaam'].unique()

array(['De Rijnhoven - Coninckshof', 'Middin - De nieuwe Lansingh',
       'Harting-Bank Den Haag Den Hoorn', 'Philadelphia - Meesplein',
       'Rijndam Revalidatiecentrum', 'Gors - Valckeslotlaan',
       'NRG Fitness Premium Terneuzen', 'Gemiva-SVG - Smaragd',
       'De Hoop - Provincialeweg', 'Gemiva-SVG - Schuttersvlucht',
       'Philadelphia - Eline Verestraat', 'BES Groothandel BV',
       "Amarant - 't Hooge Veer", 'Philadelphia - De blauwe lis',
       'Cavent - Lindehoeve', 'Yulius - A.W. de Landgraafstraat',
       'Amarant - de Heul', 'Amarant - Speelhuislaan', 'R.M.O. Oekraïne',
       'Drechtwerk', 'Gemeente Vlissingen', 'SDW - De Zuidwal',
       'Sjaloom Zorg - Wonen Westplaat',
       'Zonnehuisgroep Vlaardingen - Cred. adm.'], dtype=object)

In [34]:
df_verkoop[df_verkoop["Zorginstellingnaam"] == "R.M.O. Oekraïne"]

,Divisie,Documentfilter,Uitgevoerd,Planningdatum filter,Statuscode,Soort filter,Resource(groep)nr. filter,Uitbesteed,Productie status,Plandatum,Contractdatum,Serienr.,Originele samenstellingscode,Documentnr.,Uitgevoerd1,Resource(groep)nr.,Note,Postcode,Plaats,Zorginstellingnaam,Statuscode1,Gebruikers-id,Klantnaam,Laatste opmerkingsregel,Productie status1,Samenstellingscode,Verkoper,Adres
7431,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-08,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,NaN,NaN,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P010,BREVA\M.STROO,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN
7455,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-08,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,NaN,NaN,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P030,BREVA\D.FERNANDEZ,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN
7459,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-08,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,NaN,NaN,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P050,BREVA\M.STROO,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN
7910,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-15,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,SHEAMIE,NaN,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P115,BREVA\T.KASTEREN,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN
7995,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-16,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,SHEAMIE,SCOOTMOBIEL AFLEVEREN IN AAFJE MEERWEIDE VZ 546,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P120,BREVA\W.VANDERSTERREN,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN
8020,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-17,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,NaN,RL:OIB,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P0252,BREVA\R.LUIJENDIJK,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN
8028,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-17,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,NaN,NaN,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P040,BREVA\J.WITMONT,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN
8072,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-17,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,SHEAMIE,NaN,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P130,BREVA\A.GIJZEN,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN
8077,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-17,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,NaN,NaN,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P135,BREVA\M.STROO,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN
8156,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-19,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,NaN,NaN,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P060,BREVA\J.WITMONT,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN
8315,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-23,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,NaN,NaN,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P070,BREVA\B.VANWIJK,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN
8316,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-23,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,NaN,NaN,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P080,BREVA\B.VANWIJK,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN
8320,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-23,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,NaN,NaN,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P090,BREVA\B.VANWIJK,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN
8325,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-23,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,NaN,NaN,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P100,BREVA\S.VERSNEL,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN
8405,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-09-24,2025-09-02,2424007914801,BUDGETTAIR,VOR250044766,1,NaN,NaN,3100 AB,SCHIEDAM,R.M.O. Oekraïne,P110,BREVA\M.STROO,Mevr. S. Mikulova,Verwacht: week 39,Nog te ondertekenen,BUDGETTAIR,THOMASR,NaN

In [35]:
df_verkoop_1 = df_verkoop[df_verkoop["Zorginstellingnaam"] != "R.M.O. Oekraïne"]
df_verkoop_1

,Divisie,Documentfilter,Uitgevoerd,Planningdatum filter,Statuscode,Soort filter,Resource(groep)nr. filter,Uitbesteed,Productie status,Plandatum,Contractdatum,Serienr.,Originele samenstellingscode,Documentnr.,Uitgevoerd1,Resource(groep)nr.,Note,Postcode,Plaats,Zorginstellingnaam,Statuscode1,Gebruikers-id,Klantnaam,Laatste opmerkingsregel,Productie status1,Samenstellingscode,Verkoper,Adres
0,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-13,5526HR0514,8D,VOR240061208,1,NaN,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland,P010,BREVA\F.BOSCH,Mevr. A. van Putten-Vermoen,Verwacht: week 4,Nog te ondertekenen,8D,RUUD,Oude Watering 15
1,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-13,5526HR0514,8D,VOR240061208,1,NaN,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland,P015,BREVA\M.KASLANDER,Mevr. A. van Putten-Vermoen,Verwacht: week 4,Nog te ondertekenen,8D,RUUD,Oude Watering 15
2,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-08,ZKS02555,NTAC,VOR240061069,1,NaN,NaN,3141 CJ,MAASSLUIS,Argos - De Tweemaster,P025,BREVA\M.STROO,Mevr. J.G. Lamens-Bouter,NaN,Ondertekening goedgekeurd,NTAC,MEREL,Vondelpark 2
3,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-09,ACH0124955,8D,VOR240061926,1,NaN,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,P025,BREVA\Y.YEH,Dhr. J. de Jong,Carla; ter controle,Nog te ondertekenen,8D,ROBBY,Hamakerstraat 77
4,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-09,AGIS51556,8D,VOR240061936,1,NaN,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,P025,BREVA\P.KAPPER,Dhr. R. Petri,remblokjes blocker remsysteem nee,Nog te ondertekenen,8D,ROBBY,Hamakerstraat 77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13535,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-22,5526HR0562,8D,VOR250062583,1,NaN,NaN,3265 BV,PIERSHIL,Verzorgingshuis Heemzicht,P135,AD\MARCEL.STROO,Mevr. H. Koesveld-Prins,Aangepast formulier in de bijlagen gedaan.,Nog te ondertekenen,8D,NATHALIEH,Voorstraat 26
13536,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2026-01-02,ACH0127404,8D,VOR250063316,1,NaN,NaN,3055 JD,ROTTERDAM,WelThuis - de State Hillegersberg,P135,AD\MARCEL.STROO,Mevr. E.J. Boot-Tolk,Verwacht: week 2,Nog te ondertekenen,8D,MEREL,Beethovenlaan 60
13537,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-15,55256260,10D,VOR250058380,1,NaN,NaN,4571 HT,AXEL,SVRZ - de Vurssche,P136,AD\K2-SVC-SOAPWEB-PROD,Mevr. E.E.M. Koorevaar-van de Putte,Gewijzigd: Week 1 ivm herbevestiging fabrikant,Ondertekening afgekeurd,10D,ROBBY,Rooseveltlaan 1
13538,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-15,55256260,10D,VOR250058380,1,NaN,NaN,4571 HT,AXEL,SVRZ - de Vurssche,P137,AD\K2-SVC-SOAPWEB-PROD,Mevr. E.E.M. Koorevaar-van de Putte,Gewijzigd: Week 1 ivm herbevestiging fabrikant,Ondertekening afgekeurd,10D,ROBBY,Rooseveltlaan 1
13539,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2026-01-02,NaN,RETOUR,VOR250063955,1,NaN,NaN,3136 EA,VLAARDINGEN,Zonnehuisgroep Vlaardingen - Cred. adm.,P150,AD\NANDA.VAN.SINTMAARTE,Zonnehuis groep - Zonnehuis,NaN,Middel opgehaald,RETOUR,JOP,NaN

In [46]:
nieuwe_adressen = pd.DataFrame({
    "Zorginstellingnaam": [
        "De Rijnhoven - Coninckshof",
        "Middin - De nieuwe Lansingh",
        "Harting-Bank Den Haag Den Hoorn",
        "Philadelphia - Meesplein",
        "Rijndam Revalidatiecentrum",
        "Gors - Valckeslotlaan",
        "NRG Fitness Premium Terneuzen",
        "Gemiva-SVG - Smaragd",
        "De Hoop - Provincialeweg",
        "Gemiva-SVG - Schuttersvlucht",
        "Philadelphia - Eline Verestraat",
        "BES Groothandel BV",
        "Amarant - 't Hooge Veer",
        "Philadelphia - De blauwe lis",
        "Cavent - Lindehoeve",
        "Yulius - A.W. de Landgraafstraat",
        "Amarant - de Heul",
        "Amarant - Speelhuislaan",
        "Drechtwerk",
        "Gemeente Vlissingen",
        "SDW - De Zuidwal",
        "Sjaloom Zorg - Wonen Westplaat",
        "Zonnehuisgroep Vlaardingen - Cred. adm."
    ],
    "adres": [
        "Utrechtse Heuvelrug 180",
        "Dominee van Koetsveldstraat 3",
        "Westernesse 18",
        "Burgemeester Meesplein 43",
        "Westersingel 300",
        "Valckeslotlaan 159",
        "Vliegende Vaart 1",
        "Tuindersvaart 48",
        "Provincialeweg 70",
        "Schuttersvlucht 13",
        "Eline Verestraat 21a",
        "Harregatplein 6A",
        "Bredaseweg 375",
        "Vivaldilaan 94a",
        "Mookhoek 111",
        "A.W. de Landgraafstraat 38",
        "Kasteellaan 25",
        "Doenradestraat 50",
        "Snelliusstraat 10",
        "Paul Krugerstraat 1",
        "Van Gaverenlaan 46",
        "Antoon Coolenstraat 136",
        "Dillenburgsingel 5"
    ]
})

In [47]:
df_verkoop_2 = df_verkoop_1.merge(
    nieuwe_adressen,
    on="Zorginstellingnaam",
    how="left",
    suffixes=("", "_nieuw")
)

In [48]:
df_verkoop_2

,Divisie,Documentfilter,Uitgevoerd,Planningdatum filter,Statuscode,Soort filter,Resource(groep)nr. filter,Uitbesteed,Productie status,Plandatum,Contractdatum,Serienr.,Originele samenstellingscode,Documentnr.,Uitgevoerd1,Resource(groep)nr.,Note,Postcode,Plaats,Zorginstellingnaam,Statuscode1,Gebruikers-id,Klantnaam,Laatste opmerkingsregel,Productie status1,Samenstellingscode,Verkoper,Adres,adres
0,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-13,5526HR0514,8D,VOR240061208,1,NaN,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland,P010,BREVA\F.BOSCH,Mevr. A. van Putten-Vermoen,Verwacht: week 4,Nog te ondertekenen,8D,RUUD,Oude Watering 15,NaN
1,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-13,5526HR0514,8D,VOR240061208,1,NaN,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland,P015,BREVA\M.KASLANDER,Mevr. A. van Putten-Vermoen,Verwacht: week 4,Nog te ondertekenen,8D,RUUD,Oude Watering 15,NaN
2,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-08,ZKS02555,NTAC,VOR240061069,1,NaN,NaN,3141 CJ,MAASSLUIS,Argos - De Tweemaster,P025,BREVA\M.STROO,Mevr. J.G. Lamens-Bouter,NaN,Ondertekening goedgekeurd,NTAC,MEREL,Vondelpark 2,NaN
3,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-09,ACH0124955,8D,VOR240061926,1,NaN,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,P025,BREVA\Y.YEH,Dhr. J. de Jong,Carla; ter controle,Nog te ondertekenen,8D,ROBBY,Hamakerstraat 77,NaN
4,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-01-02,2025-01-09,AGIS51556,8D,VOR240061936,1,NaN,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,P025,BREVA\P.KAPPER,Dhr. R. Petri,remblokjes blocker remsysteem nee,Nog te ondertekenen,8D,ROBBY,Hamakerstraat 77,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13520,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-22,5526HR0562,8D,VOR250062583,1,NaN,NaN,3265 BV,PIERSHIL,Verzorgingshuis Heemzicht,P135,AD\MARCEL.STROO,Mevr. H. Koesveld-Prins,Aangepast formulier in de bijlagen gedaan.,Nog te ondertekenen,8D,NATHALIEH,Voorstraat 26,NaN
13521,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2026-01-02,ACH0127404,8D,VOR250063316,1,NaN,NaN,3055 JD,ROTTERDAM,WelThuis - de State Hillegersberg,P135,AD\MARCEL.STROO,Mevr. E.J. Boot-Tolk,Verwacht: week 2,Nog te ondertekenen,8D,MEREL,Beethovenlaan 60,NaN
13522,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-15,55256260,10D,VOR250058380,1,NaN,NaN,4571 HT,AXEL,SVRZ - de Vurssche,P136,AD\K2-SVC-SOAPWEB-PROD,Mevr. E.E.M. Koorevaar-van de Putte,Gewijzigd: Week 1 ivm herbevestiging fabrikant,Ondertekening afgekeurd,10D,ROBBY,Rooseveltlaan 1,NaN
13523,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-15,55256260,10D,VOR250058380,1,NaN,NaN,4571 HT,AXEL,SVRZ - de Vurssche,P137,AD\K2-SVC-SOAPWEB-PROD,Mevr. E.E.M. Koorevaar-van de Putte,Gewijzigd: Week 1 ivm herbevestiging fabrikant,Ondertekening afgekeurd,10D,ROBBY,Rooseveltlaan 1,NaN
13524,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2026-01-02,NaN,RETOUR,VOR250063955,1,NaN,NaN,3136 EA,VLAARDINGEN,Zonnehuisgroep Vlaardingen - Cred. adm.,P150,AD\NANDA.VAN.SINTMAARTE,Zonnehuis groep - Zonnehuis,NaN,Middel opgehaald,RETOUR,JOP,NaN,Dillenburgsingel 5

In [49]:
df_verkoop_2["Adres"] = df_verkoop_2["Adres"].fillna(df_verkoop_2["adres"])

In [50]:
df_verkoop_2 = df_verkoop_2.drop(columns=["adres"])

In [51]:
df_verkoop_2[df_verkoop_2["Adres"].isna()][["Zorginstellingnaam", "Adres"]]

Empty DataFrame
Columns: [Zorginstellingnaam, Adres]
Index: []

In [52]:
df_service

,Herstelstatuscodefilter,Toewijzingsdatumfilter,Responsdatumfilter,Resourcefilter,Resourcegroepfilter,Niet toegewezen,Opmerking,Documentnr.,Toewijzingsdatum,Resourcenr.,Herstelstatuscode,Resourcegroepnr.,Responsdatum,Laaste opmerking,Serviceordersoort,Postcode,Plaats,Punten,Aantal serviceorders,Aantal verkooporders,Cliëntnr.,Naam,Zorginstellingnaam,Orderdatum,Datum laatste opmerking,Verkoperscode,Omschrijving,Factuurnaam,Adres,Vaste monteur,Artikelnr.,Serienummer,Dagen in verwerking,Uw referentie,Portaalopmerking,Datum portaalopmerking,Totaalbedrag
0,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2322714,2025-02-18,OFFERTE,90,OFFERTE,2023-05-03,IV: Jop heeft Wouter gemaild om op te pakken 1...,REP,3232 LE,BRIELLE,12,5,0,K0011683,Mevr. B. van Toor,Careyn - De Plantage,2023-04-24,2025-02-13,JOP,Puma 40,CZ/Administratie Zorgkantoor,Plantageweg 4,Peter B,PUMA40.00010,18ZKCZ0245,288,202512200812820,NaN,NaT,943.42
1,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2339887,2025-11-27,JOP,99,ADVISEUR,2023-12-01,NH: lijst gemaakt voor Jop,REP,3363 WB,SLIEDRECHT,6,29,0,K0079751,Mevr. S. Mohar,ASVZ - De Merwebolder,2023-11-23,2025-02-14,JOP,MID Lectus,VGZ Zorgkantoor,Touwbaan 1,Tjerk P,MIDLECTUS.00010,VGZ002411,80,Wacht op zorginfo,NaN,NaT,0.00
2,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2341189,2025-01-20,OFFERTE,90,OFFERTE,2023-12-15,"ADV: vrijloophendel niet verkrijgbaar, nieuwe ...",REP,4301 NW,ZIERIKZEE,15,5,0,K0043840,Mevr. P. Verwest,Allevo - Zierik7,2023-12-08,NaT,ROBBY,Morgan Newton,CZ/Administratie Zorgkantoor,Emil Sandstromweg 2,Tom B,MORGANNEWTON.00010,55255110,262,202512200808613,NaN,NaT,2800.82
3,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2341990,2025-01-28,JOP,99,ADVISEUR,2023-12-29,NH: lijst voor Jop gemaakt,REP,2643 JJ,PIJNACKER,24,11,0,510431,Mw. S. Bhawanie,Pieter van Foreest - Weidevogelhof,2023-12-19,2025-02-14,JOP,Puma 40,NTAC Zorgkantoor,Raaigras 102,Cornelis van der G,PUMA40.00010,ZKS00464,286,Wacht op QQ-nummer,NaN,NaT,0.00
4,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2400380,2025-01-06,OFFERTE,90,OFFERTE,2024-01-15,"Uitgevoerd, ondertekening goedgekeurd",REP,4382 LJ,VLISSINGEN,9,27,2,K0062065,Mevr. N. Langstraat,S Heeren Loo - Nieuwe Zuidbeekseweg,2024-01-08,2025-05-13,RUUD,QUICKIE ATTITUDE HYBRID 2,CZ/Administratie Zorgkantoor,Stadhuisplein 22,Tom B,ATTITUDEH2.00010,5525FIE1241,231,202512200807424,NaN,NaT,1603.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25368,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2527954,2025-12-31,MARKE,90,MONTEURS,2026-01-09,BW: @Marke,REP,3078 RC,ROTTERDAM,0,14,0,K0024206,Dhr. E. Dam,Aafje - Meerweide,2025-12-31,NaT,RUUD,Puma Q400 M SedeoPro middenwielaandrijving,Zilveren Kruis Zorgkantoor,Grote Hagen 98,Sandro G,Q400M.00010,ACH0131305,51,NaN,NaN,NaT,15.41
25369,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2527961,2025-12-31,LIZA,99,MONTEURS,2026-01-09,Uitgevoerd,POREP,3079 TD,ROTTERDAM,0,19,0,K0069286,Dhr. P. Lugtigheid,Aafje - Smeetsland,2025-12-31,2025-12-31,JULIAN,Puma Q400 M SedeoPro middenwielaandrijving,Zilveren Kruis Zorgkantoor,Pietersdijk 60,Liza de G,Q400M.00010,ACH0130666,65,PO,NaN,NaT,0.00
25370,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2600367,2025-12-22,JOP,5,ADVISEUR,2026-07-20,Wacht op bericht,PASSING,2625 TD,DELFT,0,0,2,K0108508,Mevr. J.E. van der Hoeven-Bannier,Pieter van Foreest - Die Buytenweye,2026-01-07,2026-01-07,JOP,Roxx New Original Newton,NTAC Zorgkantoor,Chopinlaan 9,Cornelis van der G,ROXXNEWTON.00010,ZKS02784,60,Wacht op A nummer,NaN,NaT,0.00
25371,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2600377,2025-12-24,ROBBY,5,ADVISEUR,2026-07-20,Wacht op bericht,PASSING,4461 LX,GOES,0,9,0,K0101144,Dhr. A. Molenaar,Cedrah - Woonzorgcentrum Rehoboth,2026-01-07,2026-01-07,NATHALIEH,Ibis Pro rolstoel,CZ/Administratie Zorgkantoor,Bergweg 1,Vincent K,IBIS.00010,55253501,60,Wacht op zorginfo,NaN,NaT,0.00
25372,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2601272,2025-12-19,JOP,5,ADVISEUR,2026-07-30,Wacht op bericht,PASSING,3363 WB,SLIEDRECHT,0,4,0,162145,Mevr. E.P. Verweij,ASVZ - De Merwebolder,2026-01-19,2026-01-19,JOP,Match duwonderstel,VGZ Zorgkantoor,Touwbaan 1,Tjerk P,MATCHD.00010,UVIT-24519,52,Wacht op zorginfo,NaN,NaT,0.00

In [54]:
df_combined = pd.concat([df_service, df_verkoop_2])
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38898 entries, 0 to 13524
Data columns (total 60 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Herstelstatuscodefilter       0 non-null      float64
 1   Toewijzingsdatumfilter        25373 non-null  object
 2   Responsdatumfilter            0 non-null      float64
 3   Resourcefilter                0 non-null      float64
 4   Resourcegroepfilter           0 non-null      float64
 5   Niet toegewezen               25373 non-null  float64
 6   Opmerking                     25373 non-null  float64
 7   Documentnr.                   38898 non-null  object
 8   Toewijzingsdatum              25373 non-null  datetime64[ns]
 9   Resourcenr.                   25369 non-null  object
 10  Herstelstatuscode             25373 non-null  float64
 11  Resourcegroepnr.              25314 non-null  object
 12  Responsdatum                  25365 non-null  datetime64[ns]
 13  Laaste opmerking              25351 non-null  object
 14  Serviceordersoort             25372 non-null  object
 15  Postcode                      38897 non-null  object
 16  Plaats                        38897 non-null  object
 17  Punten                        25373 non-null  float64
 18  Aantal serviceorders          25373 non-null  float64
 19  Aantal verkooporders          25373 non-null  float64
 20  Cliëntnr.                     25372 non-null  object
 21  Naam                          25372 non-null  object
 22  Zorginstellingnaam            38895 non-null  object
 23  Orderdatum                    25373 non-null  datetime64[ns]
 24  Datum laatste opmerking       19705 non-null  datetime64[ns]
 25  Verkoperscode                 25371 non-null  object
 26  Omschrijving                  25370 non-null  object
 27  Factuurnaam                   25373 non-null  object
 28  Adres                         38897 non-null  object
 29  Vaste monteur                 24926 non-null  object
 30  Artikelnr.                    25372 non-null  object
 31  Serienummer                   25363 non-null  object
 32  Dagen in verwerking           25373 non-null  float64
 33  Uw referentie                 13370 non-null  object
 34  Portaalopmerking              2 non-null      object
 35  Datum portaalopmerking        1 non-null      datetime64[ns]
 36  Totaalbedrag                  25373 non-null  float64
 37  Divisie                       13525 non-null  object
 38  Documentfilter                13525 non-null  object
 39  Uitgevoerd                    13525 non-null  object
 40  Planningdatum filter          13525 non-null  object
 41  Statuscode                    0 non-null      float64
 42  Soort filter                  13525 non-null  object
 43  Resource(groep)nr. filter     0 non-null      float64
 44  Uitbesteed                    13525 non-null  object
 45  Productie status              0 non-null      float64
 46  Plandatum                     13525 non-null  datetime64[ns]
 47  Contractdatum                 13525 non-null  datetime64[ns]
 48  Serienr.                      12302 non-null  object
 49  Originele samenstellingscode  13525 non-null  object
 50  Uitgevoerd1                   13525 non-null  float64
 51  Resource(groep)nr.            2140 non-null   object
 52  Note                          2440 non-null   object
 53  Statuscode1                   13525 non-null  object
 54  Gebruikers-id                 13525 non-null  object
 55  Klantnaam                     13525 non-null  object
 56  Laatste opmerkingsregel       12650 non-null  object
 57  Productie status1             13525 non-null  object
 58  Samenstellingscode            13525 non-null  object
 59  Verkoper                      13493 non-null  object
dtypes: datetime64[ns](7), float64(16), object(37)
memory usage: 18.1+ MB

In [62]:
df_combined['Adres'] = df_combined['Adres'].str.lower().str.strip()

In [63]:
df_combined

,Herstelstatuscodefilter,Toewijzingsdatumfilter,Responsdatumfilter,Resourcefilter,Resourcegroepfilter,Niet toegewezen,Opmerking,Documentnr.,Toewijzingsdatum,Resourcenr.,Herstelstatuscode,Resourcegroepnr.,Responsdatum,Laaste opmerking,Serviceordersoort,Postcode,Plaats,Punten,Aantal serviceorders,Aantal verkooporders,Cliëntnr.,Naam,Zorginstellingnaam,Orderdatum,Datum laatste opmerking,Verkoperscode,Omschrijving,Factuurnaam,Adres,Vaste monteur,Artikelnr.,Serienummer,Dagen in verwerking,Uw referentie,Portaalopmerking,Datum portaalopmerking,Totaalbedrag,Divisie,Documentfilter,Uitgevoerd,Planningdatum filter,Statuscode,Soort filter,Resource(groep)nr. filter,Uitbesteed,Productie status,Plandatum,Contractdatum,Serienr.,Originele samenstellingscode,Uitgevoerd1,Resource(groep)nr.,Note,Statuscode1,Gebruikers-id,Klantnaam,Laatste opmerkingsregel,Productie status1,Samenstellingscode,Verkoper
0,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0.0,1.0,SOR2322714,2025-02-18,OFFERTE,90.0,OFFERTE,2023-05-03,IV: Jop heeft Wouter gemaild om op te pakken 1...,REP,3232 LE,BRIELLE,12.0,5.0,0.0,K0011683,Mevr. B. van Toor,Careyn - De Plantage,2023-04-24,2025-02-13,JOP,Puma 40,CZ/Administratie Zorgkantoor,plantageweg 4,Peter B,PUMA40.00010,18ZKCZ0245,288.0,202512200812820,NaN,NaT,943.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0.0,1.0,SOR2339887,2025-11-27,JOP,99.0,ADVISEUR,2023-12-01,NH: lijst gemaakt voor Jop,REP,3363 WB,SLIEDRECHT,6.0,29.0,0.0,K0079751,Mevr. S. Mohar,ASVZ - De Merwebolder,2023-11-23,2025-02-14,JOP,MID Lectus,VGZ Zorgkantoor,touwbaan 1,Tjerk P,MIDLECTUS.00010,VGZ002411,80.0,Wacht op zorginfo,NaN,NaT,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0.0,1.0,SOR2341189,2025-01-20,OFFERTE,90.0,OFFERTE,2023-12-15,"ADV: vrijloophendel niet verkrijgbaar, nieuwe ...",REP,4301 NW,ZIERIKZEE,15.0,5.0,0.0,K0043840,Mevr. P. Verwest,Allevo - Zierik7,2023-12-08,NaT,ROBBY,Morgan Newton,CZ/Administratie Zorgkantoor,emil sandstromweg 2,Tom B,MORGANNEWTON.00010,55255110,262.0,202512200808613,NaN,NaT,2800.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0.0,1.0,SOR2341990,2025-01-28,JOP,99.0,ADVISEUR,2023-12-29,NH: lijst voor Jop gemaakt,REP,2643 JJ,PIJNACKER,24.0,11.0,0.0,510431,Mw. S. Bhawanie,Pieter van Foreest - Weidevogelhof,2023-12-19,2025-02-14,JOP,Puma 40,NTAC Zorgkantoor,raaigras 102,Cornelis van der G,PUMA40.00010,ZKS00464,286.0,Wacht op QQ-nummer,NaN,NaT,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0.0,1.0,SOR2400380,2025-01-06,OFFERTE,90.0,OFFERTE,2024-01-15,"Uitgevoerd, ondertekening goedgekeurd",REP,4382 LJ,VLISSINGEN,9.0,27.0,2.0,K0062065,Mevr. N. Langstraat,S Heeren Loo - Nieuwe Zuidbeekseweg,2024-01-08,2025-05-13,RUUD,QUICKIE ATTITUDE HYBRID 2,CZ/Administratie Zorgkantoor,stadhuisplein 22,Tom B,ATTITUDEH2.00010,5525FIE1241,231.0,202512200807424,NaN,NaT,1603.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VOR250062583,NaT,NaN,NaN,NaN,NaT,NaN,NaN,3265 BV,PIERSHIL,NaN,NaN,NaN,NaN,NaN,Verzorgingshuis Heemzicht,NaT,NaT,NaN,NaN,NaN,voorstraat 26,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-22,5526HR0562,8D,1.0,NaN,NaN,P135,AD\MARCEL.STROO,Mevr. H. Koesveld-Prins,Aangepast formulier in de bijlagen gedaan.,Nog te ondertekenen,8D,NATHALIEH
13521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VOR250063316,NaT,NaN,NaN,NaN,NaT,NaN,NaN,3055 JD,ROTTERDAM,NaN,NaN,NaN,NaN,NaN,WelThuis - de State Hillegersberg,NaT,NaT,NaN,NaN,NaN,beethovenlaan 60,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2026-01-02,ACH0127404,8D,1.0,NaN,NaN,P135,AD\MARCEL.STROO,Mevr. E.J. Boot-Tolk,Verwacht: week 2,Nog te ondertekenen,8D,MEREL
13522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VOR250058380,NaT,NaN,NaN,NaN,NaT,NaN,NaN,4571 HT,AXEL,NaN,NaN,NaN,NaN,NaN,SVRZ - de Vurssche,NaT,NaT,NaN,NaN,NaN,rooseveltlaan 1,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-15,55256260,10D,1.0,NaN,NaN,P136,AD\K2-SVC-SOAPWEB-PROD,Mevr. E.E.M. Koorevaar-van de Putte,Gewijzigd: Week 1 ivm herbevestiging fabrikant,Ondertekening afgekeurd,10D,ROBBY
13523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VOR250058380,NaT,NaN,NaN,NaN,NaT,NaN,NaN,4571 HT,AXEL,NaN,NaN,NaN,NaN,NaN,SVRZ - de Vurssche,NaT,NaT,NaN,NaN,NaN,rooseveltlaan 1,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2025-12-15,55256260,10D,1.0,NaN,NaN,P137,AD\K2-SVC-SOAPWEB-PROD,Mevr. E.E.M. Koorevaar-van de Putte,Gewijzigd: Week 1 ivm herbevestiging fabrikant,Ondertekening afgekeurd,10D,ROBBY
13524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VOR250063955,NaT,NaN,NaN,NaN,NaT,NaN,NaN,3136 EA,VLAARDINGEN,NaN,NaN,NaN,NaN,NaN,Zonnehuisgroep Vlaardingen - Cred. adm.,NaT,NaT,NaN,NaN,NaN,dillenburgsingel 5,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,2 DORDRECH,Alle,Ja,01-01-25..31-12-25,NaN,Resource,NaN,No,NaN,2025-12-31,2026-01-02,NaN,RETOUR,1.0,NaN,NaN,P150,AD\NANDA.VAN.SINTMAARTE,Zonnehuis groep - Zonnehuis,NaN,Middel opgehaald,RETOUR,JOP

In [64]:
df01

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,postcode,plaats,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,latitude,longitude,adres,match
0,967 (VDG-43-S),10-03-2025,07:52,08:29,09:52,"36,00",00:37,1:22,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,dordrecht,0.0,0:00,1:59,0:37,1:22,0:00,"36,00",51.780566,4.638908,kamerlingh onnesweg 9,False
1,967 (VDG-43-S),10-03-2025,09:52,10:31,10:35,"29,70",00:39,0:04,"Rijksweg A20 2, Nieuwerkerk Ad Ijssel",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Rijksweg A20 2,2913 LW,nieuwerkerk ad ijssel,NaN,0:00,2:43,1:16,1:26,0:00,"65,70",51.966202,4.588517,rijksweg a20 2,False
2,967 (VDG-43-S),10-03-2025,10:35,10:50,12:08,"13,70",00:14,1:17,"Ronsseweg 485, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Ronsseweg 485,2803 ZG,gouda,NaN,0:00,4:15,1:31,2:44,0:00,"79,40",52.018854,4.705738,ronsseweg 485,False
3,967 (VDG-43-S),10-03-2025,12:08,12:14,13:40,"0,80",00:06,1:25,"Savelberghof 43, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Savelberghof 43,2805 RT,gouda,NaN,0:00,5:48,1:38,4:09,0:00,"80,20",52.020777,4.713963,savelberghof 43,False
4,967 (VDG-43-S),10-03-2025,13:40,14:07,14:32,"13,50",00:27,0:25,"Poorthuisstraat 59, Bergambacht",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Poorthuisstraat 59,2861 DV,bergambacht,NaN,0:00,6:40,2:05,4:35,0:00,"93,70",51.929160,4.784648,poorthuisstraat 59,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5770,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055 JD,rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793,van beethovenlaan 56,False
5771,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906 BC,capelle aan den ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842,dotterlei 143,False
5772,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317 SP,dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400,groen van prinstererweg 38,False
5773,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328 HN,dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293,minnaertweg 4,False
5774,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417,kamerlingh onnesweg 9,False

In [65]:
df01['match'] = df01['adres'].isin(df_combined['Adres'])
df01

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,postcode,plaats,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,latitude,longitude,adres,match
0,967 (VDG-43-S),10-03-2025,07:52,08:29,09:52,"36,00",00:37,1:22,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,dordrecht,0.0,0:00,1:59,0:37,1:22,0:00,"36,00",51.780566,4.638908,kamerlingh onnesweg 9,False
1,967 (VDG-43-S),10-03-2025,09:52,10:31,10:35,"29,70",00:39,0:04,"Rijksweg A20 2, Nieuwerkerk Ad Ijssel",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Rijksweg A20 2,2913 LW,nieuwerkerk ad ijssel,NaN,0:00,2:43,1:16,1:26,0:00,"65,70",51.966202,4.588517,rijksweg a20 2,False
2,967 (VDG-43-S),10-03-2025,10:35,10:50,12:08,"13,70",00:14,1:17,"Ronsseweg 485, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Ronsseweg 485,2803 ZG,gouda,NaN,0:00,4:15,1:31,2:44,0:00,"79,40",52.018854,4.705738,ronsseweg 485,False
3,967 (VDG-43-S),10-03-2025,12:08,12:14,13:40,"0,80",00:06,1:25,"Savelberghof 43, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Savelberghof 43,2805 RT,gouda,NaN,0:00,5:48,1:38,4:09,0:00,"80,20",52.020777,4.713963,savelberghof 43,False
4,967 (VDG-43-S),10-03-2025,13:40,14:07,14:32,"13,50",00:27,0:25,"Poorthuisstraat 59, Bergambacht",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Poorthuisstraat 59,2861 DV,bergambacht,NaN,0:00,6:40,2:05,4:35,0:00,"93,70",51.929160,4.784648,poorthuisstraat 59,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5770,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055 JD,rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793,van beethovenlaan 56,False
5771,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906 BC,capelle aan den ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842,dotterlei 143,False
5772,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317 SP,dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400,groen van prinstererweg 38,True
5773,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328 HN,dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293,minnaertweg 4,True
5774,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417,kamerlingh onnesweg 9,False

In [66]:
result = df01.groupby(['SerialNumber', 'Date']).agg(
    totaal_adressen=('VisitingAddress', 'count'),
    aantal_matches=('match', 'sum')
).reset_index()

In [67]:
result

        SerialNumber        Date  totaal_adressen  aantal_matches
0    1001 (VFK-90-R)  03-04-2025                2               0
1    1001 (VFK-90-R)  03-12-2025               10               0
2    1001 (VFK-90-R)  04-06-2025               12               2
3    1001 (VFK-90-R)  06-02-2025                6               0
4    1001 (VFK-90-R)  09-01-2025                4               1
..               ...         ...              ...             ...
612   967 (VDG-43-S)  10-03-2025                7               0
613   967 (VDG-43-S)  14-11-2025                2               0
614   967 (VDG-43-S)  17-07-2025                6               0
615   967 (VDG-43-S)  21-11-2025                1               0
616   967 (VDG-43-S)  23-12-2025                2               0

[617 rows x 4 columns]

In [68]:
result['match_percentage'] = result['aantal_matches'] / result['totaal_adressen']

In [69]:
result[result['match_percentage'] > 0.5]

,SerialNumber,Date,totaal_adressen,aantal_matches,match_percentage
176,1185 (VJL-22-K),10-07-2025,7,4,0.571429
531,1702 (V-19-FXR),31-10-2025,11,6,0.545455
542,1705 (V-18-FXR),13-06-2025,16,9,0.562500
580,1775 (V-11-GGL),01-10-2025,15,8,0.533333