In [ ]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv(
    'data/Bezoeken per voertuig 01-01-2025 - 31-12-2025.Csv',
    sep=';',
    encoding='utf-16',
    skiprows=1
)

C:\Users\aniek.kasius\AppData\Local\Temp\ipykernel_22376\1523193955.py:1: DtypeWarning: Columns (0: Contact) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [4]:
df

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,967 (VDG-43-S),02-01-2025,06:48,07:17,10:27,"35,90",00:28,3:10,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,3:39,0:28,3:10,0:00,"35,90",51.905395,4.332835
1,967 (VDG-43-S),02-01-2025,10:27,10:39,10:43,"5,10",00:11,0:03,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,3:54,0:40,3:14,0:00,"41,00",51.905395,4.332835
2,967 (VDG-43-S),02-01-2025,10:43,11:36,12:17,"61,00",00:53,0:41,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,5:29,1:33,3:55,0:00,"102,00",51.905395,4.332835
3,967 (VDG-43-S),02-01-2025,12:17,12:58,14:51,"27,30",00:40,1:52,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,8:02,2:14,5:47,0:00,"129,30",51.905395,4.332835
4,967 (VDG-43-S),02-01-2025,14:51,15:06,06:55,"3,70",00:15,15:49,"Produktiestraat 2, Vlaardingen",NaN,NaN,BBT Dordrecht/MHG,NaN,NaN,Produktiestraat 2,3133ES,Vlaardingen,NaN,0:00,8:17,2:29,5:47,8:17,"133,00",51.905395,4.332835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59128,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
59129,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
59130,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400
59131,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293
59132,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417

In [5]:
# bekijken welke auto's elke dag naar het depot gaan
depot_naam = "Kamerlingh Onnesweg 9, Dordrecht"

In [6]:
# als de dataframe al in de juiste volgorde staat:
# per Date en SerialNumber de eerste en laatste rij pakken

eerste_stop = (
    df.groupby(["Date", "SerialNumber"], sort=False)
      .first()
      .reset_index()[["Date", "SerialNumber", "VisitingAddress"]]
      .rename(columns={"VisitingAddress": "eerste_stop"})
)

laatste_stop = (
    df.groupby(["Date", "SerialNumber"], sort=False)
      .last()
      .reset_index()[["Date", "SerialNumber", "VisitingAddress"]]
      .rename(columns={"VisitingAddress": "laatste_stop"})
)

# samenvoegen
start_eind_check = eerste_stop.merge(
    laatste_stop,
    on=["Date", "SerialNumber"],
    how="inner"
)

# alleen groepen die starten én eindigen bij depot
groepen_depot_start_eind = start_eind_check[
    (start_eind_check["eerste_stop"] == depot_naam) &
    (start_eind_check["laatste_stop"] == depot_naam)
][["Date", "SerialNumber"]]

# originele dataset filteren op die groepen
df01 = df.merge(
    groepen_depot_start_eind,
    on=["Date", "SerialNumber"],
    how="inner"
)

df01

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,967 (VDG-43-S),14-10-2025,07:50,08:20,09:41,"35,70",00:29,1:20,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:50,0:29,1:20,0:00,"35,70",51.780592,4.638408
1,967 (VDG-43-S),14-10-2025,09:41,09:42,10:08,"0,10",00:01,0:26,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,2:17,0:30,1:46,0:00,"35,80",51.780628,4.639095
2,967 (VDG-43-S),14-10-2025,10:08,10:47,11:21,"43,10",00:38,0:33,"Ronsseweg 410, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Ronsseweg 410,2803ZX,Gouda,NaN,0:00,3:30,1:09,2:20,0:00,"78,90",52.018870,4.705445
3,967 (VDG-43-S),14-10-2025,11:21,11:30,11:54,"1,60",00:09,0:24,"Van De Puttestraat 119, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Van De Puttestraat 119,2804JL,Gouda,NaN,0:00,4:03,1:18,2:45,0:00,"80,50",52.027592,4.708583
4,967 (VDG-43-S),14-10-2025,11:54,12:06,13:26,"3,00",00:11,1:19,"De Lange Van Wijngaardenstraat 5, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,De Lange Van Wijngaardenstraat 5,2806WN,Gouda,NaN,0:00,5:35,1:29,4:05,0:00,"83,50",52.013176,4.718882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
2742,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
2743,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400
2744,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293
2745,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417

In [7]:
depot_adres = "Kamerlingh Onnesweg 9, Dordrecht"

In [8]:
depot_lat = 51.780566
depot_long = 4.638908

In [9]:
df01.loc[df01['VisitingAddress'] == depot_adres, 'Lat'] = depot_lat
df01.loc[df01['VisitingAddress'] == depot_adres, 'Long'] = depot_long

In [10]:
# missende waarden zipcode toevoegen
df01[df01['ZipCode'].isna()]

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
744,1313 (VPS-11-J),18-02-2025,07:26,07:26,08:09,"0,00",00:00,0:42,", ?",NaN,Robin Kovács,BBT Dordrecht/MHG,NaN,NaN,NaN,NaN,?,NaN,0:00,1:31,0:39,0:51,0:00,"34,50",0.000000,0.000000
2208,1705 (V-18-FXR),14-08-2025,10:29,11:01,11:01,"30,74",00:32,0:00,De Val,NaN,Marcus Dekker,BBT Dordrecht/MHG,NaN,NaN,NaN,NaN,De Val,NaN,0:00,4:15,2:19,1:56,0:00,"158,79",51.622348,3.904958
2223,1705 (V-18-FXR),15-08-2025,10:20,10:58,11:07,"30,84",00:38,0:08,"Straalweg 10, Zierikzee",NaN,Marcus Dekker,BBT Dordrecht/MHG,NaN,NaN,Straalweg 10,NaN,Zierikzee,NaN,0:00,4:39,2:24,2:15,0:00,"126,98",51.628897,3.913879
2444,1775 (V-11-GGL),06-03-2025,11:19,11:20,11:36,"0,17",00:01,0:16,"Amphia Ziekenhuis Molengracht 1, Breda",NaN,Frido Wijnen,BBT Dordrecht/MHG,NaN,NaN,Amphia Ziekenhuis Molengracht 1,NaN,Breda,NaN,0:00,4:09,2:00,2:09,0:00,"137,36",51.582783,4.798137
2457,1775 (V-11-GGL),26-03-2025,11:04,11:05,12:21,"0,18",00:00,1:16,"Amphia Ziekenhuis Molengracht 1, Breda",NaN,Geertjan van der Wulp,BBT Dordrecht/MHG,NaN,NaN,Amphia Ziekenhuis Molengracht 1,NaN,Breda,NaN,0:00,4:33,1:15,3:17,0:00,"45,42",51.582735,4.798040

In [11]:
df01.loc[[2444, 2457], "ZipCode"] = "4818 CK"
df01.loc[[2223], "ZipCode"] = "4301 RJ"

In [12]:
# van het ene voertuig en die dag er geheel uithalen, want niets bekend over die coordinaten
df01 = df01[
    ~(
        (df01["Date"] == "18-02-2025") &
        (df01["SerialNumber"] == '1313 (VPS-11-J)')
    )
]

df01

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,967 (VDG-43-S),14-10-2025,07:50,08:20,09:41,"35,70",00:29,1:20,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:50,0:29,1:20,0:00,"35,70",51.780566,4.638908
1,967 (VDG-43-S),14-10-2025,09:41,09:42,10:08,"0,10",00:01,0:26,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,2:17,0:30,1:46,0:00,"35,80",51.780566,4.638908
2,967 (VDG-43-S),14-10-2025,10:08,10:47,11:21,"43,10",00:38,0:33,"Ronsseweg 410, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Ronsseweg 410,2803ZX,Gouda,NaN,0:00,3:30,1:09,2:20,0:00,"78,90",52.018870,4.705445
3,967 (VDG-43-S),14-10-2025,11:21,11:30,11:54,"1,60",00:09,0:24,"Van De Puttestraat 119, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Van De Puttestraat 119,2804JL,Gouda,NaN,0:00,4:03,1:18,2:45,0:00,"80,50",52.027592,4.708583
4,967 (VDG-43-S),14-10-2025,11:54,12:06,13:26,"3,00",00:11,1:19,"De Lange Van Wijngaardenstraat 5, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,De Lange Van Wijngaardenstraat 5,2806WN,Gouda,NaN,0:00,5:35,1:29,4:05,0:00,"83,50",52.013176,4.718882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
2742,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
2743,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400
2744,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293
2745,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780566,4.638908

In [13]:
# van het ene voertuig en die dag er geheel uithalen, want niets bekend over die coordinaten
df01 = df01[
    ~(
        (df01["Date"] == "14-08-2025") &
        (df01["SerialNumber"] == '1705 (V-18-FXR)')
    )
]

df01

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,Contact,Remark,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,967 (VDG-43-S),14-10-2025,07:50,08:20,09:41,"35,70",00:29,1:20,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,1:50,0:29,1:20,0:00,"35,70",51.780566,4.638908
1,967 (VDG-43-S),14-10-2025,09:41,09:42,10:08,"0,10",00:01,0:26,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,2:17,0:30,1:46,0:00,"35,80",51.780566,4.638908
2,967 (VDG-43-S),14-10-2025,10:08,10:47,11:21,"43,10",00:38,0:33,"Ronsseweg 410, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Ronsseweg 410,2803ZX,Gouda,NaN,0:00,3:30,1:09,2:20,0:00,"78,90",52.018870,4.705445
3,967 (VDG-43-S),14-10-2025,11:21,11:30,11:54,"1,60",00:09,0:24,"Van De Puttestraat 119, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,Van De Puttestraat 119,2804JL,Gouda,NaN,0:00,4:03,1:18,2:45,0:00,"80,50",52.027592,4.708583
4,967 (VDG-43-S),14-10-2025,11:54,12:06,13:26,"3,00",00:11,1:19,"De Lange Van Wijngaardenstraat 5, Gouda",NaN,Laurens-Jan Burkx,BBT Dordrecht/MHG,NaN,NaN,De Lange Van Wijngaardenstraat 5,2806WN,Gouda,NaN,0:00,5:35,1:29,4:05,0:00,"83,50",52.013176,4.718882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Van Beethovenlaan 56,3055JD,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
2742,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Dotterlei 143,2906BC,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
2743,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Groen Van Prinstererweg 38,3317SP,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400
2744,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Minnaertweg 4,3328HN,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293
2745,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,Patrick Baas,BBT Dordrecht/MHG,NaN,NaN,Kamerlingh Onnesweg 9,3316 GK,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780566,4.638908

In [14]:
df01['Date'].unique()

<StringArray>
['14-10-2025', '23-10-2025', '07-11-2025', '14-11-2025', '21-11-2025',
 '23-12-2025', '25-04-2025', '08-08-2025', '19-08-2025', '20-10-2025',
 ...
 '10-01-2025', '19-02-2025', '05-03-2025', '01-04-2025', '22-05-2025',
 '30-06-2025', '15-07-2025', '11-08-2025', '13-10-2025', '10-11-2025']
Length: 163, dtype: str

In [15]:
result = df01.groupby('Date')['SerialNumber'].nunique()

In [16]:
max_datum = result.idxmax()
max_aantal = result.max()

print("Datum met meeste aantal voertuigen:", max_datum)
print("Aantal unieke voertuigen:", max_aantal)

Datum met meeste aantal voertuigen: 03-01-2025
Aantal unieke voertuigen: 4

In [17]:
import pandas as pd
import numpy as np
from math import sin, cos, atan2, sqrt, radians
from ortools.constraint_solver import pywrapcp, routing_enums_pb2

In [33]:
# Kies de dag waarvoor je het VRP wilt draaien
gekozen_datum = '2025-01-03'

# Zorg dat Date datetime is
df01['Date'] = pd.to_datetime(df01['Date'], dayfirst=True)

# Filter op 1 dag
df_dag = df01[df01['Date'].dt.strftime('%Y-%m-%d') == gekozen_datum].copy()


# Depot als eerste node toevoegen
depot_df = pd.DataFrame({
    'VisitingAddress': [depot_adres],
    'Lat': [depot_lat],
    'Long': [depot_long]
})

# unieke adressen
locations = df_dag[['VisitingAddress', 'Lat', 'Long']].drop_duplicates().reset_index(drop=True)

# node_id toevoegen
locations['node_id'] = locations.index

orders = df_dag[['Date', 'VisitingAddress']].copy()

# koppel node_id
orders = orders.merge(locations, on='VisitingAddress', how='left')

In [34]:
locations

                              VisitingAddress        Lat      Long  node_id
0            Kamerlingh Onnesweg 9, Dordrecht  51.780566  4.638908        0
1                      Touwbaan 4, Sliedrecht  51.826952  4.749070        1
2                   Kerkbuurt 220, Sliedrecht  51.823185  4.768565        2
3                   Kerkbuurt 143, Sliedrecht  51.823212  4.770912        3
4   Jupiterstraat 257, Hardinxveld-Giessendam  51.823860  4.822770        4
5                      Banneweg 57, Gorinchem  51.838402  4.956703        5
6                   Oosterhagen 17, Rotterdam  51.888896  4.559616        6
7             Boergoensestraat 128, Rotterdam  51.891157  4.469975        7
8               Maashaven O.Z. 103, Rotterdam  51.901225  4.496593        8
9                   Motorstraat 96, Rotterdam  51.887381  4.495082        9
10            Haastrechtstraat 130, Rotterdam  51.879893  4.536429       10
11                  Pietersdijk 60, Rotterdam  51.876447  4.553634       11
12                  Oosterhagen 17, Rotterdam  51.888769  4.559626       12
13                     Reling 19, Barendrecht  51.849359  4.499366       13
14                       De Poort 24, Rilland  51.422343  4.191176       14
15                     Vliete 1, Krabbendijke  51.422770  4.096706       15
16                      Rooseveltlaan 1, Axel  51.264724  3.901339       16
17                   Molenstraat 95, Zaamslag  51.309141  3.907935       17
18                 Pattistpark 137, Terneuzen  51.334522  3.856521       18
19                     Bachlaan 88, Terneuzen  51.319076  3.846755       19
20                   Agaat 2 -12 , Middelburg  51.492988  3.618438       20
21                Noordbolwerk 33, Middelburg  51.504080  3.611004       21
22       Latijnse Schoolstraat 19, Middelburg  51.499643  3.612741       22
23                 Plantageweg 3, Zwijndrecht  51.815552  4.630477       23
24                 Bankastraat 158, Dordrecht  51.807987  4.686260       24
25       Albert Schweitzerplaats 1, Dordrecht  51.792806  4.682664       25
26                   Minnaertweg 4, Dordrecht  51.783445  4.686297       26
27      Groen Van Prinstererweg 38, Dordrecht  51.791081  4.666262       27

In [35]:
# afstandsmatrix op basis van GPS-coördinaten

def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # km
    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)

    a = sin(dlat / 2)**2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    return R * c

n = len(locations)
distance_matrix = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        distance_matrix[i, j] = haversine(
            locations.loc[i, 'Lat'],
            locations.loc[i, 'Long'],
            locations.loc[j, 'Lat'],
            locations.loc[j, 'Long']
        )

# OR-Tools werkt liever met integers
distance_matrix = (distance_matrix * 1000).astype(int)  # meters

In [36]:
num_vehicles = df_dag['SerialNumber'].nunique()

## MODEL 1

In [37]:
import time
import pandas as pd
from ortools.constraint_solver import pywrapcp, routing_enums_pb2

In [46]:
TIME_LIMIT_SECONDS = 30

first_solution_strategies = {
    "PATH_CHEAPEST_ARC": routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC,
    "PATH_MOST_CONSTRAINED_ARC": routing_enums_pb2.FirstSolutionStrategy.PATH_MOST_CONSTRAINED_ARC,
    "EVALUATOR_STRATEGY": routing_enums_pb2.FirstSolutionStrategy.EVALUATOR_STRATEGY,
    "SAVINGS": routing_enums_pb2.FirstSolutionStrategy.SAVINGS,
    "SWEEP": routing_enums_pb2.FirstSolutionStrategy.SWEEP,
    "CHRISTOFIDES": routing_enums_pb2.FirstSolutionStrategy.CHRISTOFIDES,
    "ALL_UNPERFORMED": routing_enums_pb2.FirstSolutionStrategy.ALL_UNPERFORMED,
    "BEST_INSERTION": routing_enums_pb2.FirstSolutionStrategy.BEST_INSERTION,
    "PARALLEL_CHEAPEST_INSERTION": routing_enums_pb2.FirstSolutionStrategy.PARALLEL_CHEAPEST_INSERTION,
    "LOCAL_CHEAPEST_INSERTION": routing_enums_pb2.FirstSolutionStrategy.LOCAL_CHEAPEST_INSERTION,
    "GLOBAL_CHEAPEST_ARC": routing_enums_pb2.FirstSolutionStrategy.GLOBAL_CHEAPEST_ARC,
    "LOCAL_CHEAPEST_ARC": routing_enums_pb2.FirstSolutionStrategy.LOCAL_CHEAPEST_ARC,
    "FIRST_UNBOUND_MIN_VALUE": routing_enums_pb2.FirstSolutionStrategy.FIRST_UNBOUND_MIN_VALUE,
}

local_search_metaheuristics = {
    "GREEDY_DESCENT": routing_enums_pb2.LocalSearchMetaheuristic.GREEDY_DESCENT,
    "GUIDED_LOCAL_SEARCH": routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH,
    "SIMULATED_ANNEALING": routing_enums_pb2.LocalSearchMetaheuristic.SIMULATED_ANNEALING,
    "TABU_SEARCH": routing_enums_pb2.LocalSearchMetaheuristic.TABU_SEARCH,
    "GENERIC_TABU_SEARCH": routing_enums_pb2.LocalSearchMetaheuristic.GENERIC_TABU_SEARCH,
}

In [47]:
# FUNCTIE: MODEL OPBOUWEN
def build_routing_model(distance_matrix, num_vehicles, depot=0):
    """
    Bouwt steeds een vers RoutingIndexManager + RoutingModel.
    """
    manager = pywrapcp.RoutingIndexManager(
        len(distance_matrix),
        num_vehicles,
        [depot] * num_vehicles,   # start depot per voertuig
        [depot] * num_vehicles    # eind depot per voertuig
    )

    routing = pywrapcp.RoutingModel(manager)

    def distance_callback(from_index, to_index):
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return int(distance_matrix[from_node][to_node])

    transit_callback_index = routing.RegisterTransitCallback(distance_callback)
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

    return manager, routing

In [48]:
# FUNCTIE: TOTALE AFSTAND BEREKENEN
def calculate_total_distance(solution, routing, num_vehicles):
    total_distance = 0

    for vehicle_id in range(num_vehicles):
        index = routing.Start(vehicle_id)
        while not routing.IsEnd(index):
            next_index = solution.Value(routing.NextVar(index))
            total_distance += routing.GetArcCostForVehicle(index, next_index, vehicle_id)
            index = next_index

    return total_distance

In [49]:
# FUNCTIE: RESULTATEN UIT ROUTES HALEN
def extract_routes(solution, manager, routing, num_vehicles, locations):
    totaal_afstand = 0
    routes_output = []

    for vehicle_id in range(num_vehicles):
        index = routing.Start(vehicle_id)
        route_nodes = []
        route_adressen = []
        route_distance = 0

        while not routing.IsEnd(index):
            node = manager.IndexToNode(index)
            route_nodes.append(node)
            route_adressen.append(locations.loc[node, 'VisitingAddress'])

            previous_index = index
            index = solution.Value(routing.NextVar(index))
            route_distance += routing.GetArcCostForVehicle(previous_index, index, vehicle_id)

        # einddepot toevoegen
        end_node = manager.IndexToNode(index)
        route_nodes.append(end_node)
        route_adressen.append(locations.loc[end_node, 'VisitingAddress'])

        totaal_afstand += route_distance

        routes_output.append({
            'vehicle_id': vehicle_id,
            'route_nodes': route_nodes,
            'route_adressen': route_adressen,
            'afstand_meters': route_distance,
            'afstand_km': round(route_distance / 1000, 2)
        })

    return totaal_afstand, routes_output

In [50]:
# FUNCTIE: ALLE COMBINATIES TESTEN
def compare_strategies(distance_matrix, num_vehicles,
                       first_solution_strategies,
                       local_search_metaheuristics,
                       time_limit_seconds=30):
    results = []

    for fs_name, fs_value in first_solution_strategies.items():
        for ls_name, ls_value in local_search_metaheuristics.items():

            # Altijd een vers model bouwen
            manager, routing = build_routing_model(distance_matrix, num_vehicles, depot=0)

            search_parameters = pywrapcp.DefaultRoutingSearchParameters()
            search_parameters.first_solution_strategy = fs_value
            search_parameters.local_search_metaheuristic = ls_value
            search_parameters.time_limit.seconds = time_limit_seconds

            start = time.time()
            solution = routing.SolveWithParameters(search_parameters)
            runtime = time.time() - start

            if solution:
                total_distance = calculate_total_distance(solution, routing, num_vehicles)

                results.append({
                    "first_solution_strategy": fs_name,
                    "local_search_metaheuristic": ls_name,
                    "solution_found": True,
                    "total_distance": total_distance,
                    "runtime_sec": round(runtime, 2),
                })
            else:
                results.append({
                    "first_solution_strategy": fs_name,
                    "local_search_metaheuristic": ls_name,
                    "solution_found": False,
                    "total_distance": None,
                    "runtime_sec": round(runtime, 2),
                })

    df_results = pd.DataFrame(results)

    # Sorteer: eerst oplossingen, dan laagste afstand, dan snelste runtime
    df_results = df_results.sort_values(
        by=["solution_found", "total_distance", "runtime_sec"],
        ascending=[False, True, True]
    ).reset_index(drop=True)

    return df_results

In [51]:
# FUNCTIE: BESTE PARAMETERS KIEZEN
def get_best_parameters(df_results, allow_zero_distance=False):
    """
    Kiest de beste combinatie uit de resultaten.
    Standaard worden verdachte oplossingen met total_distance <= 0 niet gekozen.
    """

    df_valid = df_results[df_results["solution_found"] == True].copy()

    # Verwijder lege waarden
    df_valid = df_valid[df_valid["total_distance"].notna()]

    # Filter verdachte 0-afstand oplossingen eruit
    if not allow_zero_distance:
        df_valid = df_valid[df_valid["total_distance"] > 0]

    if df_valid.empty:
        raise ValueError(
            "Geen geldige oplossing gevonden. "
            "Controleer je distance_matrix, aantal voertuigen en modelinstellingen."
        )

    best_row = df_valid.sort_values(
        by=["total_distance", "runtime_sec"],
        ascending=[True, True]
    ).iloc[0]

    return best_row["first_solution_strategy"], best_row["local_search_metaheuristic"]

In [52]:
print(locations.shape)
print(locations.head())

(28, 4)
                             VisitingAddress        Lat      Long  node_id
0           Kamerlingh Onnesweg 9, Dordrecht  51.780566  4.638908        0
1                     Touwbaan 4, Sliedrecht  51.826952  4.749070        1
2                  Kerkbuurt 220, Sliedrecht  51.823185  4.768565        2
3                  Kerkbuurt 143, Sliedrecht  51.823212  4.770912        3
4  Jupiterstraat 257, Hardinxveld-Giessendam  51.823860  4.822770        4

In [53]:
# ALLE COMBINATIES VERGELIJKEN
# =========================================================
df_results = compare_strategies(
    distance_matrix=distance_matrix,
    num_vehicles=num_vehicles,
    first_solution_strategies=first_solution_strategies,
    local_search_metaheuristics=local_search_metaheuristics,
    time_limit_seconds=TIME_LIMIT_SECONDS
)

print("Top 10 beste combinaties:")
print(df_results.head(10))

Top 10 beste combinaties:
     first_solution_strategy local_search_metaheuristic  solution_found  \
0   LOCAL_CHEAPEST_INSERTION             GREEDY_DESCENT            True
1          PATH_CHEAPEST_ARC             GREEDY_DESCENT            True
2  PATH_MOST_CONSTRAINED_ARC             GREEDY_DESCENT            True
3                    SAVINGS             GREEDY_DESCENT            True
4               CHRISTOFIDES             GREEDY_DESCENT            True
5    FIRST_UNBOUND_MIN_VALUE             GREEDY_DESCENT            True
6                    SAVINGS                TABU_SEARCH            True
7          PATH_CHEAPEST_ARC                TABU_SEARCH            True
8  PATH_MOST_CONSTRAINED_ARC                TABU_SEARCH            True
9   LOCAL_CHEAPEST_INSERTION                TABU_SEARCH            True

   total_distance  runtime_sec
0        257720.0         0.01
1        257720.0         0.02
2        257720.0         0.03
3        257720.0         0.03
4        257720.0         0.03
5        257720.0         0.08
6        257720.0         2.51
7        257720.0         7.48
8        257720.0         7.78
9        257720.0        18.25

In [54]:
# BESTE COMBINATIE KIEZEN
# =========================================================
best_fs, best_ls = get_best_parameters(df_results, allow_zero_distance=False)

print("\nBeste combinatie voor Model 1:")
print(f"FirstSolutionStrategy: {best_fs}")
print(f"LocalSearchMetaheuristic: {best_ls}")

Beste combinatie voor Model 1:
FirstSolutionStrategy: LOCAL_CHEAPEST_INSERTION
LocalSearchMetaheuristic: GREEDY_DESCENT

In [55]:
# MODEL 1 BOUWEN MET BESTE COMBINATIE
manager, routing = build_routing_model(distance_matrix, num_vehicles, depot=0)

search_parameters = pywrapcp.DefaultRoutingSearchParameters()
search_parameters.first_solution_strategy = getattr(
    routing_enums_pb2.FirstSolutionStrategy, best_fs
)
search_parameters.local_search_metaheuristic = getattr(
    routing_enums_pb2.LocalSearchMetaheuristic, best_ls
)
search_parameters.time_limit.seconds = TIME_LIMIT_SECONDS

print(f"\nModel 1 gebruikt nu:")
print(f"FirstSolutionStrategy: {best_fs}")
print(f"LocalSearchMetaheuristic: {best_ls}")

solution = routing.SolveWithParameters(search_parameters)

Model 1 gebruikt nu:
FirstSolutionStrategy: LOCAL_CHEAPEST_INSERTION
LocalSearchMetaheuristic: GREEDY_DESCENT

In [56]:
# ROUTES UITPRINTEN
if solution:
    totaal_afstand, routes_output = extract_routes(
        solution=solution,
        manager=manager,
        routing=routing,
        num_vehicles=num_vehicles,
        locations=locations
    )

    print(f"\nTotaal aantal voertuigen: {num_vehicles}")
    print(f"Totaal aantal locaties incl. depot: {len(locations)}")
    print(f"Totale afstand: {round(totaal_afstand / 1000, 2)} km\n")

    for route in routes_output:
        print(f"Bus {route['vehicle_id']}:")
        print(" -> ".join(route['route_adressen']))
        print(f"Afstand: {route['afstand_km']} km")
        print("-" * 60)

else:
    print("Geen oplossing gevonden voor Model 1.")

Totaal aantal voertuigen: 4
Totaal aantal locaties incl. depot: 28
Totale afstand: 257.72 km

Bus 0:
Kamerlingh Onnesweg 9, Dordrecht -> Groen Van Prinstererweg 38, Dordrecht -> Albert Schweitzerplaats 1, Dordrecht -> Minnaertweg 4, Dordrecht -> Banneweg 57, Gorinchem -> Jupiterstraat 257, Hardinxveld-Giessendam -> Kerkbuurt 143, Sliedrecht -> Kerkbuurt 220, Sliedrecht -> Touwbaan 4, Sliedrecht -> Bankastraat 158, Dordrecht -> Plantageweg 3, Zwijndrecht -> Pietersdijk 60, Rotterdam -> Oosterhagen 17, Rotterdam -> Oosterhagen 17, Rotterdam -> Haastrechtstraat 130, Rotterdam -> Motorstraat 96, Rotterdam -> Maashaven O.Z. 103, Rotterdam -> Boergoensestraat 128, Rotterdam -> Reling 19, Barendrecht -> Noordbolwerk 33, Middelburg -> Latijnse Schoolstraat 19, Middelburg -> Agaat 2 -12 , Middelburg -> Pattistpark 137, Terneuzen -> Bachlaan 88, Terneuzen -> Rooseveltlaan 1, Axel -> Molenstraat 95, Zaamslag -> Vliete 1, Krabbendijke -> De Poort 24, Rilland -> Kamerlingh Onnesweg 9, Dordrecht
Afstand: 257.72 km
------------------------------------------------------------
Bus 1:
Kamerlingh Onnesweg 9, Dordrecht -> Kamerlingh Onnesweg 9, Dordrecht
Afstand: 0.0 km
------------------------------------------------------------
Bus 2:
Kamerlingh Onnesweg 9, Dordrecht -> Kamerlingh Onnesweg 9, Dordrecht
Afstand: 0.0 km
------------------------------------------------------------
Bus 3:
Kamerlingh Onnesweg 9, Dordrecht -> Kamerlingh Onnesweg 9, Dordrecht
Afstand: 0.0 km
------------------------------------------------------------

## MODEL 2

In [57]:
TIME_LIMIT_SECONDS = 30
MAX_ADRESSEN_PER_BUS = 15

first_solution_strategies = {
    "PATH_CHEAPEST_ARC": routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC,
    "PATH_MOST_CONSTRAINED_ARC": routing_enums_pb2.FirstSolutionStrategy.PATH_MOST_CONSTRAINED_ARC,
    "EVALUATOR_STRATEGY": routing_enums_pb2.FirstSolutionStrategy.EVALUATOR_STRATEGY,
    "SAVINGS": routing_enums_pb2.FirstSolutionStrategy.SAVINGS,
    "SWEEP": routing_enums_pb2.FirstSolutionStrategy.SWEEP,
    "CHRISTOFIDES": routing_enums_pb2.FirstSolutionStrategy.CHRISTOFIDES,
    "ALL_UNPERFORMED": routing_enums_pb2.FirstSolutionStrategy.ALL_UNPERFORMED,
    "BEST_INSERTION": routing_enums_pb2.FirstSolutionStrategy.BEST_INSERTION,
    "PARALLEL_CHEAPEST_INSERTION": routing_enums_pb2.FirstSolutionStrategy.PARALLEL_CHEAPEST_INSERTION,
    "LOCAL_CHEAPEST_INSERTION": routing_enums_pb2.FirstSolutionStrategy.LOCAL_CHEAPEST_INSERTION,
    "GLOBAL_CHEAPEST_ARC": routing_enums_pb2.FirstSolutionStrategy.GLOBAL_CHEAPEST_ARC,
    "LOCAL_CHEAPEST_ARC": routing_enums_pb2.FirstSolutionStrategy.LOCAL_CHEAPEST_ARC,
    "FIRST_UNBOUND_MIN_VALUE": routing_enums_pb2.FirstSolutionStrategy.FIRST_UNBOUND_MIN_VALUE,
}

local_search_metaheuristics = {
    "GREEDY_DESCENT": routing_enums_pb2.LocalSearchMetaheuristic.GREEDY_DESCENT,
    "GUIDED_LOCAL_SEARCH": routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH,
    "SIMULATED_ANNEALING": routing_enums_pb2.LocalSearchMetaheuristic.SIMULATED_ANNEALING,
    "TABU_SEARCH": routing_enums_pb2.LocalSearchMetaheuristic.TABU_SEARCH,
    "GENERIC_TABU_SEARCH": routing_enums_pb2.LocalSearchMetaheuristic.GENERIC_TABU_SEARCH,
}

In [58]:
# depot = 0, alle andere adressen krijgen vraag 1
demands = [0] + [1] * (len(locations) - 1)

# elk voertuig mag max 15 adressen doen
vehicle_capacities = [MAX_ADRESSEN_PER_BUS] * num_vehicles

In [59]:
# MODEL 2
def build_capacity_model(distance_matrix, num_vehicles, demands, vehicle_capacities, depot=0):
    manager = pywrapcp.RoutingIndexManager(
        len(distance_matrix),
        num_vehicles,
        [depot] * num_vehicles,
        [depot] * num_vehicles
    )

    routing = pywrapcp.RoutingModel(manager)

    # afstand callback
    def distance_callback(from_index, to_index):
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return int(distance_matrix[from_node][to_node])

    transit_callback_index = routing.RegisterTransitCallback(distance_callback)
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

    # demand callback
    def demand_callback(from_index):
        from_node = manager.IndexToNode(from_index)
        return demands[from_node]

    demand_callback_index = routing.RegisterUnaryTransitCallback(demand_callback)

    # capacity dimension
    routing.AddDimensionWithVehicleCapacity(
        demand_callback_index,
        0,  # geen overschrijding toegestaan
        vehicle_capacities,
        True,
        "Capacity"
    )

    return manager, routing

In [60]:
# AFSTAND BEREKENEN
def calculate_total_distance(solution, routing, num_vehicles):
    total_distance = 0

    for vehicle_id in range(num_vehicles):
        index = routing.Start(vehicle_id)
        while not routing.IsEnd(index):
            next_index = solution.Value(routing.NextVar(index))
            total_distance += routing.GetArcCostForVehicle(index, next_index, vehicle_id)
            index = next_index

    return total_distance

In [61]:
# ROUTES UITLEZEN
def extract_capacity_routes(solution, manager, routing, num_vehicles, locations, demands):
    totaal_afstand = 0
    routes_output = []

    for vehicle_id in range(num_vehicles):
        index = routing.Start(vehicle_id)
        route_nodes = []
        route_adressen = []
        route_distance = 0
        route_demand = 0

        while not routing.IsEnd(index):
            node = manager.IndexToNode(index)
            route_nodes.append(node)
            route_adressen.append(locations.loc[node, 'VisitingAddress'])
            route_demand += demands[node]

            previous_index = index
            index = solution.Value(routing.NextVar(index))
            route_distance += routing.GetArcCostForVehicle(previous_index, index, vehicle_id)

        # einddepot toevoegen
        end_node = manager.IndexToNode(index)
        route_nodes.append(end_node)
        route_adressen.append(locations.loc[end_node, 'VisitingAddress'])

        totaal_afstand += route_distance

        routes_output.append({
            "vehicle_id": vehicle_id,
            "route_nodes": route_nodes,
            "route_adressen": route_adressen,
            "aantal_adressen": route_demand,
            "afstand_meters": route_distance,
            "afstand_km": round(route_distance / 1000, 2)
        })

    return totaal_afstand, routes_output

In [62]:
# FUNCTIE: ALLE COMBINATIES TESTEN VOOR MODEL 2
def compare_capacity_strategies(distance_matrix,
                                num_vehicles,
                                demands,
                                vehicle_capacities,
                                first_solution_strategies,
                                local_search_metaheuristics,
                                time_limit_seconds=10):
    results = []

    for fs_name, fs_value in first_solution_strategies.items():
        for ls_name, ls_value in local_search_metaheuristics.items():

            # vers model per combinatie
            manager, routing = build_capacity_model(
                distance_matrix=distance_matrix,
                num_vehicles=num_vehicles,
                demands=demands,
                vehicle_capacities=vehicle_capacities,
                depot=0
            )

            search_parameters = pywrapcp.DefaultRoutingSearchParameters()
            search_parameters.first_solution_strategy = fs_value
            search_parameters.local_search_metaheuristic = ls_value
            search_parameters.time_limit.seconds = time_limit_seconds

            start = time.time()
            solution = routing.SolveWithParameters(search_parameters)
            runtime = time.time() - start

            if solution:
                total_distance = calculate_total_distance(solution, routing, num_vehicles)

                # optioneel: aantal gebruikte voertuigen tellen
                used_vehicles = 0
                for vehicle_id in range(num_vehicles):
                    index = routing.Start(vehicle_id)
                    next_index = solution.Value(routing.NextVar(index))
                    if not routing.IsEnd(next_index):
                        used_vehicles += 1

                results.append({
                    "first_solution_strategy": fs_name,
                    "local_search_metaheuristic": ls_name,
                    "solution_found": True,
                    "total_distance": total_distance,
                    "used_vehicles": used_vehicles,
                    "runtime_sec": round(runtime, 2),
                })
            else:
                results.append({
                    "first_solution_strategy": fs_name,
                    "local_search_metaheuristic": ls_name,
                    "solution_found": False,
                    "total_distance": None,
                    "used_vehicles": None,
                    "runtime_sec": round(runtime, 2),
                })

    df_results = pd.DataFrame(results)

    df_results = df_results.sort_values(
        by=["solution_found", "total_distance", "runtime_sec"],
        ascending=[False, True, True]
    ).reset_index(drop=True)

    return df_results

In [63]:
# BESTE PARAMETERS KIEZEN
def get_best_parameters(df_results, allow_zero_distance=False):
    df_valid = df_results[df_results["solution_found"] == True].copy()
    df_valid = df_valid[df_valid["total_distance"].notna()]

    if not allow_zero_distance:
        df_valid = df_valid[df_valid["total_distance"] > 0]

    if df_valid.empty:
        raise ValueError(
            "Geen geldige oplossing gevonden voor model 2. "
            "Controleer of er genoeg voertuigen zijn voor de capaciteitsrestrictie."
        )

    best_row = df_valid.sort_values(
        by=["total_distance", "runtime_sec"],
        ascending=[True, True]
    ).iloc[0]

    return best_row["first_solution_strategy"], best_row["local_search_metaheuristic"]

In [64]:
# COMBINATIES TESTEN VOOR MODEL 2
df_results_model2 = compare_capacity_strategies(
    distance_matrix=distance_matrix,
    num_vehicles=num_vehicles,
    demands=demands,
    vehicle_capacities=vehicle_capacities,
    first_solution_strategies=first_solution_strategies,
    local_search_metaheuristics=local_search_metaheuristics,
    time_limit_seconds=TIME_LIMIT_SECONDS
)

print("Top 10 beste combinaties voor MODEL 2:")
print(df_results_model2.head(10))

Top 10 beste combinaties voor MODEL 2:
     first_solution_strategy local_search_metaheuristic  solution_found  \
0   LOCAL_CHEAPEST_INSERTION             GREEDY_DESCENT            True
1   LOCAL_CHEAPEST_INSERTION                TABU_SEARCH            True
2        GLOBAL_CHEAPEST_ARC                TABU_SEARCH            True
3    FIRST_UNBOUND_MIN_VALUE                TABU_SEARCH            True
4         LOCAL_CHEAPEST_ARC                TABU_SEARCH            True
5                    SAVINGS                TABU_SEARCH            True
6               CHRISTOFIDES        SIMULATED_ANNEALING            True
7          PATH_CHEAPEST_ARC        GUIDED_LOCAL_SEARCH            True
8  PATH_MOST_CONSTRAINED_ARC        GUIDED_LOCAL_SEARCH            True
9                    SAVINGS        GUIDED_LOCAL_SEARCH            True

   total_distance  used_vehicles  runtime_sec
0        277365.0            2.0         0.03
1        277365.0            2.0         3.85
2        277365.0            2.0         6.92
3        277365.0            2.0        10.94
4        277365.0            2.0        15.71
5        277365.0            2.0        23.88
6        277365.0            2.0        29.99
7        277365.0            2.0        30.00
8        277365.0            2.0        30.00
9        277365.0            2.0        30.00

In [65]:
# BESTE COMBINATIE KIEZEN
best_fs2, best_ls2 = get_best_parameters(df_results_model2, allow_zero_distance=False)

print("\nBeste combinatie voor MODEL 2:")
print(f"FirstSolutionStrategy: {best_fs2}")
print(f"LocalSearchMetaheuristic: {best_ls2}")

Beste combinatie voor MODEL 2:
FirstSolutionStrategy: LOCAL_CHEAPEST_INSERTION
LocalSearchMetaheuristic: GREEDY_DESCENT

In [66]:
# MODEL 2 OPNIEUW BOUWEN MET BESTE COMBINATIE
manager2, routing2 = build_capacity_model(
    distance_matrix=distance_matrix,
    num_vehicles=num_vehicles,
    demands=demands,
    vehicle_capacities=vehicle_capacities,
    depot=0
)

search_parameters2 = pywrapcp.DefaultRoutingSearchParameters()
search_parameters2.first_solution_strategy = getattr(
    routing_enums_pb2.FirstSolutionStrategy, best_fs2
)
search_parameters2.local_search_metaheuristic = getattr(
    routing_enums_pb2.LocalSearchMetaheuristic, best_ls2
)
search_parameters2.time_limit.seconds = TIME_LIMIT_SECONDS

print(f"\nMODEL 2 gebruikt nu:")
print(f"FirstSolutionStrategy: {best_fs2}")
print(f"LocalSearchMetaheuristic: {best_ls2}")

solution2 = routing2.SolveWithParameters(search_parameters2)

MODEL 2 gebruikt nu:
FirstSolutionStrategy: LOCAL_CHEAPEST_INSERTION
LocalSearchMetaheuristic: GREEDY_DESCENT

In [67]:
# RESULTATEN MODEL 2 UITLEZEN
if solution2:
    totaal_afstand2, routes_output2 = extract_capacity_routes(
        solution=solution2,
        manager=manager2,
        routing=routing2,
        num_vehicles=num_vehicles,
        locations=locations,
        demands=demands
    )

    print(f"\nMODEL 2: Totaal aantal voertuigen: {num_vehicles}")
    print(f"MODEL 2: Totaal aantal locaties incl. depot: {len(locations)}")
    print(f"MODEL 2: Totale afstand: {round(totaal_afstand2 / 1000, 2)} km\n")

    for route in routes_output2:
        print(f"Bus {route['vehicle_id']}:")
        print(" -> ".join(route['route_adressen']))
        print(f"Aantal adressen: {route['aantal_adressen']}")
        print(f"Afstand: {route['afstand_km']} km")
        print("-" * 60)

else:
    print("MODEL 2: Geen oplossing gevonden.")

MODEL 2: Totaal aantal voertuigen: 4
MODEL 2: Totaal aantal locaties incl. depot: 28
MODEL 2: Totale afstand: 277.37 km

Bus 0:
Kamerlingh Onnesweg 9, Dordrecht -> De Poort 24, Rilland -> Vliete 1, Krabbendijke -> Molenstraat 95, Zaamslag -> Rooseveltlaan 1, Axel -> Bachlaan 88, Terneuzen -> Pattistpark 137, Terneuzen -> Agaat 2 -12 , Middelburg -> Latijnse Schoolstraat 19, Middelburg -> Noordbolwerk 33, Middelburg -> Boergoensestraat 128, Rotterdam -> Maashaven O.Z. 103, Rotterdam -> Motorstraat 96, Rotterdam -> Reling 19, Barendrecht -> Kamerlingh Onnesweg 9, Dordrecht
Aantal adressen: 13
Afstand: 208.0 km
------------------------------------------------------------
Bus 1:
Kamerlingh Onnesweg 9, Dordrecht -> Groen Van Prinstererweg 38, Dordrecht -> Minnaertweg 4, Dordrecht -> Albert Schweitzerplaats 1, Dordrecht -> Bankastraat 158, Dordrecht -> Touwbaan 4, Sliedrecht -> Kerkbuurt 220, Sliedrecht -> Kerkbuurt 143, Sliedrecht -> Jupiterstraat 257, Hardinxveld-Giessendam -> Banneweg 57, Gorinchem -> Oosterhagen 17, Rotterdam -> Oosterhagen 17, Rotterdam -> Haastrechtstraat 130, Rotterdam -> Pietersdijk 60, Rotterdam -> Plantageweg 3, Zwijndrecht -> Kamerlingh Onnesweg 9, Dordrecht
Aantal adressen: 14
Afstand: 69.37 km
------------------------------------------------------------
Bus 2:
Kamerlingh Onnesweg 9, Dordrecht -> Kamerlingh Onnesweg 9, Dordrecht
Aantal adressen: 0
Afstand: 0.0 km
------------------------------------------------------------
Bus 3:
Kamerlingh Onnesweg 9, Dordrecht -> Kamerlingh Onnesweg 9, Dordrecht
Aantal adressen: 0
Afstand: 0.0 km
------------------------------------------------------------