In [1]:
import pandas as pd

In [3]:
df_ritten = pd.read_csv(
    'Bezoeken per voertuig 01-01-2025 - 31-12-2025.Csv',
    sep=';',
    encoding='utf-16',
    skiprows=1  # <-- dit is de key!
)

C:\Users\aniek.kasius\AppData\Local\Temp\ipykernel_5912\3429196175.py:1: DtypeWarning: Columns (0: Contact) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ritten = pd.read_csv(

In [4]:
df_ritten.info()

<class 'pandas.DataFrame'>
RangeIndex: 59133 entries, 0 to 59132
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SerialNumber         59133 non-null  str
 1   Date                 59133 non-null  str
 2   StartRide            59133 non-null  str
 3   Start                59133 non-null  str
 4   Stop                 59133 non-null  str
 5   Distance             59133 non-null  str
 6   TravelTime           59133 non-null  str
 7   Duration             59133 non-null  str
 8   VisitingAddress      59133 non-null  str
 9   Description          9187 non-null   str
 10  DriverName           55209 non-null  str
 11  GroupName            59133 non-null  str
 12  Contact              19 non-null     object
 13  Remark               5 non-null      str
 14  To                   58902 non-null  str
 15  ZipCode              58872 non-null  str
 16  City                 59133 non-null  str
 17  ProjectNumber        9165 non-null   float64
 18  Break                59133 non-null  str
 19  TotalTime            59133 non-null  str
 20  TotalTravelTime      59133 non-null  str
 21  TotalDuration        59133 non-null  str
 22  TotalTimeMinusBreak  59133 non-null  str
 23  TotalDistance        59133 non-null  str
 24  Lat                  59133 non-null  float64
 25  Long                 59133 non-null  float64
dtypes: float64(3), object(1), str(22)
memory usage: 11.7+ MB

In [5]:
df_ritten

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,...,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,967 (VDG-43-S),02-01-2025,06:48,07:17,10:27,"35,90",00:28,3:10,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,0:00,3:39,0:28,3:10,0:00,"35,90",51.905395,4.332835
1,967 (VDG-43-S),02-01-2025,10:27,10:39,10:43,"5,10",00:11,0:03,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,0:00,3:54,0:40,3:14,0:00,"41,00",51.905395,4.332835
2,967 (VDG-43-S),02-01-2025,10:43,11:36,12:17,"61,00",00:53,0:41,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,0:00,5:29,1:33,3:55,0:00,"102,00",51.905395,4.332835
3,967 (VDG-43-S),02-01-2025,12:17,12:58,14:51,"27,30",00:40,1:52,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,0:00,8:02,2:14,5:47,0:00,"129,30",51.905395,4.332835
4,967 (VDG-43-S),02-01-2025,14:51,15:06,06:55,"3,70",00:15,15:49,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,0:00,8:17,2:29,5:47,8:17,"133,00",51.905395,4.332835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59128,1775 (V-11-GGL),31-12-2025,09:17,09:28,10:18,"5,81",00:10,0:50,"Van Beethovenlaan 56, Rotterdam",NaN,...,Rotterdam,NaN,0:00,3:50,1:27,2:22,0:00,"68,85",51.956123,4.512793
59129,1775 (V-11-GGL),31-12-2025,10:18,10:38,10:57,"6,61",00:19,0:19,"Dotterlei 143, Capelle Aan Den Ijssel",NaN,...,Capelle Aan Den Ijssel,NaN,0:00,4:29,1:47,2:42,0:00,"75,46",51.932790,4.563842
59130,1775 (V-11-GGL),31-12-2025,10:57,11:28,11:46,"22,78",00:30,0:17,"Groen Van Prinstererweg 38, Dordrecht",NaN,...,Dordrecht,NaN,0:00,5:18,2:18,3:00,0:00,"98,24",51.790982,4.665400
59131,1775 (V-11-GGL),31-12-2025,11:46,11:54,12:02,"1,99",00:08,0:07,"Minnaertweg 4, Dordrecht",NaN,...,Dordrecht,NaN,0:00,5:34,2:26,3:07,0:00,"100,23",51.783413,4.686293
59132,1775 (V-11-GGL),31-12-2025,12:02,12:10,12:21,"5,18",00:08,0:11,"Kamerlingh Onnesweg 9, Dordrecht",Medux Kamerlingh Onnesweg,...,Dordrecht,0.0,0:00,5:53,2:34,3:18,5:53,"105,41",51.780550,4.639417

In [6]:
df_orders = pd.read_excel("Serviceorders - 01-01-2025 - 31-12-2025.xlsx")
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 25373 entries, 0 to 25372
Data columns (total 37 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Herstelstatuscodefilter  0 non-null      float64
 1   Toewijzingsdatumfilter   25373 non-null  str
 2   Responsdatumfilter       0 non-null      float64
 3   Resourcefilter           0 non-null      float64
 4   Resourcegroepfilter      0 non-null      float64
 5   Niet toegewezen          25373 non-null  int64
 6   Opmerking                25373 non-null  int64
 7   Documentnr.              25373 non-null  str
 8   Toewijzingsdatum         25373 non-null  datetime64[us]
 9   Resourcenr.              25369 non-null  str
 10  Herstelstatuscode        25373 non-null  int64
 11  Resourcegroepnr.         25314 non-null  str
 12  Responsdatum             25365 non-null  datetime64[us]
 13  Laaste opmerking         25351 non-null  str
 14  Serviceordersoort        25372 non-null  str
 15  Postcode                 25372 non-null  str
 16  Plaats                   25372 non-null  str
 17  Punten                   25373 non-null  int64
 18  Aantal serviceorders     25373 non-null  int64
 19  Aantal verkooporders     25373 non-null  int64
 20  Cliëntnr.                25372 non-null  str
 21  Naam                     25372 non-null  str
 22  Zorginstellingnaam       25370 non-null  str
 23  Orderdatum               25373 non-null  datetime64[us]
 24  Datum laatste opmerking  19705 non-null  datetime64[us]
 25  Verkoperscode            25371 non-null  str
 26  Omschrijving             25370 non-null  str
 27  Factuurnaam              25373 non-null  str
 28  Adres                    25372 non-null  str
 29  Vaste monteur            24926 non-null  str
 30  Artikelnr.               25372 non-null  str
 31  Serienummer              25363 non-null  str
 32  Dagen in verwerking      25373 non-null  int64
 33  Uw referentie            13370 non-null  str
 34  Portaalopmerking         2 non-null      str
 35  Datum portaalopmerking   1 non-null      datetime64[us]
 36  Totaalbedrag             25373 non-null  float64
dtypes: datetime64[us](5), float64(5), int64(7), str(20)
memory usage: 7.2 MB

In [7]:
df_orders

,Herstelstatuscodefilter,Toewijzingsdatumfilter,Responsdatumfilter,Resourcefilter,Resourcegroepfilter,Niet toegewezen,Opmerking,Documentnr.,Toewijzingsdatum,Resourcenr.,...,Factuurnaam,Adres,Vaste monteur,Artikelnr.,Serienummer,Dagen in verwerking,Uw referentie,Portaalopmerking,Datum portaalopmerking,Totaalbedrag
0,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2322714,2025-02-18,OFFERTE,...,CZ/Administratie Zorgkantoor,Plantageweg 4,Peter B,PUMA40.00010,18ZKCZ0245,288,202512200812820,NaN,NaT,943.42
1,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2339887,2025-11-27,JOP,...,VGZ Zorgkantoor,Touwbaan 1,Tjerk P,MIDLECTUS.00010,VGZ002411,80,Wacht op zorginfo,NaN,NaT,0.00
2,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2341189,2025-01-20,OFFERTE,...,CZ/Administratie Zorgkantoor,Emil Sandstromweg 2,Tom B,MORGANNEWTON.00010,55255110,262,202512200808613,NaN,NaT,2800.82
3,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2341990,2025-01-28,JOP,...,NTAC Zorgkantoor,Raaigras 102,Cornelis van der G,PUMA40.00010,ZKS00464,286,Wacht op QQ-nummer,NaN,NaT,0.00
4,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2400380,2025-01-06,OFFERTE,...,CZ/Administratie Zorgkantoor,Stadhuisplein 22,Tom B,ATTITUDEH2.00010,5525FIE1241,231,202512200807424,NaN,NaT,1603.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25368,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2527954,2025-12-31,MARKE,...,Zilveren Kruis Zorgkantoor,Grote Hagen 98,Sandro G,Q400M.00010,ACH0131305,51,NaN,NaN,NaT,15.41
25369,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2527961,2025-12-31,LIZA,...,Zilveren Kruis Zorgkantoor,Pietersdijk 60,Liza de G,Q400M.00010,ACH0130666,65,PO,NaN,NaT,0.00
25370,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2600367,2025-12-22,JOP,...,NTAC Zorgkantoor,Chopinlaan 9,Cornelis van der G,ROXXNEWTON.00010,ZKS02784,60,Wacht op A nummer,NaN,NaT,0.00
25371,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2600377,2025-12-24,ROBBY,...,CZ/Administratie Zorgkantoor,Bergweg 1,Vincent K,IBIS.00010,55253501,60,Wacht op zorginfo,NaN,NaT,0.00
25372,NaN,01-01-25..31-12-25,NaN,NaN,NaN,0,1,SOR2601272,2025-12-19,JOP,...,VGZ Zorgkantoor,Touwbaan 1,Tjerk P,MATCHD.00010,UVIT-24519,52,Wacht op zorginfo,NaN,NaT,0.00

In [118]:
# eerst data van orders opschonen

In [119]:
df01 = df_orders.drop(columns=['Herstelstatuscodefilter', 'Responsdatumfilter', 'Resourcefilter', 'Resourcegroepfilter', 'Portaalopmerking', 'Datum portaalopmerking'])
df01['Niet toegewezen'].unique()

array([0])

In [120]:
# alle orders zijn toegewezen, dus deze kolom is niet relevant
# kolom opmerking ook irrelevant, want deze geeft alleen aaf of er een opmerking is, niet wat de opmerking is
df02 = df01.drop(columns=['Niet toegewezen', 'Opmerking'])

In [121]:
df03 = df02.drop(columns=['Toewijzingsdatumfilter', 'Resourcenr.', 'Resourcegroepnr.', 'Laaste opmerking', 'Aantal serviceorders', 'Aantal verkooporders', 'Datum laatste opmerking', 'Verkoperscode', 'Serienummer', 'Dagen in verwerking', 'Uw referentie'])
df03

,Documentnr.,Toewijzingsdatum,Herstelstatuscode,Responsdatum,Serviceordersoort,Postcode,Plaats,Punten,Cliëntnr.,Naam,Zorginstellingnaam,Orderdatum,Omschrijving,Factuurnaam,Adres,Vaste monteur,Artikelnr.,Totaalbedrag
0,SOR2322714,2025-02-18,90,2023-05-03,REP,3232 LE,BRIELLE,12,K0011683,Mevr. B. van Toor,Careyn - De Plantage,2023-04-24,Puma 40,CZ/Administratie Zorgkantoor,Plantageweg 4,Peter B,PUMA40.00010,943.42
1,SOR2339887,2025-11-27,99,2023-12-01,REP,3363 WB,SLIEDRECHT,6,K0079751,Mevr. S. Mohar,ASVZ - De Merwebolder,2023-11-23,MID Lectus,VGZ Zorgkantoor,Touwbaan 1,Tjerk P,MIDLECTUS.00010,0.00
2,SOR2341189,2025-01-20,90,2023-12-15,REP,4301 NW,ZIERIKZEE,15,K0043840,Mevr. P. Verwest,Allevo - Zierik7,2023-12-08,Morgan Newton,CZ/Administratie Zorgkantoor,Emil Sandstromweg 2,Tom B,MORGANNEWTON.00010,2800.82
3,SOR2341990,2025-01-28,99,2023-12-29,REP,2643 JJ,PIJNACKER,24,510431,Mw. S. Bhawanie,Pieter van Foreest - Weidevogelhof,2023-12-19,Puma 40,NTAC Zorgkantoor,Raaigras 102,Cornelis van der G,PUMA40.00010,0.00
4,SOR2400380,2025-01-06,90,2024-01-15,REP,4382 LJ,VLISSINGEN,9,K0062065,Mevr. N. Langstraat,S Heeren Loo - Nieuwe Zuidbeekseweg,2024-01-08,QUICKIE ATTITUDE HYBRID 2,CZ/Administratie Zorgkantoor,Stadhuisplein 22,Tom B,ATTITUDEH2.00010,1603.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25368,SOR2527954,2025-12-31,90,2026-01-09,REP,3078 RC,ROTTERDAM,0,K0024206,Dhr. E. Dam,Aafje - Meerweide,2025-12-31,Puma Q400 M SedeoPro middenwielaandrijving,Zilveren Kruis Zorgkantoor,Grote Hagen 98,Sandro G,Q400M.00010,15.41
25369,SOR2527961,2025-12-31,99,2026-01-09,POREP,3079 TD,ROTTERDAM,0,K0069286,Dhr. P. Lugtigheid,Aafje - Smeetsland,2025-12-31,Puma Q400 M SedeoPro middenwielaandrijving,Zilveren Kruis Zorgkantoor,Pietersdijk 60,Liza de G,Q400M.00010,0.00
25370,SOR2600367,2025-12-22,5,2026-07-20,PASSING,2625 TD,DELFT,0,K0108508,Mevr. J.E. van der Hoeven-Bannier,Pieter van Foreest - Die Buytenweye,2026-01-07,Roxx New Original Newton,NTAC Zorgkantoor,Chopinlaan 9,Cornelis van der G,ROXXNEWTON.00010,0.00
25371,SOR2600377,2025-12-24,5,2026-07-20,PASSING,4461 LX,GOES,0,K0101144,Dhr. A. Molenaar,Cedrah - Woonzorgcentrum Rehoboth,2026-01-07,Ibis Pro rolstoel,CZ/Administratie Zorgkantoor,Bergweg 1,Vincent K,IBIS.00010,0.00
25372,SOR2601272,2025-12-19,5,2026-07-30,PASSING,3363 WB,SLIEDRECHT,0,162145,Mevr. E.P. Verweij,ASVZ - De Merwebolder,2026-01-19,Match duwonderstel,VGZ Zorgkantoor,Touwbaan 1,Tjerk P,MATCHD.00010,0.00

In [122]:
df03['Herstelstatuscode'].unique()

array([90, 99, 87, 85, 88, 89,  5])

In [123]:
# deze 3 codes staan voor 90 = ondertekend, 99 = gefactureerd, 87 = nog niet ondertekend. Al deze codes betekenen wel dat de order is uitgevoerd.
# dus deze kolom kan ook verwijderd worden
df03 = df03.drop(columns=['Herstelstatuscode', 'Naam'])

In [124]:
df03.info()

<class 'pandas.DataFrame'>
RangeIndex: 25373 entries, 0 to 25372
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Documentnr.         25373 non-null  str
 1   Toewijzingsdatum    25373 non-null  datetime64[us]
 2   Responsdatum        25365 non-null  datetime64[us]
 3   Serviceordersoort   25372 non-null  str
 4   Postcode            25372 non-null  str
 5   Plaats              25372 non-null  str
 6   Punten              25373 non-null  int64
 7   Cliëntnr.           25372 non-null  str
 8   Zorginstellingnaam  25370 non-null  str
 9   Orderdatum          25373 non-null  datetime64[us]
 10  Omschrijving        25370 non-null  str
 11  Factuurnaam         25373 non-null  str
 12  Adres               25372 non-null  str
 13  Vaste monteur       24926 non-null  str
 14  Artikelnr.          25372 non-null  str
 15  Totaalbedrag        25373 non-null  float64
dtypes: datetime64[us](3), float64(1), int64(1), str(11)
memory usage: 3.1 MB

In [125]:
# document nummer, toewijzingsdatum, clientnummer, orderdatum, omschrijving, factuurnaam, artikelnummer en totaal bedrijf zijn ook niet relevant
df04 = df03.drop(columns=['Documentnr.', 'Toewijzingsdatum', 'Cliëntnr.', 'Orderdatum', 'Omschrijving', 'Factuurnaam', 'Artikelnr.', 'Totaalbedrag', 'Serviceordersoort'])

In [126]:
df04

,Responsdatum,Postcode,Plaats,Punten,Zorginstellingnaam,Adres,Vaste monteur
0,2023-05-03,3232 LE,BRIELLE,12,Careyn - De Plantage,Plantageweg 4,Peter B
1,2023-12-01,3363 WB,SLIEDRECHT,6,ASVZ - De Merwebolder,Touwbaan 1,Tjerk P
2,2023-12-15,4301 NW,ZIERIKZEE,15,Allevo - Zierik7,Emil Sandstromweg 2,Tom B
3,2023-12-29,2643 JJ,PIJNACKER,24,Pieter van Foreest - Weidevogelhof,Raaigras 102,Cornelis van der G
4,2024-01-15,4382 LJ,VLISSINGEN,9,S Heeren Loo - Nieuwe Zuidbeekseweg,Stadhuisplein 22,Tom B
...,...,...,...,...,...,...,...
25368,2026-01-09,3078 RC,ROTTERDAM,0,Aafje - Meerweide,Grote Hagen 98,Sandro G
25369,2026-01-09,3079 TD,ROTTERDAM,0,Aafje - Smeetsland,Pietersdijk 60,Liza de G
25370,2026-07-20,2625 TD,DELFT,0,Pieter van Foreest - Die Buytenweye,Chopinlaan 9,Cornelis van der G
25371,2026-07-20,4461 LX,GOES,0,Cedrah - Woonzorgcentrum Rehoboth,Bergweg 1,Vincent K
25372,2026-07-30,3363 WB,SLIEDRECHT,0,ASVZ - De Merwebolder,Touwbaan 1,Tjerk P

In [127]:
df_ritten

,Date,StartTime,StopTime,From,To,Distance,Time,DriverName,SerialNumber
0,02-01-2025,06:48,07:17,"Vlaardingen, Produktiestraat 2","Vlaardingen, Produktiestraat 2","35,9 km",0:28:33,NaN,967 (VDG-43-S)
1,02-01-2025,10:27,10:39,"Vlaardingen, Produktiestraat 2","Vlaardingen, Produktiestraat 2","5,1 km",0:11:50,NaN,967 (VDG-43-S)
2,02-01-2025,10:43,11:36,"Vlaardingen, Produktiestraat 2","Vlaardingen, Produktiestraat 2",61 km,0:53:10,NaN,967 (VDG-43-S)
3,02-01-2025,12:17,12:58,"Vlaardingen, Produktiestraat 2","Vlaardingen, Produktiestraat 2","27,3 km",0:40:54,NaN,967 (VDG-43-S)
4,02-01-2025,14:51,15:06,"Vlaardingen, Produktiestraat 2","Vlaardingen, Produktiestraat 2","3,7 km",0:15:27,NaN,967 (VDG-43-S)
...,...,...,...,...,...,...,...,...,...
59157,31-12-2025,10:18,10:38,"Rotterdam, Van Beethovenlaan 56","Capelle Aan Den Ijssel, Dotterlei 143","6,61 km",0:19:57,Patrick Baas,1775 (V-11-GGL)
59158,31-12-2025,10:57,11:28,"Capelle Aan Den Ijssel, Dotterlei 143","Dordrecht, Groen Van Prinstererweg 38","22,78 km",0:30:33,Patrick Baas,1775 (V-11-GGL)
59159,31-12-2025,11:46,11:54,"Dordrecht, Groen Van Prinstererweg 38","Dordrecht, Minnaertweg 4","1,99 km",0:08:30,Patrick Baas,1775 (V-11-GGL)
59160,31-12-2025,12:02,12:10,"Dordrecht, Minnaertweg 4","Dordrecht, Kamerlingh Onnesweg 9 (Medux Kamerl...","5,18 km",0:08:23,Patrick Baas,1775 (V-11-GGL)
59161,31-12-2025,12:21,12:23,"Dordrecht, Kamerlingh Onnesweg 9","Dordrecht, Kamerlingh Onnesweg 9 (Medux Kamerl...","0,07 km",0:01:09,Patrick Baas,1775 (V-11-GGL)

In [128]:
df_ritten['To'] = df_ritten['To'].str.replace(r'\s*\(.*?\)', '', regex=True)

In [129]:
df_ritten[['Plaats bestemming', 'Adres bestemming']] = df_ritten['To'].str.split(',', n=1, expand=True)

In [130]:
df_ritten[['Plaats herkomst', 'Adres herkomst']] = df_ritten['From'].str.split(',', n=1, expand=True)

In [131]:
df_ritten

,Date,StartTime,StopTime,From,To,Distance,Time,DriverName,SerialNumber,Plaats bestemming,Adres bestemming,Plaats herkomst,Adres herkomst
0,02-01-2025,06:48,07:17,"Vlaardingen, Produktiestraat 2","Vlaardingen, Produktiestraat 2","35,9 km",0:28:33,NaN,967 (VDG-43-S),Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2
1,02-01-2025,10:27,10:39,"Vlaardingen, Produktiestraat 2","Vlaardingen, Produktiestraat 2","5,1 km",0:11:50,NaN,967 (VDG-43-S),Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2
2,02-01-2025,10:43,11:36,"Vlaardingen, Produktiestraat 2","Vlaardingen, Produktiestraat 2",61 km,0:53:10,NaN,967 (VDG-43-S),Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2
3,02-01-2025,12:17,12:58,"Vlaardingen, Produktiestraat 2","Vlaardingen, Produktiestraat 2","27,3 km",0:40:54,NaN,967 (VDG-43-S),Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2
4,02-01-2025,14:51,15:06,"Vlaardingen, Produktiestraat 2","Vlaardingen, Produktiestraat 2","3,7 km",0:15:27,NaN,967 (VDG-43-S),Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59157,31-12-2025,10:18,10:38,"Rotterdam, Van Beethovenlaan 56","Capelle Aan Den Ijssel, Dotterlei 143","6,61 km",0:19:57,Patrick Baas,1775 (V-11-GGL),Capelle Aan Den Ijssel,Dotterlei 143,Rotterdam,Van Beethovenlaan 56
59158,31-12-2025,10:57,11:28,"Capelle Aan Den Ijssel, Dotterlei 143","Dordrecht, Groen Van Prinstererweg 38","22,78 km",0:30:33,Patrick Baas,1775 (V-11-GGL),Dordrecht,Groen Van Prinstererweg 38,Capelle Aan Den Ijssel,Dotterlei 143
59159,31-12-2025,11:46,11:54,"Dordrecht, Groen Van Prinstererweg 38","Dordrecht, Minnaertweg 4","1,99 km",0:08:30,Patrick Baas,1775 (V-11-GGL),Dordrecht,Minnaertweg 4,Dordrecht,Groen Van Prinstererweg 38
59160,31-12-2025,12:02,12:10,"Dordrecht, Minnaertweg 4","Dordrecht, Kamerlingh Onnesweg 9","5,18 km",0:08:23,Patrick Baas,1775 (V-11-GGL),Dordrecht,Kamerlingh Onnesweg 9,Dordrecht,Minnaertweg 4
59161,31-12-2025,12:21,12:23,"Dordrecht, Kamerlingh Onnesweg 9","Dordrecht, Kamerlingh Onnesweg 9","0,07 km",0:01:09,Patrick Baas,1775 (V-11-GGL),Dordrecht,Kamerlingh Onnesweg 9,Dordrecht,Kamerlingh Onnesweg 9

In [132]:
df_ritten = df_ritten.drop(columns=['From', 'To'])

In [133]:
df_ritten = df_ritten[
    [
        'Date',
        'StartTime',
        'StopTime',
        'Plaats herkomst',
        'Adres herkomst',
        'Plaats bestemming',
        'Adres bestemming',
        'Distance',
        'Time',
        'DriverName',
        'SerialNumber'
    ]
]

In [134]:
df_ritten.info()

<class 'pandas.DataFrame'>
RangeIndex: 59162 entries, 0 to 59161
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               59162 non-null  str
 1   StartTime          59162 non-null  str
 2   StopTime           59162 non-null  str
 3   Plaats herkomst    59162 non-null  str
 4   Adres herkomst     59158 non-null  str
 5   Plaats bestemming  59162 non-null  str
 6   Adres bestemming   59158 non-null  str
 7   Distance           59162 non-null  str
 8   Time               59162 non-null  str
 9   DriverName         55234 non-null  str
 10  SerialNumber       59162 non-null  str
dtypes: str(11)
memory usage: 5.0 MB

In [135]:
df_ritten['Date'] = pd.to_datetime(df_ritten['Date'], format='%d-%m-%Y')

In [136]:
df_ritten.info()

<class 'pandas.DataFrame'>
RangeIndex: 59162 entries, 0 to 59161
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               59162 non-null  datetime64[us]
 1   StartTime          59162 non-null  str
 2   StopTime           59162 non-null  str
 3   Plaats herkomst    59162 non-null  str
 4   Adres herkomst     59158 non-null  str
 5   Plaats bestemming  59162 non-null  str
 6   Adres bestemming   59158 non-null  str
 7   Distance           59162 non-null  str
 8   Time               59162 non-null  str
 9   DriverName         55234 non-null  str
 10  SerialNumber       59162 non-null  str
dtypes: datetime64[us](1), str(10)
memory usage: 5.0 MB

In [137]:
# zorgen dat de drivers dezelfde namen hebben zodat er niet teveel data is
df04['Vaste monteur'].unique()

<StringArray>
[           'Peter B',            'Tjerk P',              'Tom B',
 'Cornelis van der G',             'René H',             'Alin A',
          'Vincent K',     'Aart van der W',         'Mark den E',
              'Ron T',           'Jeremy R',          'Liza de G',
           'Marcel K',      'Laurens-Jan B',          'Patrick B',
           'Sandro G',                  nan,             'Rene H',
             'Jeremy']
Length: 19, dtype: str

In [138]:
df_ritten['DriverName'].unique()

<StringArray>
[                               nan,                'Laurens-Jan Burkx',
        'Auto Mertens Auto Mertens',                        'John Stam',
                    'Tuur de Lange',                'Aart van der Wulp',
                    'Bas van Steen',             'Joeri van  Zijverden',
                  'Tom Barendrecht',                      'Berijder 31',
              'Peter van den Bosch',                   'Marcel Koevoet',
                  'Vincent  Knapen',                  'Tjerk Polderman',
                   'Sandro Glasius',                   'Garage Mertens',
                     'Liza de Gier',                       'Ronald Kok',
                       'Erik-Jan 3',                  'Alenka Marjetic',
                    'Berijder 1548',                'Autogarage Smeets',
                  'Mark den  Elzen',         'Cornelis van der Giessen',
            'Geertjan van der Wulp',                     'Roy Albersen',
                    'Berijder 1426',                     'Patrick Baas',
                     'Frido Wijnen',             'Joost van der Linden',
                   'Alon Ben-David',                     'Robin Kovács',
                      'Kees Kuiper',                    'Marcus Dekker',
                       'Han Jonker',                       'Peter Bood',
                     'berijder 503',                    'Berijder 1528',
                  'Joost Oerlemans',                    'Onno Havelaar',
                    'Berijder 1643',                  'Enzo van Dongen',
                       'Ron Timmer',                    'Hans de Groot',
                   'Sheamie Gerard',                   'Frans Boshoven',
                    'Berijder 1517',               'Karhof Carrosserie',
              'René Hoppenbrouwers',                   'Barend de Jong',
 'Lars van de Griek Garage Louwman',                    'Ronald Griend',
       'Bosch Car Service Fijneman',              'Transport Autoreset',
                    'Berijder 2127',                      'Alin Apetri']
Length: 56, dtype: str

In [139]:
df_ritten[df_ritten['DriverName'].isna()]

,Date,StartTime,StopTime,Plaats herkomst,Adres herkomst,Plaats bestemming,Adres bestemming,Distance,Time,DriverName,SerialNumber
0,2025-01-02,06:48,07:17,Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2,"35,9 km",0:28:33,NaN,967 (VDG-43-S)
1,2025-01-02,10:27,10:39,Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2,"5,1 km",0:11:50,NaN,967 (VDG-43-S)
2,2025-01-02,10:43,11:36,Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2,61 km,0:53:10,NaN,967 (VDG-43-S)
3,2025-01-02,12:17,12:58,Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2,"27,3 km",0:40:54,NaN,967 (VDG-43-S)
4,2025-01-02,14:51,15:06,Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2,"3,7 km",0:15:27,NaN,967 (VDG-43-S)
...,...,...,...,...,...,...,...,...,...,...,...
59077,2025-12-16,10:11,10:11,Terneuzen,Alberdingk Thijmstraat 3,Terneuzen,Alberdingk Thijmstraat 3,-,0:00:40,NaN,1775 (V-11-GGL)
59083,2025-12-16,13:04,13:08,Kapelle,Bruëlisstraat 71,Kapelle,Bruëlisstraat 71,-,0:04:24,NaN,1775 (V-11-GGL)
59094,2025-12-17,10:29,10:29,Dordrecht,Bankastraat 158,Dordrecht,Bankastraat 158,-,0:00:24,NaN,1775 (V-11-GGL)
59109,2025-12-18,09:52,09:52,Zevenbergen,Kasteelweg 103,Zevenbergen,Kasteelweg 103,-,0:00:02,NaN,1775 (V-11-GGL)
59136,2025-12-24,10:29,10:31,Rotterdam,Van Der Sasstraat 61,Rotterdam,Van Der Sasstraat 15,"0,05 km",0:01:33,NaN,1775 (V-11-GGL)

In [140]:
df_ritten.groupby(['Date', 'SerialNumber'])['DriverName'].unique()

Date        SerialNumber
2025-01-01  1040 (VFT-36-H)                         [nan]
            1326 (VNT-05-X)                         [nan]
            1515 (VVF-65-D)    [Cornelis van der Giessen]
            1660 (V-20-DKR)         [René Hoppenbrouwers]
            1687 (V-22-DKR)              [Barend de Jong]
                                          ...
2025-12-31  1624 (VZV-80-H)              [Frans Boshoven]
            1660 (V-20-DKR)         [René Hoppenbrouwers]
            1705 (V-18-FXR)               [Marcus Dekker]
            1772 (V-13-DLF)                 [Alin Apetri]
            1775 (V-11-GGL)                [Patrick Baas]
Name: DriverName, Length: 6071, dtype: object

In [141]:
df_check = df_ritten.groupby(['Date', 'SerialNumber'])['DriverName'].nunique()

df_check.value_counts()

DriverName
1    5862
0     124
2      80
3       5
Name: count, dtype: int64

In [142]:
# Dit houdt in dat voertuigen op bepaalde dagen 80 keer door 2 mensen zijn gebruikt, 5 keer door 3 mensen en 5862 keer door 1 persoon. Daarnaast is het van 124 ritten niet bekend wie de chauffeur was.
# Door te achterhalen wie de chauffeurs waren van deze 124 ritten, kunnen we de data koppelen aan de orders.
# Eerst moet de data gereed zijn om te kunnen koppelen. En halen we sowieso alle ritten eruit van de chauffers die niet bij onze order data staan.
df04['Vaste monteur'].unique()

<StringArray>
[           'Peter B',            'Tjerk P',              'Tom B',
 'Cornelis van der G',             'René H',             'Alin A',
          'Vincent K',     'Aart van der W',         'Mark den E',
              'Ron T',           'Jeremy R',          'Liza de G',
           'Marcel K',      'Laurens-Jan B',          'Patrick B',
           'Sandro G',                  nan,             'Rene H',
             'Jeremy']
Length: 19, dtype: str

In [143]:
df_ritten['DriverName'].unique()

<StringArray>
[                               nan,                'Laurens-Jan Burkx',
        'Auto Mertens Auto Mertens',                        'John Stam',
                    'Tuur de Lange',                'Aart van der Wulp',
                    'Bas van Steen',             'Joeri van  Zijverden',
                  'Tom Barendrecht',                      'Berijder 31',
              'Peter van den Bosch',                   'Marcel Koevoet',
                  'Vincent  Knapen',                  'Tjerk Polderman',
                   'Sandro Glasius',                   'Garage Mertens',
                     'Liza de Gier',                       'Ronald Kok',
                       'Erik-Jan 3',                  'Alenka Marjetic',
                    'Berijder 1548',                'Autogarage Smeets',
                  'Mark den  Elzen',         'Cornelis van der Giessen',
            'Geertjan van der Wulp',                     'Roy Albersen',
                    'Berijder 1426',                     'Patrick Baas',
                     'Frido Wijnen',             'Joost van der Linden',
                   'Alon Ben-David',                     'Robin Kovács',
                      'Kees Kuiper',                    'Marcus Dekker',
                       'Han Jonker',                       'Peter Bood',
                     'berijder 503',                    'Berijder 1528',
                  'Joost Oerlemans',                    'Onno Havelaar',
                    'Berijder 1643',                  'Enzo van Dongen',
                       'Ron Timmer',                    'Hans de Groot',
                   'Sheamie Gerard',                   'Frans Boshoven',
                    'Berijder 1517',               'Karhof Carrosserie',
              'René Hoppenbrouwers',                   'Barend de Jong',
 'Lars van de Griek Garage Louwman',                    'Ronald Griend',
       'Bosch Car Service Fijneman',              'Transport Autoreset',
                    'Berijder 2127',                      'Alin Apetri']
Length: 56, dtype: str

In [144]:
def maak_korte_naam(naam):
    if pd.isna(naam):
        return None
    delen = naam.lower().strip().split()
    if len(delen) >= 2:
        return delen[0] + ' ' + delen[1][0]
    elif len(delen) == 1:
        return delen[0]
    return None

df_ritten['Driver_short'] = df_ritten['DriverName'].apply(maak_korte_naam)

In [145]:
df04['Monteur_short'] = (
    df04['Vaste monteur']
    .astype(str)
    .str.lower()
    .str.strip()
)

In [146]:
df_ritten_1 = df_ritten[
    df_ritten['Driver_short'].isin(df04['Monteur_short'])
]

In [147]:
print(len(df_ritten))
print(len(df_ritten_1))

59162
20372

In [148]:
df04['Monteur_short'].unique()

<StringArray>
[           'peter b',            'tjerk p',              'tom b',
 'cornelis van der g',             'rené h',             'alin a',
          'vincent k',     'aart van der w',         'mark den e',
              'ron t',           'jeremy r',          'liza de g',
           'marcel k',      'laurens-jan b',          'patrick b',
           'sandro g',                  nan,             'rene h',
             'jeremy']
Length: 19, dtype: str

In [149]:
df_ritten_1['Driver_short'].unique()

<StringArray>
[            nan, 'laurens-jan b',         'tom b',      'marcel k',
     'vincent k',       'tjerk p',      'sandro g',     'patrick b',
       'peter b',         'ron t',        'rené h',        'alin a']
Length: 12, dtype: str

In [150]:
# 7 namen verwijderen uit df04
df05 = df04[~df04['Monteur_short'].isin(df_ritten_1['Driver_short'])]

In [153]:
df05['Plaats'] = df05['Plaats'].str.lower().str.capitalize()

In [154]:
df05

,Responsdatum,Postcode,Plaats,Punten,Zorginstellingnaam,Adres,Vaste monteur,Monteur_short
3,2023-12-29,2643 JJ,Pijnacker,24,Pieter van Foreest - Weidevogelhof,Raaigras 102,Cornelis van der G,cornelis van der g
8,2024-04-23,2612 VC,Delft,6,Pieter van Foreest - Bieslandhof,Beukenlaan 2,Cornelis van der G,cornelis van der g
9,2024-04-25,2685 SZ,Poeldijk,3,Middin - Westland Eliasdreef,Eliasdreef 9,Cornelis van der G,cornelis van der g
12,2024-07-19,2612 VC,Delft,3,Pieter van Foreest - Bieslandhof,Beukenlaan 2,Cornelis van der G,cornelis van der g
13,2025-02-05,3241 LK,Middelharnis,18,Zuidwester - Middelharnis,Oosthavendijk 30,Aart van der W,aart van der w
...,...,...,...,...,...,...,...,...
25364,2026-01-09,2991 HP,Barendrecht,0,Laurens - Borgstede,Marjoleinlaan 43,Liza de G,liza de g
25366,2026-01-09,3281 BC,Numansdorp,0,Alerimus - De Buitensluis,Bernhardstraat 25,Mark den E,mark den e
25367,2026-01-09,3281 BC,Numansdorp,0,Alerimus - De Buitensluis,Bernhardstraat 25,Mark den E,mark den e
25369,2026-01-09,3079 TD,Rotterdam,0,Aafje - Smeetsland,Pietersdijk 60,Liza de G,liza de g
25370,2026-07-20,2625 TD,Delft,0,Pieter van Foreest - Die Buytenweye,Chopinlaan 9,Cornelis van der G,cornelis van der g

In [152]:
df_ritten_1

,Date,StartTime,StopTime,Plaats herkomst,Adres herkomst,Plaats bestemming,Adres bestemming,Distance,Time,DriverName,SerialNumber,Driver_short
0,2025-01-02,06:48,07:17,Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2,"35,9 km",0:28:33,NaN,967 (VDG-43-S),NaN
1,2025-01-02,10:27,10:39,Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2,"5,1 km",0:11:50,NaN,967 (VDG-43-S),NaN
2,2025-01-02,10:43,11:36,Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2,61 km,0:53:10,NaN,967 (VDG-43-S),NaN
3,2025-01-02,12:17,12:58,Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2,"27,3 km",0:40:54,NaN,967 (VDG-43-S),NaN
4,2025-01-02,14:51,15:06,Vlaardingen,Produktiestraat 2,Vlaardingen,Produktiestraat 2,"3,7 km",0:15:27,NaN,967 (VDG-43-S),NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
59157,2025-12-31,10:18,10:38,Rotterdam,Van Beethovenlaan 56,Capelle Aan Den Ijssel,Dotterlei 143,"6,61 km",0:19:57,Patrick Baas,1775 (V-11-GGL),patrick b
59158,2025-12-31,10:57,11:28,Capelle Aan Den Ijssel,Dotterlei 143,Dordrecht,Groen Van Prinstererweg 38,"22,78 km",0:30:33,Patrick Baas,1775 (V-11-GGL),patrick b
59159,2025-12-31,11:46,11:54,Dordrecht,Groen Van Prinstererweg 38,Dordrecht,Minnaertweg 4,"1,99 km",0:08:30,Patrick Baas,1775 (V-11-GGL),patrick b
59160,2025-12-31,12:02,12:10,Dordrecht,Minnaertweg 4,Dordrecht,Kamerlingh Onnesweg 9,"5,18 km",0:08:23,Patrick Baas,1775 (V-11-GGL),patrick b
59161,2025-12-31,12:21,12:23,Dordrecht,Kamerlingh Onnesweg 9,Dordrecht,Kamerlingh Onnesweg 9,"0,07 km",0:01:09,Patrick Baas,1775 (V-11-GGL),patrick b

In [155]:
df_orders = df05
df_orders.info()
df_ritten_1.info()

<class 'pandas.DataFrame'>
Index: 7635 entries, 3 to 25370
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Responsdatum        7633 non-null   datetime64[us]
 1   Postcode            7634 non-null   str
 2   Plaats              7634 non-null   str
 3   Punten              7635 non-null   int64
 4   Zorginstellingnaam  7634 non-null   str
 5   Adres               7634 non-null   str
 6   Vaste monteur       7635 non-null   str
 7   Monteur_short       7635 non-null   str
dtypes: datetime64[us](1), int64(1), str(6)
memory usage: 536.8 KB
<class 'pandas.DataFrame'>
Index: 20372 entries, 0 to 59161
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               20372 non-null  datetime64[us]
 1   StartTime          20372 non-null  str
 2   StopTime           20372 non-null  str
 3   Plaats herkomst    20372 non-null  str
 4   Adres herkomst     20371 non-null  str
 5   Plaats bestemming  20372 non-null  str
 6   Adres bestemming   20371 non-null  str
 7   Distance           20372 non-null  str
 8   Time               20372 non-null  str
 9   DriverName         16444 non-null  str
 10  SerialNumber       20372 non-null  str
 11  Driver_short       16444 non-null  str
dtypes: datetime64[us](1), str(11)
memory usage: 2.0 MB

In [156]:
# Veilig kopieën maken
df_orders = df05.copy()
df_ritten = df_ritten_1.copy()

# Datumkolommen naar alleen datum/tijd 00:00:00
df_orders['Responsdatum_dag'] = df_orders['Responsdatum'].dt.normalize()
df_ritten['Date_dag'] = df_ritten['Date'].dt.normalize()

# Tekstkolommen opschonen
df_orders['Plaats_clean'] = df_orders['Plaats'].str.strip().str.lower()
df_orders['Adres_clean'] = df_orders['Adres'].str.strip().str.lower()
df_orders['Monteur_short_clean'] = df_orders['Monteur_short'].str.strip().str.lower()

df_ritten['Plaats_bestemming_clean'] = df_ritten['Plaats bestemming'].str.strip().str.lower()
df_ritten['Adres_bestemming_clean'] = df_ritten['Adres bestemming'].str.strip().str.lower()
df_ritten['Driver_short_clean'] = df_ritten['Driver_short'].str.strip().str.lower()

# Merge
df_merge = df_ritten.merge(
    df_orders,
    left_on=[
        'Date_dag',
        'Plaats_bestemming_clean',
        'Adres_bestemming_clean',
        'Driver_short_clean'
    ],
    right_on=[
        'Responsdatum_dag',
        'Plaats_clean',
        'Adres_clean',
        'Monteur_short_clean'
    ],
    how='left'
)

# Check hoeveel matches
print(df_merge['Responsdatum'].notna().value_counts())
print('Aantal matches:', df_merge['Responsdatum'].notna().sum())
print('Matchpercentage:', round(df_merge['Responsdatum'].notna().sum() / len(df_merge) * 100, 2), '%')

Responsdatum
False    20372
Name: count, dtype: int64
Aantal matches: 0
Matchpercentage: 0.0 %

In [157]:
# Veilige kopieën
df_orders = df05.copy()
df_ritten = df_ritten_1.copy()

# Datum alleen dag
df_orders['Responsdatum_dag'] = df_orders['Responsdatum'].dt.normalize()
df_ritten['Date_dag'] = df_ritten['Date'].dt.normalize()

# Tekst opschonen
df_orders['Plaats_clean'] = df_orders['Plaats'].astype(str).str.strip().str.lower()
df_orders['Adres_clean'] = df_orders['Adres'].astype(str).str.strip().str.lower()
df_orders['Monteur_short_clean'] = df_orders['Monteur_short'].astype(str).str.strip().str.lower()

df_ritten['Plaats_bestemming_clean'] = df_ritten['Plaats bestemming'].astype(str).str.strip().str.lower()
df_ritten['Adres_bestemming_clean'] = df_ritten['Adres bestemming'].astype(str).str.strip().str.lower()
df_ritten['Driver_short_clean'] = df_ritten['Driver_short'].astype(str).str.strip().str.lower()

In [158]:
set_datum_ritten = set(df_ritten['Date_dag'].dropna().unique())
set_datum_orders = set(df_orders['Responsdatum_dag'].dropna().unique())

print("Overlap datums:", len(set_datum_ritten & set_datum_orders))

Overlap datums: 258

In [159]:
set_plaats_ritten = set(df_ritten['Plaats_bestemming_clean'].dropna().unique())
set_plaats_orders = set(df_orders['Plaats_clean'].dropna().unique())

print("Overlap plaatsen:", len(set_plaats_ritten & set_plaats_orders))
print(set_plaats_ritten & set_plaats_orders)

Overlap plaatsen: 54
{'halsteren', 'breda', 'oud-beijerland', 'sliedrecht', 'zwijndrecht', 'monster', 'etten-leur', 'naaldwijk', 'vlaardingen', 'piershil', 'schipluiden', 'nootdorp', 'terheijden', 'ouddorp zh', 'hardinxveld-giessendam', 'wateringen', 'spijkenisse', 'hellevoetsluis', 'capelle aan den ijssel', 'rockanje', 'maasland', 'zuidland', 'maassluis', 'wouw', 'strijen', 'delft', 'ridderkerk', 'sommelsdijk', 'fijnaart', 'oostvoorne', 'schiedam', 'rotterdam', 'bergen op zoom', 'puttershoek', 'zevenbergschen hoek', 'brielle', 'dirksland', "'s-gravendeel", 'middelharnis', 'poeldijk', 'barendrecht', 'nieuw lekkerland', 'numansdorp', 'zevenbergen', 'roosendaal', 'goes', 'lage zwaluwe', 'de lier', 'pijnacker', 'rozenburg zh', 'klundert', "'s-gravenzande", 'nieuw-lekkerland', 'dordrecht'}

In [161]:
set_adres_ritten = set(df_ritten['Adres_bestemming_clean'].dropna().unique())
set_adres_orders = set(df_orders['Adres_clean'].dropna().unique())

print("Overlap adressen:", len(set_adres_ritten & set_adres_orders))

Overlap adressen: 80