In [1]:
import pandas as pd

df = pd.read_excel("Bezoeken per voertuig 01-01-2025 - 31-01-2025.xlsx")
df.head()

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,...,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
0,1311 (VPZ-03-J),2025-01-02,12:31:00,12:38:00,12:40:00,3.2,00:06:00,00:01:00,"Johan Schippersplantsoen 1, Amsterdam",NaN,...,Amsterdam,NaN,00:00:00,00:08:00,00:06:00,00:01:00,00:00:00,3.2,523793823.0,48256393.0
1,1311 (VPZ-03-J),2025-01-02,12:40:00,13:00:00,13:01:00,13.5,00:20:00,00:00:00,"Schmidtstraat 12, Spaarndam",NaN,...,Spaarndam,NaN,00:00:00,00:29:00,00:27:00,00:02:00,00:00:00,16.7,524150138.0,46937561.0
2,1311 (VPZ-03-J),2025-01-02,13:01:00,13:01:00,13:36:00,0.1,00:00:00,00:34:00,"Schmidtstraat 12, Spaarndam",NaN,...,Spaarndam,NaN,00:00:00,01:04:00,00:27:00,00:36:00,00:00:00,16.8,524149597.0,4693831.0
3,1311 (VPZ-03-J),2025-01-02,13:36:00,13:56:00,14:16:00,10.7,00:20:00,00:20:00,"Schouwtjeslaan 55, Haarlem",NaN,...,Haarlem,NaN,00:00:00,01:44:00,00:47:00,00:57:00,00:00:00,27.5,523710894.0,46199301.0
4,1311 (VPZ-03-J),2025-01-02,14:16:00,14:33:00,14:40:00,16.0,00:17:00,00:06:00,"Tijnmuiden 75, Amsterdam",NaN,...,Amsterdam,NaN,00:00:00,02:08:00,01:05:00,01:03:00,00:00:00,43.5,523912751.0,47789565.0

In [2]:
df['GroupName'].unique()

<StringArray>
[                     '11810500 Amsterdam - ZV',
                     '12030100 Apeldoorn - WMO',
                        '12220100 Arnhem - WMO',
                        '12220700 Arnhem - BBT',
                     '18410 300001 Deventer BT',
                     '19210700 Dordrecht - BBT',
          '22410100 - Goes Klein Frankrijk WMO',
                     '23210100 Groningen - WMO',
                     '23210700 Groningen - BBT',
                       '25310100 Heerlen - WMO',
                       '25810100 Helmond - WMO',
                        '25810300 Helmond - BT',
                       '25810700 Helmond - BBT',
               '25810800 Helmond - Orthototaal',
                        '25820500 Helmond - ZV',
                       '26020100 Hengelo - WMO',
                          '26710700 Goor - BBT',
                        '27220100 Houten - WMO',
                        '32310700 Meppel - BBT',
                         '32320500 Meppel - ZV',
    '32610.100001 - Den Hoorn - Den Haag - WMO',
               '32610.100002 - Den Hoorn - WMO',
               '32610.700001 - Den Hoorn - BBT',
                   '32610300004 Den Hoorn - BT',
           '37010810 Ravenstein - AtlasKidtech',
                           '37610500 Elst - ZV',
                         '37620100013 WMO ELST',
                      '38110300 Purmerend - BT',
                       '41920300 Drachten - BT',
                      '41930100 Drachten - WMO',
                          '44020 600038 Retail',
                       '44040100 Tilburg - WMO',
          '45010104 Utrecht - WMO Advies Pool ',
                        '45010300 Utrecht - BT',
                 '45010516 Utrecht - ZV Advies',
         '45010600 Utrecht - Medipoint winkels',
                       '45010700 Utrecht - BBT',
                         '46130100 Venlo - WMO',
 '48010100 Weesp/Gooi & Vechtstreek/Adam - WMO',
                      '48510100 Maasdijk - WMO',
                       '50120700 Zaandam - BBT',
                         '50130.100 Wormerveer',
                    '51720500 Zwijndrecht - ZV',
            '680 Medipoint Retail Thuisservice',
                           'Poolauto's Utrecht',
                                            nan]
Length: 46, dtype: str

In [3]:
df01 = df[df['GroupName'] == '19210700 Dordrecht - BBT']
df01

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,...,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
16939,967 (VDG-43-S),2025-01-02,06:48:00,07:17:00,10:27:00,35.90,00:28:00,03:10:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,03:39:00,00:28:00,03:10:00,00:00:00,35.90,519053952.0,43328348.0
16940,967 (VDG-43-S),2025-01-02,10:27:00,10:39:00,10:43:00,5.10,00:11:00,00:03:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,03:54:00,00:40:00,03:14:00,00:00:00,41.00,519053952.0,43328348.0
16941,967 (VDG-43-S),2025-01-02,10:43:00,11:36:00,12:17:00,61.00,00:53:00,00:41:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,05:29:00,01:33:00,03:55:00,00:00:00,102.00,519053952.0,43328348.0
16942,967 (VDG-43-S),2025-01-02,12:17:00,12:58:00,14:51:00,27.30,00:40:00,01:52:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,08:02:00,02:14:00,05:47:00,00:00:00,129.30,519053952.0,43328348.0
16943,967 (VDG-43-S),2025-01-02,14:51:00,15:06:00,06:55:00,3.70,00:15:00,15:49:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,08:17:00,02:29:00,05:47:00,08:17:00,133.00,519053952.0,43328348.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21738,1775 (V-11-GGL),2025-01-31,07:35:00,07:41:00,08:05:00,1.37,00:05:00,00:24:00,"Groen Van Prinstererweg 38, Dordrecht",NaN,...,Dordrecht,NaN,00:00:00,02:22:00,00:49:00,01:33:00,00:00:00,42.95,51791194.0,46664807.0
21739,1775 (V-11-GGL),2025-01-31,08:05:00,08:12:00,08:28:00,2.02,00:06:00,00:16:00,"Albert Schweitzerplaats 1, Dordrecht",NaN,...,Dordrecht,NaN,00:00:00,02:45:00,00:55:00,01:50:00,00:00:00,44.97,51792834.0,46826266.0
21740,1775 (V-11-GGL),2025-01-31,08:28:00,08:35:00,08:45:00,3.44,00:06:00,00:09:00,"Bankastraat 158, Dordrecht",NaN,...,Dordrecht,NaN,00:00:00,03:02:00,01:02:00,01:59:00,00:00:00,48.41,518080094.0,46862529.0
21741,1775 (V-11-GGL),2025-01-31,08:45:00,09:06:00,09:18:00,13.52,00:21:00,00:11:00,"Ijsvogelplein 33, Zwijndrecht",NaN,...,Zwijndrecht,NaN,00:00:00,03:35:00,01:24:00,02:11:00,00:00:00,61.93,518124186.0,46221905.0
21742,1775 (V-11-GGL),2025-01-31,09:18:00,09:23:00,09:40:00,2.28,00:04:00,00:16:00,"Plantageweg 3, Zwijndrecht",NaN,...,Zwijndrecht,NaN,00:00:00,03:57:00,01:29:00,02:28:00,03:57:00,64.21,518153146.0,46308245.0

In [4]:
df01.columns

Index(['SerialNumber', 'Date', 'StartRide', 'Start', 'Stop', 'Distance',
       'TravelTime', 'Duration', 'VisitingAddress', 'Description',
       'DriverName', 'GroupName', 'To', 'ZipCode', 'City', 'ProjectNumber',
       'Break', 'TotalTime', 'TotalTravelTime', 'TotalDuration',
       'TotalTimeMinusBreak', 'TotalDistance', 'Lat', 'Long'],
      dtype='str')

In [5]:
df01.info()

<class 'pandas.DataFrame'>
RangeIndex: 4804 entries, 16939 to 21742
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SerialNumber         4804 non-null   str
 1   Date                 4804 non-null   datetime64[us]
 2   StartRide            4804 non-null   object
 3   Start                4804 non-null   object
 4   Stop                 4804 non-null   object
 5   Distance             4804 non-null   float64
 6   TravelTime           4804 non-null   object
 7   Duration             4804 non-null   object
 8   VisitingAddress      4804 non-null   str
 9   Description          741 non-null    str
 10  DriverName           4324 non-null   str
 11  GroupName            4804 non-null   str
 12  To                   4797 non-null   object
 13  ZipCode              4794 non-null   object
 14  City                 4804 non-null   str
 15  ProjectNumber        741 non-null    float64
 16  Break                4804 non-null   object
 17  TotalTime            4804 non-null   object
 18  TotalTravelTime      4804 non-null   object
 19  TotalDuration        4804 non-null   object
 20  TotalTimeMinusBreak  4804 non-null   object
 21  TotalDistance        4804 non-null   float64
 22  Lat                  4804 non-null   float64
 23  Long                 4804 non-null   float64
dtypes: datetime64[us](1), float64(5), object(12), str(6)
memory usage: 900.9+ KB

In [6]:
# Er zijn 4804 rijen, dus moeten er zoveel waarden in een kolom staan.
# Bij Description, DriverName, Contact, Remark, To, Zipcode en ProjectNumber zijn niet compleet.
# bij Description maar 741 waarden, dus deze verwijderen want dit kan ook uit de order data gehaald worden.
# bij Contact en Remark helemaal geen waarden bekend, deze kunnen dus ook verwijderd worden.
df01.head()

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,...,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
16939,967 (VDG-43-S),2025-01-02,06:48:00,07:17:00,10:27:00,35.9,00:28:00,03:10:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,03:39:00,00:28:00,03:10:00,00:00:00,35.9,519053952.0,43328348.0
16940,967 (VDG-43-S),2025-01-02,10:27:00,10:39:00,10:43:00,5.1,00:11:00,00:03:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,03:54:00,00:40:00,03:14:00,00:00:00,41.0,519053952.0,43328348.0
16941,967 (VDG-43-S),2025-01-02,10:43:00,11:36:00,12:17:00,61.0,00:53:00,00:41:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,05:29:00,01:33:00,03:55:00,00:00:00,102.0,519053952.0,43328348.0
16942,967 (VDG-43-S),2025-01-02,12:17:00,12:58:00,14:51:00,27.3,00:40:00,01:52:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,08:02:00,02:14:00,05:47:00,00:00:00,129.3,519053952.0,43328348.0
16943,967 (VDG-43-S),2025-01-02,14:51:00,15:06:00,06:55:00,3.7,00:15:00,15:49:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,08:17:00,02:29:00,05:47:00,08:17:00,133.0,519053952.0,43328348.0

In [8]:
pd.set_option('display.max_columns', None)
df02 = df01
df02.head()

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,DriverName,GroupName,To,ZipCode,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
16939,967 (VDG-43-S),2025-01-02,06:48:00,07:17:00,10:27:00,35.9,00:28:00,03:10:00,"Produktiestraat 2, Vlaardingen",NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,Vlaardingen,NaN,00:00:00,03:39:00,00:28:00,03:10:00,00:00:00,35.9,519053952.0,43328348.0
16940,967 (VDG-43-S),2025-01-02,10:27:00,10:39:00,10:43:00,5.1,00:11:00,00:03:00,"Produktiestraat 2, Vlaardingen",NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,Vlaardingen,NaN,00:00:00,03:54:00,00:40:00,03:14:00,00:00:00,41.0,519053952.0,43328348.0
16941,967 (VDG-43-S),2025-01-02,10:43:00,11:36:00,12:17:00,61.0,00:53:00,00:41:00,"Produktiestraat 2, Vlaardingen",NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,Vlaardingen,NaN,00:00:00,05:29:00,01:33:00,03:55:00,00:00:00,102.0,519053952.0,43328348.0
16942,967 (VDG-43-S),2025-01-02,12:17:00,12:58:00,14:51:00,27.3,00:40:00,01:52:00,"Produktiestraat 2, Vlaardingen",NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,Vlaardingen,NaN,00:00:00,08:02:00,02:14:00,05:47:00,00:00:00,129.3,519053952.0,43328348.0
16943,967 (VDG-43-S),2025-01-02,14:51:00,15:06:00,06:55:00,3.7,00:15:00,15:49:00,"Produktiestraat 2, Vlaardingen",NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,Vlaardingen,NaN,00:00:00,08:17:00,02:29:00,05:47:00,08:17:00,133.0,519053952.0,43328348.0

In [9]:
df02['VisitingAddress'].unique()

<StringArray>
[       'Produktiestraat 2, Vlaardingen',
     'Douwes Dekkerlaan 14, Papendrecht',
      'Kamerlingh Onnesweg 9, Dordrecht',
        'Ijsvogelplein 104, Zwijndrecht',
       ''t Anker 101 -118 , Zwijndrecht',
              'Hoofdland 1, Zwijndrecht',
         'Munnikensteeg 26, Zwijndrecht',
        'Oosthavendijk 30, Middelharnis',
      'Delta Boulevard 13, Middelharnis',
         'Industrieweg 50, Middelharnis',
 ...
   'Burg De Zeeuwstraat 197, Numansdorp',
             'Nijhofflaan 55, Dordrecht',
        'Ijsvogelplein 310, Zwijndrecht',
 'Winston Churchilllaan 25, Spijkenisse',
                     'Tweespan 7, Rhoon',
         'Bernhardstraat 25, Numansdorp',
             'Hoofdland 29, Zwijndrecht',
             'Judopad 2, Hellevoetsluis',
              'Beukenlaan 6, Numansdorp',
     'Polluxstraat 12, Pernis Rotterdam']
Length: 1185, dtype: str

In [10]:
df02["adres"] = df02["VisitingAddress"].str.split(",").str[0]

In [11]:
df03 = df02.drop(columns=['VisitingAddress'])

In [12]:
df03 = df03.rename(columns={
    "ZipCode": "postcode",
    "City": "plaats",
    "Lat": "latitude",
    "Long": "longitude"
})

In [13]:
df03["adres"] = df03["adres"].str.strip().str.lower()
df03["postcode"] = df03["postcode"].str.strip().str.upper()
df03["plaats"] = df03["plaats"].str.strip().str.lower()

In [14]:
df03

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,Description,DriverName,GroupName,To,postcode,plaats,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,latitude,longitude,adres
16939,967 (VDG-43-S),2025-01-02,06:48:00,07:17:00,10:27:00,35.90,00:28:00,03:10:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,vlaardingen,NaN,00:00:00,03:39:00,00:28:00,03:10:00,00:00:00,35.90,519053952.0,43328348.0,produktiestraat 2
16940,967 (VDG-43-S),2025-01-02,10:27:00,10:39:00,10:43:00,5.10,00:11:00,00:03:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,vlaardingen,NaN,00:00:00,03:54:00,00:40:00,03:14:00,00:00:00,41.00,519053952.0,43328348.0,produktiestraat 2
16941,967 (VDG-43-S),2025-01-02,10:43:00,11:36:00,12:17:00,61.00,00:53:00,00:41:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,vlaardingen,NaN,00:00:00,05:29:00,01:33:00,03:55:00,00:00:00,102.00,519053952.0,43328348.0,produktiestraat 2
16942,967 (VDG-43-S),2025-01-02,12:17:00,12:58:00,14:51:00,27.30,00:40:00,01:52:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,vlaardingen,NaN,00:00:00,08:02:00,02:14:00,05:47:00,00:00:00,129.30,519053952.0,43328348.0,produktiestraat 2
16943,967 (VDG-43-S),2025-01-02,14:51:00,15:06:00,06:55:00,3.70,00:15:00,15:49:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,vlaardingen,NaN,00:00:00,08:17:00,02:29:00,05:47:00,08:17:00,133.00,519053952.0,43328348.0,produktiestraat 2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21738,1775 (V-11-GGL),2025-01-31,07:35:00,07:41:00,08:05:00,1.37,00:05:00,00:24:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Groen Van Prinstererweg 38,3317SP,dordrecht,NaN,00:00:00,02:22:00,00:49:00,01:33:00,00:00:00,42.95,51791194.0,46664807.0,groen van prinstererweg 38
21739,1775 (V-11-GGL),2025-01-31,08:05:00,08:12:00,08:28:00,2.02,00:06:00,00:16:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Albert Schweitzerplaats 1,3318AS,dordrecht,NaN,00:00:00,02:45:00,00:55:00,01:50:00,00:00:00,44.97,51792834.0,46826266.0,albert schweitzerplaats 1
21740,1775 (V-11-GGL),2025-01-31,08:28:00,08:35:00,08:45:00,3.44,00:06:00,00:09:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Bankastraat 158,3312GT,dordrecht,NaN,00:00:00,03:02:00,01:02:00,01:59:00,00:00:00,48.41,518080094.0,46862529.0,bankastraat 158
21741,1775 (V-11-GGL),2025-01-31,08:45:00,09:06:00,09:18:00,13.52,00:21:00,00:11:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Ijsvogelplein 33,3334XB,zwijndrecht,NaN,00:00:00,03:35:00,01:24:00,02:11:00,00:00:00,61.93,518124186.0,46221905.0,ijsvogelplein 33
21742,1775 (V-11-GGL),2025-01-31,09:18:00,09:23:00,09:40:00,2.28,00:04:00,00:16:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Plantageweg 3,3333GZ,zwijndrecht,NaN,00:00:00,03:57:00,01:29:00,02:28:00,03:57:00,64.21,518153146.0,46308245.0,plantageweg 3

In [15]:
df03["postcode"] = (
    df03["postcode"]
    .str.strip()
    .str.upper()
    .str.replace(" ", "", regex=False)
)

In [16]:
df03

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,Description,DriverName,GroupName,To,postcode,plaats,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,latitude,longitude,adres
16939,967 (VDG-43-S),2025-01-02,06:48:00,07:17:00,10:27:00,35.90,00:28:00,03:10:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,vlaardingen,NaN,00:00:00,03:39:00,00:28:00,03:10:00,00:00:00,35.90,519053952.0,43328348.0,produktiestraat 2
16940,967 (VDG-43-S),2025-01-02,10:27:00,10:39:00,10:43:00,5.10,00:11:00,00:03:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,vlaardingen,NaN,00:00:00,03:54:00,00:40:00,03:14:00,00:00:00,41.00,519053952.0,43328348.0,produktiestraat 2
16941,967 (VDG-43-S),2025-01-02,10:43:00,11:36:00,12:17:00,61.00,00:53:00,00:41:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,vlaardingen,NaN,00:00:00,05:29:00,01:33:00,03:55:00,00:00:00,102.00,519053952.0,43328348.0,produktiestraat 2
16942,967 (VDG-43-S),2025-01-02,12:17:00,12:58:00,14:51:00,27.30,00:40:00,01:52:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,vlaardingen,NaN,00:00:00,08:02:00,02:14:00,05:47:00,00:00:00,129.30,519053952.0,43328348.0,produktiestraat 2
16943,967 (VDG-43-S),2025-01-02,14:51:00,15:06:00,06:55:00,3.70,00:15:00,15:49:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133ES,vlaardingen,NaN,00:00:00,08:17:00,02:29:00,05:47:00,08:17:00,133.00,519053952.0,43328348.0,produktiestraat 2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21738,1775 (V-11-GGL),2025-01-31,07:35:00,07:41:00,08:05:00,1.37,00:05:00,00:24:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Groen Van Prinstererweg 38,3317SP,dordrecht,NaN,00:00:00,02:22:00,00:49:00,01:33:00,00:00:00,42.95,51791194.0,46664807.0,groen van prinstererweg 38
21739,1775 (V-11-GGL),2025-01-31,08:05:00,08:12:00,08:28:00,2.02,00:06:00,00:16:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Albert Schweitzerplaats 1,3318AS,dordrecht,NaN,00:00:00,02:45:00,00:55:00,01:50:00,00:00:00,44.97,51792834.0,46826266.0,albert schweitzerplaats 1
21740,1775 (V-11-GGL),2025-01-31,08:28:00,08:35:00,08:45:00,3.44,00:06:00,00:09:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Bankastraat 158,3312GT,dordrecht,NaN,00:00:00,03:02:00,01:02:00,01:59:00,00:00:00,48.41,518080094.0,46862529.0,bankastraat 158
21741,1775 (V-11-GGL),2025-01-31,08:45:00,09:06:00,09:18:00,13.52,00:21:00,00:11:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Ijsvogelplein 33,3334XB,zwijndrecht,NaN,00:00:00,03:35:00,01:24:00,02:11:00,00:00:00,61.93,518124186.0,46221905.0,ijsvogelplein 33
21742,1775 (V-11-GGL),2025-01-31,09:18:00,09:23:00,09:40:00,2.28,00:04:00,00:16:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Plantageweg 3,3333GZ,zwijndrecht,NaN,00:00:00,03:57:00,01:29:00,02:28:00,03:57:00,64.21,518153146.0,46308245.0,plantageweg 3

In [17]:
df03["postcode"] = df03["postcode"].str.replace(
    r"(\d{4})([A-Z]{2})", r"\1 \2", regex=True
)

In [18]:
df03.info()

<class 'pandas.DataFrame'>
RangeIndex: 4804 entries, 16939 to 21742
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SerialNumber         4804 non-null   str
 1   Date                 4804 non-null   datetime64[us]
 2   StartRide            4804 non-null   object
 3   Start                4804 non-null   object
 4   Stop                 4804 non-null   object
 5   Distance             4804 non-null   float64
 6   TravelTime           4804 non-null   object
 7   Duration             4804 non-null   object
 8   Description          741 non-null    str
 9   DriverName           4324 non-null   str
 10  GroupName            4804 non-null   str
 11  To                   4797 non-null   object
 12  postcode             4794 non-null   object
 13  plaats               4804 non-null   str
 14  ProjectNumber        741 non-null    float64
 15  Break                4804 non-null   object
 16  TotalTime            4804 non-null   object
 17  TotalTravelTime      4804 non-null   object
 18  TotalDuration        4804 non-null   object
 19  TotalTimeMinusBreak  4804 non-null   object
 20  TotalDistance        4804 non-null   float64
 21  latitude             4804 non-null   float64
 22  longitude            4804 non-null   float64
 23  adres                4804 non-null   object
dtypes: datetime64[us](1), float64(5), object(13), str(5)
memory usage: 900.9+ KB

In [19]:
df03[df03["postcode"].isna()]

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,Description,DriverName,GroupName,To,postcode,plaats,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,latitude,longitude,adres
17369,1040 (VFT-36-H),2025-01-15,14:07:00,14:17:00,14:36:00,6.84,00:09:00,00:19:00,NaN,Tjerk Polderman,19210700 Dordrecht - BBT,Rijksweg A2 Westzijde 3,NaN,breukelen,NaN,00:00:00,06:28:00,01:53:00,04:34:00,00:00:00,120.89,521426316.0,5000235.0,rijksweg a2 westzijde 3
19048,1345 (VRP-40-X),2025-01-07,14:44:00,14:46:00,14:56:00,0.30,00:02:00,00:09:00,NaN,Bas van Steen,19210700 Dordrecht - BBT,Amphia Ziekenhuis Molengracht 1,NaN,breda,NaN,00:00:00,07:12:00,01:52:00,05:20:00,00:00:00,88.00,515824766.0,47987366.0,amphia ziekenhuis molengracht 1
19990,1597 (VZT-42-V),2025-01-15,06:44:00,06:58:00,07:05:00,0.00,00:13:00,00:07:00,NaN,Sheamie Gerard,19210700 Dordrecht - BBT,NaN,NaN,?,NaN,00:00:00,00:20:00,00:13:00,00:07:00,00:00:00,0.00,0.0,0.0,
19991,1597 (VZT-42-V),2025-01-15,07:05:00,07:06:00,07:21:00,0.00,00:00:00,00:14:00,NaN,Sheamie Gerard,19210700 Dordrecht - BBT,NaN,NaN,?,NaN,00:00:00,00:36:00,00:14:00,00:21:00,00:00:00,0.00,0.0,0.0,
19995,1597 (VZT-42-V),2025-01-16,06:37:00,06:49:00,06:57:00,0.00,00:11:00,00:08:00,NaN,Sheamie Gerard,19210700 Dordrecht - BBT,NaN,NaN,?,NaN,00:00:00,00:20:00,00:11:00,00:08:00,00:00:00,0.00,0.0,0.0,
19996,1597 (VZT-42-V),2025-01-16,06:57:00,06:58:00,07:31:00,0.00,00:00:00,00:33:00,NaN,Sheamie Gerard,19210700 Dordrecht - BBT,NaN,NaN,?,NaN,00:00:00,00:54:00,00:12:00,00:41:00,00:00:00,0.00,0.0,0.0,
20039,1597 (VZT-42-V),2025-01-21,06:12:00,06:24:00,07:02:00,0.00,00:11:00,00:38:00,NaN,Sheamie Gerard,19210700 Dordrecht - BBT,NaN,NaN,?,NaN,00:00:00,00:49:00,00:11:00,00:38:00,00:00:00,0.00,0.0,0.0,
20108,1597 (VZT-42-V),2025-01-28,06:13:00,06:25:00,07:04:00,0.00,00:11:00,00:39:00,NaN,Sheamie Gerard,19210700 Dordrecht - BBT,NaN,NaN,?,NaN,00:00:00,00:50:00,00:11:00,00:39:00,00:00:00,0.00,0.0,0.0,
20972,1702 (V-19-FXR),2025-01-16,11:25:00,11:27:00,11:57:00,0.63,00:02:00,00:29:00,NaN,Frido Wijnen,19210700 Dordrecht - BBT,Amphia Ziekenhuis Molengracht 1,NaN,breda,NaN,00:00:00,02:48:00,00:45:00,02:03:00,00:00:00,34.24,515827928.0,47981552.0,amphia ziekenhuis molengracht 1
21158,1705 (V-18-FXR),2025-01-10,16:05:00,16:05:00,08:04:00,0.00,00:00:00,"2 days, 15:58:00",NaN,Marcus Dekker,19210700 Dordrecht - BBT,NaN,NaN,?,NaN,00:00:00,08:39:00,04:44:00,03:54:00,08:39:00,263.01,0.0,0.0,

In [20]:
df03.loc[[19048, 20972], "postcode"] = "4818 CK"
df03.loc[[17369], "postcode"] = "3607 NN"

In [21]:
df04 = df03.dropna(subset=["postcode"])

In [22]:
df04

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,Description,DriverName,GroupName,To,postcode,plaats,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,latitude,longitude,adres
16939,967 (VDG-43-S),2025-01-02,06:48:00,07:17:00,10:27:00,35.90,00:28:00,03:10:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133 ES,vlaardingen,NaN,00:00:00,03:39:00,00:28:00,03:10:00,00:00:00,35.90,519053952.0,43328348.0,produktiestraat 2
16940,967 (VDG-43-S),2025-01-02,10:27:00,10:39:00,10:43:00,5.10,00:11:00,00:03:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133 ES,vlaardingen,NaN,00:00:00,03:54:00,00:40:00,03:14:00,00:00:00,41.00,519053952.0,43328348.0,produktiestraat 2
16941,967 (VDG-43-S),2025-01-02,10:43:00,11:36:00,12:17:00,61.00,00:53:00,00:41:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133 ES,vlaardingen,NaN,00:00:00,05:29:00,01:33:00,03:55:00,00:00:00,102.00,519053952.0,43328348.0,produktiestraat 2
16942,967 (VDG-43-S),2025-01-02,12:17:00,12:58:00,14:51:00,27.30,00:40:00,01:52:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133 ES,vlaardingen,NaN,00:00:00,08:02:00,02:14:00,05:47:00,00:00:00,129.30,519053952.0,43328348.0,produktiestraat 2
16943,967 (VDG-43-S),2025-01-02,14:51:00,15:06:00,06:55:00,3.70,00:15:00,15:49:00,NaN,NaN,19210700 Dordrecht - BBT,Produktiestraat 2,3133 ES,vlaardingen,NaN,00:00:00,08:17:00,02:29:00,05:47:00,08:17:00,133.00,519053952.0,43328348.0,produktiestraat 2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21738,1775 (V-11-GGL),2025-01-31,07:35:00,07:41:00,08:05:00,1.37,00:05:00,00:24:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Groen Van Prinstererweg 38,3317 SP,dordrecht,NaN,00:00:00,02:22:00,00:49:00,01:33:00,00:00:00,42.95,51791194.0,46664807.0,groen van prinstererweg 38
21739,1775 (V-11-GGL),2025-01-31,08:05:00,08:12:00,08:28:00,2.02,00:06:00,00:16:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Albert Schweitzerplaats 1,3318 AS,dordrecht,NaN,00:00:00,02:45:00,00:55:00,01:50:00,00:00:00,44.97,51792834.0,46826266.0,albert schweitzerplaats 1
21740,1775 (V-11-GGL),2025-01-31,08:28:00,08:35:00,08:45:00,3.44,00:06:00,00:09:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Bankastraat 158,3312 GT,dordrecht,NaN,00:00:00,03:02:00,01:02:00,01:59:00,00:00:00,48.41,518080094.0,46862529.0,bankastraat 158
21741,1775 (V-11-GGL),2025-01-31,08:45:00,09:06:00,09:18:00,13.52,00:21:00,00:11:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Ijsvogelplein 33,3334 XB,zwijndrecht,NaN,00:00:00,03:35:00,01:24:00,02:11:00,00:00:00,61.93,518124186.0,46221905.0,ijsvogelplein 33
21742,1775 (V-11-GGL),2025-01-31,09:18:00,09:23:00,09:40:00,2.28,00:04:00,00:16:00,NaN,Joost van der Linden,19210700 Dordrecht - BBT,Plantageweg 3,3333 GZ,zwijndrecht,NaN,00:00:00,03:57:00,01:29:00,02:28:00,03:57:00,64.21,518153146.0,46308245.0,plantageweg 3

In [23]:
df04.info()

<class 'pandas.DataFrame'>
Index: 4797 entries, 16939 to 21742
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SerialNumber         4797 non-null   str
 1   Date                 4797 non-null   datetime64[us]
 2   StartRide            4797 non-null   object
 3   Start                4797 non-null   object
 4   Stop                 4797 non-null   object
 5   Distance             4797 non-null   float64
 6   TravelTime           4797 non-null   object
 7   Duration             4797 non-null   object
 8   Description          741 non-null    str
 9   DriverName           4317 non-null   str
 10  GroupName            4797 non-null   str
 11  To                   4797 non-null   object
 12  postcode             4797 non-null   object
 13  plaats               4797 non-null   str
 14  ProjectNumber        741 non-null    float64
 15  Break                4797 non-null   object
 16  TotalTime            4797 non-null   object
 17  TotalTravelTime      4797 non-null   object
 18  TotalDuration        4797 non-null   object
 19  TotalTimeMinusBreak  4797 non-null   object
 20  TotalDistance        4797 non-null   float64
 21  latitude             4797 non-null   float64
 22  longitude            4797 non-null   float64
 23  adres                4797 non-null   object
dtypes: datetime64[us](1), float64(5), object(13), str(5)
memory usage: 936.9+ KB

In [26]:
df05 = df04.drop(columns=['Description', 'SerialNumber', 'Date', 'StartRide', 'Start', 'Stop', 'Distance', 'TravelTime', 'Duration', 'GroupName', 'To', 'Break', 'TotalTime', 'TotalTravelTime', 'TotalDuration', 'TotalTimeMinusBreak', 'TotalDistance', 'ProjectNumber'])

In [27]:
df05

,DriverName,postcode,plaats,latitude,longitude,adres
16939,NaN,3133 ES,vlaardingen,519053952.0,43328348.0,produktiestraat 2
16940,NaN,3133 ES,vlaardingen,519053952.0,43328348.0,produktiestraat 2
16941,NaN,3133 ES,vlaardingen,519053952.0,43328348.0,produktiestraat 2
16942,NaN,3133 ES,vlaardingen,519053952.0,43328348.0,produktiestraat 2
16943,NaN,3133 ES,vlaardingen,519053952.0,43328348.0,produktiestraat 2
...,...,...,...,...,...,...
21738,Joost van der Linden,3317 SP,dordrecht,51791194.0,46664807.0,groen van prinstererweg 38
21739,Joost van der Linden,3318 AS,dordrecht,51792834.0,46826266.0,albert schweitzerplaats 1
21740,Joost van der Linden,3312 GT,dordrecht,518080094.0,46862529.0,bankastraat 158
21741,Joost van der Linden,3334 XB,zwijndrecht,518124186.0,46221905.0,ijsvogelplein 33
21742,Joost van der Linden,3333 GZ,zwijndrecht,518153146.0,46308245.0,plantageweg 3

In [28]:
# van 3 drivers de adressen bekijken, anders 1200 adressen/knopen en dat is wel veel.
df05["DriverName"].unique()

<StringArray>
[                        nan,         'Aart van der Wulp',
 'Auto Mertens Auto Mertens',           'Tom Barendrecht',
           'Tjerk Polderman',            'Sandro Glasius',
              'Liza de Gier',                'Ronald Kok',
            'Marcel Koevoet',  'Cornelis van der Giessen',
     'Geertjan van der Wulp',              'Roy Albersen',
              'Robin Kovács',               'Kees Kuiper',
                'Peter Bood',           'Joost Oerlemans',
             'Onno Havelaar',           'Enzo van Dongen',
                'Erik-Jan 3',             'Bas van Steen',
                'Ron Timmer',       'Peter van den Bosch',
             'Hans de Groot',              'Frido Wijnen',
            'Sheamie Gerard',            'Frans Boshoven',
       'René Hoppenbrouwers',            'Barend de Jong',
             'Ronald Griend',             'Marcus Dekker',
               'Alin Apetri',      'Joost van der Linden']
Length: 32, dtype: str

In [29]:
df06 = df05

In [30]:
df07 = (
    df06
    .sort_values(by=["adres", "postcode", "plaats"])  # optioneel maar netjes
    .groupby(["adres", "plaats"], as_index=False)
    .first()
)

In [31]:
df07

,adres,plaats,DriverName,postcode,latitude,longitude
0,'s-gravenpolderseweg,kloetinge,Ronald Griend,4462 RA,514852865.0,3908449.0
1,'s-gravenpolderseweg 63,goes,Tom Barendrecht,4462 RA,51481875.0,39016683.0
2,'s-gravenweg 254,nieuwerkerk ad ijssel,Joost Oerlemans,2911 CL,519636651.0,46228455.0
3,'s-gravenweg 322,capelle aan den ijssel,Joost Oerlemans,2905 LB,519404973.0,45939131.0
4,'s-gravenweg 355,capelle aan den ijssel,Robin Kovács,2905 LC,519440072.0,45988859.0
...,...,...,...,...,...,...
1179,zuiderdreef 157,bergen op zoom,Aart van der Wulp,4616 AJ,51480725.0,42891195.0
1180,zuiderdreef 30,bergen op zoom,Geertjan van der Wulp,4616 AJ,51477445.0,42904266.0
1181,zuidpad,hendrik-ido-ambacht,Cornelis van der Giessen,2986 SH,518556312.0,46278381.0
1182,zwaardleliestraat 30,rotterdam,Marcel Koevoet,3053 VX,519563953.0,44713934.0
1183,zwaluwenlaan 36,rhoon,Sandro Glasius,3161 TZ,51852915.0,4423475.0

In [32]:
df07['adres'].unique()

<StringArray>
[   ''s-gravenpolderseweg', ''s-gravenpolderseweg 63',
        ''s-gravenweg 254',        ''s-gravenweg 322',
        ''s-gravenweg 355',        ''s-gravenweg 382',
       ''t anker 101 -118',              ''t getij 2',
             ''t getij 40',               ''t scheld',
 ...
              'zoommeer 7',          'zoutmanplein 6',
          'zuidendijk 465',          'zuidendijk 467',
           'zuidendijk 89',         'zuiderdreef 157',
          'zuiderdreef 30',                 'zuidpad',
    'zwaardleliestraat 30',         'zwaluwenlaan 36']
Length: 1182, dtype: str

In [33]:
df07[df07.duplicated(subset=["adres"], keep=False)].sort_values("adres")

,adres,plaats,DriverName,postcode,latitude,longitude
453,industrieweg 7,papendrecht,Tjerk Polderman,3351 LB,5182707.0,467453.0
454,industrieweg 7,sliedrecht,Cornelis van der Giessen,3361 HJ,518188837.0,47681652.0
864,rijksweg,nieuwerkerk,Tom Barendrecht,4306 BE,516460533.0,39986833.0
865,rijksweg,roosendaal,Marcus Dekker,4703 SB,515105467.0,44115558.0

In [34]:
df07.info()

<class 'pandas.DataFrame'>
RangeIndex: 1184 entries, 0 to 1183
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   adres       1184 non-null   str
 1   plaats      1184 non-null   str
 2   DriverName  1172 non-null   str
 3   postcode    1184 non-null   object
 4   latitude    1184 non-null   float64
 5   longitude   1184 non-null   float64
dtypes: float64(2), object(1), str(3)
memory usage: 55.6+ KB

In [35]:
# depot adres eruit halen
df08 = df07[~(
    (df07["adres"] == "kamerlingh onnesweg 9") &
    (df07["postcode"] == "3316 GK")
)]
df08

,adres,plaats,DriverName,postcode,latitude,longitude
0,'s-gravenpolderseweg,kloetinge,Ronald Griend,4462 RA,514852865.0,3908449.0
1,'s-gravenpolderseweg 63,goes,Tom Barendrecht,4462 RA,51481875.0,39016683.0
2,'s-gravenweg 254,nieuwerkerk ad ijssel,Joost Oerlemans,2911 CL,519636651.0,46228455.0
3,'s-gravenweg 322,capelle aan den ijssel,Joost Oerlemans,2905 LB,519404973.0,45939131.0
4,'s-gravenweg 355,capelle aan den ijssel,Robin Kovács,2905 LC,519440072.0,45988859.0
...,...,...,...,...,...,...
1179,zuiderdreef 157,bergen op zoom,Aart van der Wulp,4616 AJ,51480725.0,42891195.0
1180,zuiderdreef 30,bergen op zoom,Geertjan van der Wulp,4616 AJ,51477445.0,42904266.0
1181,zuidpad,hendrik-ido-ambacht,Cornelis van der Giessen,2986 SH,518556312.0,46278381.0
1182,zwaardleliestraat 30,rotterdam,Marcel Koevoet,3053 VX,519563953.0,44713934.0
1183,zwaluwenlaan 36,rhoon,Sandro Glasius,3161 TZ,51852915.0,4423475.0

In [36]:
df09 = df08.reset_index(drop=True)
df09["node_id"] = df09.index
df09

,adres,plaats,DriverName,postcode,latitude,longitude,node_id
0,'s-gravenpolderseweg,kloetinge,Ronald Griend,4462 RA,514852865.0,3908449.0,0
1,'s-gravenpolderseweg 63,goes,Tom Barendrecht,4462 RA,51481875.0,39016683.0,1
2,'s-gravenweg 254,nieuwerkerk ad ijssel,Joost Oerlemans,2911 CL,519636651.0,46228455.0,2
3,'s-gravenweg 322,capelle aan den ijssel,Joost Oerlemans,2905 LB,519404973.0,45939131.0,3
4,'s-gravenweg 355,capelle aan den ijssel,Robin Kovács,2905 LC,519440072.0,45988859.0,4
...,...,...,...,...,...,...,...
1178,zuiderdreef 157,bergen op zoom,Aart van der Wulp,4616 AJ,51480725.0,42891195.0,1178
1179,zuiderdreef 30,bergen op zoom,Geertjan van der Wulp,4616 AJ,51477445.0,42904266.0,1179
1180,zuidpad,hendrik-ido-ambacht,Cornelis van der Giessen,2986 SH,518556312.0,46278381.0,1180
1181,zwaardleliestraat 30,rotterdam,Marcel Koevoet,3053 VX,519563953.0,44713934.0,1181
1182,zwaluwenlaan 36,rhoon,Sandro Glasius,3161 TZ,51852915.0,4423475.0,1182

In [37]:
df10 = df09.drop(columns=['DriverName'])
df10

,adres,plaats,postcode,latitude,longitude,node_id
0,'s-gravenpolderseweg,kloetinge,4462 RA,514852865.0,3908449.0,0
1,'s-gravenpolderseweg 63,goes,4462 RA,51481875.0,39016683.0,1
2,'s-gravenweg 254,nieuwerkerk ad ijssel,2911 CL,519636651.0,46228455.0,2
3,'s-gravenweg 322,capelle aan den ijssel,2905 LB,519404973.0,45939131.0,3
4,'s-gravenweg 355,capelle aan den ijssel,2905 LC,519440072.0,45988859.0,4
...,...,...,...,...,...,...
1178,zuiderdreef 157,bergen op zoom,4616 AJ,51480725.0,42891195.0,1178
1179,zuiderdreef 30,bergen op zoom,4616 AJ,51477445.0,42904266.0,1179
1180,zuidpad,hendrik-ido-ambacht,2986 SH,518556312.0,46278381.0,1180
1181,zwaardleliestraat 30,rotterdam,3053 VX,519563953.0,44713934.0,1181
1182,zwaluwenlaan 36,rhoon,3161 TZ,51852915.0,4423475.0,1182

In [38]:
# orders linken aan de knopen

In [39]:
df20 = pd.read_excel("Serviceorders - 01-01-2025-31-01-2025.xlsx")
df20.head()

,Responsdatum,Postcode,Plaats,Punten,Zorginstellingnaam,Adres,Vaste monteur
0,2023-12-15,4301 NW,ZIERIKZEE,15,Allevo - Zierik7,Emil Sandstromweg 2,Tom B
1,2023-12-29,2643 JJ,PIJNACKER,24,Pieter van Foreest - Weidevogelhof,Raaigras 102,Cornelis van der G
2,2024-01-15,4382 LJ,VLISSINGEN,9,S Heeren Loo - Nieuwe Zuidbeekseweg,Stadhuisplein 22,Tom B
3,2024-04-25,2685 SZ,POELDIJK,3,Middin - Westland Eliasdreef,Eliasdreef 9,Cornelis van der G
4,2024-07-19,2612 VC,DELFT,3,Pieter van Foreest - Bieslandhof,Beukenlaan 2,Cornelis van der G

In [40]:
df23 = df20.rename(columns={
    "Postcode": "postcode",
    "Plaats": "plaats",
    "Adres": "adres",
})

In [41]:
df23["adres"] = df23["adres"].str.strip().str.lower()
df23["postcode"] = df23["postcode"].str.strip().str.upper()
df23["plaats"] = df23["plaats"].str.strip().str.lower()

In [42]:
df23["postcode"] = (
    df23["postcode"]
    .str.strip()
    .str.upper()
    .str.replace(" ", "", regex=False)
)

In [43]:
df23["postcode"] = df23["postcode"].str.replace(
    r"(\d{4})([A-Z]{2})", r"\1 \2", regex=True
)

In [44]:
df23

,Responsdatum,postcode,plaats,Punten,Zorginstellingnaam,adres,Vaste monteur
0,2023-12-15,4301 NW,zierikzee,15,Allevo - Zierik7,emil sandstromweg 2,Tom B
1,2023-12-29,2643 JJ,pijnacker,24,Pieter van Foreest - Weidevogelhof,raaigras 102,Cornelis van der G
2,2024-01-15,4382 LJ,vlissingen,9,S Heeren Loo - Nieuwe Zuidbeekseweg,stadhuisplein 22,Tom B
3,2024-04-25,2685 SZ,poeldijk,3,Middin - Westland Eliasdreef,eliasdreef 9,Cornelis van der G
4,2024-07-19,2612 VC,delft,3,Pieter van Foreest - Bieslandhof,beukenlaan 2,Cornelis van der G
...,...,...,...,...,...,...,...
2138,2025-02-17,3014 GC,rotterdam,0,Laurens - Antonius Binnenweg,nieuwe binnenweg 33,Jeremy R
2139,2025-02-17,4614 CH,bergen op zoom,0,S&L Zorg - Lambertijnenhof,lambertijnenhof 200,Aart van der W
2140,2025-02-17,4614 CH,bergen op zoom,0,S&L Zorg - Lambertijnenhof,lambertijnenhof 200,Aart van der W
2141,2025-02-11,5101 TB,dongen,0,GGZ Breburg - Dongen,heuvelstraat 33,René H
2142,2025-02-24,3371 PR,hardinxveld giessendam,0,Waardeburgh - Pedaja,claversweer 1 k301,Cornelis van der G

In [ ]:
df24 = df23[["adres", "plaats", "postcode", "Punten", "Zorginstellingnaam", 'Responsdatum', "Vaste monteur"]]
df24

,adres,plaats,postcode,Punten,Zorginstellingnaam,Responsdatum,Vaste monteur
0,emil sandstromweg 2,zierikzee,4301 NW,15,Allevo - Zierik7,2023-12-15,Tom B
1,raaigras 102,pijnacker,2643 JJ,24,Pieter van Foreest - Weidevogelhof,2023-12-29,Cornelis van der G
2,stadhuisplein 22,vlissingen,4382 LJ,9,S Heeren Loo - Nieuwe Zuidbeekseweg,2024-01-15,Tom B
3,eliasdreef 9,poeldijk,2685 SZ,3,Middin - Westland Eliasdreef,2024-04-25,Cornelis van der G
4,beukenlaan 2,delft,2612 VC,3,Pieter van Foreest - Bieslandhof,2024-07-19,Cornelis van der G
...,...,...,...,...,...,...,...
2138,nieuwe binnenweg 33,rotterdam,3014 GC,0,Laurens - Antonius Binnenweg,2025-02-17,Jeremy R
2139,lambertijnenhof 200,bergen op zoom,4614 CH,0,S&L Zorg - Lambertijnenhof,2025-02-17,Aart van der W
2140,lambertijnenhof 200,bergen op zoom,4614 CH,0,S&L Zorg - Lambertijnenhof,2025-02-17,Aart van der W
2141,heuvelstraat 33,dongen,5101 TB,0,GGZ Breburg - Dongen,2025-02-11,René H
2142,claversweer 1 k301,hardinxveld giessendam,3371 PR,0,Waardeburgh - Pedaja,2025-02-24,Cornelis van der G

In [85]:
df25 = df24.rename(columns={
    "Responsdatum": "datum",
})

In [86]:
df25

,adres,plaats,postcode,Punten,Zorginstellingnaam,datum,Vaste monteur
0,emil sandstromweg 2,zierikzee,4301 NW,15,Allevo - Zierik7,2023-12-15,Tom B
1,raaigras 102,pijnacker,2643 JJ,24,Pieter van Foreest - Weidevogelhof,2023-12-29,Cornelis van der G
2,stadhuisplein 22,vlissingen,4382 LJ,9,S Heeren Loo - Nieuwe Zuidbeekseweg,2024-01-15,Tom B
3,eliasdreef 9,poeldijk,2685 SZ,3,Middin - Westland Eliasdreef,2024-04-25,Cornelis van der G
4,beukenlaan 2,delft,2612 VC,3,Pieter van Foreest - Bieslandhof,2024-07-19,Cornelis van der G
...,...,...,...,...,...,...,...
2138,nieuwe binnenweg 33,rotterdam,3014 GC,0,Laurens - Antonius Binnenweg,2025-02-17,Jeremy R
2139,lambertijnenhof 200,bergen op zoom,4614 CH,0,S&L Zorg - Lambertijnenhof,2025-02-17,Aart van der W
2140,lambertijnenhof 200,bergen op zoom,4614 CH,0,S&L Zorg - Lambertijnenhof,2025-02-17,Aart van der W
2141,heuvelstraat 33,dongen,5101 TB,0,GGZ Breburg - Dongen,2025-02-11,René H
2142,claversweer 1 k301,hardinxveld giessendam,3371 PR,0,Waardeburgh - Pedaja,2025-02-24,Cornelis van der G

In [53]:
df30 = pd.read_excel("Verkooporders - 01-01-2025-31-01-2025.xlsx")
df30

,Plandatum,Contractdatum,Serienr.,Punten,Resource(groep)nr.,Postcode,Plaats,Zorginstellingnaam
0,2025-01-02,2025-01-13,5526HR0514,4,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland
1,2025-01-02,2025-01-13,5526HR0514,4,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland
2,2025-01-02,2025-01-08,ZKS02555,4,NaN,3141 CJ,MAASSLUIS,Argos - De Tweemaster
3,2025-01-02,2025-01-09,ACH0124955,4,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof
4,2025-01-02,2025-01-09,AGIS51556,4,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof
...,...,...,...,...,...,...,...,...
632,2025-01-31,2025-02-04,55253031,4,MARCUS,4431 DR,'S-GRAVENPOLDER,Siloah - De Beukelaar
633,2025-01-31,2024-12-31,VGZFIE-000449,4,SANDRO,5101 TB,DONGEN,GGZ Breburg - Dongen
634,2025-01-31,2025-02-04,ACH0113971,4,JOERLEMA,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof
635,2025-01-31,2024-12-31,VGZFIE-000449,4,NaN,5101 TB,DONGEN,GGZ Breburg - Dongen
636,2025-01-31,2025-02-04,ACH0113971,4,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof

In [54]:
# adres maken, kijken of zorginstelling in serviceorders ook in verkooporders staat, want dan kunnen we deze aan elkaar linken.
df30[df30["Zorginstellingnaam"].isin(df24["Zorginstellingnaam"])]

,Plandatum,Contractdatum,Serienr.,Punten,Resource(groep)nr.,Postcode,Plaats,Zorginstellingnaam
0,2025-01-02,2025-01-13,5526HR0514,4,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland
1,2025-01-02,2025-01-13,5526HR0514,4,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland
2,2025-01-02,2025-01-08,ZKS02555,4,NaN,3141 CJ,MAASSLUIS,Argos - De Tweemaster
3,2025-01-02,2025-01-09,ACH0124955,4,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof
4,2025-01-02,2025-01-09,AGIS51556,4,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof
...,...,...,...,...,...,...,...,...
631,2025-01-31,2025-02-03,VGZ003608,4,GEERT,4201 KW,GORINCHEM,Rivas - Steijndeld
633,2025-01-31,2024-12-31,VGZFIE-000449,4,SANDRO,5101 TB,DONGEN,GGZ Breburg - Dongen
634,2025-01-31,2025-02-04,ACH0113971,4,JOERLEMA,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof
635,2025-01-31,2024-12-31,VGZFIE-000449,4,NaN,5101 TB,DONGEN,GGZ Breburg - Dongen
636,2025-01-31,2025-02-04,ACH0113971,4,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof

In [56]:
df24_unique = (
    df24.groupby("Zorginstellingnaam", as_index=False)
    .first()[["Zorginstellingnaam", "adres"]]
)

df30 = df30.merge(
    df24_unique,
    on="Zorginstellingnaam",
    how="left"
)
df30

,Plandatum,Contractdatum,Serienr.,Punten,Resource(groep)nr.,Postcode,Plaats,Zorginstellingnaam,adres
0,2025-01-02,2025-01-13,5526HR0514,4,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland,oude watering 15
1,2025-01-02,2025-01-13,5526HR0514,4,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland,oude watering 15
2,2025-01-02,2025-01-08,ZKS02555,4,NaN,3141 CJ,MAASSLUIS,Argos - De Tweemaster,vondelpark 2
3,2025-01-02,2025-01-09,ACH0124955,4,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,hamakerstraat 77
4,2025-01-02,2025-01-09,AGIS51556,4,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,hamakerstraat 77
...,...,...,...,...,...,...,...,...,...
632,2025-01-31,2025-02-04,55253031,4,MARCUS,4431 DR,'S-GRAVENPOLDER,Siloah - De Beukelaar,NaN
633,2025-01-31,2024-12-31,VGZFIE-000449,4,SANDRO,5101 TB,DONGEN,GGZ Breburg - Dongen,piet heinstraat 1
634,2025-01-31,2025-02-04,ACH0113971,4,JOERLEMA,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,hamakerstraat 77
635,2025-01-31,2024-12-31,VGZFIE-000449,4,NaN,5101 TB,DONGEN,GGZ Breburg - Dongen,piet heinstraat 1
636,2025-01-31,2025-02-04,ACH0113971,4,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,hamakerstraat 77

In [65]:
df30[df30['adres'].isna()]

,Plandatum,Contractdatum,Serienr.,Punten,Resource(groep)nr.,Postcode,Plaats,Zorginstellingnaam,adres
19,2025-01-02,2025-01-03,ZKL13319,4,NaN,2681 KA,MONSTER,Pieter van Foreest - De Opmaat,NaN
20,2025-01-02,2025-01-06,AGIS56235,4,NaN,3452 LM,VLEUTEN,De Rijnhoven - Coninckshof,NaN
24,2025-01-02,2025-01-03,ZKL13319,4,NaN,2681 KA,MONSTER,Pieter van Foreest - De Opmaat,NaN
25,2025-01-02,2025-01-06,AGIS56235,4,NaN,3452 LM,VLEUTEN,De Rijnhoven - Coninckshof,NaN
27,2025-01-02,2024-12-19,21ZKCZ1547,4,NaN,4813 HM,BREDA,Amarant - Ambachtenlaan,NaN
...,...,...,...,...,...,...,...,...,...
597,2025-01-31,2025-02-11,5526HR0887,4,NaN,3225 GT,HELLEVOETSLUIS,Careyn - Dierenriem,NaN
601,2025-01-31,2025-02-11,5526HR0887,4,NaN,3225 GT,HELLEVOETSLUIS,Careyn - Dierenriem,NaN
628,2025-01-31,2025-02-04,55253031,4,NaN,4431 DR,'S-GRAVENPOLDER,Siloah - De Beukelaar,NaN
630,2025-01-31,2025-02-04,55253031,4,NaN,4431 DR,'S-GRAVENPOLDER,Siloah - De Beukelaar,NaN
632,2025-01-31,2025-02-04,55253031,4,MARCUS,4431 DR,'S-GRAVENPOLDER,Siloah - De Beukelaar,NaN

In [68]:
df30[df30['Zorginstellingnaam'] == 'Amarant - Ambachtenlaan']

,Plandatum,Contractdatum,Serienr.,Punten,Resource(groep)nr.,Postcode,Plaats,Zorginstellingnaam,adres
27,2025-01-02,2024-12-19,21ZKCZ1547,4,NaN,4813 HM,BREDA,Amarant - Ambachtenlaan,NaN
29,2025-01-02,2024-12-19,21ZKCZ1547,4,NaN,4813 HM,BREDA,Amarant - Ambachtenlaan,NaN
34,2025-01-02,2024-12-19,21ZKCZ1547,4,HANS,4813 HM,BREDA,Amarant - Ambachtenlaan,NaN
65,2025-01-03,2024-12-19,21ZKCZ1547,4,NaN,4813 HM,BREDA,Amarant - Ambachtenlaan,NaN
67,2025-01-03,2024-12-19,21ZKCZ1547,4,NaN,4813 HM,BREDA,Amarant - Ambachtenlaan,NaN
77,2025-01-03,2024-12-19,21ZKCZ1547,4,HANS,4813 HM,BREDA,Amarant - Ambachtenlaan,NaN
121,2025-01-06,2024-12-19,21ZKCZ1547,4,HANS,4813 HM,BREDA,Amarant - Ambachtenlaan,NaN
122,2025-01-06,2024-12-19,21ZKCZ1547,4,NaN,4813 HM,BREDA,Amarant - Ambachtenlaan,NaN

In [72]:
# hier de adressen van opzoeken.
nieuwe_adressen = pd.DataFrame({
    "Zorginstellingnaam": [
        "Careyn - Hart van Zuidland",
        "Argos - De Tweemaster",
        "HSB - De Vijverhof",
        "Salem",
        "Middin - Kop van Zuid",
        "Waardeburgh - Open Vensters",
        "ASVZ - Bleskensgraaf",
        "Pieter van Foreest - De Opmaat",
        "De Rijnhoven - Coninckshof",
        "Salios - Lindonk",
        "Amarant - Ambachtenlaan",
        "Gors - Stromenwijk",
        "De Rijnhoven - Princenhof",
        "Rivas - Molenhoek",
        "SVRZ - ter Valcke",
        "Pieter van Foreest - Bieslandhof",
        "Waardeburgh - Meesplein",
        "Middin - De nieuwe Lansingh",
        "Pieter van Foreest - Lindenhof",
        "Harting-Bank Den Haag Den Hoorn",
        "Pieter van Foreest - Delfshove",
        "GGZ Breburg - Dongen",
        "Verzorgingshuis Heemzicht",
        "SVRZ - Erasmuspark",
        "Pieter van Foreest - Die Buytenweye",
        "De Rijnhoven - Vijverhof",
        "Syndion - Haarstraat",
        "Stichting Kio - Sleutelbloemstraat",
        "SDW - 't Zand",
        "Rivas - De Vijverhof Nieuwpoort",
        "Laurens - Den Hoogenban",
        "Amarant - Don Boscoplein",
        "Rivas - Steijndeld",
        "Amarant - Rijsbergen",
        "ASVZ - De Merwebolder",
        "Philadelphia - Phila Rank",
        "Amarant - Teteringen",
        "Siloah - De Beukelaar",
        "Amarijn - Verpleeghuis Scheldehof",
        "St. Ouderenzorg - Cleijenborch",
        "SVRZ - 't Gasthuis",
        "Middin - Orion Aquarius 1, 2",
        "Careyn - Dierenriem"
    ],
    "adres": [
        "Oude Watering 15",
        "Vondelpark 2",
        "Reigerlaan 251",
        "Vlietlaan 2",
        "Lodewijk Pincoffsweg 374",
        "Pr. Marijkeweg 34",
        "Burgemeester Dekkingstraat 1",
        "Van Goghlaan 2",
        "Utrechtse Heuvelrug 180",
        "Rotterdamseweg 137b",
        "Ambachtenlaan 106",
        "Westerscheldeplein 92",
        "Spruit en Bosch 1",
        "Kortendijk 113",
        "Louise de Colignylaan 2",
        "Beukenlaan 2",
        "Burgemeester Meesplein 7",
        "Dominee van Koetsveldstraat 3",
        "Cort van der Lindenstraat 245",
        "Westernesse 18",
        "Vorrinkplein 99",
        "Heuvelstraat 33",
        "Voorstraat 26",
        "Troelstralaan 160",
        "Chopinlaan 9",
        "Spruit en Bosch 1",
        "Stadhuisplein 4",
        "Van der Biltplein 6",
        "Het Zand 14",
        "Vlietzicht 13",
        "Van der Sasstraat 61",
        "Don Boscoplein 39",
        "Kortendijk 72",
        "Leijakkerplein 4",
        "Touwbaan 1",
        "Wijnkoperstraat 90",
        "Zuringveld 119",
        "De Beukelaar 1",
        "Peperdijk 263",
        "Dokter Maasstraat 4",
        "Noordpoortplein 2",
        "Boy Edgarstraat 206",
        "Polaris 60"
    ]
})

In [73]:
df30 = df30.merge(
    nieuwe_adressen,
    on="Zorginstellingnaam",
    how="left",
    suffixes=("", "_nieuw")
)

In [74]:
df30["adres"] = df30["adres"].fillna(df30["adres_nieuw"])

In [76]:
df30 = df30.drop(columns=["adres_nieuw"])

In [77]:
df30[df30["adres"].isna()][["Zorginstellingnaam", "adres"]]

Empty DataFrame
Columns: [Zorginstellingnaam, adres]
Index: []

In [78]:
df30

,Plandatum,Contractdatum,Serienr.,Punten,Resource(groep)nr.,Postcode,Plaats,Zorginstellingnaam,adres
0,2025-01-02,2025-01-13,5526HR0514,4,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland,oude watering 15
1,2025-01-02,2025-01-13,5526HR0514,4,NaN,3214 DC,ZUIDLAND,Careyn - Hart van Zuidland,oude watering 15
2,2025-01-02,2025-01-08,ZKS02555,4,NaN,3141 CJ,MAASSLUIS,Argos - De Tweemaster,vondelpark 2
3,2025-01-02,2025-01-09,ACH0124955,4,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,hamakerstraat 77
4,2025-01-02,2025-01-09,AGIS51556,4,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,hamakerstraat 77
...,...,...,...,...,...,...,...,...,...
632,2025-01-31,2025-02-04,55253031,4,MARCUS,4431 DR,'S-GRAVENPOLDER,Siloah - De Beukelaar,De Beukelaar 1
633,2025-01-31,2024-12-31,VGZFIE-000449,4,SANDRO,5101 TB,DONGEN,GGZ Breburg - Dongen,piet heinstraat 1
634,2025-01-31,2025-02-04,ACH0113971,4,JOERLEMA,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,hamakerstraat 77
635,2025-01-31,2024-12-31,VGZFIE-000449,4,NaN,5101 TB,DONGEN,GGZ Breburg - Dongen,piet heinstraat 1
636,2025-01-31,2025-02-04,ACH0113971,4,NaN,2903 LJ,CAPELLE AAN DEN IJSSEL,HSB - De Vijverhof,hamakerstraat 77

In [79]:
df31 = df30.rename(columns={
    "Postcode": "postcode",
    "Plaats": "plaats",
    "Adres": "adres",
    "Plandatum": "datum",
    "Resource(groep)nr.": "Vaste monteur"
})

In [80]:
df31["adres"] = df31["adres"].str.strip().str.lower()
df31["postcode"] = df31["postcode"].str.strip().str.upper()
df31["plaats"] = df31["plaats"].str.strip().str.lower()

In [81]:
df31["postcode"] = (
    df31["postcode"]
    .str.strip()
    .str.upper()
    .str.replace(" ", "", regex=False)
)

In [82]:
df31["postcode"] = df31["postcode"].str.replace(
    r"(\d{4})([A-Z]{2})", r"\1 \2", regex=True
)

In [83]:
df32 = df31[["adres", "plaats", "postcode", "Punten", "Zorginstellingnaam", 'datum', "Vaste monteur"]]

In [84]:
df32

,adres,plaats,postcode,Punten,Zorginstellingnaam,datum,Vaste monteur
0,oude watering 15,zuidland,3214 DC,4,Careyn - Hart van Zuidland,2025-01-02,NaN
1,oude watering 15,zuidland,3214 DC,4,Careyn - Hart van Zuidland,2025-01-02,NaN
2,vondelpark 2,maassluis,3141 CJ,4,Argos - De Tweemaster,2025-01-02,NaN
3,hamakerstraat 77,capelle aan den ijssel,2903 LJ,4,HSB - De Vijverhof,2025-01-02,NaN
4,hamakerstraat 77,capelle aan den ijssel,2903 LJ,4,HSB - De Vijverhof,2025-01-02,NaN
...,...,...,...,...,...,...,...
632,de beukelaar 1,'s-gravenpolder,4431 DR,4,Siloah - De Beukelaar,2025-01-31,MARCUS
633,piet heinstraat 1,dongen,5101 TB,4,GGZ Breburg - Dongen,2025-01-31,SANDRO
634,hamakerstraat 77,capelle aan den ijssel,2903 LJ,4,HSB - De Vijverhof,2025-01-31,JOERLEMA
635,piet heinstraat 1,dongen,5101 TB,4,GGZ Breburg - Dongen,2025-01-31,NaN
636,hamakerstraat 77,capelle aan den ijssel,2903 LJ,4,HSB - De Vijverhof,2025-01-31,NaN

In [87]:
df_combined = pd.concat([df25, df32])

In [88]:
df_combined

,adres,plaats,postcode,Punten,Zorginstellingnaam,datum,Vaste monteur
0,emil sandstromweg 2,zierikzee,4301 NW,15,Allevo - Zierik7,2023-12-15,Tom B
1,raaigras 102,pijnacker,2643 JJ,24,Pieter van Foreest - Weidevogelhof,2023-12-29,Cornelis van der G
2,stadhuisplein 22,vlissingen,4382 LJ,9,S Heeren Loo - Nieuwe Zuidbeekseweg,2024-01-15,Tom B
3,eliasdreef 9,poeldijk,2685 SZ,3,Middin - Westland Eliasdreef,2024-04-25,Cornelis van der G
4,beukenlaan 2,delft,2612 VC,3,Pieter van Foreest - Bieslandhof,2024-07-19,Cornelis van der G
...,...,...,...,...,...,...,...
632,de beukelaar 1,'s-gravenpolder,4431 DR,4,Siloah - De Beukelaar,2025-01-31,MARCUS
633,piet heinstraat 1,dongen,5101 TB,4,GGZ Breburg - Dongen,2025-01-31,SANDRO
634,hamakerstraat 77,capelle aan den ijssel,2903 LJ,4,HSB - De Vijverhof,2025-01-31,JOERLEMA
635,piet heinstraat 1,dongen,5101 TB,4,GGZ Breburg - Dongen,2025-01-31,NaN
636,hamakerstraat 77,capelle aan den ijssel,2903 LJ,4,HSB - De Vijverhof,2025-01-31,NaN

In [89]:
df_combined.duplicated().sum()

np.int64(500)

In [90]:
df_combined[df_combined.duplicated()]

,adres,plaats,postcode,Punten,Zorginstellingnaam,datum,Vaste monteur
49,de alblashof 1 b,alblasserdam,2951 XR,6,Waardeburgh - De Waard,2024-11-22,Tjerk P
161,buitenruststraat 221,middelburg,4337 EP,6,Amarijn - Hof Ravensteijn,2025-01-02,Tom B
178,buitenruststraat 221,middelburg,4337 EP,6,Amarijn - Hof Ravensteijn,2025-01-03,Tom B
246,mathenesserlaan 500 5e,rotterdam,3023 HL,2,Laurens - Delfshaven,2025-01-16,Jeremy R
284,plantageweg 4,brielle,3232 LE,3,Careyn - De Plantage,2025-01-02,Peter B
...,...,...,...,...,...,...,...
626,kortendijk 72,gorinchem,4201 KW,4,Rivas - Steijndeld,2025-01-31,NaN
627,hamakerstraat 77,capelle aan den ijssel,2903 LJ,4,HSB - De Vijverhof,2025-01-31,NaN
629,hamakerstraat 77,capelle aan den ijssel,2903 LJ,4,HSB - De Vijverhof,2025-01-31,NaN
630,de beukelaar 1,'s-gravenpolder,4431 DR,4,Siloah - De Beukelaar,2025-01-31,NaN
636,hamakerstraat 77,capelle aan den ijssel,2903 LJ,4,HSB - De Vijverhof,2025-01-31,NaN

In [92]:
df_combined = df_combined.drop_duplicates()

In [93]:
df_combined

,adres,plaats,postcode,Punten,Zorginstellingnaam,datum,Vaste monteur
0,emil sandstromweg 2,zierikzee,4301 NW,15,Allevo - Zierik7,2023-12-15,Tom B
1,raaigras 102,pijnacker,2643 JJ,24,Pieter van Foreest - Weidevogelhof,2023-12-29,Cornelis van der G
2,stadhuisplein 22,vlissingen,4382 LJ,9,S Heeren Loo - Nieuwe Zuidbeekseweg,2024-01-15,Tom B
3,eliasdreef 9,poeldijk,2685 SZ,3,Middin - Westland Eliasdreef,2024-04-25,Cornelis van der G
4,beukenlaan 2,delft,2612 VC,3,Pieter van Foreest - Bieslandhof,2024-07-19,Cornelis van der G
...,...,...,...,...,...,...,...
631,kortendijk 72,gorinchem,4201 KW,4,Rivas - Steijndeld,2025-01-31,GEERT
632,de beukelaar 1,'s-gravenpolder,4431 DR,4,Siloah - De Beukelaar,2025-01-31,MARCUS
633,piet heinstraat 1,dongen,5101 TB,4,GGZ Breburg - Dongen,2025-01-31,SANDRO
634,hamakerstraat 77,capelle aan den ijssel,2903 LJ,4,HSB - De Vijverhof,2025-01-31,JOERLEMA
635,piet heinstraat 1,dongen,5101 TB,4,GGZ Breburg - Dongen,2025-01-31,NaN