In [2]:
import pandas as pd

In [2]:
# Load the Excel file
df = pd.read_excel("Serviceorders - 01-01-2025-31-01-2025.xlsx")
print(df.head())

   Herstelstatuscodefilter Toewijzingsdatumfilter  Responsdatumfilter  \
0                      NaN     01-01-25..31-01-25                 NaN
1                      NaN     01-01-25..31-01-25                 NaN
2                      NaN     01-01-25..31-01-25                 NaN
3                      NaN     01-01-25..31-01-25                 NaN
4                      NaN     01-01-25..31-01-25                 NaN

   Resourcefilter  Resourcegroepfilter  Niet toegewezen  Opmerking  \
0             NaN                  NaN            False       True
1             NaN                  NaN            False       True
2             NaN                  NaN            False       True
3             NaN                  NaN            False       True
4             NaN                  NaN            False       True

  Documentnr. Toewijzingsdatum Resourcenr.  ...                   Factuurnaam  \
0  SOR2341189       2025-01-20     OFFERTE  ...  CZ/Administratie Zorgkantoor
1  SOR2341990       2025-01-28         JOP  ...              NTAC Zorgkantoor
2  SOR2400380       2025-01-06     OFFERTE  ...  CZ/Administratie Zorgkantoor
3  SOR2408893       2025-01-28       MINDY  ...              NTAC Zorgkantoor
4  SOR2415627       2025-01-10     OFFERTE  ...              NTAC Zorgkantoor

                 Adres       Vaste monteur          Artikelnr.  Serienummer  \
0  Emil Sandstromweg 2               Tom B  MORGANNEWTON.00010     55255110
1         Raaigras 102  Cornelis van der G        PUMA40.00010     ZKS00464
2     Stadhuisplein 22               Tom B    ATTITUDEH2.00010  5525FIE1241
3         Eliasdreef 9  Cornelis van der G         Q500M.00010     ZKS03344
4         Beukenlaan 2  Cornelis van der G          ROXX.00010     ZKL10813

  Dagen in verwerking       Uw referentie  Portaalopmerking  \
0                 261     202512200808613               NaN
1                 285  Wacht op QQ-nummer               NaN
2                 230     202512200807424               NaN
3                  13       QQ-6000522259               NaN
4                 312       QQ-6000518683               NaN

   Datum portaalopmerking  Totaalbedrag
0                     NaN       2800.82
1                     NaN          0.00
2                     NaN       1603.95
3                     NaN         71.59
4                     NaN        510.30

[5 rows x 37 columns]

In [3]:
df

,Herstelstatuscodefilter,Toewijzingsdatumfilter,Responsdatumfilter,Resourcefilter,Resourcegroepfilter,Niet toegewezen,Opmerking,Documentnr.,Toewijzingsdatum,Resourcenr.,...,Factuurnaam,Adres,Vaste monteur,Artikelnr.,Serienummer,Dagen in verwerking,Uw referentie,Portaalopmerking,Datum portaalopmerking,Totaalbedrag
0,NaN,01-01-25..31-01-25,NaN,NaN,NaN,False,True,SOR2341189,2025-01-20,OFFERTE,...,CZ/Administratie Zorgkantoor,Emil Sandstromweg 2,Tom B,MORGANNEWTON.00010,55255110,261,202512200808613,NaN,NaN,2800.82
1,NaN,01-01-25..31-01-25,NaN,NaN,NaN,False,True,SOR2341990,2025-01-28,JOP,...,NTAC Zorgkantoor,Raaigras 102,Cornelis van der G,PUMA40.00010,ZKS00464,285,Wacht op QQ-nummer,NaN,NaN,0.00
2,NaN,01-01-25..31-01-25,NaN,NaN,NaN,False,True,SOR2400380,2025-01-06,OFFERTE,...,CZ/Administratie Zorgkantoor,Stadhuisplein 22,Tom B,ATTITUDEH2.00010,5525FIE1241,230,202512200807424,NaN,NaN,1603.95
3,NaN,01-01-25..31-01-25,NaN,NaN,NaN,False,True,SOR2408893,2025-01-28,MINDY,...,NTAC Zorgkantoor,Eliasdreef 9,Cornelis van der G,Q500M.00010,ZKS03344,13,QQ-6000522259,NaN,NaN,71.59
4,NaN,01-01-25..31-01-25,NaN,NaN,NaN,False,True,SOR2415627,2025-01-10,OFFERTE,...,NTAC Zorgkantoor,Beukenlaan 2,Cornelis van der G,ROXX.00010,ZKL10813,312,QQ-6000518683,NaN,NaN,510.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2138,NaN,01-01-25..31-01-25,NaN,NaN,NaN,False,True,SOR2502343,2025-01-29,MARCEL,...,Zilveren Kruis Zorgkantoor,Nieuwe Binnenweg 33,Jeremy R,ROXXNEWTONNO.00010,FRL02237,302,PO,NaN,NaN,0.00
2139,NaN,01-01-25..31-01-25,NaN,NaN,NaN,False,True,SOR2502349,2025-01-28,ONNO,...,CZ/Administratie Zorgkantoor,Lambertijnenhof 200,Aart van der W,MAXI2.00010,5526FI0098,302,PO,NaN,NaN,0.00
2140,NaN,01-01-25..31-01-25,NaN,NaN,NaN,False,True,SOR2502353,2025-01-28,ONNO,...,CZ/Administratie Zorgkantoor,Lambertijnenhof 200,Aart van der W,MIDI2.00010,5526FI0222,302,PO,NaN,NaN,0.00
2141,NaN,01-01-25..31-01-25,NaN,NaN,NaN,False,True,SOR2502547,2025-01-31,ALIN,...,VGZ Zorgkantoor,Heuvelstraat 33,René H,Q500R.00010,5528-13435,300,Order,NaN,NaN,109.41
2142,NaN,01-01-25..31-01-25,NaN,NaN,NaN,False,True,SOR2502788,2025-01-27,ONNO,...,VGZ Zorgkantoor,Claversweer 1 K301,Cornelis van der G,Q400M.00010,VGZ001677,297,po,NaN,NaN,0.00

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2143 entries, 0 to 2142
Data columns (total 37 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Herstelstatuscodefilter  0 non-null      float64
 1   Toewijzingsdatumfilter   2143 non-null   str
 2   Responsdatumfilter       0 non-null      float64
 3   Resourcefilter           0 non-null      float64
 4   Resourcegroepfilter      0 non-null      float64
 5   Niet toegewezen          2143 non-null   bool
 6   Opmerking                2143 non-null   bool
 7   Documentnr.              2143 non-null   str
 8   Toewijzingsdatum         2143 non-null   datetime64[us]
 9   Resourcenr.              2143 non-null   str
 10  Herstelstatuscode        2143 non-null   int64
 11  Resourcegroepnr.         2137 non-null   str
 12  Responsdatum             2142 non-null   datetime64[us]
 13  Laaste opmerking         2138 non-null   str
 14  Serviceordersoort        2143 non-null   str
 15  Postcode                 2143 non-null   str
 16  Plaats                   2143 non-null   str
 17  Punten                   2143 non-null   int64
 18  Aantal serviceorders     2143 non-null   int64
 19  Aantal verkooporders     2143 non-null   int64
 20  Cliëntnr.                2143 non-null   str
 21  Naam                     2143 non-null   str
 22  Zorginstellingnaam       2143 non-null   str
 23  Orderdatum               2143 non-null   datetime64[us]
 24  Datum laatste opmerking  1654 non-null   datetime64[us]
 25  Verkoperscode            2143 non-null   str
 26  Omschrijving             2143 non-null   str
 27  Factuurnaam              2143 non-null   str
 28  Adres                    2143 non-null   str
 29  Vaste monteur            2109 non-null   str
 30  Artikelnr.               2143 non-null   str
 31  Serienummer              2142 non-null   str
 32  Dagen in verwerking      2143 non-null   int64
 33  Uw referentie            1075 non-null   str
 34  Portaalopmerking         0 non-null      float64
 35  Datum portaalopmerking   0 non-null      float64
 36  Totaalbedrag             2143 non-null   float64
dtypes: bool(2), datetime64[us](4), float64(7), int64(5), str(19)
memory usage: 590.3 KB

In [5]:
df01 = df.drop(columns=['Herstelstatuscodefilter', 'Responsdatumfilter', 'Resourcefilter', 'Resourcegroepfilter', 'Portaalopmerking', 'Datum portaalopmerking'])
df01

,Toewijzingsdatumfilter,Niet toegewezen,Opmerking,Documentnr.,Toewijzingsdatum,Resourcenr.,Herstelstatuscode,Resourcegroepnr.,Responsdatum,Laaste opmerking,...,Verkoperscode,Omschrijving,Factuurnaam,Adres,Vaste monteur,Artikelnr.,Serienummer,Dagen in verwerking,Uw referentie,Totaalbedrag
0,01-01-25..31-01-25,False,True,SOR2341189,2025-01-20,OFFERTE,90,OFFERTE,2023-12-15,"ADV: vrijloophendel niet verkrijgbaar, nieuwe ...",...,ROBBY,Morgan Newton,CZ/Administratie Zorgkantoor,Emil Sandstromweg 2,Tom B,MORGANNEWTON.00010,55255110,261,202512200808613,2800.82
1,01-01-25..31-01-25,False,True,SOR2341990,2025-01-28,JOP,99,ADVISEUR,2023-12-29,NH: lijst voor Jop gemaakt,...,JOP,Puma 40,NTAC Zorgkantoor,Raaigras 102,Cornelis van der G,PUMA40.00010,ZKS00464,285,Wacht op QQ-nummer,0.00
2,01-01-25..31-01-25,False,True,SOR2400380,2025-01-06,OFFERTE,90,OFFERTE,2024-01-15,"Uitgevoerd, ondertekening goedgekeurd",...,RUUD,QUICKIE ATTITUDE HYBRID 2,CZ/Administratie Zorgkantoor,Stadhuisplein 22,Tom B,ATTITUDEH2.00010,5525FIE1241,230,202512200807424,1603.95
3,01-01-25..31-01-25,False,True,SOR2408893,2025-01-28,MINDY,99,ADVISEUR,2024-04-25,FS: Cor gaat toch 22-4,...,MINDY,Puma Q500 M SedeoPro midwielaandrijving,NTAC Zorgkantoor,Eliasdreef 9,Cornelis van der G,Q500M.00010,ZKS03344,13,QQ-6000522259,71.59
4,01-01-25..31-01-25,False,True,SOR2415627,2025-01-10,OFFERTE,90,OFFERTE,2024-07-19,"Uitgevoerd, ondertekening goedgekeurd",...,JOP,Roxx Trippel & Zelfrijder,NTAC Zorgkantoor,Beukenlaan 2,Cornelis van der G,ROXX.00010,ZKL10813,312,QQ-6000518683,510.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2138,01-01-25..31-01-25,False,True,SOR2502343,2025-01-29,MARCEL,99,MONTEURS,2025-02-17,Uitgevoerd,...,MINDY,Roxx Newton New Original model,Zilveren Kruis Zorgkantoor,Nieuwe Binnenweg 33,Jeremy R,ROXXNEWTONNO.00010,FRL02237,302,PO,0.00
2139,01-01-25..31-01-25,False,True,SOR2502349,2025-01-28,ONNO,99,MONTEURS,2025-02-17,"Uitgevoerd, ondertekening goedgekeurd",...,BRIGIT,"Maxi 2 Basis INC licht, slot, bel, parkeerrem",CZ/Administratie Zorgkantoor,Lambertijnenhof 200,Aart van der W,MAXI2.00010,5526FI0098,302,PO,0.00
2140,01-01-25..31-01-25,False,True,SOR2502353,2025-01-28,ONNO,99,MONTEURS,2025-02-17,Uitgevoerd,...,BRIGIT,Midi 2 driewielfiets,CZ/Administratie Zorgkantoor,Lambertijnenhof 200,Aart van der W,MIDI2.00010,5526FI0222,302,PO,0.00
2141,01-01-25..31-01-25,False,True,SOR2502547,2025-01-31,ALIN,87,MONTEURS,2025-02-11,"Uitgevoerd, nog te ondertekenen",...,BRIGIT,Puma Q500 R SedeoPro achterwielaandrijving,VGZ Zorgkantoor,Heuvelstraat 33,René H,Q500R.00010,5528-13435,300,Order,109.41
2142,01-01-25..31-01-25,False,True,SOR2502788,2025-01-27,ONNO,99,MONTEURS,2025-02-24,Uitgevoerd,...,MAX,Puma Q400 M SedeoPro middenwielaandrijving,VGZ Zorgkantoor,Claversweer 1 K301,Cornelis van der G,Q400M.00010,VGZ001677,297,po,0.00

In [6]:
df02 = df01[df01['Niet toegewezen'] == 'False']
df02

Empty DataFrame
Columns: [Toewijzingsdatumfilter, Niet toegewezen, Opmerking, Documentnr., Toewijzingsdatum, Resourcenr., Herstelstatuscode, Resourcegroepnr., Responsdatum, Laaste opmerking, Serviceordersoort, Postcode, Plaats, Punten, Aantal serviceorders, Aantal verkooporders, Cliëntnr., Naam, Zorginstellingnaam, Orderdatum, Datum laatste opmerking, Verkoperscode, Omschrijving, Factuurnaam, Adres, Vaste monteur, Artikelnr., Serienummer, Dagen in verwerking, Uw referentie, Totaalbedrag]
Index: []

[0 rows x 31 columns]

In [7]:
# alle orders zijn toegewezen, dus deze kolom is niet relevant
# kolom opmerking ook irrelevant, want deze geeft alleen aaf of er een opmerking is, niet wat de opmerking is
df02 = df01.drop(columns=['Niet toegewezen', 'Opmerking'])
df02

,Toewijzingsdatumfilter,Documentnr.,Toewijzingsdatum,Resourcenr.,Herstelstatuscode,Resourcegroepnr.,Responsdatum,Laaste opmerking,Serviceordersoort,Postcode,...,Verkoperscode,Omschrijving,Factuurnaam,Adres,Vaste monteur,Artikelnr.,Serienummer,Dagen in verwerking,Uw referentie,Totaalbedrag
0,01-01-25..31-01-25,SOR2341189,2025-01-20,OFFERTE,90,OFFERTE,2023-12-15,"ADV: vrijloophendel niet verkrijgbaar, nieuwe ...",REP,4301 NW,...,ROBBY,Morgan Newton,CZ/Administratie Zorgkantoor,Emil Sandstromweg 2,Tom B,MORGANNEWTON.00010,55255110,261,202512200808613,2800.82
1,01-01-25..31-01-25,SOR2341990,2025-01-28,JOP,99,ADVISEUR,2023-12-29,NH: lijst voor Jop gemaakt,REP,2643 JJ,...,JOP,Puma 40,NTAC Zorgkantoor,Raaigras 102,Cornelis van der G,PUMA40.00010,ZKS00464,285,Wacht op QQ-nummer,0.00
2,01-01-25..31-01-25,SOR2400380,2025-01-06,OFFERTE,90,OFFERTE,2024-01-15,"Uitgevoerd, ondertekening goedgekeurd",REP,4382 LJ,...,RUUD,QUICKIE ATTITUDE HYBRID 2,CZ/Administratie Zorgkantoor,Stadhuisplein 22,Tom B,ATTITUDEH2.00010,5525FIE1241,230,202512200807424,1603.95
3,01-01-25..31-01-25,SOR2408893,2025-01-28,MINDY,99,ADVISEUR,2024-04-25,FS: Cor gaat toch 22-4,REP,2685 SZ,...,MINDY,Puma Q500 M SedeoPro midwielaandrijving,NTAC Zorgkantoor,Eliasdreef 9,Cornelis van der G,Q500M.00010,ZKS03344,13,QQ-6000522259,71.59
4,01-01-25..31-01-25,SOR2415627,2025-01-10,OFFERTE,90,OFFERTE,2024-07-19,"Uitgevoerd, ondertekening goedgekeurd",AANPASSING,2612 VC,...,JOP,Roxx Trippel & Zelfrijder,NTAC Zorgkantoor,Beukenlaan 2,Cornelis van der G,ROXX.00010,ZKL10813,312,QQ-6000518683,510.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2138,01-01-25..31-01-25,SOR2502343,2025-01-29,MARCEL,99,MONTEURS,2025-02-17,Uitgevoerd,POREP,3014 GC,...,MINDY,Roxx Newton New Original model,Zilveren Kruis Zorgkantoor,Nieuwe Binnenweg 33,Jeremy R,ROXXNEWTONNO.00010,FRL02237,302,PO,0.00
2139,01-01-25..31-01-25,SOR2502349,2025-01-28,ONNO,99,MONTEURS,2025-02-17,"Uitgevoerd, ondertekening goedgekeurd",POREP,4614 CH,...,BRIGIT,"Maxi 2 Basis INC licht, slot, bel, parkeerrem",CZ/Administratie Zorgkantoor,Lambertijnenhof 200,Aart van der W,MAXI2.00010,5526FI0098,302,PO,0.00
2140,01-01-25..31-01-25,SOR2502353,2025-01-28,ONNO,99,MONTEURS,2025-02-17,Uitgevoerd,POREP,4614 CH,...,BRIGIT,Midi 2 driewielfiets,CZ/Administratie Zorgkantoor,Lambertijnenhof 200,Aart van der W,MIDI2.00010,5526FI0222,302,PO,0.00
2141,01-01-25..31-01-25,SOR2502547,2025-01-31,ALIN,87,MONTEURS,2025-02-11,"Uitgevoerd, nog te ondertekenen",REP,5101 TB,...,BRIGIT,Puma Q500 R SedeoPro achterwielaandrijving,VGZ Zorgkantoor,Heuvelstraat 33,René H,Q500R.00010,5528-13435,300,Order,109.41
2142,01-01-25..31-01-25,SOR2502788,2025-01-27,ONNO,99,MONTEURS,2025-02-24,Uitgevoerd,POREP,3371 PR,...,MAX,Puma Q400 M SedeoPro middenwielaandrijving,VGZ Zorgkantoor,Claversweer 1 K301,Cornelis van der G,Q400M.00010,VGZ001677,297,po,0.00

In [8]:
df02.info()

<class 'pandas.DataFrame'>
RangeIndex: 2143 entries, 0 to 2142
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Toewijzingsdatumfilter   2143 non-null   str
 1   Documentnr.              2143 non-null   str
 2   Toewijzingsdatum         2143 non-null   datetime64[us]
 3   Resourcenr.              2143 non-null   str
 4   Herstelstatuscode        2143 non-null   int64
 5   Resourcegroepnr.         2137 non-null   str
 6   Responsdatum             2142 non-null   datetime64[us]
 7   Laaste opmerking         2138 non-null   str
 8   Serviceordersoort        2143 non-null   str
 9   Postcode                 2143 non-null   str
 10  Plaats                   2143 non-null   str
 11  Punten                   2143 non-null   int64
 12  Aantal serviceorders     2143 non-null   int64
 13  Aantal verkooporders     2143 non-null   int64
 14  Cliëntnr.                2143 non-null   str
 15  Naam                     2143 non-null   str
 16  Zorginstellingnaam       2143 non-null   str
 17  Orderdatum               2143 non-null   datetime64[us]
 18  Datum laatste opmerking  1654 non-null   datetime64[us]
 19  Verkoperscode            2143 non-null   str
 20  Omschrijving             2143 non-null   str
 21  Factuurnaam              2143 non-null   str
 22  Adres                    2143 non-null   str
 23  Vaste monteur            2109 non-null   str
 24  Artikelnr.               2143 non-null   str
 25  Serienummer              2142 non-null   str
 26  Dagen in verwerking      2143 non-null   int64
 27  Uw referentie            1075 non-null   str
 28  Totaalbedrag             2143 non-null   float64
dtypes: datetime64[us](4), float64(1), int64(5), str(19)
memory usage: 485.7 KB

In [9]:
df03 = df02.drop(columns=['Toewijzingsdatumfilter', 'Resourcenr.', 'Resourcegroepnr.', 'Laaste opmerking', 'Aantal serviceorders', 'Aantal verkooporders', 'Datum laatste opmerking', 'Verkoperscode', 'Serienummer', 'Dagen in verwerking', 'Uw referentie'])
df03

,Documentnr.,Toewijzingsdatum,Herstelstatuscode,Responsdatum,Serviceordersoort,Postcode,Plaats,Punten,Cliëntnr.,Naam,Zorginstellingnaam,Orderdatum,Omschrijving,Factuurnaam,Adres,Vaste monteur,Artikelnr.,Totaalbedrag
0,SOR2341189,2025-01-20,90,2023-12-15,REP,4301 NW,ZIERIKZEE,15,K0043840,Mevr. P. Verwest,Allevo - Zierik7,2023-12-08,Morgan Newton,CZ/Administratie Zorgkantoor,Emil Sandstromweg 2,Tom B,MORGANNEWTON.00010,2800.82
1,SOR2341990,2025-01-28,99,2023-12-29,REP,2643 JJ,PIJNACKER,24,510431,Mw. S. Bhawanie,Pieter van Foreest - Weidevogelhof,2023-12-19,Puma 40,NTAC Zorgkantoor,Raaigras 102,Cornelis van der G,PUMA40.00010,0.00
2,SOR2400380,2025-01-06,90,2024-01-15,REP,4382 LJ,VLISSINGEN,9,K0062065,Mevr. N. Langstraat,S Heeren Loo - Nieuwe Zuidbeekseweg,2024-01-08,QUICKIE ATTITUDE HYBRID 2,CZ/Administratie Zorgkantoor,Stadhuisplein 22,Tom B,ATTITUDEH2.00010,1603.95
3,SOR2408893,2025-01-28,99,2024-04-25,REP,2685 SZ,POELDIJK,3,K0087579,Dhr. R. Viersma,Middin - Westland Eliasdreef,2024-04-17,Puma Q500 M SedeoPro midwielaandrijving,NTAC Zorgkantoor,Eliasdreef 9,Cornelis van der G,Q500M.00010,71.59
4,SOR2415627,2025-01-10,90,2024-07-19,AANPASSING,2612 VC,DELFT,3,K0085783,Mevr. G.M. de Cock-van der Voort,Pieter van Foreest - Bieslandhof,2024-07-11,Roxx Trippel & Zelfrijder,NTAC Zorgkantoor,Beukenlaan 2,Cornelis van der G,ROXX.00010,510.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2138,SOR2502343,2025-01-29,99,2025-02-17,POREP,3014 GC,ROTTERDAM,0,K0097064,Dhr. C.D. Storm,Laurens - Antonius Binnenweg,2025-01-31,Roxx Newton New Original model,Zilveren Kruis Zorgkantoor,Nieuwe Binnenweg 33,Jeremy R,ROXXNEWTONNO.00010,0.00
2139,SOR2502349,2025-01-28,99,2025-02-17,POREP,4614 CH,BERGEN OP ZOOM,0,K0097396,Mevr. D.C.J.M. Goossens,S&L Zorg - Lambertijnenhof,2025-01-31,"Maxi 2 Basis INC licht, slot, bel, parkeerrem",CZ/Administratie Zorgkantoor,Lambertijnenhof 200,Aart van der W,MAXI2.00010,0.00
2140,SOR2502353,2025-01-28,99,2025-02-17,POREP,4614 CH,BERGEN OP ZOOM,0,K0076862,Dhr. P. Verburgt,S&L Zorg - Lambertijnenhof,2025-01-31,Midi 2 driewielfiets,CZ/Administratie Zorgkantoor,Lambertijnenhof 200,Aart van der W,MIDI2.00010,0.00
2141,SOR2502547,2025-01-31,87,2025-02-11,REP,5101 TB,DONGEN,0,K0059773,Dhr. A.N.P. Jansson,GGZ Breburg - Dongen,2025-02-04,Puma Q500 R SedeoPro achterwielaandrijving,VGZ Zorgkantoor,Heuvelstraat 33,René H,Q500R.00010,109.41
2142,SOR2502788,2025-01-27,99,2025-02-24,POREP,3371 PR,HARDINXVELD GIESSENDAM,0,509154,Mevr. G.D.J. Combee-van den Heuvel,Waardeburgh - Pedaja,2025-02-07,Puma Q400 M SedeoPro middenwielaandrijving,VGZ Zorgkantoor,Claversweer 1 K301,Cornelis van der G,Q400M.00010,0.00

In [10]:
df03['Herstelstatuscode'].unique()

array([90, 99, 87])

In [11]:
# deze 3 codes staan voor 90 = ondertekend, 99 = gefactureerd, 87 = nog niet ondertekend. Al deze codes betekenen wel dat de order is uitgevoerd.
# dus deze kolom kan ook verwijderd worden
df03 = df03.drop(columns=['Herstelstatuscode', 'Naam'])

In [12]:
df03

,Documentnr.,Toewijzingsdatum,Responsdatum,Serviceordersoort,Postcode,Plaats,Punten,Cliëntnr.,Zorginstellingnaam,Orderdatum,Omschrijving,Factuurnaam,Adres,Vaste monteur,Artikelnr.,Totaalbedrag
0,SOR2341189,2025-01-20,2023-12-15,REP,4301 NW,ZIERIKZEE,15,K0043840,Allevo - Zierik7,2023-12-08,Morgan Newton,CZ/Administratie Zorgkantoor,Emil Sandstromweg 2,Tom B,MORGANNEWTON.00010,2800.82
1,SOR2341990,2025-01-28,2023-12-29,REP,2643 JJ,PIJNACKER,24,510431,Pieter van Foreest - Weidevogelhof,2023-12-19,Puma 40,NTAC Zorgkantoor,Raaigras 102,Cornelis van der G,PUMA40.00010,0.00
2,SOR2400380,2025-01-06,2024-01-15,REP,4382 LJ,VLISSINGEN,9,K0062065,S Heeren Loo - Nieuwe Zuidbeekseweg,2024-01-08,QUICKIE ATTITUDE HYBRID 2,CZ/Administratie Zorgkantoor,Stadhuisplein 22,Tom B,ATTITUDEH2.00010,1603.95
3,SOR2408893,2025-01-28,2024-04-25,REP,2685 SZ,POELDIJK,3,K0087579,Middin - Westland Eliasdreef,2024-04-17,Puma Q500 M SedeoPro midwielaandrijving,NTAC Zorgkantoor,Eliasdreef 9,Cornelis van der G,Q500M.00010,71.59
4,SOR2415627,2025-01-10,2024-07-19,AANPASSING,2612 VC,DELFT,3,K0085783,Pieter van Foreest - Bieslandhof,2024-07-11,Roxx Trippel & Zelfrijder,NTAC Zorgkantoor,Beukenlaan 2,Cornelis van der G,ROXX.00010,510.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2138,SOR2502343,2025-01-29,2025-02-17,POREP,3014 GC,ROTTERDAM,0,K0097064,Laurens - Antonius Binnenweg,2025-01-31,Roxx Newton New Original model,Zilveren Kruis Zorgkantoor,Nieuwe Binnenweg 33,Jeremy R,ROXXNEWTONNO.00010,0.00
2139,SOR2502349,2025-01-28,2025-02-17,POREP,4614 CH,BERGEN OP ZOOM,0,K0097396,S&L Zorg - Lambertijnenhof,2025-01-31,"Maxi 2 Basis INC licht, slot, bel, parkeerrem",CZ/Administratie Zorgkantoor,Lambertijnenhof 200,Aart van der W,MAXI2.00010,0.00
2140,SOR2502353,2025-01-28,2025-02-17,POREP,4614 CH,BERGEN OP ZOOM,0,K0076862,S&L Zorg - Lambertijnenhof,2025-01-31,Midi 2 driewielfiets,CZ/Administratie Zorgkantoor,Lambertijnenhof 200,Aart van der W,MIDI2.00010,0.00
2141,SOR2502547,2025-01-31,2025-02-11,REP,5101 TB,DONGEN,0,K0059773,GGZ Breburg - Dongen,2025-02-04,Puma Q500 R SedeoPro achterwielaandrijving,VGZ Zorgkantoor,Heuvelstraat 33,René H,Q500R.00010,109.41
2142,SOR2502788,2025-01-27,2025-02-24,POREP,3371 PR,HARDINXVELD GIESSENDAM,0,509154,Waardeburgh - Pedaja,2025-02-07,Puma Q400 M SedeoPro middenwielaandrijving,VGZ Zorgkantoor,Claversweer 1 K301,Cornelis van der G,Q400M.00010,0.00

In [13]:
df_orders = df03
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 2143 entries, 0 to 2142
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Documentnr.         2143 non-null   str
 1   Toewijzingsdatum    2143 non-null   datetime64[us]
 2   Responsdatum        2142 non-null   datetime64[us]
 3   Serviceordersoort   2143 non-null   str
 4   Postcode            2143 non-null   str
 5   Plaats              2143 non-null   str
 6   Punten              2143 non-null   int64
 7   Cliëntnr.           2143 non-null   str
 8   Zorginstellingnaam  2143 non-null   str
 9   Orderdatum          2143 non-null   datetime64[us]
 10  Omschrijving        2143 non-null   str
 11  Factuurnaam         2143 non-null   str
 12  Adres               2143 non-null   str
 13  Vaste monteur       2109 non-null   str
 14  Artikelnr.          2143 non-null   str
 15  Totaalbedrag        2143 non-null   float64
dtypes: datetime64[us](3), float64(1), int64(1), str(11)
memory usage: 268.0 KB

In [14]:
df_orders['Vaste monteur'].unique()

<StringArray>
[             'Tom B', 'Cornelis van der G',            'Peter B',
            'Tjerk P',              'Ron T',           'Jeremy R',
             'René H',           'Marcel K',     'Aart van der W',
          'Liza de G',      'Laurens-Jan B',         'Mark den E',
             'Alin A',          'Vincent K',          'Patrick B',
           'Sandro G',                  nan,             'Rene H',
             'Jeremy']
Length: 19, dtype: str

In [16]:
# dit vergelijken met de chauffeurs van de bussen

In [27]:
df_fleetgo = pd.read_excel("Bezoeken per voertuig 01-01-2025 - 31-01-2025.xlsx")

In [28]:
df20 = df_fleetgo[df_fleetgo['GroupName'] == '19210700 Dordrecht - BBT']
df20.info()

<class 'pandas.DataFrame'>
RangeIndex: 4804 entries, 16939 to 21742
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SerialNumber         4804 non-null   str
 1   Date                 4804 non-null   datetime64[us]
 2   StartRide            4804 non-null   object
 3   Start                4804 non-null   object
 4   Stop                 4804 non-null   object
 5   Distance             4804 non-null   float64
 6   TravelTime           4804 non-null   object
 7   Duration             4804 non-null   object
 8   VisitingAddress      4804 non-null   str
 9   Description          741 non-null    str
 10  DriverName           4324 non-null   str
 11  GroupName            4804 non-null   str
 12  Contact              0 non-null      object
 13  Remark               0 non-null      str
 14  To                   4797 non-null   object
 15  ZipCode              4794 non-null   object
 16  City                 4804 non-null   str
 17  ProjectNumber        741 non-null    float64
 18  Break                4804 non-null   object
 19  TotalTime            4804 non-null   object
 20  TotalTravelTime      4804 non-null   object
 21  TotalDuration        4804 non-null   object
 22  TotalTimeMinusBreak  4804 non-null   object
 23  TotalDistance        4804 non-null   float64
 24  Lat                  4804 non-null   float64
 25  Long                 4804 non-null   float64
dtypes: datetime64[us](1), float64(5), object(13), str(7)
memory usage: 975.9+ KB

In [29]:
df21 = df20.drop(columns=['Description', 'Contact', 'Remark', 'ProjectNumber'])
df21.info()

<class 'pandas.DataFrame'>
RangeIndex: 4804 entries, 16939 to 21742
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SerialNumber         4804 non-null   str
 1   Date                 4804 non-null   datetime64[us]
 2   StartRide            4804 non-null   object
 3   Start                4804 non-null   object
 4   Stop                 4804 non-null   object
 5   Distance             4804 non-null   float64
 6   TravelTime           4804 non-null   object
 7   Duration             4804 non-null   object
 8   VisitingAddress      4804 non-null   str
 9   DriverName           4324 non-null   str
 10  GroupName            4804 non-null   str
 11  To                   4797 non-null   object
 12  ZipCode              4794 non-null   object
 13  City                 4804 non-null   str
 14  Break                4804 non-null   object
 15  TotalTime            4804 non-null   object
 16  TotalTravelTime      4804 non-null   object
 17  TotalDuration        4804 non-null   object
 18  TotalTimeMinusBreak  4804 non-null   object
 19  TotalDistance        4804 non-null   float64
 20  Lat                  4804 non-null   float64
 21  Long                 4804 non-null   float64
dtypes: datetime64[us](1), float64(4), object(12), str(5)
memory usage: 825.8+ KB

In [30]:
df21['DriverName'].unique()

<StringArray>
[                        nan,         'Aart van der Wulp',
 'Auto Mertens Auto Mertens',           'Tom Barendrecht',
           'Tjerk Polderman',            'Sandro Glasius',
              'Liza de Gier',                'Ronald Kok',
            'Marcel Koevoet',  'Cornelis van der Giessen',
     'Geertjan van der Wulp',              'Roy Albersen',
              'Robin Kovács',               'Kees Kuiper',
                'Peter Bood',           'Joost Oerlemans',
             'Onno Havelaar',           'Enzo van Dongen',
                'Erik-Jan 3',             'Bas van Steen',
                'Ron Timmer',       'Peter van den Bosch',
             'Hans de Groot',              'Frido Wijnen',
            'Sheamie Gerard',            'Frans Boshoven',
       'René Hoppenbrouwers',            'Barend de Jong',
             'Ronald Griend',             'Marcus Dekker',
               'Alin Apetri',      'Joost van der Linden']
Length: 32, dtype: str

In [31]:
conflicten = (
    df21.assign(Naam_monteur_schoon=df21['DriverName'].replace('', pd.NA))
      .dropna(subset=['Naam_monteur_schoon'])
      .groupby(['Date', 'SerialNumber'])['Naam_monteur_schoon']
      .agg([
          ('aantal_unieke_monteurs', 'nunique'),
          ('monteurs', lambda x: list(pd.unique(x)))
      ])
      .reset_index()
)

conflicten = conflicten[conflicten['aantal_unieke_monteurs'] > 1]

print(conflicten)

          Date     SerialNumber  aantal_unieke_monteurs  \
216 2025-01-16  1040 (VFT-36-H)                       2
260 2025-01-20  1001 (VFK-90-R)                       2
404 2025-01-29  1001 (VFK-90-R)                       2
429 2025-01-30  1040 (VFT-36-H)                       2

                                           monteurs
216    [Tjerk Polderman, Auto Mertens Auto Mertens]
260  [Aart van der Wulp, Auto Mertens Auto Mertens]
404  [Auto Mertens Auto Mertens, Aart van der Wulp]
429    [Auto Mertens Auto Mertens, Tjerk Polderman]

In [32]:
df21[df21['DriverName'] == 'Auto Mertens Auto Mertens']

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,DriverName,...,ZipCode,City,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
17062,1001 (VFK-90-R),2025-01-20,08:51:00,10:20:00,13:17:00,107.49,01:28:00,02:57:00,"Bolle Akker 13, Bakel",Auto Mertens Auto Mertens,...,5761RW,Bakel,00:00:00,04:57:00,01:45:00,03:12:00,00:00:00,120.48,514975095.0,57434225.0
17063,1001 (VFK-90-R),2025-01-20,13:17:00,13:30:00,13:35:00,4.13,00:13:00,00:04:00,"Bolle Akker 13, Bakel",Auto Mertens Auto Mertens,...,5761RW,Bakel,00:00:00,05:15:00,01:58:00,03:17:00,00:00:00,124.61,514975776.0,57432788.0
17065,1001 (VFK-90-R),2025-01-20,14:03:00,14:04:00,14:20:00,0.04,00:01:00,00:16:00,"Bolle Akker 13, Bakel",Auto Mertens Auto Mertens,...,5761RW,Bakel,00:00:00,06:01:00,02:03:00,03:57:00,00:00:00,124.68,514975405.0,57431281.0
17069,1001 (VFK-90-R),2025-01-21,10:42:00,10:44:00,11:57:00,0.24,00:01:00,01:13:00,"Bolle Akker 15, Bakel",Auto Mertens Auto Mertens,...,5761RW,Bakel,00:00:00,01:15:00,00:01:00,01:13:00,00:00:00,0.24,514979728.0,57432743.0
17071,1001 (VFK-90-R),2025-01-21,12:08:00,12:21:00,08:20:00,10.76,00:12:00,"2 days, 19:59:00","Bolle Akker 13, Bakel",Auto Mertens Auto Mertens,...,5761RW,Bakel,00:00:00,01:38:00,00:17:00,01:21:00,01:38:00,11.00,514975016.0,57431628.0
17073,1001 (VFK-90-R),2025-01-24,08:24:00,08:24:00,08:25:00,0.00,00:00:00,00:01:00,"Bolle Akker 13, Bakel",Auto Mertens Auto Mertens,...,5761RW,Bakel,00:00:00,00:05:00,00:03:00,00:01:00,00:00:00,0.04,514975473.0,57432108.0
17077,1001 (VFK-90-R),2025-01-29,05:48:00,05:55:00,05:57:00,1.76,00:07:00,00:02:00,"Benthem 3, Bakel",Auto Mertens Auto Mertens,...,5761PN,Bakel,00:00:00,00:09:00,00:07:00,00:02:00,00:00:00,1.76,514991386.0,57278886.0
17078,1001 (VFK-90-R),2025-01-29,05:57:00,07:37:00,07:40:00,105.60,01:39:00,00:02:00,"Kamerlingh Onnesweg 9, Dordrecht",Auto Mertens Auto Mertens,...,3316 GK,Dordrecht,00:00:00,01:51:00,01:46:00,00:05:00,00:00:00,107.36,517806956.0,46387746.0
17131,1026 (VFR-80-J),2025-01-09,08:24:00,08:34:00,08:36:00,0.70,00:09:00,00:02:00,"Beekakker 5, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,00:11:00,00:09:00,00:02:00,00:00:00,0.70,514991333.0,5743425.0
17135,1026 (VFR-80-J),2025-01-14,13:41:00,14:04:00,14:06:00,0.00,00:23:00,00:01:00,"Beekakker 7, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,00:24:00,00:23:00,00:01:00,00:00:00,0.00,514989599.0,57434416.0
17137,1026 (VFR-80-J),2025-01-14,14:07:00,14:08:00,14:09:00,0.00,00:00:00,00:00:00,"Beekakker 7, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,00:27:00,00:24:00,00:02:00,00:00:00,0.00,514989599.0,57434416.0
17138,1026 (VFR-80-J),2025-01-14,14:09:00,14:14:00,15:24:00,0.00,00:05:00,01:09:00,"Beekakker 7, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,01:43:00,00:30:00,01:12:00,00:00:00,0.00,514989599.0,57434416.0
17141,1026 (VFR-80-J),2025-01-16,09:38:00,09:59:00,10:36:00,14.20,00:20:00,00:36:00,"Beekakker 7, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,01:10:00,00:32:00,00:37:00,00:00:00,14.20,51499105.0,57434766.0
17143,1026 (VFR-80-J),2025-01-16,15:59:00,16:58:00,06:51:00,1.40,00:58:00,13:53:00,"Beekakker 7, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,07:32:00,01:33:00,05:58:00,07:32:00,15.60,51499135.0,5743335.0
17144,1026 (VFR-80-J),2025-01-17,06:51:00,07:01:00,07:04:00,1.70,00:10:00,00:02:00,"Benthem 3, Bakel",Auto Mertens Auto Mertens,...,5761PN,Bakel,00:00:00,00:13:00,00:10:00,00:02:00,00:00:00,1.70,5149917.0,57279033.0
17145,1026 (VFR-80-J),2025-01-17,07:04:00,08:33:00,07:04:00,107.50,01:29:00,"2 days, 22:31:00","Kamerlingh Onnesweg 9, Dordrecht",Auto Mertens Auto Mertens,...,3316 GK,Dordrecht,00:00:00,01:42:00,01:39:00,00:02:00,01:42:00,109.20,51780535.0,4638915.0
17384,1040 (VFT-36-H),2025-01-16,16:02:00,16:03:00,16:05:00,0.00,00:00:00,00:02:00,"Dokter Rietveldplein 22, Papendrecht",Auto Mertens Auto Mertens,...,3353SJ,Papendrecht,00:00:00,08:01:00,02:25:00,05:35:00,00:00:00,109.78,518239383.0,46893583.0
17391,1040 (VFT-36-H),2025-01-21,08:24:00,08:26:00,08:31:00,0.06,00:02:00,00:05:00,"Beekakker 5, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,00:07:00,00:02:00,00:05:00,00:00:00,0.06,514991633.0,5743235.0
17402,1040 (VFT-36-H),2025-01-27,08:26:00,08:28:00,09:45:00,0.04,00:01:00,01:17:00,"Beekakker 5, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,01:18:00,00:01:00,01:17:00,00:00:00,0.04,514992333.0,57433383.0
17405,1040 (VFT-36-H),2025-01-27,10:52:00,10:56:00,10:56:00,0.00,00:04:00,00:00:00,"Beekakker 5, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,02:29:00,00:07:00,02:22:00,00:00:00,0.04,514992333.0,57433383.0
17406,1040 (VFT-36-H),2025-01-27,10:56:00,11:03:00,11:18:00,0.04,00:07:00,00:14:00,"Beekakker 5, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,02:51:00,00:14:00,02:37:00,00:00:00,0.08,514992333.0,57433383.0
17411,1040 (VFT-36-H),2025-01-29,15:52:00,16:06:00,16:39:00,4.95,00:13:00,00:33:00,"Beekakker 5, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,03:11:00,00:15:00,02:56:00,00:00:00,4.95,514991666.0,5743375.0
17412,1040 (VFT-36-H),2025-01-29,16:39:00,16:54:00,17:06:00,11.74,00:14:00,00:12:00,"Bolle Akker 13, Bakel",Auto Mertens Auto Mertens,...,5761RW,Bakel,00:00:00,03:38:00,00:29:00,03:08:00,00:00:00,16.69,514975.0,57431916.0
17416,1040 (VFT-36-H),2025-01-30,06:16:00,08:19:00,08:30:00,116.47,02:02:00,00:11:00,"Mandenmakersstraat 1, Zwijndrecht",Auto Mertens Auto Mertens,...,3334KE,Zwijndrecht,00:00:00,02:13:00,02:02:00,00:11:00,00:00:00,116.47,518100266.0,4594445.0
17417,1040 (VFT-36-H),2025-01-30,08:30:00,08:47:00,08:51:00,13.38,00:16:00,00:04:00,"Kamerlingh Onnesweg 9, Dordrecht",Auto Mertens Auto Mertens,...,3316 GK,Dordrecht,00:00:00,02:34:00,02:19:00,00:15:00,00:00:00,129.85,517806183.0,46388166.0
17876,1170 (VHL-86-K),2025-01-22,05:53:00,07:10:00,07:13:00,109.99,01:17:00,00:02:00,"Rijksweg A58 63, Oirschot",Auto Mertens Auto Mertens,...,5688PZ,Oirschot,00:00:00,01:19:00,01:17:00,00:02:00,00:00:00,109.99,514923001.0,53499633.0
17877,1170 (VHL-86-K),2025-01-22,07:13:00,07:47:00,08:12:00,39.38,00:34:00,00:24:00,"Haverdijk 11, Helmond",Auto Mertens Auto Mertens,...,5704RC,Helmond,00:00:00,02:18:00,01:51:00,00:27:00,00:00:00,149.37,514475283.0,57126198.0
17879,1170 (VHL-86-K),2025-01-22,08:13:00,08:26:00,08:41:00,8.35,00:12:00,00:15:00,"Beekakker 5, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,02:48:00,02:05:00,00:42:00,00:00:00,157.72,514993541.0,5743382.0
17880,1170 (VHL-86-K),2025-01-22,08:41:00,08:46:00,08:46:00,0.07,00:04:00,00:00:00,"Beekakker 5, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,02:53:00,02:10:00,00:42:00,00:00:00,157.79,514992005.0,57434478.0
17881,1170 (VHL-86-K),2025-01-22,08:46:00,08:47:00,08:47:00,0.00,00:00:00,00:00:00,"Beekakker 5, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,02:54:00,02:11:00,00:42:00,00:00:00,157.79,51499197.0,57434386.0
17882,1170 (VHL-86-K),2025-01-22,08:47:00,08:48:00,10:40:00,0.00,00:00:00,01:52:00,"Beekakker 5, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,04:47:00,02:11:00,02:35:00,00:00:00,157.79,514991875.0,57434305.0
17889,1170 (VHL-86-K),2025-01-22,15:46:00,15:53:00,15:53:00,5.60,00:06:00,00:00:00,"Beekakker 5, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,10:00:00,02:22:00,07:37:00,00:00:00,163.55,51499276.0,57433435.0
17890,1170 (VHL-86-K),2025-01-22,15:53:00,15:53:00,15:55:00,0.00,00:00:00,00:01:00,"Beekakker 5, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,10:02:00,02:22:00,07:39:00,00:00:00,163.55,51499276.0,57433435.0
17891,1170 (VHL-86-K),2025-01-22,15:55:00,15:56:00,15:59:00,0.04,00:00:00,00:03:00,"Beekakker 4, Bakel",Auto Mertens Auto Mertens,...,5761EN,Bakel,00:00:00,10:06:00,02:22:00,07:43:00,00:00:00,163.59,514996065.0,57434193.0
17892,1170 (VHL-86-K),2025-01-22,15:59:00,18:10:00,07:46:00,133.19,02:10:00,13:36:00,"Koninginnelaan 403, Vlaardingen",Auto Mertens Auto Mertens,...,3136ET,Vlaardingen,00:00:00,12:16:00,04:33:00,07:43:00,12:16:00,296.78,519272983.0,43517865.0

In [33]:
# Auto Mertens eruit halen
df22 = df21.drop(df21[df21['DriverName'] == 'Auto Mertens Auto Mertens'].index)
df22['DriverName'].unique()

<StringArray>
[                       nan,        'Aart van der Wulp',
          'Tom Barendrecht',          'Tjerk Polderman',
           'Sandro Glasius',             'Liza de Gier',
               'Ronald Kok',           'Marcel Koevoet',
 'Cornelis van der Giessen',    'Geertjan van der Wulp',
             'Roy Albersen',             'Robin Kovács',
              'Kees Kuiper',               'Peter Bood',
          'Joost Oerlemans',            'Onno Havelaar',
          'Enzo van Dongen',               'Erik-Jan 3',
            'Bas van Steen',               'Ron Timmer',
      'Peter van den Bosch',            'Hans de Groot',
             'Frido Wijnen',           'Sheamie Gerard',
           'Frans Boshoven',      'René Hoppenbrouwers',
           'Barend de Jong',            'Ronald Griend',
            'Marcus Dekker',              'Alin Apetri',
     'Joost van der Linden']
Length: 31, dtype: str

In [34]:
# nu kijken naar NaN waarden
df22[df22['DriverName'].isna()]

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,DriverName,...,ZipCode,City,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
16939,967 (VDG-43-S),2025-01-02,06:48:00,07:17:00,10:27:00,35.90,00:28:00,03:10:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,03:39:00,00:28:00,03:10:00,00:00:00,35.90,519053952.0,43328348.0
16940,967 (VDG-43-S),2025-01-02,10:27:00,10:39:00,10:43:00,5.10,00:11:00,00:03:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,03:54:00,00:40:00,03:14:00,00:00:00,41.00,519053952.0,43328348.0
16941,967 (VDG-43-S),2025-01-02,10:43:00,11:36:00,12:17:00,61.00,00:53:00,00:41:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,05:29:00,01:33:00,03:55:00,00:00:00,102.00,519053952.0,43328348.0
16942,967 (VDG-43-S),2025-01-02,12:17:00,12:58:00,14:51:00,27.30,00:40:00,01:52:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,08:02:00,02:14:00,05:47:00,00:00:00,129.30,519053952.0,43328348.0
16943,967 (VDG-43-S),2025-01-02,14:51:00,15:06:00,06:55:00,3.70,00:15:00,15:49:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,08:17:00,02:29:00,05:47:00,08:17:00,133.00,519053952.0,43328348.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21566,1775 (V-11-GGL),2025-01-03,07:15:00,07:16:00,07:45:00,0.13,00:00:00,00:29:00,"Kamerlingh Onnesweg 9, Dordrecht",NaN,...,3316 GK,Dordrecht,00:00:00,01:09:00,00:30:00,00:38:00,00:00:00,36.17,517805897.0,4638873.0
21574,1775 (V-11-GGL),2025-01-07,07:44:00,07:45:00,08:08:00,0.04,00:01:00,00:23:00,"Kamerlingh Onnesweg 9, Dordrecht",NaN,...,3316 GK,Dordrecht,00:00:00,00:24:00,00:01:00,00:23:00,00:00:00,0.04,517805879.0,46389157.0
21577,1775 (V-11-GGL),2025-01-07,08:36:00,08:36:00,08:42:00,0.00,00:00:00,00:05:00,"Minnaertweg 4, Dordrecht",NaN,...,3328HN,Dordrecht,00:00:00,00:57:00,00:25:00,00:32:00,00:00:00,5.24,517834808.0,46862303.0
21650,1775 (V-11-GGL),2025-01-16,06:54:00,06:54:00,07:05:00,0.00,00:00:00,00:10:00,"Langemeetstraat 7, Hellevoetsluis",NaN,...,3223BL,Hellevoetsluis,00:00:00,01:41:00,01:14:00,00:27:00,00:00:00,85.65,518533617.0,4146702.0
21686,1775 (V-11-GGL),2025-01-20,13:17:00,13:18:00,07:08:00,0.00,00:00:00,17:50:00,"Buttervliet 1, Numansdorp",NaN,...,3281LK,Numansdorp,00:00:00,07:41:00,04:12:00,03:28:00,07:41:00,187.39,51737958.0,44372958.0

In [36]:
df22.groupby(['Date', 'SerialNumber'])['DriverName'].unique()

Date        SerialNumber
2025-01-01  1040 (VFT-36-H)                         [nan]
            1326 (VNT-05-X)                         [nan]
            1515 (VVF-65-D)    [Cornelis van der Giessen]
            1660 (V-20-DKR)         [René Hoppenbrouwers]
            1687 (V-22-DKR)              [Barend de Jong]
                                          ...
2025-01-31  1687 (V-22-DKR)              [Barend de Jong]
            1702 (V-19-FXR)          [Ronald Griend, nan]
            1705 (V-18-FXR)               [Marcus Dekker]
            1772 (V-13-DLF)            [nan, Alin Apetri]
            1775 (V-11-GGL)        [Joost van der Linden]
Name: DriverName, Length: 506, dtype: object

In [37]:
# lege strings eerst als missend behandelen
df22['DriverName'] = df22['DriverName'].replace('', pd.NA)

# vul alleen groepen zonder conflict
df22['DriverName'] = (
    df22.groupby(['Date', 'SerialNumber'])['DriverName']
      .transform(lambda x: x.ffill().bfill() if x.dropna().nunique() <= 1 else x)
)

df22['DriverName'].unique()

<StringArray>
[                       nan,        'Aart van der Wulp',
          'Tom Barendrecht',          'Tjerk Polderman',
           'Sandro Glasius',             'Liza de Gier',
               'Ronald Kok',           'Marcel Koevoet',
 'Cornelis van der Giessen',    'Geertjan van der Wulp',
             'Roy Albersen',             'Robin Kovács',
              'Kees Kuiper',               'Peter Bood',
          'Joost Oerlemans',            'Onno Havelaar',
          'Enzo van Dongen',               'Erik-Jan 3',
            'Bas van Steen',               'Ron Timmer',
      'Peter van den Bosch',            'Hans de Groot',
             'Frido Wijnen',           'Sheamie Gerard',
           'Frans Boshoven',      'René Hoppenbrouwers',
           'Barend de Jong',            'Ronald Griend',
            'Marcus Dekker',              'Alin Apetri',
     'Joost van der Linden']
Length: 31, dtype: str

In [38]:
df22[df22['DriverName'].isna()]

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,DriverName,...,ZipCode,City,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
16939,967 (VDG-43-S),2025-01-02,06:48:00,07:17:00,10:27:00,35.90,00:28:00,03:10:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,03:39:00,00:28:00,03:10:00,00:00:00,35.90,519053952.0,43328348.0
16940,967 (VDG-43-S),2025-01-02,10:27:00,10:39:00,10:43:00,5.10,00:11:00,00:03:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,03:54:00,00:40:00,03:14:00,00:00:00,41.00,519053952.0,43328348.0
16941,967 (VDG-43-S),2025-01-02,10:43:00,11:36:00,12:17:00,61.00,00:53:00,00:41:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,05:29:00,01:33:00,03:55:00,00:00:00,102.00,519053952.0,43328348.0
16942,967 (VDG-43-S),2025-01-02,12:17:00,12:58:00,14:51:00,27.30,00:40:00,01:52:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,08:02:00,02:14:00,05:47:00,00:00:00,129.30,519053952.0,43328348.0
16943,967 (VDG-43-S),2025-01-02,14:51:00,15:06:00,06:55:00,3.70,00:15:00,15:49:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,08:17:00,02:29:00,05:47:00,08:17:00,133.00,519053952.0,43328348.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18998,1335 (VPP-97-V),2025-01-28,13:03:00,13:19:00,13:22:00,5.58,00:16:00,00:02:00,"Robert Fruinstraat 29, Rotterdam",NaN,...,3021XB,Rotterdam,00:00:00,06:16:00,02:33:00,03:42:00,00:00:00,67.62,51915074.0,44577931.0
18999,1335 (VPP-97-V),2025-01-28,13:22:00,13:26:00,13:38:00,0.62,00:04:00,00:12:00,"Robert Fruinstraat 29, Rotterdam",NaN,...,3021XB,Rotterdam,00:00:00,06:33:00,02:38:00,03:55:00,00:00:00,68.24,51915074.0,44577931.0
19000,1335 (VPP-97-V),2025-01-28,13:38:00,13:48:00,14:28:00,3.80,00:10:00,00:39:00,"Robert Fruinstraat 29, Rotterdam",NaN,...,3021XB,Rotterdam,00:00:00,07:22:00,02:48:00,04:34:00,00:00:00,72.04,51915074.0,44577931.0
19001,1335 (VPP-97-V),2025-01-28,14:28:00,14:56:00,07:38:00,29.40,00:28:00,16:41:00,"Robert Fruinstraat 29, Rotterdam",NaN,...,3021XB,Rotterdam,00:00:00,07:51:00,03:17:00,04:34:00,07:51:00,101.44,51915074.0,44577931.0
21398,1772 (V-13-DLF),2025-01-11,10:13:00,10:20:00,07:13:00,0.24,00:06:00,"1 day, 20:53:00","Boris Pasternak-Erf 254, Dordrecht",NaN,...,3315BV,Dordrecht,00:00:00,00:06:00,00:06:00,00:00:00,00:06:00,0.24,517988938.0,4729185.0

In [39]:
df22[
    df22.groupby(['Date', 'SerialNumber'])['DriverName']
        .transform(lambda x: x.isna())
]

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,DriverName,...,ZipCode,City,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
16939,967 (VDG-43-S),2025-01-02,06:48:00,07:17:00,10:27:00,35.90,00:28:00,03:10:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,03:39:00,00:28:00,03:10:00,00:00:00,35.90,519053952.0,43328348.0
16940,967 (VDG-43-S),2025-01-02,10:27:00,10:39:00,10:43:00,5.10,00:11:00,00:03:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,03:54:00,00:40:00,03:14:00,00:00:00,41.00,519053952.0,43328348.0
16941,967 (VDG-43-S),2025-01-02,10:43:00,11:36:00,12:17:00,61.00,00:53:00,00:41:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,05:29:00,01:33:00,03:55:00,00:00:00,102.00,519053952.0,43328348.0
16942,967 (VDG-43-S),2025-01-02,12:17:00,12:58:00,14:51:00,27.30,00:40:00,01:52:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,08:02:00,02:14:00,05:47:00,00:00:00,129.30,519053952.0,43328348.0
16943,967 (VDG-43-S),2025-01-02,14:51:00,15:06:00,06:55:00,3.70,00:15:00,15:49:00,"Produktiestraat 2, Vlaardingen",NaN,...,3133ES,Vlaardingen,00:00:00,08:17:00,02:29:00,05:47:00,08:17:00,133.00,519053952.0,43328348.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18998,1335 (VPP-97-V),2025-01-28,13:03:00,13:19:00,13:22:00,5.58,00:16:00,00:02:00,"Robert Fruinstraat 29, Rotterdam",NaN,...,3021XB,Rotterdam,00:00:00,06:16:00,02:33:00,03:42:00,00:00:00,67.62,51915074.0,44577931.0
18999,1335 (VPP-97-V),2025-01-28,13:22:00,13:26:00,13:38:00,0.62,00:04:00,00:12:00,"Robert Fruinstraat 29, Rotterdam",NaN,...,3021XB,Rotterdam,00:00:00,06:33:00,02:38:00,03:55:00,00:00:00,68.24,51915074.0,44577931.0
19000,1335 (VPP-97-V),2025-01-28,13:38:00,13:48:00,14:28:00,3.80,00:10:00,00:39:00,"Robert Fruinstraat 29, Rotterdam",NaN,...,3021XB,Rotterdam,00:00:00,07:22:00,02:48:00,04:34:00,00:00:00,72.04,51915074.0,44577931.0
19001,1335 (VPP-97-V),2025-01-28,14:28:00,14:56:00,07:38:00,29.40,00:28:00,16:41:00,"Robert Fruinstraat 29, Rotterdam",NaN,...,3021XB,Rotterdam,00:00:00,07:51:00,03:17:00,04:34:00,07:51:00,101.44,51915074.0,44577931.0
21398,1772 (V-13-DLF),2025-01-11,10:13:00,10:20:00,07:13:00,0.24,00:06:00,"1 day, 20:53:00","Boris Pasternak-Erf 254, Dordrecht",NaN,...,3315BV,Dordrecht,00:00:00,00:06:00,00:06:00,00:00:00,00:06:00,0.24,517988938.0,4729185.0

In [40]:
# dit zijn dus rijen die bij het kenteken en de datum geen driver hebben gevonden en deze halen we er dus uit. en zijn ook de enige rijen die nog Nan zijn
df23 = df22.drop(df22[
    df22.groupby(['Date', 'SerialNumber'])['DriverName']
        .transform(lambda x: x.isna())
].index)

In [41]:
df23['DriverName'].unique()

<StringArray>
[       'Aart van der Wulp',          'Tom Barendrecht',
          'Tjerk Polderman',           'Sandro Glasius',
             'Liza de Gier',               'Ronald Kok',
           'Marcel Koevoet', 'Cornelis van der Giessen',
    'Geertjan van der Wulp',             'Roy Albersen',
             'Robin Kovács',              'Kees Kuiper',
               'Peter Bood',          'Joost Oerlemans',
            'Onno Havelaar',          'Enzo van Dongen',
               'Erik-Jan 3',            'Bas van Steen',
               'Ron Timmer',      'Peter van den Bosch',
            'Hans de Groot',             'Frido Wijnen',
           'Sheamie Gerard',           'Frans Boshoven',
      'René Hoppenbrouwers',           'Barend de Jong',
            'Ronald Griend',            'Marcus Dekker',
              'Alin Apetri',     'Joost van der Linden']
Length: 30, dtype: str

In [42]:
# namen omzetten naar alleen voornaam en eerste letter van achternaam
df23['Naam monteur'] = df23['DriverName'].str.split().str[0] + ' ' + df23['DriverName'].str.split().str[-1].str[0]

In [45]:
df23['Naam monteur'].unique()

array(['Aart W', 'Tom B', 'Tjerk P', 'Sandro G', 'Liza G', 'Ronald K',
       'Marcel K', 'Cornelis G', 'Geertjan W', 'Roy A', 'Robin K',
       'Kees K', 'Peter B', 'Joost O', 'Onno H', 'Enzo D', 'Erik-Jan 3',
       'Bas S', 'Ron T', 'Hans G', 'Frido W', 'Sheamie G', 'Frans B',
       'René H', 'Barend J', 'Ronald G', 'Marcus D', 'Alin A', 'Joost L'],
      dtype=object)

In [47]:
# nu van orders de namen hetzelfde krijgen
df_orders['Vaste monteur'].unique()

<StringArray>
[             'Tom B', 'Cornelis van der G',            'Peter B',
            'Tjerk P',              'Ron T',           'Jeremy R',
             'René H',           'Marcel K',     'Aart van der W',
          'Liza de G',      'Laurens-Jan B',         'Mark den E',
             'Alin A',          'Vincent K',          'Patrick B',
           'Sandro G',                  nan,             'Rene H',
             'Jeremy']
Length: 19, dtype: str

In [48]:
df_orders['Vaste monteur'] = df_orders['Vaste monteur'].replace('', pd.NA)

In [51]:
mapping = (
    df_orders.dropna(subset=['Vaste monteur'])
      .groupby('Zorginstellingnaam')['Vaste monteur']
      .agg(lambda x: x.value_counts().idxmax())
)
mapping

Zorginstellingnaam
ASVZ - Bleskensgraaf                    Tjerk P
ASVZ - De Lingebolder                   Tjerk P
ASVZ - De Merwebolder                   Tjerk P
ASVZ - Neptunuslaan                   Patrick B
ASVZ - Nijhofflaan                    Patrick B
                                      ...
Zuidwester - Beneden Oostdijk        Mark den E
Zuidwester - Hellevoetsluis          Mark den E
Zuidwester - Middelharnis        Aart van der W
Zuidwester - Oud-Beijerland          Mark den E
Zuidwester - Spijkenisse             Mark den E
Name: Vaste monteur, Length: 318, dtype: str

In [52]:
df_orders['Vaste monteur'] = df_orders.apply(
    lambda row: mapping.get(row['Zorginstellingnaam'], pd.NA)
    if pd.isna(row['Vaste monteur'])
    else row['Vaste monteur'],
    axis=1
)

In [53]:
df_orders['Vaste monteur'].unique()

<StringArray>
[             'Tom B', 'Cornelis van der G',            'Peter B',
            'Tjerk P',              'Ron T',           'Jeremy R',
             'René H',           'Marcel K',     'Aart van der W',
          'Liza de G',      'Laurens-Jan B',         'Mark den E',
             'Alin A',          'Vincent K',          'Patrick B',
           'Sandro G',                  nan,             'Rene H',
             'Jeremy']
Length: 19, dtype: str

In [54]:
df_orders[df_orders['Vaste monteur'].isna()]

,Documentnr.,Toewijzingsdatum,Responsdatum,Serviceordersoort,Postcode,Plaats,Punten,Cliëntnr.,Zorginstellingnaam,Orderdatum,Omschrijving,Factuurnaam,Adres,Vaste monteur,Artikelnr.,Totaalbedrag
108,SOR2427336,2025-01-09,2024-12-12,AANPASSING,3201 DB,SPIJKENISSE,6,K0082798,Philadelphia - Puttesteijn,2024-12-04,Quickie Life I Sedeo rolstoel,CZ/Administratie Zorgkantoor,Gorsstraat 61,NaN,LIFEIS.00010,440.42
110,SOR2427375,2025-01-28,2024-12-12,REP,3328 HG,DORDRECHT,6,K0075587,Syndion - de Jagerweg,2024-12-05,Quickie Life I Sedeo rolstoel,VGZ Zorgkantoor,Jagerweg 54,NaN,LIFEIS.00010,174.33
165,SOR2428069,2025-01-06,2024-12-24,AANPASSING,4332 XS,MIDDELBURG,3,K0065661,Philadelphia - Nassaulaan,2024-12-16,"Easy Rider 3 inc verlichting, slot,bel parkeerrem",CZ/Administratie Zorgkantoor,Nassaulaan 207,NaN,EASYRIDER3.00010,0.00
203,SOR2428342,2025-01-06,2025-01-14,IND MAATWE,4201 JB,GORINCHEM,3,K0058607,Syndion - Haarstraat,2024-12-18,Puma Q500 M SedeoPro midwielaandrijving,VGZ Zorgkantoor,Haarstraat 63,NaN,Q500M.00010,145.50
211,SOR2428374,2025-01-07,2024-12-27,REP,3328 HG,DORDRECHT,6,K0055058,Syndion - de Jagerweg,2024-12-18,Roxx New Original Newton,VGZ Zorgkantoor,Jagerweg 54,NaN,ROXXNEWTON.00010,15.41
318,SOR2428786,2025-01-10,2025-01-03,REP,4614 CH,BERGEN OP ZOOM,9,K0082664,S&L Zorg - Lambertijnenhof 210,2024-12-24,Midi 2 driewielfiets,CZ/Administratie Zorgkantoor,Lambertijnenhof 210,NaN,MIDI2.00010,18.36
342,SOR2428874,2025-01-03,2025-01-06,REP,3202 GN,SPIJKENISSE,3,K0099464,Careyn - Herman Gorterhof,2024-12-27,Roxx New Original Matrixx,Careyn Crediteurenadministratie,Winston Churchillaan 191,NaN,ROXXNO.00010,0.00
623,SOR2500228,2025-01-07,2025-01-13,REP,3328 HG,DORDRECHT,2,K0056333,Syndion - de Jagerweg,2025-01-06,Match onderstel Zelfrijder,VGZ Zorgkantoor,Jagerweg 54,NaN,MATCHZ.00010,222.41
633,SOR2500244,2025-01-07,2025-01-13,REP,4201 JB,GORINCHEM,2,K0042412,Syndion - Haarstraat,2025-01-06,Action5 vouwframe rolstoel WLZ,VGZ Zorgkantoor,Haarstraat 63,NaN,ACTION5.00010,498.56
763,SOR2500392,2025-01-17,2025-01-30,IND MAATWE,5306 GM,BRAKEL,0,K0079194,Philadelphia - De regenboog Brakel,2025-01-08,Quickie Argon 2 rolstoel,VGZ Zorgkantoor,Molenkamp 24,NaN,ARGON2.00010,972.96
811,SOR2500453,2025-01-14,2025-01-15,REP,3328 HG,DORDRECHT,6,K0078196,Syndion - de Jagerweg,2025-01-08,Roxx Newton New Original model,VGZ Zorgkantoor,Jagerweg 54,NaN,ROXXNEWTONNO.00010,131.41
907,SOR2500566,2025-01-17,2025-01-21,AANPASSING,4201 JB,GORINCHEM,9,K0075888,Syndion - Haarstraat,2025-01-13,Roxx Newton New Original model,VGZ Zorgkantoor,Haarstraat 63,NaN,ROXXNEWTONNO.00010,7103.05
956,SOR2500624,2025-01-14,2025-01-20,AANPASSING,2643 JJ,PIJNACKER,4,K0096968,Laurens - De Oudelandse Hof,2025-01-10,Roxx New Original Matrixx,NTAC Zorgkantoor,Raaigras 102,NaN,ROXXNO.00010,0.00
991,SOR2500665,2025-01-15,2025-01-20,AANPASSING,4332 XS,MIDDELBURG,4,K0065661,Philadelphia - Nassaulaan,2025-01-10,"Easy Rider 3 inc verlichting, slot,bel parkeerrem",CZ/Administratie Zorgkantoor,Nassaulaan 207,NaN,EASYRIDER3.00010,18.52
1067,SOR2500759,2025-01-31,2025-01-21,AANPASSING,3328 HG,DORDRECHT,3,K0099216,Syndion - de Jagerweg,2025-01-13,Puma Q400 F SedeoPro voorwielaandrijving,VGZ Zorgkantoor,Jagerweg 54,NaN,Q400F.00010,0.00
1129,SOR2500829,2025-01-20,2025-01-21,REP,3328 HN,DORDRECHT,6,K0030835,Syndion - de Jagerweg,2025-01-14,Puma 20,VGZ Zorgkantoor,Minnaertweg 4,NaN,PUMA20.00010,25.68
1168,SOR2500873,2025-01-17,2025-01-21,REP,4707 JV,ROOSENDAAL,3,K0048119,S&L Zorg - Potgieterlaan,2025-01-14,MID Lectus,CZ/Administratie Zorgkantoor,Potgieterlaan 26,NaN,MIDLECTUS.00010,109.12
1177,SOR2500883,2025-01-21,2025-01-21,REP,3297 AA,PUTTERSHOEK,3,K0016354,Profila zorg - Oogstlaan Puttershoek,2025-01-14,Roxx Newton New Original model,CZ/Administratie Zorgkantoor,Oogstlaan 18 -26,NaN,ROXXNEWTONNO.00010,30.51
1245,SOR2500963,2025-01-16,2025-01-22,REP,3123 AX,SCHIEDAM,6,K0064978,DSW zorgkantoor,2025-01-15,Sterling 3 wiel uitvoering Elite 2 XS (15 km/u),Zorgdepot,Voorberghlaan 35,NaN,ELITE2XS.00010,0.00
1263,SOR2500984,2025-01-17,2025-01-22,REP,3134 BS,VLAARDINGEN,6,K0049905,Stichting Herman Frantsenhuizen,2025-01-15,Ibis Pro rolstoel,NTAC Zorgkantoor,Schiedamseweg 96,NaN,IBIS.00010,0.00
1265,SOR2500986,2025-01-21,2025-01-23,AANPASSING,3328 HG,DORDRECHT,4,K0099216,Syndion - de Jagerweg,2025-01-15,Puma Q400 F SedeoPro voorwielaandrijving,VGZ Zorgkantoor,Jagerweg 54,NaN,Q400F.00010,10.49
1384,SOR2501133,2025-01-20,2025-01-24,AANPASSING,3055 JD,ROTTERDAM,6,K0103768,Particuliere verhuur,2025-01-16,Roxx New Original Matrixx,Transmitt Revalidatie,Van Beethovenlaan 60,NaN,ROXXNO.00010,0.00
1393,SOR2501145,2025-01-20,2025-01-27,AANPASSING,2803 ZX,GOUDA,0,K0101688,Particuliere verhuur,2025-01-17,Roxx New Original Matrixx,Zorgpartners Midden Holland,Ronsseweg 410,NaN,ROXXNO.00010,0.00
1452,SOR2501219,2025-01-21,2025-01-27,REP,3328 HG,DORDRECHT,9,K0063638,Syndion - de Jagerweg,2025-01-20,Sterling 3 wiel uitvoering Elite 2 XS (15 km/u),VGZ Zorgkantoor,Jagerweg 54,NaN,ELITE2XS.00010,0.00
1453,SOR2501221,2025-01-21,2025-01-27,REP,3328 HG,DORDRECHT,6,K0063638,Syndion - de Jagerweg,2025-01-20,Roxx Newton New Original model,VGZ Zorgkantoor,Jagerweg 54,NaN,ROXXNEWTONNO.00010,277.41
1460,SOR2501231,2025-01-31,2025-01-27,REP,3297 AA,PUTTERSHOEK,3,K0016354,Profila zorg - Oogstlaan Puttershoek,2025-01-20,Roxx Newton New Original model,CZ/Administratie Zorgkantoor,Oogstlaan 18 -26,NaN,ROXXNEWTONNO.00010,688.22
1484,SOR2501262,2025-01-21,2025-01-27,REP,3134 BS,VLAARDINGEN,6,K0085605,Stichting Herman Frantsenhuizen,2025-01-20,Ibis XC duwrolstoel,NTAC Zorgkantoor,Schiedamseweg 96,NaN,IBISXC.00010,0.00
1588,SOR2501394,2025-01-22,2025-01-29,AANPASSING,3055 JD,ROTTERDAM,6,K0103768,Particuliere verhuur,2025-01-21,Roxx New Original Matrixx,Transmitt Revalidatie,Van Beethovenlaan 60,NaN,ROXXNO.00010,0.00
1613,SOR2501427,2025-01-22,2025-01-28,REP,3055 JD,ROTTERDAM,3,K0103768,Particuliere verhuur,2025-01-21,Roxx New Original Matrixx,Transmitt Revalidatie,Van Beethovenlaan 60,NaN,ROXXNO.00010,0.00
1659,SOR2501493,2025-01-23,2025-01-30,AANPASSING,2612 VC,DELFT,3,K0103835,Particuliere verhuur,2025-01-22,Canto NXT Matrixx Zelfrijder,St. Zorginst. Pieter v Foreest,Beukenlaan 2,NaN,CANTONXTZ.00010,0.00
1682,SOR2501523,2025-01-27,2025-01-29,REP,4201 JB,GORINCHEM,4,121039,Syndion - Haarstraat,2025-01-22,EVO Lectus,VGZ Zorgkantoor,Haarstraat 63,NaN,EVOLECTUS.00010,27.95
1789,SOR2501666,2025-01-28,2025-01-30,REP,4231 AA,MEERKERK,5,K0091075,Syndion - Woonlocatie Meerkant,2025-01-23,"Adremco frame kaal inclusief sjorogen, ongecoat",VGZ Zorgkantoor,Burgemeester Sloblaan 25,NaN,ADREMCO.00010,401.74
1952,SOR2501888,2025-01-29,2025-02-03,REP,3134 BS,VLAARDINGEN,6,K0085605,Stichting Herman Frantsenhuizen,2025-01-27,Ibis XC duwrolstoel,NTAC Zorgkantoor,Schiedamseweg 96,NaN,IBISXC.00010,0.00
2130,SOR2502253,2025-01-31,2025-02-07,AANPASSING,2803 ZX,GOUDA,0,K0101688,Particuliere verhuur,2025-01-30,Roxx New Original Matrixx,Zorgpartners Midden Holland,Ronsseweg 410,NaN,ROXXNO.00010,0.00

In [55]:
# deze waarden niet zomaar verwijderen want misschien komt er uit de GPS data wie er is geweest.

In [ ]:

namen_houden = [
    'Aart W',
    'Tom B',
    'Tjerk P',
    'Sandro G',
    'Liza G',
    'Marcel K',
    'Cornelis G',
    'Peter B',
    'Ron T',
    'René H',
    'Alin A'
]

In [62]:
df_orders = df_orders[df_orders['Naam monteur'].isin(namen_houden)]
df21 = df21[df21['Naam monteur'].isin(namen_houden)]

In [63]:
df_orders

,Documentnr.,Toewijzingsdatum,Responsdatum,Serviceordersoort,Postcode,Plaats,Punten,Cliëntnr.,Zorginstellingnaam,Orderdatum,Omschrijving,Factuurnaam,Adres,Vaste monteur,Artikelnr.,Totaalbedrag,Naam monteur
0,SOR2341189,2025-01-20,2023-12-15,REP,4301 NW,ZIERIKZEE,15,K0043840,Allevo - Zierik7,2023-12-08,Morgan Newton,CZ/Administratie Zorgkantoor,Emil Sandstromweg 2,Tom B,MORGANNEWTON.00010,2800.82,Tom B.
1,SOR2341990,2025-01-28,2023-12-29,REP,2643 JJ,PIJNACKER,24,510431,Pieter van Foreest - Weidevogelhof,2023-12-19,Puma 40,NTAC Zorgkantoor,Raaigras 102,Cornelis van der G,PUMA40.00010,0.00,Cornelis G.
2,SOR2400380,2025-01-06,2024-01-15,REP,4382 LJ,VLISSINGEN,9,K0062065,S Heeren Loo - Nieuwe Zuidbeekseweg,2024-01-08,QUICKIE ATTITUDE HYBRID 2,CZ/Administratie Zorgkantoor,Stadhuisplein 22,Tom B,ATTITUDEH2.00010,1603.95,Tom B.
3,SOR2408893,2025-01-28,2024-04-25,REP,2685 SZ,POELDIJK,3,K0087579,Middin - Westland Eliasdreef,2024-04-17,Puma Q500 M SedeoPro midwielaandrijving,NTAC Zorgkantoor,Eliasdreef 9,Cornelis van der G,Q500M.00010,71.59,Cornelis G.
4,SOR2415627,2025-01-10,2024-07-19,AANPASSING,2612 VC,DELFT,3,K0085783,Pieter van Foreest - Bieslandhof,2024-07-11,Roxx Trippel & Zelfrijder,NTAC Zorgkantoor,Beukenlaan 2,Cornelis van der G,ROXX.00010,510.30,Cornelis G.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2137,SOR2502331,2025-01-31,2025-02-07,REP,3353 BT,PAPENDRECHT,0,K0092462,Rivas - Waalburcht PG,2025-01-31,Ibis Pro rolstoel,VGZ Zorgkantoor,Kleine Waal 6,Tjerk P,IBIS.00010,15.41,Tjerk P.
2139,SOR2502349,2025-01-28,2025-02-17,POREP,4614 CH,BERGEN OP ZOOM,0,K0097396,S&L Zorg - Lambertijnenhof,2025-01-31,"Maxi 2 Basis INC licht, slot, bel, parkeerrem",CZ/Administratie Zorgkantoor,Lambertijnenhof 200,Aart van der W,MAXI2.00010,0.00,Aart W.
2140,SOR2502353,2025-01-28,2025-02-17,POREP,4614 CH,BERGEN OP ZOOM,0,K0076862,S&L Zorg - Lambertijnenhof,2025-01-31,Midi 2 driewielfiets,CZ/Administratie Zorgkantoor,Lambertijnenhof 200,Aart van der W,MIDI2.00010,0.00,Aart W.
2141,SOR2502547,2025-01-31,2025-02-11,REP,5101 TB,DONGEN,0,K0059773,GGZ Breburg - Dongen,2025-02-04,Puma Q500 R SedeoPro achterwielaandrijving,VGZ Zorgkantoor,Heuvelstraat 33,René H,Q500R.00010,109.41,René H.
2142,SOR2502788,2025-01-27,2025-02-24,POREP,3371 PR,HARDINXVELD GIESSENDAM,0,509154,Waardeburgh - Pedaja,2025-02-07,Puma Q400 M SedeoPro middenwielaandrijving,VGZ Zorgkantoor,Claversweer 1 K301,Cornelis van der G,Q400M.00010,0.00,Cornelis G.

In [65]:
df21

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,DriverName,...,City,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long,Naam monteur
16951,1001 (VFK-90-R),2025-01-02,06:33:00,06:46:00,09:43:00,13.00,00:12:00,02:57:00,"Kamerlingh Onnesweg 9, Dordrecht",Aart van der Wulp,...,Dordrecht,00:00:00,03:09:00,00:12:00,02:57:00,00:00:00,13.00,517805366.0,46391348.0,Aart W.
16952,1001 (VFK-90-R),2025-01-02,09:43:00,09:57:00,09:57:00,9.54,00:14:00,00:00:00,"Ijsvogelplein 104, Zwijndrecht",Aart van der Wulp,...,Zwijndrecht,00:00:00,03:24:00,00:26:00,02:57:00,00:00:00,22.54,51812489.0,46224083.0,Aart W.
16953,1001 (VFK-90-R),2025-01-02,09:57:00,10:02:00,10:25:00,0.00,00:05:00,00:22:00,"Ijsvogelplein 104, Zwijndrecht",Aart van der Wulp,...,Zwijndrecht,00:00:00,03:52:00,00:32:00,03:19:00,00:00:00,22.54,51812497.0,46224118.0,Aart W.
16954,1001 (VFK-90-R),2025-01-02,10:25:00,10:37:00,11:03:00,2.46,00:11:00,00:26:00,"'t Anker 101 -118 , Zwijndrecht",Aart van der Wulp,...,Zwijndrecht,00:00:00,04:30:00,00:44:00,03:45:00,00:00:00,25.00,518210746.0,4651274.0,Aart W.
16955,1001 (VFK-90-R),2025-01-02,11:03:00,11:08:00,11:43:00,1.92,00:04:00,00:35:00,"Hoofdland 1, Zwijndrecht",Aart van der Wulp,...,Zwijndrecht,00:00:00,05:10:00,00:49:00,04:21:00,00:00:00,26.92,518247238.0,4644713.0,Aart W.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21548,1772 (V-13-DLF),2025-01-31,10:36:00,10:58:00,11:34:00,19.78,00:22:00,00:35:00,"Heuvelstraat 23, Dongen",Alin Apetri,...,Dongen,00:00:00,04:23:00,01:54:00,02:29:00,00:00:00,72.28,516245537.0,49289767.0,Alin A.
21549,1772 (V-13-DLF),2025-01-31,11:34:00,11:39:00,12:17:00,2.57,00:05:00,00:37:00,"Konijnendonk 2, Dongen",Alin Apetri,...,Dongen,00:00:00,05:06:00,02:00:00,03:06:00,00:00:00,74.85,516339193.0,49451326.0,Alin A.
21550,1772 (V-13-DLF),2025-01-31,12:17:00,12:56:00,14:37:00,46.27,00:39:00,01:40:00,"Boris Pasternak-Erf 44, Dordrecht",Alin Apetri,...,Dordrecht,00:00:00,07:26:00,02:39:00,04:47:00,00:00:00,121.12,517995595.0,47287933.0,Alin A.
21551,1772 (V-13-DLF),2025-01-31,14:37:00,14:51:00,15:04:00,8.36,00:14:00,00:12:00,"Kleine Waal 52, Papendrecht",Alin Apetri,...,Papendrecht,00:00:00,07:53:00,02:53:00,04:59:00,00:00:00,129.48,518256916.0,46887975.0,Alin A.
21552,1772 (V-13-DLF),2025-01-31,15:04:00,15:16:00,19:17:00,8.34,00:12:00,04:00:00,"Boris Pasternak-Erf 44, Dordrecht",Alin Apetri,...,Dordrecht,00:00:00,12:06:00,03:06:00,09:00:00,12:06:00,137.82,517995396.0,47288163.0,Alin A.